### ISSUE TITLE
Grouping non-Lights E1926 IKEA Blinds

### ISSUE THREAD

**Issue by kaykoch** [Koenkk/zigbee2mqtt#2548] opened 2019-12-17 16:46 UTC
I paired two E1926 (CC2530, Raspberry). Both reacting to {"state": "ON"} or {"state": "OPEN"}.
(also close, position, stop). "zigbee2mqtt/balkon_rollo-rechts_ikea/set"
I grouped both in configuration.yaml cause both a covering big window. When I send one of these ON/OFF-orders to friendly_group_name nothing happens. "zigbee2mqtt/rolladen_wohnzimmer_gruppe/set"

Using {"state": "ON"} blind is responding: {"state":"OFF","brightness":0}
Using {"position": "60"} log gives: No converter available for 'position'

Does that mean, It's not possible to group blinds

thanks
Kay

**Comment by Koenkk** [comment] 2019-12-17 18:49
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/2505#issuecomment-565530439 (should already work in zigbee2mqtt 1.8.0)

**Closed by Koenkk** 2019-12-17 18:49 UTC
