### ISSUE TITLE
issue still with QBKG04LM

### ISSUE THREAD

**Issue by mayrp2001** [Koenkk/zigbee2mqtt#1368] opened 2019-04-04 13:26 UTC
Still having an issue with my QBKG04LM. I was reverted to zigbee2mqtt edge as suggested but still can't control the switch and getting the following errors in the log.

`zigbee2mqtt:error 4/4/2019, 1:23:18 PM Zigbee publish to device '0x00158d0002ec227d', genOnOff - on - {} - {"manufSpec":0,"disDefaultRsp":0} - 2 failed with error Error: AF data request fails, status code: 240. MAC transaction expired.`

Any help would be great.

**Comment by Koenkk** [comment] 2019-04-04 13:37
Duplicate of #943

**Closed by Koenkk** 2019-04-04 13:37 UTC
