### ISSUE TITLE
Ui Problem after update to 1.53.3

### ISSUE THREAD

**Issue by moshiko2312** [Koenkk/zigbee2mqtt#21538] opened 2024-02-23 08:25 UTC
### What happened?

all the ui like a list

<img width="1336" alt="image" src="https://github.com/Koenkk/zigbee2mqtt/assets/48163773/2547c9bb-170e-45e1-9d2b-798af6a9de38">

### What did you expect to happen?

i expected to get normal UI on web 

### Zigbee2MQTT version

1.35.3

### Adapter firmware version

7.3.2.0 build 212

### Adapter

EZSP v12 Skyconnect HA

### Setup

pi 4 home assistant core on Docker compose

### Debug log

[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/14383131/log.txt)

**Comment by thkn1973** [comment] 2024-02-23 09:45
I have the same problem.
However, the problem only occurs in the Chrome Browser.
In e.g. Brave or Microsoft Edge it is ok

**Comment by redpixy** [comment] 2024-02-23 10:32
Mine was back to normal after clearing the browser cache.

**Comment by gizmo69the2nd** [comment] 2024-02-23 16:29
Same problem on Firefox for Ubuntu - 122.0.1 (64-bit)

**Comment by moshiko2312** [comment] 2024-02-24 08:00
Ok thanks I wi check with safari

בתאריך יום ו׳, 23 בפבר׳ 2024 ב-18:29 מאת gizmo69the2nd <
***@***.***>:

**Comment by Koenkk** [comment] 2024-02-24 08:07
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/21268

**Closed by Koenkk** 2024-02-24 08:07 UTC
Labels: problem
