### ISSUE TITLE
Ikea E1524

### ISSUE THREAD

**Issue by hexxter** [Koenkk/zigbee2mqtt#2172] opened 2019-10-20 13:16 UTC
# Bug Report
## What happened
PROBLEM DETECTED
Oct 20 13:12:35 zigbee npm[505]: Please create an issue here with the contents of below: https://github.com/koenkk/zigbee2mqtt/issues
Oct 20 13:12:35 zigbee npm[505]: ===== Stack =====
Oct 20 13:12:35 zigbee npm[505]: AssertionError [ERR_ASSERTION]: { frameCntl:
Oct 20 13:12:35 zigbee npm[505]:    { frameType: 1, manufSpec: 1, direction: 0, disDefaultRsp: 0 },
Oct 20 13:12:35 zigbee npm[505]:   manufCode: 4476,
Oct 20 13:12:35 zigbee npm[505]:   seqNum: 12,
Oct 20 13:12:35 zigbee npm[505]:   cmdId: 'tr... deepEqual { frameCntl:
Oct 20 13:12:35 zigbee npm[505]:    { frameType: 1, manufSpec: 1, direction: 0, disDefaultRsp: 0 },
Oct 20 13:12:35 zigbee npm[505]:   manufCode: 4476,
Oct 20 13:12:35 zigbee npm[505]:   seqNum: 12,
Oct 20 13:12:35 zigbee npm[505]:   cmdId: 'tr...
Oct 20 13:12:35 zigbee npm[505]:     at cb (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/lib/components/zcl.js:59:24)
Oct 20 13:12:35 zigbee npm[505]:     at /opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/deprecated/zcl-packet/lib/zcl.js:31:17
Oct 20 13:12:35 zigbee npm[505]:     at Dissolve.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/deprecated/zcl-packet/lib/functional.js:76:17)
Oct 20 13:12:35 zigbee npm[505]:     at Object.onceWrapper (events.js:286:20)
Oct 20 13:12:35 zigbee npm[505]:     at Dissolve.emit (events.js:198:13)
Oct 20 13:12:35 zigbee npm[505]:     at Dissolve.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/deprecated/dissolve-chunks/index.js:65:29)
Oct 20 13:12:35 zigbee npm[505]:     at Dissolve.emit (events.js:198:13)
Oct 20 13:12:35 zigbee npm[505]:     at emitReadable_ (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/node_modules/readable-stream/lib/_stream_readable.js:456:10)
Oct 20 13:12:35 zigbee npm[505]:     at emitReadable (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/node_modules/readable-stream/lib/_stream_readable.js:450:7)
Oct 20 13:12:35 zigbee npm[505]:     at readableAddChunk (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/node_modules/readable-stream/lib/_stream_readable.js:206:11)
Oct 20 13:12:35 zigbee npm[505]: ===== Buffer =====
Oct 20 13:12:35 zigbee npm[505]: { type: 'Buffer', data: [ 5, 124, 17, 12, 7, 2, 0, 0, 0 ] }
Oct 20 13:12:35 zigbee npm[505]: ===== Arguments =====
Oct 20 13:12:35 zigbee npm[505]: <Buffer 05 7c 11 0c 07 02 00 00 00> 5
Oct 20 13:12:35 zigbee npm[505]: ===== zcl-packet parse =====
Oct 20 13:12:35 zigbee npm[505]: {"frameCntl":{"frameType":1,"manufSpec":1,"direction":0,"disDefaultRsp":0},"manufCode":4476,"seqNum":12,"cmdId":"tradfriArrowSingle","payload":{"value":2}}
Oct 20 13:12:35 zigbee npm[505]: ===== zcl =====
Oct 20 13:12:35 zigbee npm[505]: {"frameCntl":{"frameType":1,"manufSpec":1,"direction":0,"disDefaultRsp":0},"manufCode":4476,"seqNum":12,"cmdId":"tradfriArrowSingle","payload":{"value":2,"value2":0}}
Oct 20 13:12:35 zigbee npm[505]: ===============
Oct 20 13:12:36 zigbee npm[505]:   zigbee2mqtt:info 10/20/2019, 1:12:36 PM Zigbee publish to device '0x000b57fffe3a4892', genBasic - readRsp - [] - {"direction":1,"seqNum":13,"disDefaultRsp":1} - 1

## How to reproduce it (minimal and precise)
hold long button

## Debug Info
zigbee2mqtt version:1.6.0
CC253X firmware version: CC2531_DEFAULT_20190608.zip

**Comment by Koenkk** [comment] 2019-10-20 13:48
Thanks for reporting, closing this as it is a duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/2006#issuecomment-533691577

**Closed by Koenkk** 2019-10-20 13:48 UTC
