### ISSUE TITLE
TV02 window_open after ON to OFF

### ISSUE THREAD

**Issue by Wikibear** [Koenkk/zigbee2mqtt#15181] opened 2022-11-25 15:42 UTC
### What happened?

After a time  I can't switch on window_open. After ON it needs 2-3 sec and switch to OFF.

Same as reported here:
https://github.com/Koenkk/zigbee2mqtt/issues/14163

After restart of z2m it will work again.

### Zigbee2MQTT version

1.28.2-dev commit: 3b221d4f

### Adapter firmware version

0x26780700

### Adapter

ConBee2/RaspBee2

**Comment by vladi1234** [comment] 2022-11-26 09:21
https://github.com/Koenkk/zigbee2mqtt/issues/15164#issuecomment-1326806395

**Comment by Koenkk** [comment] 2022-11-26 09:26
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/15164

**Closed by Koenkk** 2022-11-26 09:26 UTC
Labels: problem
