### ISSUE TITLE
Touchlink fails in 1.15.0 (Failed to call 'BridgeLegacy'...)

### ISSUE THREAD

**Issue by MacValley** [Koenkk/zigbee2mqtt#4565] opened 2020-10-05 17:13 UTC
## What happened
My hue bulb (Philips 9290012573A) was working fine with zigbee2mqtt (tagged 1.14.4), but at some point I messed up my configuration file, so in order to pair again I had to reset the bulb. Since I don't have a Hue Bridge I issued the following Touchlink message: 
mosquitto_pub -h 192.168.1.202 -m '{}' -t "zigbee2mqtt_h202/bridge/config/touchlink/factory_reset".
No reset. In the log I see following error:
info  2020-10-05 18:27:10: Starting touchlink factory reset...
info  2020-10-05 18:27:10: MQTT publish: topic 'zigbee2mqtt_h202/bridge/log', payload '{"message":"reset_started","meta":{"status":"started"},"type":"touchlink"}'
error 2020-10-05 18:27:13: Failed to call 'BridgeLegacy' 'onMQTTMessage' (Error: Write for 'BUFFER' not available
    at BuffaloZnp.write (/app/node_modules/zigbee-herdsman/dist/buffalo/buffalo.js:259:19)
    at ZpiObject.createPayloadBuffer (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/zpiObject.js:87:21)
    at ZpiObject.toUnpiFrame (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/zpiObject.js:38:29)
    at Znp.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:279:34)
    at Generator.next (<anonymous>)
    at /app/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:23:12)
    at Object.func (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:277:41)
    at Queue.<anonymous> (/app/node_modules/zigbee-herdsman/dist/utils/queue.js:29:46))

## What did you expect to happen
When I paired the first time some months ago I issued the same mqtt message and that worked perfectly. In less than a minute the bulb was reset and automatically paired and configured. 
To solve the issue today, I deleted version 1.15.0 and put "image: koenkk/zigbee2mqtt:1.14.4" in my docker-compose file instead of just "image: koenkk/zigbee2mqtt".
With version 1.14.4 up and running I again sent mqtt message: 
mosquitto_pub -h 192.168.1.202 -m '{}' -t "zigbee2mqtt_h202/bridge/config/touchlink/factory_reset".
Worked like a charm, after 15 seconds it was identified and configured, and I was able to send "on" and "off" payloads.

## How to reproduce it (minimal and precise)
Connect bulb to power at a distance some 5-10 cm from CC2531, issue command 
mosquitto_pub -h 192.168.1.202 -m '{}' -t "zigbee2mqtt_h202/bridge/config/touchlink/factory_reset"

## Debug info
Zigbee2MQTT version: 1.15.0
Adapter hardware: CC2531
Adapter firmware version: '{"meta":{"maintrel":3,"majorrel":2,"minorrel":6,"product":0,"revision":20190608,"transportrev":2},"type":"zStack12"}'

**Comment by Koenkk** [comment] 2020-10-05 17:23
Duplicate of #4543

**Closed by Koenkk** 2020-10-05 17:23 UTC
Labels: problem
