### ISSUE TITLE
touchlink fails with using the dev branch

### ISSUE THREAD

**Issue by falcke** [Koenkk/zigbee2mqtt#4895] opened 2020-11-07 16:29 UTC
Sorry for the delay. I made it to use the dev branch now and I'm getting [these messages](https://gist.github.com/falcke/e695cd4ac9644dcc73c4af9d1f19e9d9) now. Is it related or something different? Thank you so far!

_Originally posted by @falcke in https://github.com/Koenkk/zigbee2mqtt/issues/4543#issuecomment-720499088_

...I've created tis issue because the referenced issue was already closed. Hope this ist the right way.

**Comment by Koenkk** [comment] 2020-11-07 18:38
Duplicate of: https://github.com/Koenkk/zigbee2mqtt/issues/4729, current workaround, stop Zigbee2MQTT and replug stick and try again.

**Closed by Koenkk** 2020-11-07 18:38 UTC
