### ISSUE TITLE
Device is listed as joined, but doesnt work and not in config.yaml

### ISSUE THREAD

**Issue by GMFalka** [Koenkk/zigbee2mqtt#2527] opened 2019-12-14 17:07 UTC
Hi!

Got a Tradfri dimmer, that worked for a while, then not.. Now i cant repair it to the stick.

Tried removing/force removing it from the config or resetting the device or deleting database.db but nothing worked so far. 
Theres no log about the pairing even in debug mode.

I can directly pair the dimmer to a tradfri bulb the "IKEA way" and it works. So the dimmer is functional.

Any help would be appreciated.

I know these dimmers are crap (i have a bunch of them), but there are no real alternative to this type of device.

**Comment by Koenkk** [comment] 2019-12-15 13:19
Duplicate of/possible solution: https://github.com/Koenkk/zigbee2mqtt/issues/2343#issuecomment-565146154

**Closed by Koenkk** 2019-12-15 13:19 UTC

**Comment by GMFalka** [comment] 2019-12-17 20:01
> Duplicate of/possible solution: [#2343 (comment)](https://github.com/Koenkk/zigbee2mqtt/issues/2343#issuecomment-565146154)

Thank you @Koenkk!! Reflashing the stick solved it.

I actually bought a few extra IKEA puck and bulb, i could not pair any of them so. Now it works! :)
