### ISSUE TITLE
Z2M crashes after some time, trying to identify the issue. Logs attached.

### ISSUE THREAD

**Issue by bednim** [Koenkk/zigbee2mqtt#13631] opened 2022-08-21 07:13 UTC
### What happened?

Z2M should start automatically with my system.
After startup it works fine but it seems that after few minutes/hours/not sure how long - this happens: 
Also - processor usage goes to over 50% constant. Proxmox HA CPU goes to 100%.  Not sure if both CPU usages are related.

When this shows in LOG Z2M doeesn't work. null should be config/zigbee2mqtt folder which does exist.

Haven't done any customized configs.

Home assistant ver 2022.8.6.

After having below error when I stop and start Z2M -it will work fine for some time (not sure how long).
```
[09:03:56] INFO: Handing over control to Zigbee2MQTT Core ...
> zigbee2mqtt@1.27.0 start
> node index.js
Error: ENOENT: no such file or directory, open 'null/configuration.yaml'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at Object.read (/app/lib/util/yaml.ts:7:29)
    at read (/app/lib/util/settings.ts:311:20)
    at getInternalSettings (/app/lib/util/settings.ts:418:21)
    at Object.reRead (/app/lib/util/settings.ts:696:5)
    at start (/app/index.js:93:14)
[09:03:58] INFO: Handing over control to Zigbee2MQTT Core ...
> zigbee2mqtt@1.27.0 start
> node index.js
Error: ENOENT: no such file or directory, open 'null/configuration.yaml'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at Object.read (/app/lib/util/yaml.ts:7:29)
    at read (/app/lib/util/settings.ts:311:20)
    at getInternalSettings (/app/lib/util/settings.ts:418:21)
    at Object.reRead (/app/lib/util/settings.ts:696:5)
    at start (/app/index.js:93:14)
[09:03:59] INFO: Handing over control to Zigbee2MQTT Core ...
> zigbee2mqtt@1.27.0 start
> node index.js
Error: ENOENT: no such file or directory, open 'null/configuration.yaml'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at Object.read (/app/lib/util/yaml.ts:7:29)
    at read (/app/lib/util/settings.ts:311:20)
    at getInternalSettings (/app/lib/util/settings.ts:418:21)
    at Object.reRead (/app/lib/util/settings.ts:696:5)
    at start (/app/index.js:93:14)
[09:04:01] INFO: Handing over control to Zigbee2MQTT Core ...
> zigbee2mqtt@1.27.0 start
> node index.js
Error: ENOENT: no such file or directory, open 'null/configuration.yaml'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at Object.read (/app/lib/util/yaml.ts:7:29)
    at read (/app/lib/util/settings.ts:311:20)
    at getInternalSettings (/app/lib/util/settings.ts:418:21)
    at Object.reRead (/app/lib/util/settings.ts:696:5)
    at start (/app/index.js:93:14)
```

### What did you expect to happen?

Just work as intended I suppose?

### How to reproduce it (minimal and precise)

No idea.

### Zigbee2MQTT version

1.27.0-1

### Adapter firmware version

CC2652RB_coordinator_20220219.zip

### Adapter

cc2652RB slaesh

**Comment by Koenkk** [comment] 2022-08-21 08:10
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/12801

**Closed by Koenkk** 2022-08-21 08:10 UTC
Labels: problem
