### ISSUE TITLE
Touchlink reset not working with zzh (zig-a-zig-ah)

### ISSUE THREAD

**Issue by piotrekoo** [Koenkk/zigbee2mqtt#4548] opened 2020-10-03 19:14 UTC
## What happened
Lately, I decided to give my network an upgrade and bought a zzh to replace my old CC2531. My Philips Hue bulbs need a factory reset to be re-paired. The Touchlink reset doesn't work though, that's stdout:
```
Zigbee2MQTT:info  2020-10-03 20:56:40: Starting touchlink factory reset...
Zigbee2MQTT:info  2020-10-03 20:56:40: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"reset_started","meta":{"status":"started"},"type":"touchlink"}'
Zigbee2MQTT:error 2020-10-03 20:56:43: Failed to call 'BridgeLegacy' 'onMQTTMessage' (Error: Write for 'BUFFER' not available
    at BuffaloZnp.write (/app/node_modules/zigbee-herdsman/dist/buffalo/buffalo.js:259:19)
    at ZpiObject.createPayloadBuffer (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/zpiObject.js:87:21)
    at ZpiObject.toUnpiFrame (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/zpiObject.js:38:29)
    at Znp.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:279:34)
    at Generator.next (<anonymous>)
    at /app/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:23:12)
    at Object.func (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:277:41)
    at Queue.<anonymous> (/app/node_modules/zigbee-herdsman/dist/utils/queue.js:29:46))
```

## What did you expect to happen
Well, Touchlink reset to work.

## How to reproduce it (minimal and precise)
Run Touchlink reset.

## Debug info
Zigbee2MQTT version: latest-dev Docker image, same happens on 1.15.0
Adapter hardware: CC26X2R1 (zzh)
Adapter firmware version: Z-Stack 3.x.0 20200925

**Comment by Koenkk** [comment] 2020-10-03 22:07
Dupe of https://github.com/Koenkk/zigbee2mqtt/issues/4543

**Closed by Koenkk** 2020-10-03 22:07 UTC
Labels: problem
