### ISSUE TITLE
Add support for Xiaomi Aqara Smart Light Bulbs

### ISSUE THREAD

**Issue by sapkra** [Koenkk/zigbee2mqtt#621] opened 2018-11-22 14:09 UTC
Aqara released a light bulb with zigbee. Would be great to support it. ;D

Unsupported device
https://www.aliexpress.com/wholesale?catId=0&initiative_id=SB_20181122060617&SearchText=Aqara+Smart+Light+Bulbs

**Comment by Koenkk** [comment] 2018-11-22 14:59
In case you have this device, we can add support for it.

**Comment by kiwinol** [comment] 2018-11-25 19:59
I have just ordered one of these so if it's not added by the time mine arrives and I can get some help with the process I will add support.

**Comment by paskyecijano** [comment] 2018-11-28 07:50
I have just ordered one of these too and would be phantastic give support for the bulb

**Comment by kiwinol** [comment] 2018-12-05 08:31
My bulb arrived today.  My laptop I usually use is not booting due to an update :(  I tried to connect the bulb anyway.  Hopefully I have some time this weekend:

> zigbee2mqtt:info 2018-12-5 19:23:08 New device with address 0x00158d0002c64b73 connected!
  zigbee2mqtt:info 2018-12-5 19:23:08 MQTT publish, topic: 'zigbee2mqtt/bridge/log', payload: '{"type":"device_connected","message":"0x00158d0002c64b73"}'
  zigbee2mqtt:warn 2018-12-5 19:23:08 Device with modelID 'lumi.light.aqcn02' is not supported.
  zigbee2mqtt:warn 2018-12-5 19:23:08 Please see: https://github.com/Koenkk/zigbee2mqtt/wiki/How-to-support-new-devices
  zigbee2mqtt:debug 2018-12-5 19:23:08 Received zigbee message of type 'attReport' with data '{"cid":"genBasic","data":{"65281":{"3":24,"5":9,"7":"0x0000000000000000","8":278,"9":1280,"10":13100,"100":1,"101":255,"102":153}}}' of device 'lumi.light.aqcn02' (0x00158d0002c64b73)
  zigbee2mqtt:warn 2018-12-5 19:23:08 Device with modelID 'lumi.light.aqcn02' is not supported.
  zigbee2mqtt:warn 2018-12-5 19:23:08 Please see: https://github.com/Koenkk/zigbee2mqtt/wiki/How-to-support-new-devices
  zigbee2mqtt:debug 2018-12-5 19:23:08 Received zigbee message of type 'devInterview' with data '"0x00158d0002c64b73"'
  zigbee2mqtt:debug 2018-12-5 19:23:09 Received zigbee message of type 'devInterview' with data '"0x00158d0002c64b73"'
  zigbee2mqtt:debug 2018-12-5 19:23:09 Received zigbee message of type 'devInterview' with data '"0x00158d0002c64b73"'
  zigbee2mqtt:debug 2018-12-5 19:23:09 Received zigbee message of type 'devInterview' with data '"0x00158d0002c64b73"'
  zigbee2mqtt:debug 2018-12-5 19:23:09 Received zigbee message of type 'devInterview' with data '"0x00158d0002c64b73"'
  zigbee2mqtt:debug 2018-12-5 19:23:10 Received zigbee message of type 'devInterview' with data '"0x00158d0002c64b73"'
  zigbee2mqtt:debug 2018-12-5 19:23:10 Received zigbee message of type 'devInterview' with data '"0x00158d0002c64b73"'
  zigbee2mqtt:debug 2018-12-5 19:23:10 Received zigbee message of type 'devInterview' with data '"0x00158d0002c64b73"'
  zigbee2mqtt:debug 2018-12-5 19:23:10 Received zigbee message of type 'devInterview' with data '"0x00158d0002c64b73"'
  zigbee2mqtt:debug 2018-12-5 19:23:10 Received zigbee message of type 'devInterview' with data '"0x00158d0002c64b73"'
  zigbee2mqtt:debug 2018-12-5 19:23:10 Received zigbee message of type 'devInterview' with data '"0x00158d0002c64b73"'
  zigbee2mqtt:debug 2018-12-5 19:23:10 Received zigbee message of type 'devInterview' with data '"0x00158d0002c64b73"'
  zigbee2mqtt:debug 2018-12-5 19:23:11 Received zigbee message of type 'devInterview' with data '"0x00158d0002c64b73"'
  zigbee2mqtt:debug 2018-12-5 19:23:11 Received zigbee message of type 'devInterview' with data '"0x00158d0002c64b73"'
  zigbee2mqtt:debug 2018-12-5 19:23:11 Received zigbee message of type 'devInterview' with data '"0x00158d0002c64b73"'
  zigbee2mqtt:debug 2018-12-5 19:23:11 Received zigbee message of type 'devInterview' with data '"0x00158d0002c64b73"'
  zigbee2mqtt:debug 2018-12-5 19:23:11 Received zigbee message of type 'devInterview' with data '"0x00158d0002c64b73"'
  zigbee2mqtt:debug 2018-12-5 19:23:11 Received zigbee message of type 'devIncoming' with data '"0x00158d0002c64b73"' of device 'lumi.light.aqcn02' (0x00158d0002c64b73)
  zigbee2mqtt:info 2018-12-5 19:23:11 Device incoming...
  zigbee2mqtt:info 2018-12-5 19:23:11 MQTT publish, topic: 'zigbee2mqtt/bridge/log', payload: '{"type":"pairing","message":"device incoming"}'
  zigbee2mqtt:warn 2018-12-5 19:23:11 Device with modelID 'lumi.light.aqcn02' is not supported.
  zigbee2mqtt:warn 2018-12-5 19:23:11 Please see: https://github.com/Koenkk/zigbee2mqtt/wiki/How-to-support-new-devices
  zigbee2mqtt:debug 2018-12-5 19:23:11 Received zigbee message of type 'devStatus' with data '"online"' of device 'lumi.light.aqcn02' (0x00158d0002c64b73)
  zigbee2mqtt:warn 2018-12-5 19:23:11 Device with modelID 'lumi.light.aqcn02' is not supported.
  zigbee2mqtt:warn 2018-12-5 19:23:11 Please see: https://github.com/Koenkk/zigbee2mqtt/wiki/How-to-support-new-devices

>

**Comment by Koenkk** [comment] 2018-12-05 09:05
What features does this bulb support; brightness and color temperature?

**Comment by Koenkk** [comment] 2018-12-05 14:41
Can you add to `devices.js`:

```js
    {
        zigbeeModel: ['lumi.light.aqcn02'],
        model: 'ZNLDP12LM',
        vendor: 'Xiaomi',
        description: 'Aqara smart LED bulb',
        supports: generic.light_onoff_brightness_colortemp().supports,
        fromZigbee: generic.light_onoff_brightness_colortemp().fromZigbee,
        toZigbee: generic.light_onoff_brightness_colortemp().toZigbee,
    },
```

**Comment by kiwinol** [comment] 2018-12-07 09:34
I will try this tomorrow.  

I see that its now possible to add an external devices.js in /share/zigbee2mqtt and set "zigbee_shepherd_devices": "true" in the addon config, is this correct?

if so can I just add the following to the devices.js file?

```
     {
        zigbeeModel: ['lumi.light.aqcn02'],
        model: 'ZNLDP12LM',
        vendor: 'Xiaomi',
        description: 'Aqara smart LED bulb',
        supports: generic.light_onoff_brightness_colortemp().supports,
        fromZigbee: generic.light_onoff_brightness_colortemp().fromZigbee,
        toZigbee: generic.light_onoff_brightness_colortemp().toZigbee,
    },
`````

Also is the last coma required?

**Comment by Koenkk** [comment] 2018-12-07 17:05
Yes, but note this replace the whole `devices.js` (so devices which are not in that file won't work anymore) (https://github.com/Koenkk/zigbee2mqtt/wiki/How-to-support-new-devices-on-Hass.io)

**Comment by kiwinol** [comment] 2018-12-07 20:53
I have updated devices.js now I get

```
zigbee2mqtt:debug 2018-12-8 07:51:26 Received zigbee message of type 'attReport' with data '{"cid":"genBasic","data":{"65281":{"3":74,"5":11,"7":"0x0000000000000000","8":278,"9":768,"10":13100,"100":1,"101":255,"102":153}}}' of device 'lumi.light.aqcn02' (0x00158d0002c64b73)
  zigbee2mqtt:warn 2018-12-8 07:51:26 No converter available for 'ZNLDP12LM' with cid 'genBasic', type 'attReport' and data '{"cid":"genBasic","data":{"65281":{"3":74,"5":11,"7":"0x0000000000000000","8":278,"9":768,"10":13100,"100":1,"101":255,"102":153}}}'
  zigbee2mqtt:warn 2018-12-8 07:51:26 Please see: https://github.com/Koenkk/zigbee2mqtt/wiki/How-to-support-new-devices.
```

**Comment by Koenkk** [comment] 2018-12-09 18:55
We need to find out what the values mean.

Does turning on/off via MQTT work?

**Comment by kiwinol** [comment] 2018-12-10 08:38
No.  If I publish:
```
{"state": "OFF"}
```
to:
```
 zigbee2mqtt/0x00158d0002c64b73/set
```

it doesnt seem to have any effect.  I double checked I wasnt making a mistake by publishing the ON and OFF states to one of my working Philips Hue bulbs and that does repond.

**Comment by Koenkk** [comment] 2018-12-10 16:42
Ok, we need to sniff the packets send by the xiaomi gateway in order to support this bulb. (http://www.inzoolee.com/capture-zigbee-packets/)

**Comment by kiwinol** [comment] 2018-12-10 21:17
I was so excited by this project I sold my Xiaomi gateway :(.  I am going to borrow one off my friend (who bought it off me!) hopefully tomorrow and try this in the next couple of days.

Just to clarify.  I would pair the bulb with the Xiaomi gateway then follow the article to capture zigbee packets for On/Off, Brightness Increase,Decrease and color temp Increase,Decrease?

**Comment by kiwinol** [comment] 2018-12-11 22:08
@Koenkk can I use the same firmware I was using for zigbee2mqtt or will I need to flash a different firmware?

**Comment by Koenkk** [comment] 2018-12-12 10:32
You can use the firmware which is included in [PACKET SNIFFER](http://www.ti.com/tool/PACKET-SNIFFER)

**Comment by kiwinol** [comment] 2018-12-12 11:19
I downloaded and installed
```
PACKET-SNIFFER:
SmartRF Protocol Packet Sniffer

http://www.ti.com/general/docs/lit/getliterature.tsp?baseLiteratureNumber=swrc045&fileType=zip
```
I am not sure which firmware to use.  Below is a screenshot of the folders I see:
[https://ibb.co/DKG4y1d](url)

**Comment by Koenkk** [comment] 2018-12-12 11:49
If I remember correctly, it's in the cc debugger directory.

**Comment by kirovilya** [comment] 2018-12-12 11:58
Something did wrong ...
I was informed that someone managed to connect a light bulb and it works through clusters genOnOff, genLevelCtrl, lightingColorCtrl.
But I can not check it myself - there is no lamp.

**Comment by kiwinol** [comment] 2018-12-13 00:07
> genLevelCtrl, lightingColorCtrl

Can you provide more details of how to test?  I have the bulb but not much knowledge on how this works.

**Comment by kirovilya** [comment] 2018-12-13 05:58
@kiwinol After change devices-file, try to run zigbee2mqtt in debug mode https://github.com/Koenkk/zigbee2mqtt/wiki/How-to-debug , pair lamp and then try to turn on/off, set brightness, color temp by send message to topics.
You will have a log file with information about sending messages to the lamp and responses from it. Share it (via pastebin for example).
If the lamp did not accept commands, you would have received error messages. In other cases, commands must be accepted.

**Comment by kirovilya** [comment] 2018-12-13 06:01
https://gist.github.com/itsmepetrov/79ae4aef70cce328d2c93ea1334af07f It is an example of improvements for this lamp from the project https://github.com/itsmepetrov/homebridge-zigbee
These improvements look like a normal lamp. And it is works.

**Comment by kiwinol** [comment] 2018-12-14 04:34
@kirovilya thanks for the information. I will try to investigate more this weekend.

**Comment by kiwinol** [comment] 2018-12-14 08:09
@Koenkk I got the debugger firmware flashed and am now able to capture zigbee traffic.  Tomorrow I will switch off my HA to reduce noise and capture the traffic between the Xiaomi hub and the bulb.

**Comment by kiwinol** [comment] 2018-12-14 23:42
[Aqarabulb_1034_aus_time.zip](https://github.com/Koenkk/zigbee2mqtt/files/2682003/Aqarabulb_1034_aus_time.zip)

I have tried to do the capture.  It was all done at about 10:34am Australian time.

The sequence I tried was.
On
Increase Brightness
Decrease Brightness
Increase Color Temp
Decrease Color Temp
Off

Let me know if I need to redo it or you require more info I wasnt sure how to filter it and there are probably messages from many other zigbee devices I have at the same time.

**Comment by trfr3ak** [comment] 2018-12-15 16:57
Okay, I can now confirm, that everything just works, when you treat the device like any other bulb, I can change color_temp and brightness, everything works, with the config from above.

**Comment by kirovilya** [comment] 2018-12-15 17:00
@trfr3ak Excellent! I thought so. Thanks for checking out - can you make the PR to converters?

**Comment by trfr3ak** [comment] 2018-12-15 17:06
@kirovilya I can try, but im not quite sure, what to do. Should I add something to the fromZigbee.js?

**Comment by trfr3ak** [comment] 2018-12-15 17:09
These seem to be the missing converters:
`No converter available for 'ZNLDP12LM' with cid 'genLevelCtrl', type 'attReport' and data '{"cid":"genLevelCtrl","data":{"61440":11383040,"currentLevel":255}}'
No converter available for 'ZNLDP12LM' with cid 'genOnOff', type 'attReport' and data '{"cid":"genOnOff","data":{"61440":117440706,"onOff":1}}'
No converter available for 'ZNLDP12LM' with cid 'genBasic', type 'devChange' and data '{"cid":"genBasic","data":{"65281":[null,null,null,null,null,null,null,"0x0000000000000000",278,512,0,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1,255]}}'
No converter available for 'ZNLDP12LM' with cid 'genBasic', type 'attReport' and data '{"cid":"genBasic","data":{"65281":{"3":60,"5":62,"7":"0x0000000000000000","8":278,"9":512,"10":0,"100":1,"101":255,"102":319}}}'
No converter available for 'ZNLDP12LM' with cid 'lightingColorCtrl', type 'attReport' and data '{"cid":"lightingColorCtrl","data":{"61440":117440703,"colorTemperature":319}}'
  
`

**Comment by phoxy84** [comment] 2018-12-16 11:37
Sounds good, any idea when it is available in the edge version?

**Comment by liads** [comment] 2018-12-17 01:44
Just got my bulbs today.
The commands to the bulb seem to work correctly with the above configuration.
However, some messages from the bulb don't have mapped converters.
The bulb appears to be sending some messages twice, once with 'attReport' type and again with 'devChange' type). For example, after a single turn off request I get:
```
Received zigbee message of type 'attReport' with data '{"cid":"genOnOff","data":{"61440":117440683,"onOff":0}}' of device 'lumi.light.aqcn02'
Received zigbee message of type 'devChange' with data '{"cid":"genOnOff","data":{"61440":117440683,"onOff":0}}' of device 'lumi.light.aqcn02'
Received zigbee message of type 'attReport' with data '{"cid":"genOnOff","data":{"61440":6928384,"onOff":0}}' of device 'lumi.light.aqcn02'
Received zigbee message of type 'devChange' with data '{"cid":"genOnOff","data":{"61440":6928384}}' of device 'lumi.light.aqcn02'
```
After a brightness change:
```
Received zigbee message of type 'attReport' with data '{"cid":"genLevelCtrl","data":{"61440":117440689,"currentLevel":100}}' of device 'lumi.light.aqcn02'
Received zigbee message of type 'devChange' with data '{"cid":"genLevelCtrl","data":{"61440":117440689,"currentLevel":100}}' of device 'lumi.light.aqcn02'
Received zigbee message of type 'attReport' with data '{"cid":"genLevelCtrl","data":{"61440":6928384,"currentLevel":100}}' of device 'lumi.light.aqcn02'
Received zigbee message of type 'devChange' with data '{"cid":"genLevelCtrl","data":{"61440":6928384}}' of device 'lumi.light.aqcn02'
```
And so on.
The devChange type is handled properly by the generic light converters, but the attReport type causes a no converter warning.
I think it should be safe to ignore the duplicate attReport messages, but I wonder if those "genBasic" messages might have useful data we should decipher:
```
Received zigbee message of type 'attReport' with data '{"cid":"genBasic","data":{"65281":{"3":74,"5":100,"7":"0x0000000000000000","8":278,"9":513,"10":0,"100":1,"101":100,"102":500}}}' of device 'lumi.light.aqcn02'
Received zigbee message of type 'devChange' with data '{"cid":"genBasic","data":{"65281":[null,null,null,74,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1,100]}}' of device 'lumi.light.aqcn02'
```

**Comment by phoxy84** [comment] 2018-12-17 18:43
This is my log:

```
  zigbee2mqtt:warn 2018-12-17 19:41:44 No converter available for 'ZNLDP12LM' with cid 'genBasic', type 'attReport' and data '{"cid":"genBasic","data":{"dateCode":"09-30-2018"}}'
  zigbee2mqtt:warn 2018-12-17 19:41:44 Please see: https://github.com/Koenkk/zigbee2mqtt/wiki/How-to-support-new-devices.
  zigbee2mqtt:warn 2018-12-17 19:41:44 No converter available for 'ZNLDP12LM' with cid 'genBasic', type 'attReport' and data '{"cid":"genBasic","data":{"65281":{"3":95,"5":77,"7":"0x0000000000000000","8":278,"9":768,"10":0,"100":1,"101":255,"102":153}}}'
  zigbee2mqtt:warn 2018-12-17 19:41:44 Please see: https://github.com/Koenkk/zigbee2mqtt/wiki/How-to-support-new-devices.
  zigbee2mqtt:warn 2018-12-17 19:41:44 No converter available for 'ZNLDP12LM' with cid 'genBasic', type 'devChange' and data '{"cid":"genBasic","data":{"65281":[null,null,null,95,null,77,null,"0x0000000000000000",278,768,0,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1,255,153]}}'
  zigbee2mqtt:warn 2018-12-17 19:41:44 Please see: https://github.com/Koenkk/zigbee2mqtt/wiki/How-to-support-new-devices.
  zigbee2mqtt:warn 2018-12-17 19:41:44 No converter available for 'ZNLDP12LM' with cid 'genBasic', type 'attReport' and data '{"cid":"genBasic","data":{"65281":{"3":95,"5":77,"7":"0x0000000000000000","8":278,"9":768,"10":0,"100":1,"101":255,"102":153}}}'
  zigbee2mqtt:warn 2018-12-17 19:41:44 Please see: https://github.com/Koenkk/zigbee2mqtt/wiki/How-to-support-new-devices.
```

**Comment by liads** [comment] 2018-12-18 02:04
I noticed that whenever this bulb omitted the onOff attribute from the devChange genOnOff messages, an OFF state was being published to MQTT even though the bulb could still be on.
I managed to get stable behavior with the following in devices.js:
```
    {
        zigbeeModel: ['lumi.light.aqcn02'],
        model: 'ZNLDP12LM',
        vendor: 'Xiaomi',
        description: 'Aqara smart LED bulb',
        supports: generic.light_onoff_brightness_colortemp().supports,
        fromZigbee: [fz.light_brightness, fz.light_color_colortemp, fz.generic_state, fz.ignore_basic_change, fz.ignore_basic_report],
        toZigbee: generic.light_onoff_brightness_colortemp().toZigbee,
    },
```
I used the following config to test this in Home Assistant:
```
light:
  - platform: mqtt
    schema: json
    command_topic: "zigbee2mqtt/hall_bulb/set"
    state_topic: zigbee2mqtt/hall_bulb
    availability_topic: zigbee2mqtt/bridge/state
    name: Hall light (test)
    brightness: true
    color_temp: true
```

If this works for everyone, I can add converters to ignore the remaining messages and make a PR.

**Comment by kiwinol** [comment] 2018-12-18 05:53
> I noticed that whenever this bulb omitted the onOff attribute from the devChange genOnOff messages, an OFF state was being published to MQTT even though the bulb could still be on.
> I managed to get stable behavior with the following in devices.js:
> 
> ```
>     {
>         zigbeeModel: ['lumi.light.aqcn02'],
>         model: 'ZNLDP12LM',
>         vendor: 'Xiaomi',
>         description: 'Aqara smart LED bulb',
>         supports: generic.light_onoff_brightness_colortemp().supports,
>         fromZigbee: [fz.light_brightness, fz.light_color_colortemp, fz.generic_state, fz.ignore_basic_change, fz.ignore_basic_report],
>         toZigbee: generic.light_onoff_brightness_colortemp().toZigbee,
>     },
> ```
> I used the following config to test this in Home Assistant: (change topics to match your device id)
> 
> ```
> light:
>   - platform: mqtt
>     schema: json
>     command_topic: "zigbee2mqtt/hall_bulb/set"
>     state_topic: zigbee2mqtt/hall_bulb
>     availability_topic: zigbee2mqtt/bridge/state
>     name: Hall light (test)
>     brightness: true
>     color_temp: true
> ```
> If this works for everyone, I can add converters to ignore the remaining messages and make a PR.

Following your configuration it works fine for me 🥇

**Comment by phoxy84** [comment] 2018-12-18 11:23
I can confirm that the config works. I can turn the bulb on/off, change brightness and temp.

**Comment by phoxy84** [comment] 2018-12-19 07:47
So the supoort is there?

**Comment by liads** [comment] 2018-12-19 12:05
Yes.
Once this gets merged and referenced from the main repository, you'd be able to see it in the edge version.

**Comment by gualostly** [comment] 2018-12-20 00:00
Thanks everyone for their work in supporting this affordable bulb!
Mine arrived yesterday and I'm excited to connect it to HA via zigbee2mqtt. But I don't know how to change it to pairing mode (tried off/on 3 times, no dice). Any ideas? Thank you!

**Comment by kiwinol** [comment] 2018-12-20 00:04
> Thanks everyone for their work in supporting this affordable bulb!
> Mine arrived yesterday and I'm excited to connect it to HA via zigbee2mqtt. But I don't know how to change it to pairing mode (tried off/on 3 times, no dice). Any ideas? Thank you!

I think its 5 times.  Mine just paired when I first tried without setting it.  It will start blinking when you have reset it.

**Comment by Koenkk** [comment] 2018-12-20 06:56
Bulb is supported in the dev branch. thanks all!

**Closed by Koenkk** 2018-12-20 06:56 UTC

**Comment by kindnation** [comment] 2018-12-29 10:33
Do you know how long it usually takes before a device is supported in the standard version (not edge)?

**Comment by phoxy84** [comment] 2019-01-04 21:21
When will it come in standard version? It's not supported in latest version. I tried dev but latest gives a couple of errors:

```
  zigbee2mqtt:info 2019-1-4 22:20:04 MQTT publish: topic 'zigbee2mqtt/0x00158d0002c65c4b', payload '{"state":"ON","linkquality":0,"last_seen":"2019-01-04T21:20:04.275Z","color_temp":369,"color":{"x":0.462,"y":0.415}}'
  zigbee2mqtt:info 2019-1-4 22:20:10 Zigbee publish to device '0x00158d0002c65c4b', genLevelCtrl - moveToLevelWithOnOff - {"level":139,"transtime":0} - {"manufSpec":0,"disDefaultRsp":0} - null
  zigbee2mqtt:info 2019-1-4 22:20:10 MQTT publish: topic 'zigbee2mqtt/0x00158d0002c65c4b', payload '{"state":"ON","linkquality":0,"last_seen":"2019-01-04T21:20:10.372Z","brightness":139,"color_temp":369,"color":{"x":0.462,"y":0.415}}'
  zigbee2mqtt:info 2019-1-4 22:20:10 MQTT publish: topic 'zigbee2mqtt/0x00158d0002c65c4b', payload '{"state":"ON","linkquality":0,"last_seen":"2019-01-04T21:20:10.414Z","color_temp":369,"color":{"x":0.462,"y":0.415}}'
  zigbee2mqtt:info 2019-1-4 22:20:10 MQTT publish: topic 'zigbee2mqtt/0x00158d0002c65c4b', payload '{"state":"ON","linkquality":0,"last_seen":"2019-01-04T21:20:10.414Z","color_temp":369,"color":{"x":0.462,"y":0.415}}'
  zigbee2mqtt:info 2019-1-4 22:20:14 Zigbee publish to device '0x00158d0002c65c4b', genOnOff - off - {} - {"manufSpec":0,"disDefaultRsp":0} - null
  zigbee2mqtt:error 2019-1-4 22:20:20 Zigbee publish to device '0x00158d0002c65c4b', genOnOff - off - {} - {"manufSpec":0,"disDefaultRsp":0} - null failed with error Error: AF data request fails, status code: 205. No network route. Please confirm that the device has (re)joined the network.
  zigbee2mqtt:info 2019-1-4 22:20:20 Zigbee publish to device '0x00158d0002c65c4b', genOnOff - off - {} - {"manufSpec":0,"disDefaultRsp":0} - null
  zigbee2mqtt:error 2019-1-4 22:20:21 Zigbee publish to device '0x00158d0002c65c4b', genOnOff - off - {} - {"manufSpec":0,"disDefaultRsp":0} - null failed with error Error: AF data request fails, status code: 233. MAC no ack.
```

**Comment by soosterwaal** [comment] 2019-01-05 09:31
I got a bulb since yesterday, but im unable to pair it. It simple doesn't show up. Wat is the pairing method of the bulb?

**Comment by phoxy84** [comment] 2019-01-05 09:37
Switch on five times till the bulb blinks a couple of times

**Comment by honzaka** [comment] 2019-03-31 17:33
Does anyone know what is the min. and max. value for "color_temp" in payload? Thank you.

**Comment by ranchoiver** [comment] 2019-04-06 00:03
Also can't pair the bulb even after resetting it.. How did you do it?

Do you need to hold CC2531 sniffer near the bulb?

**Comment by honzaka** [comment] 2019-04-06 06:06
I have made a “homemade pairing cable” with standard wall connector, switch and bulb socket - about 2 meters long. With this cable I am able to pair bulb just next to sniffer without problem.

**Comment by GreenVine** [comment] 2019-04-06 10:06
Same here. Switched on five times and the bulb starts blinking, but nothing is showing in the log. Can someone confirm this bulb supports channel 25?

**Comment by urusha** [comment] 2019-04-08 19:32
@GreenVine have 3 pieces on channel 25, pairs/works fine. Try to remove from mqtt/configuration.yaml/database.db/state.json and re-pair.

**Comment by Perlovka** [comment] 2019-04-13 10:39
> Does anyone know what is the min. and max. value for "color_temp" in payload? Thank you.

153 - 370

Found here:
https://github.com/TedTolboom/com.xiaomi-mi-zigbee/blob/master/drivers/light.aqcn02/device.js

**Comment by GreenVine** [comment] 2019-04-13 10:43
@urusha It looks like this bulb cannot pair directly with the router (one Philips Hue light bulb). As soon as I move the coordinator closer with Xiaomi bulb it pairs flawlessly. I didn’t spot any issues after moving coordinator back and let Xiaomi communicate with the router.

Looks like we can’t pair it with the router?

**Comment by Perlovka** [comment] 2019-04-13 11:13
There is one issue with these bulbs. They are always powered ON after power outage :-/

**Comment by honzaka** [comment] 2019-04-15 11:28
> > Does anyone know what is the min. and max. value for "color_temp" in payload? Thank you.
> 
> 153 - 370
> 
> Found here:
> https://github.com/TedTolboom/com.xiaomi-mi-zigbee/blob/master/drivers/light.aqcn02/device.js

Great, thanks!
