### ISSUE TITLE
Can't start npm in windows

### ISSUE THREAD

**Issue by leyuansugar** [Koenkk/zigbee2mqtt#2915] opened 2020-02-08 10:33 UTC
Need help with it.

`C:\Users\leyua\Desktop\SmatHome\zigbee2mqtt-master>npm start

> zigbee2mqtt@1.10.0 start C:\Users\leyua\Desktop\SmatHome\zigbee2mqtt-master
> node index.js

zigbee2mqtt:info  2020-02-08 18:28:28: Logging to console and directory: 'C:\Users\leyua\Desktop\SmatHome\zigbee2mqtt-master\data\log\2020-02-08.18-28-28' filename: log.txt
zigbee2mqtt:info  2020-02-08 18:28:28: Starting zigbee2mqtt version 1.10.0 (commit #unknown)
zigbee2mqtt:info  2020-02-08 18:28:28: Starting zigbee-herdsman...
zigbee2mqtt:error 2020-02-08 18:29:17: Error while starting zigbee-herdsman
zigbee2mqtt:error 2020-02-08 18:29:44: Failed to start zigbee
zigbee2mqtt:error 2020-02-08 18:29:44: Exiting...
zigbee2mqtt:error 2020-02-08 18:29:44: Error: AREQ - SYS - resetInd after 30000ms
    at Timeout._onTimeout (C:\Users\leyua\Desktop\SmatHome\zigbee2mqtt-master\node_modules\zigbee-herdsman\dist\utils\waitress.js:44:24)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.10.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zigbee2mqtt@1.10.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\leyua\AppData\Roaming\npm-cache\_logs\2020-02-08T10_29_44_327Z-debug.log

C:\Users\leyua\Desktop\SmatHome\zigbee2mqtt-master>npm start

> zigbee2mqtt@1.10.0 start C:\Users\leyua\Desktop\SmatHome\zigbee2mqtt-master
> node index.js

zigbee2mqtt:info  2020-02-08 18:30:03: Logging to console and directory: 'C:\Users\leyua\Desktop\SmatHome\zigbee2mqtt-master\data\log\2020-02-08.18-30-03' filename: log.txt
zigbee2mqtt:info  2020-02-08 18:30:03: Starting zigbee2mqtt version 1.10.0 (commit #unknown)
zigbee2mqtt:info  2020-02-08 18:30:03: Starting zigbee-herdsman...
zigbee2mqtt:error 2020-02-08 18:30:03: Error while starting zigbee-herdsman
zigbee2mqtt:error 2020-02-08 18:30:03: Failed to start zigbee
zigbee2mqtt:error 2020-02-08 18:30:03: Exiting...
zigbee2mqtt:error 2020-02-08 18:30:03: Error: Error while opening socket
    at Socket.<anonymous> (C:\Users\leyua\Desktop\SmatHome\zigbee2mqtt-master\node_modules\zigbee-herdsman\dist\adapter\z-stack\znp\znp.js:162:28)
    at Socket.emit (events.js:228:7)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.10.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zigbee2mqtt@1.10.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\leyua\AppData\Roaming\npm-cache\_logs\2020-02-08T10_30_03_923Z-debug.log`

debuglog

`info  2020-02-08 18:30:03: Logging to console and directory: 'C:\Users\leyua\Desktop\SmatHome\zigbee2mqtt-master\data\log\2020-02-08.18-30-03' filename: log.txt
info  2020-02-08 18:30:03: Starting zigbee2mqtt version 1.10.0 (commit #unknown)
info  2020-02-08 18:30:03: Starting zigbee-herdsman...
error 2020-02-08 18:30:03: Error while starting zigbee-herdsman
`

**Comment by Koenkk** [comment] 2020-02-08 13:39
Duplicate of #2899

**Closed by Koenkk** 2020-02-08 13:39 UTC
