### ISSUE TITLE
[Problem]: Zigbee2mqtt changed the type of zigbee device and now it does not work

### ISSUE THREAD

**Issue by rafaamcarvalho** [Koenkk/zigbee2mqtt#10549] opened 2022-01-03 22:05 UTC
### What happened?

I'm not into programming at all, just use my home assistant in my home. Since I updated to this version of zigbee2mqtt, my 2 devices (Nue / 3A HGZB-042 - Zigbee 2 gang switch) are now being recognized as (Nue / 3A HGZB-042 - zigbee double power point). I believe that the problem is that the payloads (i guess it is called payload) of the gang are "top" and "bottom" and now the device on the zigbee2mqtt sends "left" and "right".

### What did you expect to happen?

I expect that it would work properly but since I updated it did not

### How to reproduce it (minimal and precise)

First force remove the device from the list, then allow join in zigbee network, then when it pairs it does not pair correctly.

### Zigbee2MQTT version

1.22.2

### Adapter firmware version

20210319

### Adapter

SMARTLIGHT CC2652P Zigbee USB Adapter SLZB-02

### Debug log

error 2022-01-01 10:47:13: Failed to configure 'presenca_quarto', attempt 1 (Error: Read 0x00124b002267e38e/1 genPowerCfg(["batteryVoltage"], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 45348 - 1 - 28 - 1 - 1 after 10000ms)
    at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7))
error 2022-01-01 16:36:16: Error: CommandResponse 0x00158d00041827f7/11 genOta.queryNextImageResponse({"status":152}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":1,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'MAC channel access failure' (225))
warn  2022-01-02 22:06:31: Device 'quarto' left the network
error 2022-01-02 22:06:55: Device 'quarto' has no endpoint 'left'
error 2022-01-02 22:06:56: Device 'quarto' has no endpoint 'left'
error 2022-01-02 22:06:57: Device 'quarto' has no endpoint 'left'
error 2022-01-02 22:07:34: Device 'quarto_cama' has no endpoint 'left'
error 2022-01-02 22:07:34: Device 'quarto_cama' has no endpoint 'left'
error 2022-01-02 22:07:35: Device 'quarto_cama' has no endpoint 'left'
error 2022-01-02 22:07:56: Device 'quarto' has no endpoint 'left'
warn  2022-01-03 18:34:37: Device '0x00158d000457a189' left the network
error 2022-01-03 18:35:06: Device '0x00158d000457a189' has no endpoint 'left'
error 2022-01-03 18:35:07: Device '0x00158d000457a189' has no endpoint 'left'

**Comment by Koenkk** [comment] 2022-01-04 18:18
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/10497, already fixed in the dev branch.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Closed by Koenkk** 2022-01-04 18:18 UTC
Labels: problem
