### ISSUE TITLE
1.6.0 Fails to start: Unhandled 'error' event

### ISSUE THREAD

**Issue by syphernl** [Koenkk/zigbee2mqtt#1949] opened 2019-09-10 08:23 UTC
# Bug Report
## What happened
After updating 1.5.1 to 1.6.0 via update.sh, zigbee2mqtt fails to start. It throws an exception and exits.

## Logs
https://hastebin.com/ehejamuqop.coffeescript

## What did you expect to happen
Z2M starting up without an error.

## How to reproduce it (minimal and precise)
Update 1.5.1 to 1.6.0 via `./update.sh`

## Debug Info
zigbee2mqtt version: `1.6.0`
CC253X firmware version: `20190608`
NPM version: `6.11.3`
Node version: `v10.15.1`

**Comment by Flappiee** [comment] 2019-09-10 08:38
Same problem here after updating to 1.6.0

First, a lot of errors on install dependencies:
npm WARN tar ENOENT: no such file or directory, lstat '/opt/zigbee2mqtt/node_modules/.staging/rxjs-bd0b8a77/internal/util'
npm WARN tar ENOENT: no such file or directory, lstat '/opt/zigbee2mqtt/node_modules/.staging/rxjs-bd0b8a77/internal/util'
npm WARN tar ENOENT: no such file or directory, lstat '/opt/zigbee2mqtt/node_modules/.staging/rxjs-bd0b8a77/internal/util'
npm WARN tar ENOENT: no such file or directory, lstat '/opt/zigbee2mqtt/node_modules/.staging/rxjs-bd0b8a77/internal/util'
npm WARN tar ENOENT: no such file or directory, lstat '/opt/zigbee2mqtt/node_modules/.staging/rxjs-bd0b8a77/internal/util'
npm WARN tar ENOENT: no such file or directory, lstat '/opt/zigbee2mqtt/node_modules/.staging/rxjs-bd0b8a77/internal/util'
npm WARN tar ENOENT: no such file or directory, lstat '/opt/zigbee2mqtt/node_modules/.staging/rxjs-bd0b8a77/internal/util'
npm WARN tar ENOENT: no such file or directory, lstat '/opt/zigbee2mqtt/node_modules/.staging/rxjs-bd0b8a77/internal/util'
npm WARN tar ENOENT: no such file or directory, lstat '/opt/zigbee2mqtt/node_modules/.staging/rxjs-bd0b8a77/internal/util'
npm WARN tar ENOENT: no such file or directory, lstat '/opt/zigbee2mqtt/node_modules/.staging/rxjs-bd0b8a77/internal/util'
npm WARN tar ENOENT: no such file or directory, lstat '/opt/zigbee2mqtt/node_modules/.staging/rxjs-bd0b8a77/internal/util'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: emoji-regex@7.0.3 (node_modules/zigbee-shepherd-converters/node_modules/zigbee-herdsman/node_modules/emoji-regex):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: request to https://registry.npmjs.org/emoji-regex/-/emoji-regex-7.0.3.tgz failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org registry.npmjs.org:443

npm ERR! Maximum call stack size exceeded

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-09-10T07_55_38_719Z-debug.log


En starting Zigbee2MQTT gives me this:

Sep 10 09:58:36 domoticz-pihole systemd[1]: Started zigbee2mqtt. Sep 10 09:58:37 domoticz-pihole npm[3622]: > zigbee2mqtt@1.6.0 start /opt/zigbee2mqtt Sep 10 09:58:37 domoticz-pihole npm[3622]: > node index.js Sep 10 09:58:38 domoticz-pihole npm[3622]: internal/modules/cjs/loader.js:638 Sep 10 09:58:38 domoticz-pihole npm[3622]:     throw err; Sep 10 09:58:38 domoticz-pihole npm[3622]:     ^ Sep 10 09:58:38 domoticz-pihole npm[3622]: Error: Cannot find module 'semver' Sep 10 09:58:38 domoticz-pihole npm[3622]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15) Sep 10 09:58:38 domoticz-pihole npm[3622]:     at Function.Module._load (internal/modules/cjs/loader.js:562:25) Sep 10 09:58:38 domoticz-pihole npm[3622]:     at Module.require (internal/modules/cjs/loader.js:692:17) Sep 10 09:58:38 domoticz-pihole npm[3622]:     at require (internal/modules/cjs/helpers.js:25:18) Sep 10 09:58:38 domoticz-pihole npm[3622]:     at Object.<anonymous> (/opt/zigbee2mqtt/index.js:1:16) Sep 10 09:58:38 domoticz-pihole npm[3622]:     at Module._compile (internal/modules/cjs/loader.js:778:30) Sep 10 09:58:38 domoticz-pihole npm[3622]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10) Sep 10 09:58:38 domoticz-pihole npm[3622]:     at Module.load (internal/modules/cjs/loader.js:653:32) Sep 10 09:58:38 domoticz-pihole npm[3622]:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12) Sep 10 09:58:38 domoticz-pihole npm[3622]:     at Function.Module._load (internal/modules/cjs/loader.js:585:3) Sep 10 09:58:38 domoticz-pihole npm[3622]: npm ERR! code ELIFECYCLE Sep 10 09:58:38 domoticz-pihole npm[3622]: npm ERR! errno 1 Sep 10 09:58:38 domoticz-pihole npm[3622]: npm ERR! zigbee2mqtt@1.6.0 start: `node index.js` Sep 10 09:58:38 domoticz-pihole npm[3622]: npm ERR! Exit status 1 Sep 10 09:58:38 domoticz-pihole npm[3622]: npm ERR! Sep 10 09:58:38 domoticz-pihole npm[3622]: npm ERR! Failed at the zigbee2mqtt@1.6.0 start script. Sep 10 09:58:38 domoticz-pihole npm[3622]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above. Sep 10 09:58:38 domoticz-pihole npm[3622]: npm ERR! A complete log of this run can be found in: Sep 10 09:58:38 domoticz-pihole npm[3622]: npm ERR!     /home/pi/.npm/_logs/2019-09-10T07_58_38_098Z-debug.log Sep 10 09:58:38 domoticz-pihole systemd[1]: zigbee2mqtt.service: Main process exited, code=exited, status=1/FAILURE Sep 10 09:58:38 domoticz-pihole systemd[1]: zigbee2mqtt.service: Unit entered failed state. Sep 10 09:58:38 domoticz-pihole systemd[1]: zigbee2mqtt.service: Failed with result 'exit-code'. Sep 10 09:58:38 domoticz-pihole systemd[1]: zigbee2mqtt.service: Service hold-off time over, scheduling restart. Sep 10 09:58:38 domoticz-pihole systemd[1]: Stopped zigbee2mqtt.
--

**Comment by MarsWarrior** [comment] 2019-09-10 08:58
I see zigbee-herdsman in the logging. That shouldnot be in 1.6??

**Comment by Koenkk** [comment] 2019-09-10 09:16
@syphernl what is the output of `ls /dev` and what's is in your `configuration.yaml`?

@Flappiee you are experiencing an npm issue, please try:

```
sudo npm install -g npm
rm -rf node_modules
npm install
```
if the problem is not fixed, please create a new issue

**Comment by syphernl** [comment] 2019-09-10 09:35
@Koenkk Ok this is pretty weird.. For some reason my device changed from `ttyACM0` (configured) to `ttyACM1`. It was working fine before though and I only upgraded/restarted Z2M. It's working fine now, thanks!

**Comment by Flappiee** [comment] 2019-09-10 10:23
Ended up with removing complete /opt/zigbee2mqtt directory and reinstall it and npm install gives me this errors and then stops:
https://pastebin.com/nSKXUFXB

**Comment by Koenkk** [comment] 2019-09-10 11:47
@Flappiee looks like an npm/connectivity issue (https://github.com/npm/npm/issues/16661). I will close this as the original of @syphernl has been resolved.

**Closed by Koenkk** 2019-09-10 11:47 UTC
