### ISSUE TITLE
ECO-DIM dimmer removed after latest update?

### ISSUE THREAD

**Issue by Pliind** [Koenkk/zigbee2mqtt#7294] opened 2021-05-02 17:48 UTC
Updated to latest version and now it's gone.

ECO-Dim (in-wall) dimmer 10 

some "proof" of existence here: https://github.com/Koenkk/zigbee2mqtt/issues/2342

**Comment by Koenkk** [comment] 2021-05-02 17:57
Duplicate of https://github.com/Koenkk/zigbee2mqtt/discussions/7282

**Closed by Koenkk** 2021-05-02 17:57 UTC
Labels: problem
