### ISSUE TITLE
[Problem]: TuYa TS0601_thermostat time is not set correct

### ISSUE THREAD

**Issue by CSchoch** [Koenkk/zigbee2mqtt#10665] opened 2022-01-08 20:17 UTC
### What happened?

After i power on my device and zigbee connection is established it shows always 6:38 as the current time.
In Version 1.22.1 it works as expected.

### What did you expect to happen?

The device should show the actual time.

### How to reproduce it (minimal and precise)

1. Power on the the thermostat
2. Press Ok
2. Wait until the connection icon shows up
3. Press Ok
4. Wrong time is shown

### Zigbee2MQTT version

1.22.2

### Adapter firmware version

20211217

### Adapter

Zigstar Lan Gateway

### Debug log

-

**Comment by Koenkk** [comment] 2022-01-09 12:48
Duplicate of #10489

**Closed by Koenkk** 2022-01-09 12:48 UTC
Labels: problem
