### ISSUE TITLE
Ajax Online Vintage Smart Bulb "Unsupported" in 1.25.2

### ISSUE THREAD

**Issue by ashleytayles** [Koenkk/zigbee2mqtt#12713] opened 2022-06-04 14:52 UTC
### What happened?

I have an Ajax Online "vintage' bulb that when paired joined to Z2M shows as a "Paulmann" model 50064. In version 1.25.1 it works perfectly and pairs like this:

![image](https://user-images.githubusercontent.com/9968265/172008104-c39d86ce-105c-48e4-8e30-5af8d098d2a5.png)

In the latest version however, it does not work and shows as "unsupported"

![image](https://user-images.githubusercontent.com/9968265/172008272-74f58f34-23ce-421b-9025-f3252ff8027f.png)

Restoring to 10.25.1 has it working again perfectly.

### What did you expect to happen?

The bulb that works in 1.25.1 should work in 10.25.2

### How to reproduce it (minimal and precise)

Have Ajax vintage bulb working in Z2M 1.25.1 (HA Addon): https://www.ajaxonline.co.uk/product/smart-vintage-wifi-bulb/?attribute_please-choose=Pack+of+1&gclid=Cj0KCQjwheyUBhD-ARIsAHJNM-MzP8HYRl48x1A35flHvs_23V_ZD0w37--LrfiszGKnwEPDUVK8HxUaAjZsEALw_wcB

Upgrade to 1.25.2 (HA Addon).

### Zigbee2MQTT version

1.25.2

### Adapter firmware version

0x26780700

### Adapter

ConBee2/RaspBee2

**Comment by Koenkk** [comment] 2022-06-05 19:36
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/12701

**Closed by Koenkk** 2022-06-05 19:36 UTC
Labels: problem
