### ISSUE TITLE
[New device support]: Schneider Electric - Wiser Radiator Thermostat (CCTFR6100Z3)

### ISSUE THREAD

**Issue by Ramshackles** [Koenkk/zigbee2mqtt#17377] opened 2023-04-17 14:06 UTC
### Link

https://www.lk.dk/produkter?EPIuser=null&iid=14073

### Database entry

{"id":5,"type":"EndDevice","ieeeAddr":"0x04cd15fffe815d27","nwkAddr":34262,"manufId":4190,"manufName":"Schneider Electric","powerSource":"Battery","modelId":"CCTFR6100","epList":[1,2],"endpoints":{"1":{"profId":260,"epId":1,"devId":769,"inClusterList":[0,1,3,32,513,516,2821,65027],"outClusterList":[3,25,1026],"clusters":{"genBasic":{"attributes":{"modelId":"CCTFR6100","manufacturerName":"Schneider Electric","powerSource":3,"zclVersion":3}},"genPollCtrl":{"attributes":{"checkinInterval":240}}},"binds":[{"cluster":32,"type":"endpoint","deviceIeeeAddress":"0xe0798dfffea8625d","endpointID":1}],"configuredReportings":[],"meta":{}},"2":{"profId":260,"epId":2,"devId":770,"inClusterList":[0,3,1026],"outClusterList":[3],"clusters":{"genBasic":{"attributes":{}}},"binds":[],"configuredReportings":[],"meta":{}}},"zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1681738376307,"defaultSendRequestWhen":"fastpoll"}

### Comments

I tried to follow the guide to add support for the device, since there is already a variant/model og this product supported I used the details from that - but it didn't work, so perhaps there are differences between the variants/models afterall.

Since the "CCTFR6100Z3" looks exactly like "WV704R0A0902" which already has support I tried using the converter from this but it didn't work, crashed z2m in the process.

I get these in the debug log (with just the bare minimum converter from the guide);
`2023-04-17 15:42:56Received Zigbee message from '0x04cd15fffe815d27', type 'commandCheckIn', cluster 'genPollCtrl', data '{}' from endpoint 1 with groupID 0
Debug 2023-04-17 16:05:13Received Zigbee message from '0x04cd15fffe815d27', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":1,"fileVersion":262144,"imageType":513,"manufacturerCode":4190}' from endpoint 1 with groupID 0
`

**Comment by Koenkk** [comment] 2023-04-17 16:26
Could you check if the issue is fixed with the following external converter: https://gist.github.com/Koenkk/271ce5d98578e5dedc3f0e03914db590

- save this as file next to `configuration.yaml` as `ext_converter.js`
- add it to `configuration.yaml`:
```yaml
external_converters:
  - ext_converter.js
```
- start z2m, check if issue is fixed

**Comment by Ramshackles** [comment] 2023-04-17 18:39
I certainly got a lot further with that converter, I have this in the log currently;
`Debug 2023-04-17 20:37:55Received Zigbee message from '0x04cd15fffe815d27', type 'attributeReport', cluster 'hvacThermostat', data '{"localTemp":2360}' from endpoint 1 with groupID 0
Info 2023-04-17 20:37:55Configuring '0x04cd15fffe815d27'
Info 2023-04-17 20:37:55MQTT publish: topic 'zigbee2mqtt/0x04cd15fffe815d27', payload '{"linkquality":168,"local_temperature":23.6,"pi_heating_demand":null,"running_state":null,"voltage":3100}'
Debug 2023-04-17 20:37:57Received Zigbee message from '0x04cd15fffe815d27', type 'attributeReport', cluster 'hvacThermostat', data '{"57362":0}' from endpoint 1 with groupID 0
Debug 2023-04-17 20:37:57Received Zigbee message from '0x04cd15fffe815d27', type 'commandCheckIn', cluster 'genPollCtrl', data '{}' from endpoint 1 with groupID 0
Debug 2023-04-17 20:37:58Received Zigbee message from '0x04cd15fffe815d27', type 'readResponse', cluster 'genPowerCfg', data '{"batteryVoltage":31}' from endpoint 1 with groupID 0
Info 2023-04-17 20:37:58MQTT publish: topic 'zigbee2mqtt/0x04cd15fffe815d27', payload '{"linkquality":180,"local_temperature":23.6,"pi_heating_demand":null,"running_state":null,"voltage":3100}'
Error 2023-04-17 20:38:00Failed to configure '0x04cd15fffe815d27', attempt 2 (ReferenceError: constants is not defined at Object.configure (/app/data/extension/externally-loaded.js:33:36) at Configure.configure (/app/lib/extension/configure.ts:117:13))
Debug 2023-04-17 20:38:55Received Zigbee message from '0x04cd15fffe815d27', type 'attributeReport', cluster 'hvacThermostat', data '{"localTemp":2370,"pIHeatingDemand":76}' from endpoint 1 with groupID 0
Info 2023-04-17 20:38:55Configuring '0x04cd15fffe815d27'
Info 2023-04-17 20:38:55MQTT publish: topic 'zigbee2mqtt/0x04cd15fffe815d27', payload '{"linkquality":172,"local_temperature":23.7,"pi_heating_demand":30,"running_state":null,"voltage":3100}'
Debug 2023-04-17 20:38:57Received Zigbee message from '0x04cd15fffe815d27', type 'attributeReport', cluster 'hvacThermostat', data '{"57362":0}' from endpoint 1 with groupID 0
Debug 2023-04-17 20:38:57Received Zigbee message from '0x04cd15fffe815d27', type 'commandCheckIn', cluster 'genPollCtrl', data '{}' from endpoint 1 with groupID 0
Debug 2023-04-17 20:38:58Received Zigbee message from '0x04cd15fffe815d27', type 'readResponse', cluster 'genPowerCfg', data '{"batteryVoltage":31}' from endpoint 1 with groupID 0
Info 2023-04-17 20:38:58MQTT publish: topic 'zigbee2mqtt/0x04cd15fffe815d27', payload '{"linkquality":176,"local_temperature":23.7,"pi_heating_demand":30,"running_state":null,"voltage":3100}'
Error 2023-04-17 20:39:00Failed to configure '0x04cd15fffe815d27', attempt 3 (ReferenceError: constants is not defined at Object.configure (/app/data/extension/externally-loaded.js:33:36) at Configure.configure (/app/lib/extension/configure.ts:117:13))`

**Comment by Ramshackles** [comment] 2023-04-17 19:00
I figured it might be a missing declaration, so i added;
`const constants = require('zigbee-herdsman-converters/lib/constants');`

Which, so far so good, seems to have fixed the issue

**Comment by Koenkk** [comment] 2023-04-18 17:26
Great, added the device! You can remove the external converter after updating to the next release.

**Closed by Koenkk** 2023-04-18 17:26 UTC
Labels: new device support

**Comment by Ramshackles** [comment] 2023-08-04 13:16
Is the support embedded in the release yet? I'm on the latest and tried removing the external converter, then the devices says unsupported again.

**Comment by Koenkk** [comment] 2023-08-04 17:27
Somehow I forgot to commit this, added it now (for the 1 September release).
