### ISSUE TITLE
Pairing many AwoX 33957 light bulbs, causes pairing to fail and shows NWK_TABLE_FULL errors in log.

### ISSUE THREAD

**Issue by Jazzic** [Koenkk/zigbee2mqtt#18149] opened 2023-06-29 22:41 UTC
### What happened?

When adding around 30 AwoX light bulbs, pairing stops working and errors starts to appear in the log:
warn  2023-06-29 17:49:46: Received message from unsupported device with Zigbee model 'undefined' and manufacturer name 'undefined'
error 2023-06-29 18:51:11: Failed to read state of '0xa4c1388faadf4746' after reconnect (Read 0xa4c1388faadf4746/1 genOnOff(["onOff"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (SREQ '--> ZDO - extRouteDisc - {"dstAddr":3631,"options":0,"radius":30}' failed with status '(0xc7: NWK_TABLE_FULL)' (expected '(0x00: SUCCESS)')))

The problem seems to be directly related to the number of lightbulbs in the system. When the critical number of light bulbs is reached, all subsequently attempts to pair causes errors indicating unsupported device.

### Zigbee2MQTT version

1.31.2 commit: unknown

### Adapter firmware version

20230507

### Adapter

zzh!

**Comment by Koenkk** [comment] 2023-06-30 16:44
Duplicate of https://github.com/Koenkk/Z-Stack-firmware/issues/461

**Closed by Koenkk** 2023-06-30 16:44 UTC
Labels: problem
