### ISSUE TITLE
Update flood caused by TuYa TS0601 Smart Air House Keeper

### ISSUE THREAD

**Issue by Sesshoumaru-sama** [Koenkk/zigbee2mqtt#12991] opened 2022-06-29 20:15 UTC
### What happened?

I have bought and paired the TuYa TS0601 Smart Air House Keeper with Zigbee2Mqtt.
This devices triggers an awefull lot of updates. Almost one per second. Which floods the Zigbee Network with traffic.

It would be advisable to have a means to ajust the number of updates, if not possible on Zigbee side, then at least on the MQTT side, to avoid spamming at least the MQTT broker.

### What did you expect to happen?

No update flood (into HA at my end).

### How to reproduce it (minimal and precise)

Just pair the device and then it goes...

### Zigbee2MQTT version

1.25.2-1

### Adapter firmware version

20210708

### Adapter

ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus

**Comment by Koenkk** [comment] 2022-07-01 15:03
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/8154

**Closed by Koenkk** 2022-07-01 15:03 UTC
Labels: problem

**Comment by jeroenhubgit** [comment] 2022-08-03 10:33
I had the same problem. When entering the 'debounce' settings with a number (it is seconds) then it will reduce the update frequency

**Comment by VikeDragon** [comment] 2022-08-05 17:50
But debaunce did not solve the problem... Only reduced it a little, but the network is clogged with messages from the sensor.

**Comment by kevincaradant** [comment] 2022-08-24 21:04
I didn't find any solution :(. The device is still turn off since I bought it, one of my worse buy  :(
