### ISSUE TITLE
MFKZQ01LM Aqara cube actions publish twice

### ISSUE THREAD

**Issue by sztanpet** [Koenkk/zigbee2mqtt#6052] opened 2021-02-02 15:34 UTC
## What happened
When publishing an action from the MFKZQ01LM Aqara cube, two near-identical mqtt messages get published, the second one without the action property and is at best superfluous and worst useless.

    Zigbee2MQTT:info  2021-02-02 16:10:42: MQTT publish: topic 'zigbee2mqtt/0x00158d00054b8627', payload '{"action":"rotate_right","action_angle":15.75,"angle":15.75,"battery":91,"linkquality":57,"side":0,"voltage":2985}'
    Zigbee2MQTT:info  2021-02-02 16:10:42: MQTT publish: topic 'zigbee2mqtt/0x00158d00054b8627', payload '{"action":"","angle":15.75,"battery":91,"linkquality":57,"side":0,"voltage":2985}'

## What did you expect to happen
Only a single message per action to be published.

## How to reproduce it (minimal and precise)
Rotate the cube, observe generated mqtt traffic

## Debug info
Zigbee2MQTT version: 1.7.1
Adapter hardware: zzh! CC2652R
Adapter firmware version: no idea, i received the adapter at the end of november 2020, so the firmware from around that time

**Comment by Koenkk** [comment] 2021-02-02 19:13
This is expected, required for Home Assistant automations, see https://github.com/Koenkk/zigbee2mqtt/issues/1155#issuecomment-467094619

Duplicate of #1155 and #1212

**Closed by Koenkk** 2021-02-02 19:13 UTC
Labels: problem
