### ISSUE TITLE
Add-on config 'auto_uart' is deprecated, use 'uart'.

### ISSUE THREAD

**Issue by milobt** [Koenkk/zigbee2mqtt#6193] opened 2021-02-09 13:25 UTC
Home Assistant 2021.2.2
Supervisor-2021.02.6
Core-2021.2.2

Supervisor Log:

```
21-02-09 12:20:43 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Zigbee2mqtt Edge
21-02-09 12:20:43 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Zigbee2mqtt
```

**Comment by Koenkk** [comment] 2021-02-09 16:10
Duplicate of https://github.com/danielwelch/hassio-zigbee2mqtt/issues/533

**Closed by Koenkk** 2021-02-09 16:10 UTC
Labels: problem
