### ISSUE TITLE
Aqara Cube | modelID not recognized with Firmware 20180815

### ISSUE THREAD

**Issue by AnhDuc85** [Koenkk/zigbee2mqtt#388] opened 2018-09-19 20:09 UTC
Just flashed firmware 20180815 to my CC2531 and the cube doesn't work anymore. The cube worked fine under 20180705 no matter which docker images has been used. How can it be?

db entry of the paired and previous working cube under firmware 20180705: https://pastebin.com/raw/xRPQYxTc

db entry of the paired and previous working cube under firmware 20180815: https://pastebin.com/raw/EUNYTe4t

**Comment by ben423423n32j14e** [comment] 2018-09-19 20:18
You know it's necessary to re-pair a device after updating the firmware?

**Comment by AnhDuc85** [comment] 2018-09-19 20:20
sure, I repaired all my devices, that's why I'm so confused as my cube is not working anymore

**Comment by AnhDuc85** [comment] 2018-09-21 11:12
seems like the modelID can not be recognized with new firmware.
When I edit devices.js and replace modelID 'lumi.sensor_cube' with "0x656275635f726f736e65732e696d756c" the cube is working as before.

**Comment by aptonline** [comment] 2018-09-22 09:32
In relation to this I just received my Aqara cube (ordered an Xiaomi but I'm guessing they are the same) but I cannot get the tap function to work.  All other functions are being seen in terminal except this.

Any ideas?

Also how can you update the firmware of the cube without an original hub and Xiaomi app?  It is possible?

**Comment by AnhDuc85** [comment] 2018-09-22 18:02
@aptonline tap is working out of the box, some samples:
payload: '{"battery":"98.33","voltage":2995,"linkquality":105,"action":"tap","side":0}'
payload: '{"battery":"98.33","voltage":2995,"linkquality":107,"action":"tap","side":5}'

As far as I know, there is no other way to update the cube firmware except via xiaomi hub and app.

**Comment by aptonline** [comment] 2018-09-23 14:03
No for me @AnhDuc85, I've double checked and not getting any `tap` payload exposed in terminal. All other functions are there.  Running `zigbee2mqtt@0.1.5`

**Comment by AnhDuc85** [comment] 2018-09-23 15:43
do you get the "tap" via Mi Home app?

**Comment by wilfredsmit** [comment] 2018-09-24 16:48
> seems like the modelID can not be recognized with new firmware.
> When I edit devices.js and replace modelID 'lumi.sensor_cube' with "0x656275635f726f736e65732e696d756c" the cube is working as before.

Here the same. As a workaround it's fine, but I hope it will be fixed.

**Comment by Koenkk** [comment] 2018-09-25 11:42
@wilfredsmit @AnhDuc85 are you sure this is because of the firmware update and not because a zigbee2mqtt update?

**Comment by AnhDuc85** [comment] 2018-09-25 13:00
It stopped working after I updated my firmware and re-paired the cube. Also, I tried with old zigbee2mqtt image but still same.

Within the next days, I will get another CC2531, will flash old firmware and double check. Don't want to use my current stick and re-pair the devices again :-)

**Comment by wilfredsmit** [comment] 2018-09-25 13:09
The same for me. I updated my firmware and re-paired the cube. Btw I use the docker image.

**Comment by Koenkk** [comment] 2018-09-26 10:34
@AnhDuc85 could you trigger some actions when running both firwmare?

You `20180815` has some more events:

```
  zigbee2mqtt:debug 2018-9-25 19:25:06 Recieved zigbee message of type 'attReport' with data '{"cid":"genBasic","data":{"modelId":"lumi.sensor_cube.aqgl01"}}' of device '0x656275635f726f736e65732e696d756c' (0x00158d0002791e60)
  zigbee2mqtt:warn 2018-9-25 19:25:06 Device with modelID '0x656275635f726f736e65732e696d756c' is not supported.
  zigbee2mqtt:warn 2018-9-25 19:25:06 Please see: https://github.com/Koenkk/zigbee2mqtt/wiki/How-to-support-new-devices
  zigbee2mqtt:debug 2018-9-25 19:25:07 Recieved zigbee message of type 'devInterview' with data '"0x00158d0002791e60"'
```

**Comment by AnhDuc85** [comment] 2018-09-26 10:44
same with all events (tap, rotate, flip, ...). Only the presentValues changes:

2018-09-26T10:43:07.761513174Z   zigbee2mqtt:warn 2018-9-26 10:43:07 Device with modelID '0x656275635f726f736e65732e696d756c' is not supported.
2018-09-26T10:43:07.761804293Z   zigbee2mqtt:warn 2018-9-26 10:43:07 Please see: https://github.com/Koenkk/zigbee2mqtt/wiki/How-to-support-new-devices
2018-09-26T10:43:09.077634474Z   zigbee2mqtt:debug 2018-9-26 10:43:09 Recieved zigbee message of type 'attReport' with data '{"cid":"genMultistateInput","data":{"presentValue":74}}' of device '0x656275635f726f736e65732e696d756c' (0x00158d0002791e60)
2018-09-26T10:43:09.078687909Z   zigbee2mqtt:warn 2018-9-26 10:43:09 Device with modelID '0x656275635f726f736e65732e696d756c' is not supported.
2018-09-26T10:43:09.079663091Z   zigbee2mqtt:warn 2018-9-26 10:43:09 Please see: https://github.com/Koenkk/zigbee2mqtt/wiki/How-to-support-new-devices
2018-09-26T10:43:10.381207260Z   zigbee2mqtt:debug 2018-9-26 10:43:10 Recieved zigbee message of type 'attReport' with data '{"cid":"genMultistateInput","data":{"presentValue":84}}' of device '0x656275635f726f736e65732e696d756c' (0x00158d0002791e60)
2018-09-26T10:43:10.382254528Z   zigbee2mqtt:warn 2018-9-26 10:43:10 Device with modelID '0x656275635f726f736e65732e696d756c' is not supported.
2018-09-26T10:43:10.383267175Z   zigbee2mqtt:warn 2018-9-26 10:43:10 Please see: https://github.com/Koenkk/zigbee2mqtt/wiki/How-to-support-new-devices
2018-09-26T10:43:14.999862118Z   zigbee2mqtt:debug 2018-9-26 10:43:14 Recieved zigbee message of type 'attReport' with data '{"cid":"genMultistateInput","data":{"presentValue":516}}' of device '0x656275635f726f736e65732e696d756c' (0x00158d0002791e60)
2018-09-26T10:43:15.000384229Z   zigbee2mqtt:warn 2018-9-26 10:43:15 Device with modelID '0x656275635f726f736e65732e696d756c' is not supported.
2018-09-26T10:43:15.000969296Z   zigbee2mqtt:warn 2018-9-26 10:43:15 Please see: https://github.com/Koenkk/zigbee2mqtt/wiki/How-to-support-new-devices
2018-09-26T10:43:21.218341588Z   zigbee2mqtt:debug 2018-9-26 10:43:21 Recieved zigbee message of type 'attReport' with data '{"cid":"genMultistateInput","data":{"presentValue":516}}' of device '0x656275635f726f736e65732e696d756c' (0x00158d0002791e60)

**Comment by Koenkk** [comment] 2018-09-26 12:28
And how does it look like when running with the `20180507` firmware?

**Comment by AnhDuc85** [comment] 2018-09-26 19:37
Seems like I mixed up something. Problem is not relating to Firmware.
However, it's not possible to pair the cube with stable and latest-dev BUT it's possible to pair with 0.1.3.
Once the cube is paired, switch back to latest-dev or stable and everything seems fine.
@wilfredsmit can you try that?

**Comment by wilfredsmit** [comment] 2018-09-27 11:09
@AnhDuc85 I'm afraid I don't have the time to test this the coming days, as I'm not at home.

**Comment by apeeters** [comment] 2018-09-27 21:49
I just paired 2 brand new cubes (with newer firmware, I guess). These are not recognised: "Device with modelID '0x656275635f726f736e65732e696d756c' is not supported.". Older cubes still work, so I'm not sure the problem is caused by zigbee2mqtt.

As @JaapBraam mentioned before, when decoding this modelID hex string, we get the normal model id but reversed...?

**Comment by apeeters** [comment] 2018-09-27 22:32
For the record: the old (working) cubes are Mi branded whereas the new ones are Aqara branded.

**Comment by Koenkk** [comment] 2018-09-28 10:04
Probably the issue is due to a recent change in https://github.com/Koenkk/zcl-packet or https://github.com/Koenkk/zigbee-shepherd. Will investigate...

**Comment by Koenkk** [comment] 2018-09-29 20:28
Fixed in the dev branch, thanks for reporting (don't forget to repair)

**Closed** 2018-09-29 20:31 UTC

**Comment by Koenkk** [comment] 2018-10-14 19:46
@ABeumer525 can you check the dev branch?

**Comment by wilfredsmit** [comment] 2018-10-16 17:20
It is still a problem in 0.1.7

**Comment by michel72** [comment] 2018-10-16 17:34
yup, having the same issue here. The cube was working fine before.

**Comment by Koenkk** [comment] 2018-10-16 18:54
@wilfredsmit have you done a `rm -rf node_modules && npm install`?

**Comment by wilfredsmit** [comment] 2018-10-17 07:47
@Koenkk No. I use docker. So as far as I know this should not be necessary. But correct me if I'm wrong.

**Comment by Koenkk** [comment] 2018-10-17 08:38
@wilfredsmit before pairing it again, did you remove all entries of this device from `database.db`? (and then restart zigbee2mqtt)

**Comment by wilfredsmit** [comment] 2018-10-17 10:08
No, I have not done this. Do you mean I have to remove the cube entry by entering the MQTT command `zigbee2mqtt/bridge/config/remove` with the cube device address as the payload? And then reset the cube and pair it again?

**Comment by Koenkk** [comment] 2018-10-17 10:41
Try:
- Stop zigbee2mqtt
- Remove all entries of the cube (by searching on ieeAddress) from `database.db`
- Start zigbee2mqtt
- Pair cube

**Comment by maartendamen** [comment] 2018-10-18 18:05
I am also experiencing this issue with a brand new wxkg12lm straight from the box. Paired the same model succesfully several times before. I get these errors in the logs (I am on dev branch):

Device with modelID '0x746977735f726f736e65732e696d756c' is not supported.

**Comment by wilfredsmit** [comment] 2018-10-19 16:55
@Koenkk Hi Koen,
Still no success. This is my log.

```
  zigbee2mqtt:info 2018-10-19 16:50:30 Zigbee: allowing new devices to join.
  zigbee2mqtt:info 2018-10-19 16:50:54 New device with address 0x00158d0001041de0 connected!
  zigbee2mqtt:info 2018-10-19 16:50:54 MQTT publish, topic: 'zigbee2mqtt/bridge/log', payload: '{"type":"device_connected","message":"0x00158d0001041de0"}'
  zigbee2mqtt:warn 2018-10-19 16:50:57 Device with modelID 'lumi.sensor_cube' is not supported.
  zigbee2mqtt:warn 2018-10-19 16:50:57 Please see: https://github.com/Koenkk/zigbee2mqtt/wiki/How-to-support-new-devices
  zigbee2mqtt:warn 2018-10-19 16:50:58 Device with modelID 'lumi.sensor_cube' is not supported.
  zigbee2mqtt:warn 2018-10-19 16:50:58 Please see: https://github.com/Koenkk/zigbee2mqtt/wiki/How-to-support-new-devices
  zigbee2mqtt:warn 2018-10-19 16:51:00 Device with modelID 'lumi.sensor_cube' is not supported.

```

**Comment by Ciubas** [comment] 2020-05-19 09:40
Whre is file database.db in Home Assistant with Supervisor in Docker and Zigbee2MQTT as Supervised addon?
