### ISSUE TITLE
IKEA TRADFRI remote control throws Assertion Error

### ISSUE THREAD

**Issue by d4s1r** [Koenkk/zigbee2mqtt#2188] opened 2019-10-22 18:19 UTC
# Bug Report
## What happened

I paired the 5-button IKEA TRADFRI remote and started pushing the middle button. That action sends a payload `'{"linkquality":99,"action":"toggle"}'`. The problem appears to be with the second action the button is able to send, which is `payload '{"linkquality":99,"action":"toggle_hold"}'` if you not only push it, but hold it.
I did not assign any actions to the button (I am just mentioning it for completion purposes). Then this text appeared in the log, asking me to create an issue: 
https://pastebin.com/6N8Rfruk

## How to reproduce it (minimal and precise)
Just hold the middle button

## Debug Info
zigbee2mqtt version: 1.6.0
CC253X firmware version: 20190608

**Comment by Koenkk** [comment] 2019-10-23 06:18
Thanks for reporting, closing this as it is a duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/2006#issuecomment-533691577

**Closed by Koenkk** 2019-10-23 06:18 UTC
