### ISSUE TITLE
HG08673-FR energy reports as null

### ISSUE THREAD

**Issue by jorik41** [Koenkk/zigbee2mqtt#14527] opened 2022-10-18 04:28 UTC
### What happened?

Just added the Lidl smart plugs with power meter.
Power /current/voltage are reporting correctly.
But energy reports as null

### What did you expect to happen?

kWh value

### How to reproduce it (minimal and precise)

Got 5 of them all 5 report null under energy 

### Zigbee2MQTT version

1.28

### Adapter firmware version

20220219

### Adapter

Soboff ZigBee 3.0

**Comment by Koenkk** [comment] 2022-10-18 16:26
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/14356

**Closed by Koenkk** 2022-10-18 16:26 UTC
Labels: problem
