### ISSUE TITLE
zigbee2mqtt 1.31.0 failed to start after the latest update.

### ISSUE THREAD

**Issue by choinw** [Koenkk/zigbee2mqtt#17867] opened 2023-06-02 00:25 UTC
### What happened?

The add-on itself failed to start with the error below shown in log

/app/node_modules/zigbee-herdsman-converters/index.js:79
        if (converter.options) {
                      ^
TypeError: Cannot read properties of undefined (reading 'options')
    at Object.addDefinition [as addDeviceDefinition] (/app/node_modules/zigbee-herdsman-converters/index.js:79:23)
    at new ExternalConverters (/app/lib/extension/externalConverters.ts:15:17)
    at new Controller (/app/lib/controller.ts:84:58)
    at start (/app/index.js:106:18)

### What did you expect to happen?

wake up normally.

### How to reproduce it (minimal and precise)

reproduction rate 100%

### Zigbee2MQTT version

1.31.0-1

### Adapter firmware version

20201127

### Adapter

sonoff CC2561

### Debug log

/app/node_modules/zigbee-herdsman-converters/index.js:79
        if (converter.options) {
                      ^
TypeError: Cannot read properties of undefined (reading 'options')
    at Object.addDefinition [as addDeviceDefinition] (/app/node_modules/zigbee-herdsman-converters/index.js:79:23)
    at new ExternalConverters (/app/lib/extension/externalConverters.ts:15:17)
    at new Controller (/app/lib/controller.ts:84:58)
    at start (/app/index.js:106:18)

**Comment by kufischer-hacs** [comment] 2023-06-02 05:09
Same problem here. 
Disabling
`external_converters:`
in 
`configuration.yaml` 
allows for a normal start. Maybe need updated converters?

**Comment by Martin-Dolan** [comment] 2023-06-02 06:57
Same here. If I comment out the external converter for my light switch, if will start.

**Comment by choinw** [comment] 2023-06-02 07:27
Startup problem resolved by disabling external converter from 'configuration.yaml' file.
Then what should users do to use external converter configuration in the new version?

**Comment by Koenkk** [comment] 2023-06-02 07:31
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/17863#issuecomment-1573279515

**Closed by Koenkk** 2023-06-02 07:31 UTC
Labels: problem
