### ISSUE TITLE
HA: no _linkquality entities for new devices

### ISSUE THREAD

**Issue by Masterz69** [Koenkk/zigbee2mqtt#8489] opened 2021-08-23 11:20 UTC
## What happened
Just added new devices into network: MCCGQ11LM, RTCGQ11LM & WSDCGQ11LM.
Almost all looks fine. Except - no _linkquality entities created, after hours.

State for all devices contains link quality, like:
```{
    "battery": 100,
    "humidity": 61.03,
    "last_seen": "2021-08-23T13:55:41+03:00",
    "linkquality": 117,
    "pressure": 1020,
    "temperature": 17.31,
    "voltage": 3005
}
```
Same info in MQTT topics as well. 
HA topics have this property:
![image](https://user-images.githubusercontent.com/15225823/130438934-808835fa-b7e6-4c25-9315-8640281cc610.png)

## What did you expect to happen
Same WSDCGQ11LM devices previously (on Z2M 1.18 version) added - all have _linkquality entities.

## Debug info
Zigbee2MQTT version: 1.21.0-4
Adapter hardware: zStack3x0 (CC2652)
Adapter firmware version: 20200921

![image](https://user-images.githubusercontent.com/15225823/130438509-ce0d901c-ffa6-4b1e-8ec5-c2b90c4ac3ea.png)

**Comment by Masterz69** [comment] 2021-08-23 11:29
Devices normally joined network, interview completed, looks fine.
Add-on & core restarted after, but still no _linkquality entities.

![image](https://user-images.githubusercontent.com/15225823/130439916-a53dea41-521e-46c0-beff-77636f105b8e.png)

![image](https://user-images.githubusercontent.com/15225823/130440027-faab0e14-8ea4-4a59-9fb2-b39ab46a8392.png)

All required data is in attributes, all entities (like _battery, _temperature ...) in place, except _linkquality.

**Comment by Koenkk** [comment] 2021-08-23 13:20
Duplicate of #8490

**Closed by Koenkk** 2021-08-23 13:20 UTC
Labels: problem
