### ISSUE TITLE
Support for Tuya Blind Motor - Recognised as TS0601

### ISSUE THREAD

**Issue by milobt** [Koenkk/zigbee2mqtt#5596] opened 2021-01-06 14:27 UTC
## Information about the device + link
[https://www.aliexpress.com/item/1005001775235402.html?spm=a2g0s.9042311.0.0.24644c4dOe24TO](https://www.aliexpress.com/item/1005001775235402.html?spm=a2g0s.9042311.0.0.24644c4dOe24TO)

## data/database.db entry of the device
`{"id":22,"type":"EndDevice","ieeeAddr":"0x5c0272fffeca9e6c","nwkAddr":5763,"manufId":4098,"manufName":"_TZE200_rddyvrci","powerSource":"Battery","modelId":"TS0601","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[0,4,5,61184],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS0601","manufacturerName":"_TZE200_rddyvrci","powerSource":3,"zclVersion":3,"appVersion":68,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[],"meta":{}}},"appVersion":68,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1609436887877}`

Log:
`Zigbee2MQTT:debug 2020-12-31 17:48:07: Received Zigbee message from '0x5c0272fffeca9e6c', type 'readResponse', cluster 'genBasic', data '{"stackVersion":0}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2020-12-31 17:48:07: Skipping message, definition is undefined and still interviewing
Zigbee2MQTT:debug 2020-12-31 17:48:07: Received Zigbee message from '0x5c0272fffeca9e6c', type 'readResponse', cluster 'genBasic', data '{"hwVersion":1}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2020-12-31 17:48:07: Skipping message, definition is undefined and still interviewing
Zigbee2MQTT:debug 2020-12-31 17:48:07: Received Zigbee message from '0x5c0272fffeca9e6c', type 'readResponse', cluster 'genBasic', data '{"dateCode":""}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2020-12-31 17:48:07: Skipping message, definition is undefined and still interviewing
Zigbee2MQTT:debug 2020-12-31 17:48:07: Received Zigbee message from '0x5c0272fffeca9e6c', type 'readResponse', cluster 'genBasic', data '{}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2020-12-31 17:48:07: Skipping message, definition is undefined and still interviewing
Zigbee2MQTT:info  2020-12-31 17:48:07: Successfully interviewed '0x5c0272fffeca9e6c', device has successfully been paired
Zigbee2MQTT:warn  2020-12-31 17:48:07: Device '0x5c0272fffeca9e6c' with Zigbee model 'TS0601' and manufacturer name '_TZE200_rddyvrci' is NOT supported, please follow https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html
Zigbee2MQTT:info  2020-12-31 17:48:07: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"definition":null,"friendly_name":"0x5c0272fffeca9e6c","ieee_address":"0x5c0272fffeca9e6c","status":"successful","supported":false},"type":"device_interview"}'`

**Comment by d-edge82** [comment] 2021-01-10 21:32
I have the same curtain motor (returned the unsupported livolo one)
@Koenkk please advise

**Comment by Koenkk** [comment] 2021-01-11 16:09
@d-edge82 see https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html

**Comment by d-edge82** [comment] 2021-01-11 17:21
> @d-edge82 see https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html

Thanks!
Managed to connect it, now I am struggling with it's behaviour..
Clicking "Down" on HA opens the curtain, "Up" does nothing and "Stop" closes it..

Any idea?

**Comment by milobt** [comment] 2021-01-11 17:41
I got the same result after connecting, I figured it might be because I haven’t yet configured the up and down stopping points,  but still might be an error in the Z2M profile.

**Comment by Koenkk** [comment] 2021-01-11 18:10
Try adding it to `model: 'TS0601_roller_blind',` instead of ` model: 'TS0601_curtain',`

**Comment by d-edge82** [comment] 2021-01-11 18:18
> Try adding it to `model: 'TS0601_roller_blind',` instead of ` model: 'TS0601_curtain',`

Can you please explain where I need to change it?
I am on Hassio with the latest Z2M (edge does not recognize the device)

**Comment by Koenkk** [comment] 2021-01-11 18:28
@d-edge82 can you provide the data/database.db entry of it?

**Comment by d-edge82** [comment] 2021-01-11 18:44
Is this what you are after?

{"id":2,"type":"EndDevice","ieeeAddr":"0x5c0272fffecc0047","nwkAddr":44405,"manufId":4098,"manufName":"_TZE200_rddyvrci","powerSource":"Battery","modelId":"TS0601","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[0,4,5,61184],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS0601","manufacturerName":"_TZE200_rddyvrci","powerSource":3,"zclVersion":3,"appVersion":68,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":68,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1610387106467}

**Comment by Koenkk** [comment] 2021-01-11 18:51
Can you try if it is fixed now?

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by d-edge82** [comment] 2021-01-11 18:53
Cool, thanks!

Dev-branch means edge edition of the add-on, right?
I tried that a few days ago and it did not recognize the device,
Does this mean it will be recognized if I update it tomorrow morning?

**Comment by Koenkk** [comment] 2021-01-11 18:55
@d-edge82 should be, first uninstall and install again

**Comment by d-edge82** [comment] 2021-01-11 21:17
OK, waited, uninstalled and installed back again
I now see it shows up as roller_blind, but the issue is still there:

Stop: Closes the curtain
Up: Opens
Down: Stop

![image](https://user-images.githubusercontent.com/60448083/104239382-1a059100-5463-11eb-9ed2-a9308f9c5832.png)

Should I wait longer?

**Comment by Koenkk** [comment] 2021-01-12 19:21
@milobt is it working for you?

**Comment by milobt** [comment] 2021-01-13 12:10
@Koenkk on edge I get the same @d-edge82. Although, I believe the operations to be as follows:

Lovelace Button <-> Blind Operation
Up <-> STOP
Stop <-> DOWN
Down <-> UP

**Comment by rbrueckner82** [comment] 2021-01-13 14:28
same issue

Button

OPEN / doesn't work
CLOSE / open the blind
POSITION /  doesn't work

the warning are at log when i start any event.

WARNING: owvfni3: Unhandled DP #105: {"status":0,"transid":0,"dp":105,"datatype":2,"fn":0,"data":{"type":"Buffer","data":[0,0,0,40]}}

![image](https://user-images.githubusercontent.com/6508077/104464467-3dd7ec80-55b3-11eb-9c70-6c0b74afe88b.png)

**Comment by milobt** [comment] 2021-01-14 13:15
I also find that position does not work at all.

Furthermore, considering that these motors run on batteries it would be useful if battery level was available on one of the endpoints.

**Comment by DomiStyle** [comment] 2021-01-14 13:20
@milobt Does setting the position not work or receiving the position?

Judging by @rbrueckner82 warning receiving position can't work yet.

**Comment by d-edge82** [comment] 2021-01-15 11:49
This is the current status for me (on Edge):
Position - works fine.
Close=Stop
Open - Works.
0 = Open
100 = Closed (wish it was the other way around)

On HA the behavior is as following:

Stop = Close
Up = Open
Down = Stop

Position works.

Thanks for the support @Koenkk !

**Comment by eric-zimmer** [comment] 2021-01-15 13:45
Hello, I have got the same zigbee blind motor. I am not able to pair it with zigbee2mqtt (HA) or deconz. How did you do this? Also I have a tuya gateway, also with this I cannot connect the motor. How can I put the device into pairing mode? I haven't found anything for this in the instruction

**Comment by d-edge82** [comment] 2021-01-15 13:50
> Hello, I have got the same zigbee blind motor. I am not able to pair it with zigbee2mqtt (HA) or deconz. How did you do this? Also I have a tuya gateway, also with this I cannot connect the motor. How can I put the device into pairing mode? I haven't found anything for this in the instruction

Hi Eric,

Hold the down button along with the set, this should reset the device and enter pairing mode

**Comment by eric-zimmer** [comment] 2021-01-15 14:16
Hi, thank you for your fast answer.  I thought it need to flash, it doesn't but it connected to deconz, so it should work with z2m, will try this next. thank you.

**Comment by Koenkk** [comment] 2021-01-16 11:22
Can you guys check out the latest dev branch and see if it's fixed there? (@DomiStyle did some fixes here)

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by d-edge82** [comment] 2021-01-16 13:25
> Can you guys check out the latest dev branch and see if it's fixed there? (@DomiStyle did some fixes here)
> 
> Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

Just tried;
Close = Close.
Open = stop.
And I have no other options.

Position:
100 = Open
0 = Closed.

Should I try again in a few hours?

**Comment by DomiStyle** [comment] 2021-01-16 17:11
@d-edge82 Position looks good, I reversed open and stop for your model, you can try once @Koenkk merges it.

Stop is only available from Home Assistant.

**Comment by Koenkk** [comment] 2021-01-16 17:35
Merged the fix from @DomiStyle .

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by rbrueckner82** [comment] 2021-01-16 17:46
i have tested the docker image latest-dev

same @d-edge82 

Close = Close.
Open = Stop.
And I have no other options.

Position:
100 = Open
0 = Closed

 works fine

the battery level would be interesting if possible

thanks for the great support

**Comment by Koenkk** [comment] 2021-01-16 17:47
@rbrueckner82 plesae check again in 30 mins from now

**Comment by DomiStyle** [comment] 2021-01-16 17:55
> Warning TuYa_cover_control: Unhandled DP #105 for _TZE200_rddyvrci: {"status":0,"transid":0,"dp":105,"datatype":2,"fn":0,"data":{"type":"Buffer","data":[0,0,0,40]}}

@rbrueckner82 
Do you happen to know what the battery level currently is? 105 isn't defined for covers and if 40% isn't the current position then it might be the battery level.

**Comment by rbrueckner82** [comment] 2021-01-16 18:00
now the position at 50%
![image](https://user-images.githubusercontent.com/6508077/104819332-0e341900-582d-11eb-8e69-1536c0dc51de.png)


this is the latest warning

Warning TuYa_cover_control: Unhandled DP #105 for _TZE200_rddyvrci: {"status":0,"transid":0,"dp":105,"datatype":2,"fn":0,"data":{"type":"Buffer","data":[0,0,0,40]}}

**Comment by Koenkk** [comment] 2021-01-16 18:20
> @rbrueckner82 plesae check again in 30 mins from now

Delayed a bit, check 30 mins from now

**Comment by rbrueckner82** [comment] 2021-01-16 18:25
a question like is the command topic in mqtt the state topic "zigbee2mqt /rlsh_childroom" works fine, but the command topic "zigbee2mqtt/rlsh_childroom" does not work, at the broker the  % status arrives

**Comment by rbrueckner82** [comment] 2021-01-16 19:13
> > @rbrueckner82 plesae check again in 30 mins from now
> 
> Delayed a bit, check 30 mins from now

ok i pulled the latest-dev, no changes

**Comment by d-edge82** [comment] 2021-01-16 19:19
Works perfect for me here! thank you so much!

**Comment by milobt** [comment] 2021-01-18 11:04
All works perfectly for me too. Many thanks @Koenkk.

Only additional request is whether battery level is available?

I also get the warning in the log, as @DomiStyle pointed out:
```
Zigbee2MQTT:warn  2021-01-18 11:02:37: TuYa_cover_control: Unhandled DP #105 for _TZE200_rddyvrci:
                {"status":0,"transid":0,"dp":105,"datatype":2,"fn":0,"data":{"type":"Buffer","data":[0,0,0,40]}}
```

**Comment by DomiStyle** [comment] 2021-01-18 12:15
@milobt Can you fully charge the battery and check if the parameter 105 changes? Since it shows 40 for both of you I'm not sure it's related to the battery.

Alternatively you can try checking the logs after a longer period like a week, maybe more warnings pop up.

**Comment by milobt** [comment] 2021-01-18 15:39
Have had on charge all day - green light on the charging plug when charged - and still reports the same value of 40, so sadly must not be associate with the battery level.

```
Zigbee2MQTT:warn  2021-01-18 15:36:02: TuYa_cover_control: Unhandled DP #105 for _TZE200_rddyvrci:
                {"status":0,"transid":0,"dp":105,"datatype":2,"fn":0,"data":{"type":"Buffer","data":[0,0,0,40]}}
```

**Comment by andreasg73** [comment] 2021-01-20 18:11
I have a new device signature AM43-blind zigbee, please add it to the database. Mine reports as _TZE200_zah67ekd.
Thank you

**Comment by joseant** [comment] 2021-01-22 17:59
Same here I have a AM43 and report _TZE200_zah67ekd I have added it to device,js and it is working, the only thing is when I open or close it I get a warning:

WARNING: TuYa_cover_control: Unhandled DP #105 for _TZE200_zah67ekd: {"status":0,"transid":0,"dp":105,"datatype":2,"fn":0,"data":{"type":"Buffer","data":[0,0,0,40]}}

**Comment by DomiStyle** [comment] 2021-01-22 18:28
@joseant That seems plausible. Can you try replacing your toZigbee.js with [this file](https://github.com/DomiStyle/zigbee-herdsman-converters/blob/tuya-cover-speed/converters/toZigbee.js), restart zigbee2mqtt and set the speed like this:

Publish to topic:

    zigbee2mqtt/FRIENDLY_NAME/set

With value:

    {
        "options":{
            "motor_speed": 80
        }
    }

After that you can check if the speed and/or the report for DP 105 changed.

**Comment by joseant** [comment] 2021-01-22 18:48
@DomiStyle  You are right, now it changes:

warning TuYa_cover_control: Unhandled DP #105 for _TZE200_zah67ekd: {"status":0,"transid":0,"dp":105,"datatype":2,"fn":0,"data":{"type":"Buffer","data":[0,0,0,80]}}

And the motor goes faster

**Comment by DomiStyle** [comment] 2021-01-22 18:56
@joseant Good to know, will send a pull request tomorrow so we can get this change in the dev branch, will add the new `_TZE200_zah67ekd` signature too.

Do the up/down/stop and position commands work properly as is? 100% should be open.

Does the app limit the speed selection somehow or is 0-100 all valid?

@Koenkk Can I add the "speed" attribute to the device state when it gets reported or should I ignore it?

**Comment by joseant** [comment] 2021-01-22 18:58
@DomiStyle up/down/stop and position commands work properly the only thing is the warning I sent you.

**Comment by Koenkk** [comment] 2021-01-22 19:05
@DomiStyle fine with that, but please use `motor_speed` as the name

**Comment by DomiStyle** [comment] 2021-01-22 19:09
@Koenkk Will do.

@joseant I will restrict values from 0-255 then.

**Comment by joseant** [comment] 2021-01-22 19:21
@DomiStyle 
The only thing I have seen is the state is unknown

![imagen](https://user-images.githubusercontent.com/1671279/105535605-59e43800-5cef-11eb-8534-14d3892fcd5f.png)

**Comment by DomiStyle** [comment] 2021-01-22 19:32
@joseant I noticed that my state is stuck in closed state since forever too, will fix that aswell.

@Koenkk I could have sworn that zigbee2mqtt added the state: closed/open automatically when I wrote the original tuya_curtain functions, did something change?

I assume I can just set state: open/closed? Or is it state: OPEN/CLOSE?

**Comment by Koenkk** [comment] 2021-01-23 14:03
@DomiStyle I'm not aware of any changes here. To update the state after a successful set; add `return {state: {state: value.toUpperCase()}}` here https://github.com/Koenkk/zigbee-herdsman-converters/blob/ac5d5270848c76bbdf516f65ea60d241a91cfaee/converters/toZigbee.js#L3412

**Comment by DomiStyle** [comment] 2021-01-24 00:33
@Koenkk Strange, I still have `state: closed` stuck on my curtain from ages ago.

Wouldn't it make more sense to set the state in the fromZigbee part when the position gets set? Otherwise pulling on the curtain wouldn't update the state, only the position.

**Comment by Koenkk** [comment] 2021-01-24 17:57
@DomiStyle agree, position = 0 would be `CLOSE`, else `OPEN`

**Comment by joseant** [comment] 2021-01-24 17:59
@DomiStyle 
Hello, thanks for the commit, I have review it, the motor speed works fine. But the state is still unknown

![Captura de pantalla 2021-01-24 a las 18 55 36](https://user-images.githubusercontent.com/1671279/105639041-431c1d80-5e76-11eb-9eec-4af1ae91160a.png)

**Comment by DomiStyle** [comment] 2021-01-25 10:17
@joseant Should work once https://github.com/Koenkk/zigbee-herdsman-converters/pull/2150 is merged.

**Comment by JAJBrouwers** [comment] 2021-01-25 11:37
Hello there,

I also have a cover blind on zigbee2mqtt, the only thing that's not working is the "state" it's unknown all the time... When I follow the documentation and publish a message to get the state nothing happens.

And that option for the motor speed, is that only in the dev branche? Because I don't have that option.

Thx in advanced, Jeroen

**Comment by DomiStyle** [comment] 2021-01-25 12:39
@JAJBrouwers The fix for the state is not merged yet.

The option for motor speed is only available in dev and only works for supported devices.

**Comment by JAJBrouwers** [comment] 2021-01-25 12:54
Oke then, thx for you're feedback, I have the normal version, when I take the Dev add-on... Do I need to install everything again?

**Comment by DomiStyle** [comment] 2021-01-26 15:40
@joseant Can you try again with the latest dev version? Everything should work out of the box now.

**Comment by joseant** [comment] 2021-01-26 16:58
@DomiStyle 
Hello.
I have switch to the dev branch: https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html
But I can't see the changes yet

**Comment by joseant** [comment] 2021-01-27 08:14
@DomiStyle 
I have now tried the dev branch and everything has worked fine 

![imagen](https://user-images.githubusercontent.com/1671279/105962413-13d8fc80-6080-11eb-94ab-b0da32152beb.png)

**Comment by JAJBrouwers** [comment] 2021-01-27 08:46
Nice, how do I get this update without using the Dev branche? Will there be a update or something?

**Comment by DomiStyle** [comment] 2021-01-28 11:43
@JAJBrouwers Yes, once the next update releases it will be available without dev branch.

Since everything works I guess this can be closed now @Koenkk @milobt.

**Closed** 2021-01-28 12:30 UTC
Labels: new device support

**Comment by JAJBrouwers** [comment] 2021-02-01 17:39
Hi there I have just installed the dev branch, I get the option for the motor speed... when I set it and hit apply, nothing changes. for the state value, it still does not report back open or close.

**Comment by leroyloren** [comment] 2021-02-07 00:19
Hi, same problem. Motor speed does not respond to change. For example, Setting motor speed to 34 is displayed in the log, but after the reload it is still 0 and the speed remains the same.

**Comment by DomiStyle** [comment] 2021-02-07 12:17
@leroyloren Which model are you using? Changing motor speed is not supported for all.

If you do not receive a response from the motor it's most likely not supported or needs a different command.

**Comment by leroyloren** [comment] 2021-02-07 12:21
Zemismart M515EGB

![obrazek](https://user-images.githubusercontent.com/57643470/107146261-45d34400-6947-11eb-818b-94fd8416a336.png)

![obrazek](https://user-images.githubusercontent.com/57643470/107146268-55eb2380-6947-11eb-8c7e-2d7561957f2d.png)

![obrazek](https://user-images.githubusercontent.com/57643470/107146275-5d123180-6947-11eb-97ca-a2004e78db51.png)

![obrazek](https://user-images.githubusercontent.com/57643470/107146283-626f7c00-6947-11eb-861f-28ad50f9c33e.png)

**Comment by JAJBrouwers** [comment] 2021-02-07 12:24
I have the same model, you experience also no state change

**Comment by DomiStyle** [comment] 2021-02-07 12:39
@leroyloren @JAJBrouwers  The only model we know for sure supports setting the motor speed is `_TZE200_zah67ekd`, so I would assume your model just doesn't support it.

**Comment by leroyloren** [comment] 2021-02-07 14:18
Well, the weird thing is that until the motor is configured, it runs very slowly and quietly. But I understand if it can't be set.

**Comment by JAJBrouwers** [comment] 2021-02-07 14:33
@leroyloren 
That's normal

**Comment by JAJBrouwers** [comment] 2021-02-10 15:16
@leroyloren 

You have the same model as me, does yours also report only "running" is "true"?

**Comment by leroyloren** [comment] 2021-02-10 15:39
yep, 
![obrazek](https://user-images.githubusercontent.com/57643470/107532752-81c40e80-6bbe-11eb-8a0e-99a0e7be29a8.png)

**Comment by JAJBrouwers** [comment] 2021-02-10 15:46
Oke, then it is not my only problem 😅, so you don't have the state report back.

@DomiStyle made a fix maby, but I can't test it.

**Comment by d-edge82** [comment] 2021-06-06 07:53
Hi There!

After one of the latest updates - the motor no longer publish the "Cover" entity.
I can only see the LQI..

![image](https://user-images.githubusercontent.com/60448083/120916969-5b6a3780-c6b5-11eb-942b-ba2f5fc14cfd.png)


Any idea?

**Comment by DomiStyle** [comment] 2021-06-06 07:56
@d-edge82 Update to 1.19.0.

https://github.com/Koenkk/zigbee2mqtt/issues/7680

**Comment by d-edge82** [comment] 2021-06-06 09:04
> @d-edge82 Update to 1.19.0.
> 
> #7680

Thanks! it worked.
How was I to know the repo has changed??

**Comment by nickwild-999** [comment] 2022-03-16 06:32
Sorry to resurrect an old issue, but can a battery endpoint be added to this device. It would be really useful
