### ISSUE TITLE
TRADFRI remote control IKEA E1524/E1810 not working properly after firmware update

### ISSUE THREAD

**Issue by Udeson** [Koenkk/zigbee2mqtt#9435] opened 2021-10-31 21:35 UTC
# Bug Report
## What happened
Updated the Tradfri remote's firmware. After that the remote did not control the bulbs of the group any longer.
Removed the remote device and paired it again as described below. The remote reacts to key presses on the on/off buttons as follows (other buttons are waorking too):

`Debug Received Zigbee message from 'Remco', type 'commandToggle', cluster 'genOnOff', data '{}' from endpoint 1 with groupID 0`

So, in short, remote do not control the bulbs of the group anymore.

## What did you expect to happen
Remote do control the bulbs of the group

## How to reproduce it
Pair IKEA Tradfri remote as described on the device overview page, unbind default binding group from remote, create new group #65289, add IKEA bulbs to the group, bind on/off of the device to the created group.

## Debug Info
Zigbee2MQTT version: 1.21.2 commit: 44922120
Adapter hardware: zzh CC2652R
Adapter firmware version: Coordinator zStack3x0 rev. 20210708
IKEA Tradfri remote firmware: 2.3.014 20190708

**Comment by Koenkk** [comment] 2021-11-01 07:29
Duplicate of #7716

**Closed by Koenkk** 2021-11-01 07:29 UTC
