### ISSUE TITLE
Group bindings of IKEA remotes not working after most recent firmware update

### ISSUE THREAD

**Issue by frank-f** [Koenkk/zigbee2mqtt#9388] opened 2021-10-28 18:31 UTC
## What happened

The firmware of my IKEA remotes was updated last night. The update process worked without any errors for all of them.
Now the groups bound to the remotes are not reacting to button presses anymore.

## What did you expect to happen

Group bindings should not be affected.

## How to reproduce it (minimal and precise)

I have E1810 and E1743 remotes, a few of each. They're paired to various devices, one even to an IKEA lamp and all but one are not working correctly anymore. Just one pairing works still and that's to some Hue lamps.

What could cause this besides faulty firmware? And if it turns out to be the latter, is there a way to downgrade it?

## Debug info
Zigbee2MQTT version: 1.21.2
Adapter hardware: CC2538
Adapter firmware version: 20201010

**Comment by kuzabi** [comment] 2021-10-30 08:53
It's look like duplicate of #7716

**Comment by Koenkk** [comment] 2021-10-30 10:56
Indeed a duplicate of #7716

**Closed by Koenkk** 2021-10-30 10:56 UTC
Labels: problem
