### ISSUE TITLE
EGLO bulb found as an AWOX  33943/33944/33946, all works perfectly however spamming the zigbee network

### ISSUE THREAD

**Issue by KHV8** [Koenkk/zigbee2mqtt#16623] opened 2023-02-11 15:40 UTC
### What happened?

Added 2 new EGLO bulbs connected to my zigbee network. Reconised as AWOX 33943/33944/33946 and works prefectly. They show up with a picture of a bulb with a E27, even they are with a GU10 connection, but it works prefectly and I beleive all device features are as expected.

The problem is they report this in the log (in debug mode) every 10 seonds
2023-02-11 16:34:36Received Zigbee message from 'Fælles reol v', type 'read', cluster 'genTime', data '["time","timeStatus","timeZone","lastSetTime","validUntilTime"]' from endpoint 1 with groupID 0

This is OK for 1 or 2 bulbs, however if you have a lot of them they will start create problems for zigbee network. I have tried to reduce using "last reporting", however not diffreence.

### What did you expect to happen?

Reporting as other bulbs, on changes and e.g. ever 30 min

### How to reproduce it (minimal and precise)

Looks like this is normal behaviour

### Zigbee2MQTT version

1.30.1

### Adapter firmware version

20221226

### Adapter

Sonoff 3.0 P

### Debug log

2023-02-11 16:38:15Received Zigbee message from 'Fælles Reol ø', type 'read', cluster 'genTime', data '["time","timeStatus","timeZone","lastSetTime","validUntilTime"]' from endpoint 1 with groupID 0
2023-02-11 16:38:15Received Zigbee message from 'Fælles reol v', type 'read', cluster 'genTime', data '["time","timeStatus","timeZone","lastSetTime","validUntilTime"]' from endpoint 1 with groupID 0
2023-02-11 16:38:25Received Zigbee message from 'Fælles Reol ø', type 'read', cluster 'genTime', data '["time","timeStatus","timeZone","lastSetTime","validUntilTime"]' from endpoint 1 with groupID 0
2023-02-11 16:38:26Received Zigbee message from 'Fælles reol v', type 'read', cluster 'genTime', data '["time","timeStatus","timeZone","lastSetTime","validUntilTime"]' from endpoint 1 with groupID 0
2023-02-11 16:38:35Received Zigbee message from 'Fælles Reol ø', type 'read', cluster 'genTime', data '["time","timeStatus","timeZone","lastSetTime","validUntilTime"]' from endpoint 1 with groupID 0
2023-02-11 16:38:35Received Zigbee message from 'Fælles reol v', type 'read', cluster 'genTime', data '["time","timeStatus","timeZone","lastSetTime","validUntilTime"]' from endpoint 1 with groupID 0
2023-02-11 16:38:45Received Zigbee message from 'Fælles Reol ø', type 'read', cluster 'genTime', data '["time","timeStatus","timeZone","lastSetTime","validUntilTime"]' from endpoint 1 with groupID 0
2023-02-11 16:38:45Received Zigbee message from 'Fælles reol v', type 'read', cluster 'genTime', data '["time","timeStatus","timeZone","lastSetTime","validUntilTime"]' from endpoint 1 with groupID 0

**Comment by Koenkk** [comment] 2023-02-12 08:40
Duplicate of https://github.com/Koenkk/zigbee-herdsman-converters/issues/5460 , please check if this has been fixed in the dev branch.  (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Closed by Koenkk** 2023-02-12 08:40 UTC
Labels: problem
