### ISSUE TITLE
 E12-N1E - OTA not working

### ISSUE THREAD

**Issue by fireheadman** [Koenkk/zigbee2mqtt#19572] opened 2023-11-05 03:22 UTC
### What happened?

Just installed zigbee2mqtt this evening and went around the house resetting and adding all my zigbee devices.   Everything came right in on the first try, so I'm happy with that!   Reaction times are lightning fast!

My adapter is a Nortec [HUSBZB-1] and I updated it to the latest firmware last week v6.7.8

**Here's my issue:**
Have 17x -  E12-N1E (Sengled) bulbs installed.
15x of them are on v30
2x are on v21

Home assistant is attempting to update them.    I have no way to stop the update, can't skip it either.
Have rebooted the entire server and it goes right back to OTA updates.
I also have OTA updates disabled, so not sure what I can do to prevent this?
<img width="259" alt="image" src="https://github.com/Koenkk/zigbee2mqtt/assets/19847195/9f0bd88d-a934-4758-ba80-918d3ac1b981">

Checking the guides and compatibility, the E12-N1E (Sengled) bulbs has been supported for a while now on OTA.

<img width="549" alt="image" src="https://github.com/Koenkk/zigbee2mqtt/assets/19847195/37a3c69f-195b-4389-aaac-2fc3ccbc643d">
<img width="532" alt="image" src="https://github.com/Koenkk/zigbee2mqtt/assets/19847195/0413d6d2-5c41-4f37-89b3-5c09a4a29707">

<img width="970" alt="image" src="https://github.com/Koenkk/zigbee2mqtt/assets/19847195/58a64635-bfce-4f58-aa2b-554859875d92">

<img width="464" alt="image" src="https://github.com/Koenkk/zigbee2mqtt/assets/19847195/85cd001a-6edc-4d8b-b777-f5109dc0061b">

### What did you expect to happen?

expected the OTA operation to update the firmware

### How to reproduce it (minimal and precise)

reboot server or restart home assistant (docker)

### Zigbee2MQTT version

1.33.2

### Adapter firmware version

6.7.8.0 build 373

### Adapter

Nortec [HUSBZB-1

**Comment by fireheadman** [comment] 2023-11-05 03:24
an after thought.....
If you or anyone knows the country where sengled updates/firmware might be coming from, it could be possible my firewall is block it.    If/once I know that country I can check to see if that is the case and make an exception to allow it in

**Comment by fireheadman** [comment] 2023-11-05 03:37
UPDATE:   went ahead and temporarily disable all blocking by country on my firewall (Ubiquiti UDM Pro), then restarted HA and the Zigbee2Mqtt addon.    The issue still persist.

If there is something else I can try, please let me know...
Else, let me know how I can disable OTA and get HA from trying to upgrade the firmware.

**Comment by essegi65** [comment] 2023-11-05 15:44
same problem but with device BTicino K4003C

**Comment by lichtl** [comment] 2023-11-08 11:38
having the same as well. it seems that even Z2M is not updating them HA seem to show them up incorrectly

**Comment by lichtl** [comment] 2023-11-10 14:04
Same issue as #19622 (even if this was raised earlier)

**Comment by Koenkk** [comment] 2023-11-10 20:41
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/19597, should be fixed in the dev branch

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Closed by Koenkk** 2023-11-10 20:41 UTC
Labels: problem

**Comment by fireheadman** [comment] 2023-11-10 22:14
curious how long it takes for changes in the "DEV" branch to hit the Production branch?

I'm more in this for stability than to be in a development cycle where it is possible for other issues to be present than the one I am most concerned about.

**Comment by Koenkk** [comment] 2023-11-11 09:20
Dev -> production = new release = every 1sth of the month

**Comment by andreapx** [comment] 2023-11-19 11:42
> ![Immagine 2023-11-05 174747](https://user-images.githubusercontent.com/60359328/280541574-298cd3d6-3472-4ed2-8d89-3636e1758e2b.jpg)
> 
> same problem but with device BTicino K4003C

Was your problem resolved with the update?
@Koenkk I'm on the latest dev branch (1.33.2-dev commit: fd19c86 with docker) but my bTicino devices (switches, roller shutters, plugs) don't updates, I still get the error
`Device didn't respond to OTA request`

**Comment by fireheadman** [comment] 2023-11-27 18:41
I'm see this in Z2Q, looking good so far.
Will update this with final screenshots once it completes
![image](https://github.com/Koenkk/zigbee2mqtt/assets/19847195/5009a9ba-d653-48d9-ab12-efb0d5af0f2e)

![image](https://github.com/Koenkk/zigbee2mqtt/assets/19847195/2b6c2eed-a4bc-4e53-ae2e-9904aa190b7c)

![image](https://github.com/Koenkk/zigbee2mqtt/assets/19847195/ea499f86-7d2f-4091-af05-05ccbaa7be98)

**Comment by fireheadman** [comment] 2023-11-27 18:55
Shows 100%
![image](https://github.com/Koenkk/zigbee2mqtt/assets/19847195/77895a6e-5e83-4a84-a59f-3bbde5ab947b)

takes a few more seconds to complete, then will see this
![image](https://github.com/Koenkk/zigbee2mqtt/assets/19847195/9de92b37-49d5-4fd0-966e-295db801644e)

After:
![image](https://github.com/Koenkk/zigbee2mqtt/assets/19847195/b79fe7aa-c06b-4302-97de-52d5ae9e0be4)

Looks good... no more "Update device firmware" for this bulb
![image](https://github.com/Koenkk/zigbee2mqtt/assets/19847195/9a1fb864-be09-4f10-93e8-e85b091df5bb)

**Comment by fireheadman** [comment] 2023-11-27 19:00
Lastly... if you enabled the Updater in HA, it will just show this while it is updating  (no change here, so will need to review M2Q for a status on the FW update)
![image](https://github.com/Koenkk/zigbee2mqtt/assets/19847195/e83686aa-0066-4aaa-b352-4de0c6c8d343)

![image](https://github.com/Koenkk/zigbee2mqtt/assets/19847195/dacdc401-b1f5-4b6f-95f6-0544eef149af)


Think this can be closed out since it pertains to the OP Subject.
