### ISSUE TITLE
WSDCGQ11LM Aqara (temp, hum, press) not reporting temperature

### ISSUE THREAD

**Issue by mario-g0** [Koenkk/zigbee2mqtt#496] opened 2018-10-18 13:38 UTC
As title says, my WSDCGQ11LM reports pressure and humidity fine, but the temperature sensor in Home Assistant is empty and just shows the value for a second, then disappears... 
See the graph here https://imgur.com/a/L9zbmh0 the red spots are the 1-2 second when the temperature is shown, but the suddenly disappears

**Comment by Koenkk** [comment] 2018-10-18 14:18
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/485

**Closed by Koenkk** 2018-10-18 14:18 UTC
