### ISSUE TITLE
Payload changed in TS0044 and TS0043 after upgrade to 1.31.1

### ISSUE THREAD

**Issue by shalak** [Koenkk/zigbee2mqtt#17948] opened 2023-06-07 19:08 UTC
### What happened?

After Home Assistant addon upgrade to 1.31.1-1 (which ships with 1.31.1 z2m), my Tuya-compatible multi-scene remote switches are no longer sending the same payloads.

For e.g. switch [TS0043](https://www.zigbee2mqtt.io/devices/TS0043.html#tuya-ts0043) is now only sending payloads `single`, while it used to send `single_1`/`single_2`/`single_3` before the update.

Similarly, another remote ([TS0044](https://www.zigbee2mqtt.io/devices/TS0044.html#tuya-ts0044)) is no longer sending `single_bottom_left`, `single_bottom_right`, etc, but just `single`. 

Full log for the latter now looks like this:

```
info 2023-06-07 21:06:11MQTT publish: topic 'zigbee2mqtt/Kwadraciak', payload '{"action":"single","battery":100,"linkquality":255,"voltage":3000}'
info 2023-06-07 21:06:11MQTT publish: topic 'zigbee2mqtt/Kwadraciak', payload '{"action":"","battery":100,"linkquality":255,"voltage":3000}'
info 2023-06-07 21:06:11MQTT publish: topic 'zigbee2mqtt/Kwadraciak/action', payload 'single'
```

### Zigbee2MQTT version

1.31.1

### Adapter firmware version

0x26780700

### Adapter

ConBee2/

**Comment by konrad861** [comment] 2023-06-07 19:16
I have exactly the same issue with all my TuYa TS004F and TuYa TS0042 (after update to  1.31.1-1 )

**Comment by andreidelait** [comment] 2023-06-07 19:17
The same is happening with [TS004F](https://www.zigbee2mqtt.io/devices/TS004F.html)

**Comment by thrhymes** [comment] 2023-06-07 19:32
i am seeing the same thing - and i use those alot all around the house

**Comment by shalak** [comment] 2023-06-07 19:40
@andreidelait 

> I just got back to previous version until this is fixed.

Are you using HassOS? Any idea how to downgrade an add-on?

**Comment by KoKolaj** [comment] 2023-06-07 19:43
I have exactly the same issue with all my TuYa TS0044

**Comment by andreidelait** [comment] 2023-06-07 19:45
> @andreidelait
> 
> > I just got back to previous version until this is fixed.
> 
> Are you using HassOS? Any idea how to downgrade an add-on? To what exact version did you downgrade?

Yes I'm using HassOS. I created a backup when I did uptdated z2m, so then I've just restored that backup and I'm back to 1.30.4-1

**Comment by Koenkk** [comment] 2023-06-07 19:50
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/17942#issuecomment-1581387469, should be fixed in z2m 1.31.2

**Closed by Koenkk** 2023-06-07 19:50 UTC
Labels: problem

**Comment by andreidelait** [comment] 2023-06-07 20:14
> @Koenkk this is out of scope of this issue, but are you aware of any way to downgrade an addon in hassio?

1.31.2-1 is already out so you should try this one instead

**Comment by KoKolaj** [comment] 2023-06-07 20:17
OK, repaired. Thank you big.

**Comment by thrhymes** [comment] 2023-06-07 20:32
Release often.... i like that agility... amazing! this took no time at all...
