### ISSUE TITLE
Cannot configure SONOFF SNZB-02 - not reporting any value

### ISSUE THREAD

**Issue by wizu** [Koenkk/zigbee2mqtt#9104] opened 2021-10-10 13:17 UTC
I own 15 units of https://www.zigbee2mqtt.io/devices/SNZB-02.html#sonoff-snzb-02 and they were working great, but I've noticed that one of them stopped sending values. I've tried to get it close to the coordinator, but still not reports. So I've tried to remove it from network and add again.

## What happened
I was able to connect it, but it cannot be configured, I always get same error when Z2M is configuring it after it joins.

> Info Device '0x00124b00231e60aa' joined
> Info MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x00124b00231e60aa","ieee_address":"0x00124b00231e60aa"},"type":"device_joined"}'
> Info Configuring '0x00124b00231e60aa'
> Info MQTT publish: topic 'homeassistant/sensor/0x00124b00231e60aa/battery/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00124b00231e60aa"],"manufacturer":"SONOFF","model":"Temperature and humidity sensor (SNZB-02)","name":"0x00124b00231e60aa","sw_version":"Zigbee2MQTT 1.21.2"},"device_class":"battery","enabled_by_default":true,"name":"0x00124b00231e60aa battery","state_class":"measurement","state_topic":"zigbee2mqtt/0x00124b00231e60aa","unique_id":"0x00124b00231e60aa_battery_zigbee2mqtt","unit_of_measurement":"%","value_template":"{{ value_json.battery }}"}'
> Info MQTT publish: topic 'homeassistant/sensor/0x00124b00231e60aa/temperature/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00124b00231e60aa"],"manufacturer":"SONOFF","model":"Temperature and humidity sensor (SNZB-02)","name":"0x00124b00231e60aa","sw_version":"Zigbee2MQTT 1.21.2"},"device_class":"temperature","enabled_by_default":true,"name":"0x00124b00231e60aa temperature","state_class":"measurement","state_topic":"zigbee2mqtt/0x00124b00231e60aa","unique_id":"0x00124b00231e60aa_temperature_zigbee2mqtt","unit_of_measurement":"°C","value_template":"{{ value_json.temperature }}"}'
> Info MQTT publish: topic 'homeassistant/sensor/0x00124b00231e60aa/humidity/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00124b00231e60aa"],"manufacturer":"SONOFF","model":"Temperature and humidity sensor (SNZB-02)","name":"0x00124b00231e60aa","sw_version":"Zigbee2MQTT 1.21.2"},"device_class":"humidity","enabled_by_default":true,"name":"0x00124b00231e60aa humidity","state_class":"measurement","state_topic":"zigbee2mqtt/0x00124b00231e60aa","unique_id":"0x00124b00231e60aa_humidity_zigbee2mqtt","unit_of_measurement":"%","value_template":"{{ value_json.humidity }}"}'
> Info MQTT publish: topic 'homeassistant/sensor/0x00124b00231e60aa/voltage/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00124b00231e60aa"],"manufacturer":"SONOFF","model":"Temperature and humidity sensor (SNZB-02)","name":"0x00124b00231e60aa","sw_version":"Zigbee2MQTT 1.21.2"},"device_class":"voltage","enabled_by_default":false,"name":"0x00124b00231e60aa voltage","state_class":"measurement","state_topic":"zigbee2mqtt/0x00124b00231e60aa","unique_id":"0x00124b00231e60aa_voltage_zigbee2mqtt","unit_of_measurement":"mV","value_template":"{{ value_json.voltage }}"}'
> Info MQTT publish: topic 'homeassistant/sensor/0x00124b00231e60aa/linkquality/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00124b00231e60aa"],"manufacturer":"SONOFF","model":"Temperature and humidity sensor (SNZB-02)","name":"0x00124b00231e60aa","sw_version":"Zigbee2MQTT 1.21.2"},"enabled_by_default":false,"icon":"mdi:signal","name":"0x00124b00231e60aa linkquality","state_class":"measurement","state_topic":"zigbee2mqtt/0x00124b00231e60aa","unique_id":"0x00124b00231e60aa_linkquality_zigbee2mqtt","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}"}'
> Info MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x00124b00231e60aa","ieee_address":"0x00124b00231e60aa"},"type":"device_announce"}'
> Error Configure failed: Error: Bind 0x00124b00231e60aa/1 msTemperatureMeasurement from '0x00124b001ccea44c/1' failed (AREQ - ZDO - bindRsp after 10000ms)
> Info Successfully configured '0x00124b00231e60aa'

I had another one of this model in drawer, so I've tried to connect new one to replace that malfuncing one, but I've got the same errors.
Now when I look at this device in Z2M GUI I can see that it don't have any reporting configured, and I cannot do it manualy either.

## What did you expect to happen
I expected it to join and configure without any problem.

## How to reproduce it (minimal and precise)
Change reporting of temperature, or join new device.

## Debug info
Zigbee2MQTT version: 1.21.2 commit: 4492212
Adapter hardware: SMARTLIGHT CC2652P
Adapter firmware version: 20210708

**Comment by Koenkk** [comment] 2021-10-10 16:12
Duplicate of #8971

**Closed by Koenkk** 2021-10-10 16:12 UTC
Labels: problem
