### ISSUE TITLE
SEA_801 wrongly identified as 802

### ISSUE THREAD

**Issue by BugsonPL** [Koenkk/zigbee2mqtt#5432] opened 2020-12-28 15:54 UTC
## What happened
I have two SEA_801. one is recognized as 802
0x60a423fffeb5b9ff (0x4C7E)	Saswell	SEA802-Zigbee
0x5c0272fffec3c90a (0x3687)	Saswell	SEA801-Zigbee

## How to reproduce it (minimal and precise)
With dev docker image

## Debug info
Zigbee2MQTT version: "commit": "7c7df14"
Adapter hardware: CC2531
Adapter firmware version: default 20190608

**Comment by Koenkk** [comment] 2020-12-28 16:13
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/5374 and fixed in https://github.com/Koenkk/zigbee-herdsman-converters/pull/1968

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Closed by Koenkk** 2020-12-28 16:13 UTC
Labels: problem
