### ISSUE TITLE
Electricity Grid Integration

### ISSUE THREAD

**Issue by jd1900** [Koenkk/zigbee2mqtt#8273] opened 2021-08-06 07:15 UTC
The new Electricity Grid option in HA (https://www.home-assistant.io/docs/energy/electricity-grid/) is not supported by the devices that report power usage in Z2M.

It would be great to expose them from Z2M to be able to use them in HA.

**Comment by Koenkk** [comment] 2021-08-06 09:08
Dupe of #8259

**Closed by Koenkk** 2021-08-06 09:08 UTC
Labels: feature request
