### ISSUE TITLE
[New device support]: Paulmann 500.46

### ISSUE THREAD

**Issue by Fluke242** [Koenkk/zigbee2mqtt#13006] opened 2022-07-01 15:12 UTC
### Link

https://de.paulmann.com/p/maxled-500-controller-smart-home-zigbee-tunable-white-dc-24v-max.-144w-weiss-grau/50046

### Database entry

{"id":9,"type":"Router","ieeeAddr":"0x00158d00015c54cb","nwkAddr":12295,"manufId":4509,"manufName":"Paulmann Licht GmbH ","powerSource":"Mains (single phase)","modelId":"CCT light ","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":268,"inClusterList":[0,4,3,6,8,5,768,4096],"outClusterList":[25],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":1,"stackVersion":1,"hwVersion":1,"dateCode":"20160301","swBuildId":"1218-0909","zclVersion":2,"interviewCompleted":true,"meta":{},"lastSeen":1656686968756,"defaultSendRequestWhen":"immediate"}

### Comments

I used to have that devicee working but since some time (do not know exactly the point in time), the device is shown as "Unsupported" and CCT light.
Since I need to control kids' nightlight with that device, I need support for it.

### Supported color modes

cold and warm white

**Comment by Koenkk** [comment] 2022-07-01 21:06
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/12701, fixed in z2m 1.26.0

**Closed by Koenkk** 2022-07-01 21:06 UTC
Labels: new device support
