### ISSUE TITLE
Legrand 067776 ota

### ISSUE THREAD

**Issue by stefanuytterhoeven** [Koenkk/zigbee2mqtt#18990] opened 2023-09-16 16:33 UTC
### What happened?

Ota update failed. Invalid image

Z2m:current firmware build date: 20191105
Firmware version 0037
Home assistant says the version is: 
Current version 3621887
Latest version 3686915

### What did you expect to happen?

Update to new version with correct image

### Zigbee2MQTT version

1.33.0

### Adapter firmware version

 20220219

### Adapter

Sonoff zigbee 3.0 usb dongle plus

**Comment by Koenkk** [comment] 2023-09-16 18:02
duplicate of https://github.com/Koenkk/zigbee-OTA/issues/328

**Closed** 2023-09-16 18:02 UTC
Labels: problem

**Comment by stefanuytterhoeven** [comment] 2023-09-16 18:03
Sorry, did a search, but didn't get a result.
