### ISSUE TITLE
Invalid and problematic version used for HA update entities

### ISSUE THREAD

**Issue by frenck** [Koenkk/zigbee2mqtt#15502] opened 2022-12-11 23:03 UTC
### What happened?

It seems like Zigbee2MQTT feeds Home Assistant false information about the versioning of an update.

For example:

<img width="562" alt="5815CE37-E362-4487-A127-52EDC7008712" src="https://user-images.githubusercontent.com/195327/206933992-9ddcd922-5dc9-4d0e-b75d-54a75e367fba.png">

The latest version is “newer”, but it must contain a valid version number.

As a result of this, the update entity doesn’t work as expected. A version is required for the update entity.

If an device cannot provide version details, it should provide an binary sensor with the update class instead.

Home Assistant doesn’t support fake versions, as it breaks things like, for example, skipping updates. Therefore the example shown above, should not be pushed as such to HA.

### What did you expect to happen?

Not “newer”, but an actual version reference.

### How to reproduce it (minimal and precise)

Have an update ready to installed for any device and use the HA discovery.

### Zigbee2MQTT version

1.28.4

### Adapter firmware version

Not applicable 

### Adapter

Not applicable

**Comment by rwojnarowski** [comment] 2022-12-12 14:28
i can confirm same issue:


### Zigbee2MQTT version:
1.28.4-1

### Screenshots:
![Screenshot 2022-12-12 at 15 27 19](https://user-images.githubusercontent.com/7086808/207070435-7150e104-c349-47fa-b968-7ab1c7575dde.png)
![Screenshot 2022-12-12 at 15 27 13](https://user-images.githubusercontent.com/7086808/207070437-a062f0f7-6fda-4383-9b56-8a5c3b636dbb.png)

**Comment by Koenkk** [comment] 2022-12-12 20:03
Currently the `swBuildId` attribute from the basic cluster is used. Since you cannot determine the new `swBuildId` from an OTA file it shows `newer` once an OTA update available. In Zigbee the `fileVersion` is used to determine if the OTA is newer than the current installed fw. The device requests an OTA with its current `fileVersion`, then z2m checks if the available OTA has a new `fileVersion`. I'll check if we can switch to the `fileVersion` approach, downside is that we only have the `fileVersion` available when the device requests an OTA.

**Comment by frenck** [comment] 2022-12-12 20:09
>  I'll check if we can switch to the fileVersion approach, downside is that we only have the fileVersion available when the device requests an OTA.

That is fine as well, that won't break any logic.

**Comment by Koenkk** [comment] 2022-12-18 21:06
Fixed by https://github.com/Koenkk/zigbee2mqtt/pull/15630

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Closed by Koenkk** 2022-12-18 21:06 UTC
Labels: problem

**Comment by frenck** [comment] 2022-12-19 11:55
Thanks @Koenkk ❤️ 

Happy Holidays 🎄 

../Frenck

**Comment by Koenkk** [comment] 2022-12-19 19:41
@frenck thanks, you too ❤️
