### ISSUE TITLE
IKEA E1744 action information is twice

### ISSUE THREAD

**Issue by unpack8866** [Koenkk/zigbee2mqtt#3853] opened 2020-07-05 07:11 UTC
zigbee2mqtt:info  2020-07-05 15:08:34: MQTT publish: topic 'zigbee2mqtt/0xec1bbdfffe36d6b9', payload '{"rate":195,"linkquality":117,"update_available":false,"brightness":255,"battery":60,"action":"toggle"}'
zigbee2mqtt:info  2020-07-05 15:08:34: MQTT publish: topic 'zigbee2mqtt/0xec1bbdfffe36d6b9', payload '{"rate":195,"linkquality":117,"update_available":false,"brightness":255,"battery":60,"action":""}'
zigbee2mqtt:info  2020-07-05 15:08:34: MQTT publish: topic 'zigbee2mqtt/0xec1bbdfffe36d6b9/action', payload 'toggle'
zigbee2mqtt:info  2020-07-05 15:08:34: MQTT publish: topic 'zigbee2mqtt/0xec1bbdfffe36d6b9', payload '{"rate":195,"linkquality":117,"update_available":false,"brightness":255,"battery":60,"action":"toggle"}'
zigbee2mqtt:info  2020-07-05 15:08:34: MQTT publish: topic 'zigbee2mqtt/0xec1bbdfffe36d6b9', payload '{"rate":195,"linkquality":117,"update_available":false,"brightness":255,"battery":60,"action":""}'
zigbee2mqtt:info  2020-07-05 15:08:34: MQTT publish: topic 'zigbee2mqtt/0xec1bbdfffe36d6b9/action', payload 'toggle'

**Comment by Koenkk** [comment] 2020-07-05 11:44
This is expected, required for Home Assistant automations, see https://github.com/Koenkk/zigbee2mqtt/issues/1155#issuecomment-467094619

Duplicate of #1155 and #1212

**Closed by Koenkk** 2020-07-05 11:44 UTC
