### ISSUE TITLE
New group implementation error: Covers / Blinds not working in all cases

### ISSUE THREAD

**Issue by jd1900** [Koenkk/zigbee2mqtt#7962] opened 2021-07-06 08:13 UTC
## Problem
I'm trying the new group feature using blinds / covers.

However, I have two problems:
- I can't use the Open / Close / Stop controls in Home Assistant. 
- I can't controll through Google Assistant, maybe because it uses does controls.
However, I can set position to 0 (closed), 100 (opened) or any other number in the group, it works in Home Assistant (not in Google Assistant).

Individually the commands work fine. They are Legrand wired shutter switches (https://www.zigbee2mqtt.io/devices/067776.html).

It seems that the sent command is "open" / "close" instead of "on" / "off". And yes, all of the devices in the group are covers.

I think of a workaround: change the open/close commands internally to use 0/100 positions.
However, it would still miss the stop command.

## Log
When pressing "close"
```
Zigbee2MQTT:debug 2021-07-06 10:15:19: Received MQTT message on 'zigbee2mqtt/g_my_covers/set' with data 'CLOSE'
Zigbee2MQTT:debug 2021-07-06 10:15:19: Publishing 'set' 'state' to 'g_my_covers'
Zigbee2MQTT:error 2021-07-06 10:15:19: Publish 'set' 'state' to 'g_my_covers' failed: 'Error: State value of message: '{"state":"CLOSE"}' invalid, must be 'ON', 'OFF' or 'TOGGLE''
Zigbee2MQTT:debug 2021-07-06 10:15:19: Error: State value of message: '{"state":"CLOSE"}' invalid, must be 'ON', 'OFF' or 'TOGGLE'
    at Object.convertSet (/app/node_modules/zigbee-herdsman-converters/converters/toZigbee.js:737:23)
    at EntityPublish.onMQTTMessage (/app/lib/extension/publish.js:232:52)
    at Controller.callExtensionMethod (/app/lib/controller.js:397:44)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Zigbee2MQTT:info  2021-07-06 10:15:19: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'state' to 'g_my_covers' failed: 'Error: State value of message: '{\"state\":\"CLOSE\"}' invalid, must be 'ON', 'OFF' or 'TOGGLE''","meta":{"friendly_name":"g_my_covers"},"type":"zigbee_publish_error"}'
```

Pressing STOP:
```
Zigbee2MQTT:debug 2021-07-06 10:18:14: Received MQTT message on 'zigbee2mqtt/g_my_covers/set' with data 'STOP'
Zigbee2MQTT:debug 2021-07-06 10:18:14: Publishing 'set' 'state' to 'g_my_covers'
Zigbee2MQTT:error 2021-07-06 10:18:14: Publish 'set' 'state' to 'g_my_covers' failed: 'Error: State value of message: '{"state":"STOP"}' invalid, must be 'ON', 'OFF' or 'TOGGLE''
Zigbee2MQTT:debug 2021-07-06 10:18:14: Error: State value of message: '{"state":"STOP"}' invalid, must be 'ON', 'OFF' or 'TOGGLE'
    at Object.convertSet (/app/node_modules/zigbee-herdsman-converters/converters/toZigbee.js:737:23)
    at EntityPublish.onMQTTMessage (/app/lib/extension/publish.js:232:52)
    at Controller.callExtensionMethod (/app/lib/controller.js:397:44)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Zigbee2MQTT:info  2021-07-06 10:18:14: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'state' to 'g_my_covers' failed: 'Error: State value of message: '{\"state\":\"STOP\"}' invalid, must be 'ON', 'OFF' or 'TOGGLE''","meta":{"friendly_name":"g_my_covers"},"type":"zigbee_publish_error"}'
```

## Debug info
Zigbee2MQTT version: 1.20.0 commit: 1.20.0
Adapter hardware: zzh
Coordinator type: zStack3x0
Coordinator revision: 20210120
Frontend version: 0.4.29

**Comment by sjorge** [comment] 2021-07-06 10:45
I'm guessing the group extension just needs to be updated to know about states that are not ON, OFF or TOGGLE as I believe there is some logic around that to make groups appear correctly.

It should probably treat OPEN like ON, CLOSE like OFF and STOP similar to TOGGLE.

Based on the stack though, it looks like the group extension is also picking the wrong converter and is using the one for lights.

@Koenkk probably know exactly what is going wrong with the converter selection.

**Comment by Koenkk** [comment] 2021-07-06 13:04
Duplicate of #7922

**Closed by Koenkk** 2021-07-06 13:04 UTC
Labels: problem

**Comment by jd1900** [comment] 2021-07-06 14:47
> Duplicate of #7922

In that issue you say it is fixed and that it may be a problem of not only having covers.
However, I only have covers and still have the problem.

**Comment by Koenkk** [comment] 2021-07-06 17:45
@jd1900 then the issue is not fixed yet, please post your data/databse.db entry of your group in #7922

**Comment by jd1900** [comment] 2021-07-06 19:46
> @jd1900 then the issue is not fixed yet, please post your data/databse.db entry of your group in #7922

Where can I send it to you?
And..., in which version did you solve it?
I have the latest from this repo: https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/tree/master/zigbee2mqtt
Maybe not the same as this one?

**Comment by Koenkk** [comment] 2021-07-07 15:48
@jd1900 you can put it there (just comment). You need to be on the  latest-dev. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
