### ISSUE TITLE
mqtt cover warnings

### ISSUE THREAD

**Issue by hellcry37** [Koenkk/zigbee2mqtt#15967] opened 2023-01-05 17:14 UTC
### What happened?

New warning / errors in home assistant logs from latest update of Zigbee2MQTT 1.29.0

### What did you expect to happen?

nothing, that was the best thing in this case

### How to reproduce it (minimal and precise)

look at home assistant logs

### Zigbee2MQTT version

1.29.0 commit: dddce57

### Adapter firmware version

20220219

### Adapter

zig-a-zig-ah!

### Debug log

Logger: homeassistant.components.mqtt.cover
Source: components/mqtt/cover.py:395
Integration: MQTT (documentation, issues)
First occurred: 11:58:02 (319 occurrences)
Last logged: 19:06:34

Payload is not supported (e.g. open, closed, opening, closing, stopped): OFF

**Comment by Koenkk** [comment] 2023-01-06 08:58
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/15873

**Closed by Koenkk** 2023-01-06 08:58 UTC
Labels: problem
