### ISSUE TITLE
New Loratap zigbee 1 gang dimmer module

### ISSUE THREAD

**Issue by Iroamstaff** [Koenkk/zigbee2mqtt#14582] opened 2022-10-21 19:04 UTC
### Link

https://a.aliexpress.com/_EzMEOYd

### Database entry

{"id":17,"type":"Router","ieeeAddr":"0xa4c13866d5569a61","nwkAddr":26366,"manufId":4417,"manufName":"_TZE200_vucankjx","powerSource":"Mains (single phase)","modelId":"TS0601","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[4,5,61184,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65503":"���*f���*\u0012���*e","65506":54,"65508":0,"stackVersion":0,"dateCode":"","appVersion":70}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":70,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1666384337673,"defaultSendRequestWhen":"immediate"}

**Comment by Koenkk** [comment] 2022-10-22 07:28
Could you check if the issue is fixed with the following external converter:

```js
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const ota = require('zigbee-herdsman-converters/lib/ota');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const utils = require('zigbee-herdsman-converters/lib/utils');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    fingerprint: tuya.fingerprint('TS0601', ['_TZE200_ip2akl4w', '_TZE200_1agwnems', '_TZE200_la2c2uo9', '_TZE200_579lguh2', '_TZE200_vucankjx']),
    model: 'TS0601_dimmer_1',
    vendor: 'TuYa',
    description: '1 gang smart dimmer',
    fromZigbee: [tuya.fzDataPoints],
    toZigbee: [tuya.tzDataPoints],
    configure: tuya.configureMagicPacket,
    exposes: [tuya.exposes.lightBrightnessWithMinMax(), tuya.exposes.powerOnBehavior(),
        tuya.exposes.countdown(), tuya.exposes.lightType()],
    meta: {
        tuyaDatapoints: [
            [1, 'state', tuya.valueConverter.onOff, {skip: tuya.skip.stateOnAndBrightnessPresent}],
            [2, 'brightness', tuya.valueConverter.scale0_254to0_1000],
            [3, 'min_brightness', tuya.valueConverter.scale0_254to0_1000],
            [4, 'light_type', tuya.valueConverter.lightType],
            [5, 'max_brightness', tuya.valueConverter.scale0_254to0_1000],
            [6, 'countdown', tuya.valueConverter.countdown],
            [14, 'power_on_behavior', tuya.valueConverter.powerOnBehavior],
        ],
    },
    whiteLabel: [
        {vendor: 'Moes', model: 'MS-105Z'},
        {vendor: 'Lerlink', model: 'X706U'},
        {vendor: 'Moes', model: 'ZS-EUD_1gang'},
    ],
};

module.exports = definition;
```

- save this as file next to `configuration.yaml` as `ext_converter.js`
- add it to `configuration.yaml`:
```yaml
external_converters:
  - ext_converter.js
```
- start z2m, check if device works

**Comment by Iroamstaff** [comment] 2022-10-22 08:52
Merci pour t'as rapidité de réponse
Rien ne change Il n'est toujours pas reconnu
Fonctionne qu'avec l'interrupteur brancher dessus

**Comment by Iroamstaff** [comment] 2022-10-22 09:08
Je suis novice je te montre pour être sûr d'avoir bien suivi ce que tu m'as dit faire pour pas te faire perdre ton temps par ma faute.
![Screenshot_2022-10-22-11-03-02-476_io homeassistant companion android](https://user-images.githubusercontent.com/111296265/197330996-f707a15c-d414-49d8-be57-1be575c4ce23.jpg)
![Screenshot_2022-10-22-11-02-05-371_io homeassistant companion android](https://user-images.githubusercontent.com/111296265/197331038-348a9f30-d5ee-4084-a874-9ce2438dd5cf.jpg)
Et j'ai bien redémarré zigbee2mqtt

**Comment by Iroamstaff** [comment] 2022-10-22 12:12
une erreur de ma part j'ai enlevé les espaces devant external_convecters:
maintenant z2m ne démarre plus voici le log 
[14:06:42] INFO: Preparing to start...
[14:06:43] INFO: Socat not enabled
[14:06:45] INFO: Starting Zigbee2MQTT...
/app/dist/util/externally-loaded.js:20
    exposes: [tuya.exposes.lightBrightnessWithMinMax(), tuya.exposes.powerOnBehavior(),
                           ^
TypeError: tuya.exposes.lightBrightnessWithMinMax is not a function
    at /app/dist/util/externally-loaded.js:20:28
    at Script.runInContext (node:vm:139:12)
    at Script.runInNewContext (node:vm:144:17)
    at Object.runInNewContext (node:vm:298:38)
    at loadModuleFromText (/app/lib/util/utils.ts:148:8)
    at loadModuleFromFile (/app/lib/util/utils.ts:155:12)
    at Object.getExternalConvertersDefinitions (/app/lib/util/utils.ts:165:25)
    at getExternalConvertersDefinitions.next (<anonymous>)
    at new ExternalConverters (/app/lib/extension/externalConverters.ts:12:20)
    at new Controller (/app/lib/controller.ts:84:58)

**Comment by Iroamstaff** [comment] 2022-11-05 10:09
I just tried the external converter again since the last update and now everything works thank you you are on top 👍
![16676429156197131976862882785698](https://user-images.githubusercontent.com/111296265/200114641-85c4c5eb-1e35-4286-ad55-cd689552031c.jpg)

**Closed** 2022-11-05 10:10 UTC
Labels: new device support

**Comment by Koenkk** [comment] 2022-11-05 13:59
Great, added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
