### ISSUE TITLE
Device update states stuck in a loop

### ISSUE THREAD

**Issue by Grandma-Betty** [Koenkk/zigbee2mqtt#19622] opened 2023-11-08 08:46 UTC
### What happened?

Since the latest Z2M update, when there are updates available for any ZigBee devices connected to Z2M, the according ZigBee devices appear as updateable for a few seconds and then go into "updating" state automatically without starting the updates manually. But the devices are not updating, the update circle is rotating in a loop forever.
This happens on every Home Assistant reboot again and again. The only "solution" is to disable the **update.mydevice** entity completely so it won't appear on the GUI again.

![Screenshot 2023-11-08 093537](https://github.com/Koenkk/zigbee2mqtt/assets/48346793/49cdb3f2-6a9a-4715-9bcc-132c047d0fd6)

### Zigbee2MQTT version

1.33.2-1

### Adapter firmware version

20221226

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus

**Comment by ExMacro** [comment] 2023-11-08 15:29
I have the same problem. However, starting the updates from OTA updater page in Z2M seems to work. It will get rid of the update loop. At least the first light I updated did.. Still many to go.

**Comment by Koenkk** [comment] 2023-11-08 16:42
could you check if this is solved in the dev branch? (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by lichtl** [comment] 2023-11-10 13:47
its resolved in 1.33.2-dev commit: [d26ea1a](https://github.com/Koenkk/zigbee2mqtt/commit/d26ea1a)

Had to restart the entire system (HA + MQTT as well)

**Comment by LeoCal** [comment] 2023-11-10 14:51
Same issue seen on my instance

**Comment by Koenkk** [comment] 2023-11-10 20:42
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/19597 and should be fixed in the dev branch.

**Closed by Koenkk** 2023-11-10 20:42 UTC
Labels: problem
