### ISSUE TITLE
Lidl FB20-002 the "on" button is only evaluated once

### ISSUE THREAD

**Issue by makoONE** [Koenkk/zigbee2mqtt#6509] opened 2021-03-01 11:24 UTC
## What happened
The status of the "on" button is only evaluated for a single actuation.
Pressing the "on" button again will be ignored. The other buttons ("off", "brightness up", "brightness down)" generate an event each time they are pressed, as expected.

## What did you expect to happen
I will get an event every time i press the button again.

## How to reproduce it (minimal and precise)
Pressing the "on"-button several times and watch the mqtt messages for expected actions or by debugging in a simple Node-RED flow.

## Debug info
Zigbee2MQTT version: 1.17.1 
Adapter hardware: CC2531
Adapter firmware version: 20190608 (coordinator)

**Comment by OMotornyi** [comment] 2021-11-10 23:23
Hello. Were you able to figure this one out?

**Comment by OMotornyi** [comment] 2022-08-31 17:41
yeah... It's a shame though really, basically renders this remote less useful as we can't bind a completely independent actions on every button

**Comment by chris400** [comment] 2023-10-08 20:15
I'm so glad that I found that issue. I was starting to question myself bc I thought I made a mistake in my Home Assistant configuration.

So here is my though on this:
The first "on" command looks like this
`Debug 2023-10-08 22:10:54Received Zigbee message from 'ZigBee Remote 003', type 'commandOn', cluster 'genOnOff', data '{}' from endpoint 1 with groupID 0`
the next 4 times it looks like this
`Debug 2023-10-08 22:11:01Received Zigbee message from 'ZigBee Remote 003', type 'raw', cluster 'genOnOff', data '{"data":[1,79,253,0],"type":"Buffer"}' from endpoint 1 with groupID null
Debug 2023-10-08 22:11:02Received Zigbee message from 'ZigBee Remote 003', type 'raw', cluster 'genOnOff', data '{"data":[1,79,253,0],"type":"Buffer"}' from endpoint 1 with groupID null
Debug 2023-10-08 22:11:02Received Zigbee message from 'ZigBee Remote 003', type 'raw', cluster 'genOnOff', data '{"data":[1,79,253,0],"type":"Buffer"}' from endpoint 1 with groupID null
Debug 2023-10-08 22:11:03Received Zigbee message from 'ZigBee Remote 003', type 'raw', cluster 'genOnOff', data '{"data":[1,79,253,0],"type":"Buffer"}' from endpoint 1 with groupID null
Debug 2023-10-08 22:11:04Received Zigbee message from 'ZigBee Remote 003', type 'raw', cluster 'genOnOff', data '{"data":[1,79,253,0],"type":"Buffer"}' from endpoint 1 with groupID null
Debug 2023-10-08 22:11:13Received Zigbee message from 'ZigBee Remote 003', type 'raw', cluster 'genOnOff', data '{"data":[1,80,253,1],"type":"Buffer"}' from endpoint 1 with groupID null
Debug 2023-10-08 22:11:13Received Zigbee message from 'ZigBee Remote 003', type 'raw', cluster 'genOnOff', data '{"data":[1,80,253,1],"type":"Buffer"}' from endpoint 1 with groupID null
Debug 2023-10-08 22:11:14Received Zigbee message from 'ZigBee Remote 003', type 'raw', cluster 'genOnOff', data '{"data":[1,80,253,1],"type":"Buffer"}' from endpoint 1 with groupID null
Debug 2023-10-08 22:11:15Received Zigbee message from 'ZigBee Remote 003', type 'raw', cluster 'genOnOff', data '{"data":[1,80,253,1],"type":"Buffer"}' from endpoint 1 with groupID null
Debug 2023-10-08 22:11:15Received Zigbee message from 'ZigBee Remote 003', type 'raw', cluster 'genOnOff', data '{"data":[1,80,253,1],"type":"Buffer"}' from endpoint 1 with groupID null
Debug 2023-10-08 22:11:27Received Zigbee message from 'ZigBee Remote 003', type 'raw', cluster 'genOnOff', data '{"data":[1,81,253,2],"type":"Buffer"}' from endpoint 1 with groupID null
Debug 2023-10-08 22:11:28Received Zigbee message from 'ZigBee Remote 003', type 'raw', cluster 'genOnOff', data '{"data":[1,81,253,2],"type":"Buffer"}' from endpoint 1 with groupID null
Debug 2023-10-08 22:11:29Received Zigbee message from 'ZigBee Remote 003', type 'raw', cluster 'genOnOff', data '{"data":[1,81,253,2],"type":"Buffer"}' from endpoint 1 with groupID null
Debug 2023-10-08 22:11:30Received Zigbee message from 'ZigBee Remote 003', type 'raw', cluster 'genOnOff', data '{"data":[1,81,253,2],"type":"Buffer"}' from endpoint 1 with groupID null
Debug 2023-10-08 22:11:30Received Zigbee message from 'ZigBee Remote 003', type 'raw', cluster 'genOnOff', data '{"data":[1,81,253,2],"type":"Buffer"}' from endpoint 1 with groupID null
Debug 2023-10-08 22:11:41Received Zigbee message from 'ZigBee Remote 003', type 'raw', cluster 'genOnOff', data '{"data":[1,82,253,3],"type":"Buffer"}' from endpoint 1 with groupID null
Debug 2023-10-08 22:11:41Received Zigbee message from 'ZigBee Remote 003', type 'raw', cluster 'genOnOff', data '{"data":[1,82,253,3],"type":"Buffer"}' from endpoint 1 with groupID null
Debug 2023-10-08 22:11:42Received Zigbee message from 'ZigBee Remote 003', type 'raw', cluster 'genOnOff', data '{"data":[1,82,253,3],"type":"Buffer"}' from endpoint 1 with groupID null
Debug 2023-10-08 22:11:43Received Zigbee message from 'ZigBee Remote 003', type 'raw', cluster 'genOnOff', data '{"data":[1,82,253,3],"type":"Buffer"}' from endpoint 1 with groupID null
Debug 2023-10-08 22:11:44Received Zigbee message from 'ZigBee Remote 003', type 'raw', cluster 'genOnOff', data '{"data":[1,82,253,3],"type":"Buffer"}' from endpoint 1 with groupID null`

I would like to request, that zigbee2mqtt interprets these commands as "On" as well.

**Comment by Kaskadeur111** [comment] 2023-11-05 20:10
same here, find it less usefull, if that ON Button only works once

**Comment by chris400** [comment] 2023-12-10 12:07
@makoONE I just came back here. Would you mind re-opening this issue and removing staklle lable?

**Comment by Bastelritius** [comment] 2023-12-28 17:00
Would be nice when this can be solved and the RC sending always the on command when pushing the on button

**Comment by jnswb** [comment] 2024-02-08 18:57
I second this proposal.

**Comment by chris400** [comment] 2024-02-08 22:54
Bc @makoONE is not responding, would you @Koenkk mind re-opening this issue?

**Comment by Virusmater** [comment] 2024-06-15 22:22
Same issue there, but I don't even see any RAW commands in logs. Is it because my remote was never connected to Tuya?

**Comment by chris400** [comment] 2024-06-16 06:27
> Same issue there, but I don't even see any RAW commands in logs. Is it because my remote was never connected to Tuya?

I don't think so. I have never used anything else than Zigbee2MQTT with my device and I did see these commands.
Did you set the right log level?

**Comment by Virusmater** [comment] 2024-06-16 11:39
I don't think so, logs are on the debug level and I can see codes of other button presses in logs.
Also my remote looks slightly different from the one on the z2m page:
![image](https://github.com/Koenkk/zigbee2mqtt/assets/99446/98d97674-a067-468d-a658-b556f4c15ede)

**Comment by akula3** [comment] 2024-07-04 15:20
Is here a solution or workaround?

**Comment by Koenkk** [comment] 2024-07-06 09:16
Could you check if the issue is fixed with the following [external converter](https://gist.github.com/Koenkk/d524d84f7e5e3b9d20559dd296d005b2): 

- save this as file next to `configuration.yaml` as `ext_converter.js`
- add it to `configuration.yaml`:
```yaml
external_converters:
  - ext_converter.js
```
- start z2m, check if issue is fixed

**Comment by Virusmater** [comment] 2024-07-06 13:44
Hello @Koenkk , it worked after the small change: `type: 'raw'` to `type: 'commandTuyaAction'`
Full gist:
https://gist.github.com/Virusmater/13a39d8d2fed6d2b110d1cf8968decb1

Logs before:
```
[2024-07-06 15:35:50] debug: 	z2m: Received Zigbee message from 'Guest Blinds Remote', type 'commandTuyaAction', cluster 'genOnOff', data '{"data":{"data":[],"type":"Buffer"},"value":2}' from endpoint 1 with groupID 0
[2024-07-06 15:35:50] debug: 	z2m: No converter available for 'FB20-002' with cluster 'genOnOff' and type 'commandTuyaAction' and data '{"data":{"data":[],"type":"Buffer"},"value":2}'
[2024-07-06 15:35:50] debug: 	zh:zstack:unpi:parser: <-- [254,1,100,1,0,100]
[2024-07-06 15:35:50] debug: 	zh:zstack:unpi:parser: --- parseNext [254,1,100,1,0,100]
[2024-07-06 15:35:50] debug: 	zh:zstack:unpi:parser: --> parsed 1 - 3 - 4 - 1 - [0] - 100
[2024-07-06 15:35:50] debug: 	zh:zstack:znp: SRSP: <-- AF - dataRequest - {"status":0}
[2024-07-06 15:35:50] debug: 	zh:zstack:unpi:parser: --- parseNext []
[2024-07-06 15:35:50] debug: 	zh:zstack:unpi:parser: <-- [254,3,68,128,0,1,33,231]
[2024-07-06 15:35:50] debug: 	zh:zstack:unpi:parser: --- parseNext [254,3,68,128,0,1,33,231]
[2024-07-06 15:35:50] debug: 	zh:zstack:unpi:parser: --> parsed 3 - 2 - 4 - 128 - [0,1,33] - 231
[2024-07-06 15:35:50] debug: 	zh:zstack:znp: AREQ: <-- AF - dataConfirm - {"status":0,"endpoint":1,"transid":33}
[2024-07-06 15:35:50] debug: 	zh:zstack:unpi:parser: --- parseNext []
```

Logs now:
```
[2024-07-06 15:44:17] debug: 	z2m: Received Zigbee message from 'Guest Blinds Remote', type 'commandTuyaAction', cluster 'genOnOff', data '{"data":{"data":[],"type":"Buffer"},"value":0}' from endpoint 1 with groupID 0
[2024-07-06 15:44:17] info: 	z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Guest Blinds Remote', payload '{"action":"on","linkquality":84}'
[2024-07-06 15:44:17] info: 	z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Guest Blinds Remote', payload '{"action":"","linkquality":84}'
[2024-07-06 15:44:17] info: 	z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Guest Blinds Remote/action', payload 'on'
[2024-07-06 15:44:17] debug: 	zh:zstack:unpi:parser: <-- [254,1,100,1,0,100]
[2024-07-06 15:44:17] debug: 	zh:zstack:unpi:parser: --- parseNext [254,1,100,1,0,100]
[2024-07-06 15:44:17] debug: 	zh:zstack:unpi:parser: --> parsed 1 - 3 - 4 - 1 - [0] - 100
[2024-07-06 15:44:17] debug: 	zh:zstack:znp: SRSP: <-- AF - dataRequest - {"status":0}
[2024-07-06 15:44:17] debug: 	zh:zstack:unpi:parser: --- parseNext []
[2024-07-06 15:44:17] debug: 	zh:zstack:unpi:parser: <-- [254,3,68,128,0,1,22,208]
[2024-07-06 15:44:17] debug: 	zh:zstack:unpi:parser: --- parseNext [254,3,68,128,0,1,22,208]
[2024-07-06 15:44:17] debug: 	zh:zstack:unpi:parser: --> parsed 3 - 2 - 4 - 128 - [0,1,22] - 208
[2024-07-06 15:44:17] debug: 	zh:zstack:znp: AREQ: <-- AF - dataConfirm - {"status":0,"endpoint":1,"transid":22}
[2024-07-06 15:44:17] debug: 	zh:zstack:unpi:parser: --- parseNext []
```

 
Thank you!

**Comment by akula3** [comment] 2024-07-06 22:01
Hi @Koenkk ,
the proposal from @Virusmater works!

**Comment by Koenkk** [comment] 2024-07-08 20:02
Great, integrated the fix. You can remove the ext converter after updating to the next release.

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

**Closed by Koenkk** 2024-07-08 20:02 UTC
Labels: problem

**Comment by stefan131** [comment] 2024-07-17 09:40
I was about to jump into this issue, all of my ceiling lights came with this remote and they were useless before
Thanks for the great work! Looking forward to the next release :)

**Comment by stefan131** [comment] 2024-08-14 08:18
After some testing I found out the first 'on' button press is not registered anymore after this update. @Koenkk could the issue be opened again?

**Comment by stefan131** [comment] 2024-08-14 09:12
> Do you have the steps to reproduce? I have some issues when the first button press doesn't get registered, but I think it is not related to the update, I had it before. The remote drops out from the Zigbee network and on the first step, it just reconnects to it.
> 
> Cannot debug it, because it happens only after I haven't used the remote for a week

My experience is that Zigbee remotes start blinking when they are reconnecting.
For me it just shows the normal green light, and the second press immediately works.
I'll try to debug it some more when I get home.

Reproducing is easy: don't touch your remote for about 30 minutes and push the on button.
I'll do some more testing tonight, for example if pressing off and then on gives the same result. I vaguely remember that it did
