### ISSUE TITLE
IOTPerfect PF-PM02D-TYZ  not support

### ISSUE THREAD

**Issue by kylinfedora** [Koenkk/zigbee2mqtt#12117] opened 2022-04-08 14:24 UTC
### What happened?

IOTPerfect PF-PM02D-TYZ  not support
zigbee2mqtt webpage:  https://www.zigbee2mqtt.io/devices/PF-PM02D-TYZ.html#iotperfect-pf-pm02d-tyz

zigbee2mqtt debug info:

```
Please see: https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html
Debug Received Zigbee message from '0xa4c138eb24e9e04f', type 'commandDataReport', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0],"type":"Buffer"},"datatype":1,"dp":1}],"seq":0}' from endpoint 1 with groupID 0
Warning Received message from unsupported device with Zigbee model 'TS0601' and manufacturer name '_TZE200_d0ypnbvn'
```

### Zigbee2MQTT version

 1.25.0

### Adapter firmware version

20211217

### Adapter

Tube's Zigbee Gateways (CC2652P2 variant)

**Comment by Koenkk** [comment] 2022-04-08 14:45
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/12093

**Closed by Koenkk** 2022-04-08 14:45 UTC
Labels: problem
