### ISSUE TITLE
Xiaomi SSM-U01 not showing power, energi after update ti 1.24.0

### ISSUE THREAD

**Issue by chersoph** [Koenkk/zigbee2mqtt#11689] opened 2022-03-03 10:34 UTC
### What happened?

The SSM-UO1 does not show power and energi. I have after upgrading repaired the unit with out any change, still no power or energy values.

### What did you expect to happen?

Since "https://github.com/Koenkk/zigbee2mqtt/issues/11368 Expose voltage, current and temperature for Xiaomi SSM-U01" is listed under improvement on "https://github.com/Koenkk/zigbee2mqtt/discussions/11661", I was hoping that it would be solved.

### Zigbee2MQTT version

 1.24.0 

### Adapter firmware version

 0x26690700

### Adapter

deconz Raspbee ii

**Comment by Koenkk** [comment] 2022-03-03 17:13
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/11368

**Closed by Koenkk** 2022-03-03 17:13 UTC
Labels: problem
