### ISSUE TITLE
Recent pairing issue

### ISSUE THREAD

**Issue by fjumeaux** [Koenkk/zigbee2mqtt#24111] opened 2024-09-26 18:10 UTC
### What happened?

During a small restructuring of my Zigbee network, I was unable to re-pair several devices :

- Sonoff zbmini 2 (extreme)
- Sonoff SNZP-06P
- Ikea VALLHORN
- 
The device behaves as if it had been paired (it stops flashing, etc.). But Z2M says nothing, no message, reports no pairing. No additional devices in the list.

### What did you expect to happen?

That the devices are paired

### How to reproduce it (minimal and precise)

Don't know. No change. it worked before

### Zigbee2MQTT version

1.40.1-dev commit: 15d845b

### Adapter firmware version

0x26530900

### Adapter

Conbee3

### Setup

Docker. No recent changes except z2m update regularly

### Debug log

No log .Like it was a ghost pairing

**Comment by Koenkk** [comment] 2024-09-27 15:23
Looks like a duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/23996

**Closed by Koenkk** 2024-09-27 15:23 UTC
Labels: problem
