### ISSUE TITLE
TuYa TS011F_plug_1 | Zigbee2MQTT exposing wrong values

### ISSUE THREAD

**Issue by b2Homard** [Koenkk/zigbee2mqtt#17600] opened 2023-05-08 13:30 UTC
### What happened?

Hello everyone !

As i was trying to setup some simple automation using a smart plug with power measurement, and struggled a lot, I saw something I can’t understand.

I turn ON the fan plugged to the smart plug and Zigbee2MQTT is exposing 33W, which is normal.

I also check manually the measured power using “Dev Console” Tab and read 33W.

I turn OFF the fan and Zigbee2MQTT still exposes 33W, forever. It will only change after I pull some power (e.g. >20W). It will also never go down to 0W even if the fan is OFF or unplugged.

However, if I manually check the power using the “Dev Console” tab, I always have the right value(0W when the fan is OFF and ~33W when the fan is ON).
![DevConsole](https://user-images.githubusercontent.com/128433358/236837172-e25e2165-8004-4d29-a1d8-9adbe3ab3e97.PNG)
![Exposes](https://user-images.githubusercontent.com/128433358/236837177-1c81e215-d022-4b33-a9c5-215fc23074e0.PNG)
![Reporting](https://user-images.githubusercontent.com/128433358/236837181-db10a257-1e9e-41d0-b05f-be64127673a7.PNG)

### What did you expect to happen?

Expose voltage, power and current periodically, as defined in the "Reporting" tab, no matter the load.

### How to reproduce it (minimal and precise)

Draw some power through the plug (at least 20W) then stop drawing power. Then draw less power (e.g. a small LED lamp, 6W). Observe that the exposed power (and current) is not actualizing. Manually read the consumed power to compare to the exposed power.

### Zigbee2MQTT version

 1.30.4

### Adapter firmware version

 6.10.3.0 build 297

### Adapter

Sonoff | Zigbee 3.0 | Dongle Plus-E

### Debug log

[DebugLog.txt](https://github.com/Koenkk/zigbee2mqtt/files/11421490/DebugLog.txt)

**Comment by alexh3o** [comment] 2023-05-09 11:17
Hello, I have the same problem, and according to this thread we need to wait a fix in the next z2m update
[Issue 17569](https://github.com/Koenkk/zigbee2mqtt/issues/17569)

**Comment by tjorim** [comment] 2023-05-09 16:44
Same here, Zigbee2MQTT stable version 1.30.4:

- Zigbee Model: TS011F
- Zigbee Manufacturer: _TZ3000_gvn91tmx

**Also** tested add-on **edge** version 1.30.4-dev **commit a6bebf1**, values go back to 0 but does not seem reliable.
E.g. kettle was off for hours, still took a few minutes and toggling the plug off and on a few times in z2m before it got to 0.
So seems to run better, but not as before. Will keep monitoring and try to compare to pre-1.30.4.

**Comment by Koenkk** [comment] 2023-05-09 17:43
Duplicate of #16709

**Closed by Koenkk** 2023-05-09 17:43 UTC
Labels: problem

**Comment by b2Homard** [comment] 2023-05-14 21:32
I don't think that I expose the same problem in my issue ! Maybe I'm missing something though.

**Comment by sved-SI** [comment] 2023-05-15 16:05
> Duplicate of #16709

Different problem. power stuck and won't change for days!  ( even if the heater is turned off ) Switch is set to off

**Comment by sved-SI** [comment] 2023-05-15 16:30
how you check the power using the “Dev Console ?

**Comment by Koenkk** [comment] 2023-05-15 17:17
Did you already check with the latest dev branch?  (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by b2Homard** [comment] 2023-05-20 14:22
Go to Zigbee2MQTT extension. Click on a device and go in the "Dev Console" Tab. Select "haElectricalMeasurement" in "Cluster" and  select "activePower" in "Attribute". _Above the green button "Read", a line will be added._ Click the "Read" button. This value is always right (for me at least).
![ReadUsingDevConsole](https://github.com/Koenkk/zigbee2mqtt/assets/128433358/1300ec03-834e-4788-8060-6a8947028774)

**Comment by Koenkk** [comment] 2023-05-21 13:55
@b2Homard the fix will be included in the next release on 1 June.

**Comment by sakirsek** [comment] 2023-06-22 10:02
> @b2Homard the fix will be included in the next release on 1 June.

hey Koenkk, the case of showing wrong current value continues. wattage is correct but current is wrong. It should be 2A but it shows 1A. 5v * 2A = 11W is correct.

![g1](https://github.com/Koenkk/zigbee2mqtt/assets/26142915/7f18c85c-0948-49b4-9e4c-1e838c03151b)
![g2](https://github.com/Koenkk/zigbee2mqtt/assets/26142915/9b761ab8-4e06-4c12-9115-a3bd4630e27b)
![g3](https://github.com/Koenkk/zigbee2mqtt/assets/26142915/2ff48510-6288-4524-a784-75187230dc59)

**Comment by network-shark** [comment] 2025-04-23 18:43
Could it be , that the issue is back ? I do have one TS011F_plug_3 which always sends power set to 35W it was working for month. Power cycle does not help .
