### ISSUE TITLE
HASS Z2M Add-on frontend/user interface "broken" after update to 1.35.3

### ISSUE THREAD

**Issue by denniskemmerling** [Koenkk/zigbee2mqtt#21298] opened 2024-02-08 06:51 UTC
### What happened?

After the update the frontend/user interface looks broken and not correct. 
![Screenshot 2024-02-08 074319](https://github.com/Koenkk/zigbee2mqtt/assets/143586208/5926a14a-4341-44dd-aea1-0dcf0adf0ff9)

### What did you expect to happen?

The standard user interface of Z2M

### Zigbee2MQTT version

1.35.3-1

### Adapter firmware version

20230507

### Adapter

Smlight SLZB-06

### Setup

Add-on on HASS OS on a Raspberry Pi

**Comment by joschaschultze** [comment] 2024-02-08 07:06
Yes, I had exactly the same problem and went back to 1.35.2.

**Comment by DuncanRae** [comment] 2024-02-08 07:18
This is a big that needs to be fixed, but the workaround is to click on the light/dark button. This seems to fix it.

**Comment by marsonde** [comment] 2024-02-08 07:19
Oh, great, that was simple! 😎 Thanks!

**Comment by joschaschultze** [comment] 2024-02-08 07:35
Great solution :-)

**Comment by jsa91** [comment] 2024-02-08 07:56
> This is a big that needs to be fixed, but the workaround is to click on the light/dark button. This seems to fix it.

Same issue here but thanks for the quick fix!

**Comment by kayserjan** [comment] 2024-02-08 09:35
> This is a bug that needs to be fixed, but the workaround is to click on the light/dark button. This seems to fix it.

where?
![image](https://github.com/Koenkk/zigbee2mqtt/assets/76105672/f02efa4f-d10c-4789-aeec-e997a0b91930)

**Comment by SVH-Powel** [comment] 2024-02-08 09:37
![image](https://github.com/Koenkk/zigbee2mqtt/assets/64255194/7a9feaae-3b18-4e8b-bbad-da604b3de382)

**Comment by Koenkk** [comment] 2024-02-08 19:11
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/21268

**Closed by Koenkk** 2024-02-08 19:11 UTC
Labels: problem
