### ISSUE TITLE
No network route with new firmware

### ISSUE THREAD

**Issue by LouisMT** [Koenkk/zigbee2mqtt#1537] opened 2019-05-16 21:18 UTC
# Bug Report
## What happened
After upgrading to the latest firmware (CC2530_20190425) my IKEA lamps are unresponsive at random times and for random lamps. I may be able to turn on all lamps now, but if I try to turn them off 5 seconds later, only half of them turn off. A few seconds later none of the lamps seem to respond, then only 1 or 2, etc. The log is full of lines like these:

```
zigbee2mqtt:error 5/16/2019, 8:54:02 PM Zigbee publish to device '0xd0cf5efffe16a96f', lightingColorCtrl - moveToColorTemp - {"colortemp":454,"transtime":0} - {"manufSpec":0,"disDefaultRsp":0} - null failed with error Error: AF data request fails, status code: 205. No network route. Please confirm that the device has (re)joined the network
```

[Full log here](https://pastebin.com/YQTUq6wY)

I have:
* Waited a long time to let the network find the correct routes again (the coordinator has been unavailable for quite some time during flashing)
* Power cycled the lamps
* Power cycled the coordinator
* Repaired the lamps (reset them while `permit_join` is `true`)

All the lamps are pretty close to the coordinator. One lamp less than 1 meter. Also, the network graph isn't showing any mesh network (it did before), all lamps are directly connected to the coordinator and some don't even have a line in the graph.

## What did you expect to happen
The lamps to respond. :smile: 

## How to reproduce it (minimal and precise)
Upgrade firmware to latest.

## Debug Info
zigbee2mqtt version: 1.4.0
CC253X firmware version: 20190425

**Comment by Koenkk** [comment] 2019-05-17 06:05
Duplicate of #1536

**Closed by Koenkk** 2019-05-17 06:05 UTC
