### ISSUE TITLE
Crash on loading due to undefined javascript object 

### ISSUE THREAD

**Issue by cat2devnull** [Koenkk/zigbee2mqtt#17993] opened 2023-06-11 06:00 UTC
### What happened?

Unable to launch zigbee2mqtt after a recent upgrade.
Running as docker on Unraid, pulling from koenkk/zigbee2mqtt repository.
1.30.4 and below work.
1.31.0 and above fail to launch with the error in the debug log below.
Also upgraded to latest adapter firmware to help rule that out as a potential issue.

### Zigbee2MQTT version

>1.31

### Adapter firmware version

20230507

### Adapter

Sonoff Zigbee 3.0 CC2652P

### Debug log

```
/app/node_modules/zigbee-herdsman-converters/index.js:79
        if (converter.options) {
                      ^
TypeError: Cannot read properties of undefined (reading 'options')
    at Object.addDefinition [as addDeviceDefinition] (/app/node_modules/zigbee-herdsman-converters/index.js:79:23)
    at new ExternalConverters (/app/lib/extension/externalConverters.ts:15:17)
    at new Controller (/app/lib/controller.ts:84:58)
    at start (/app/index.js:106:18)
Using '/app/data' as data directory
```

**Comment by Koenkk** [comment] 2023-06-12 15:50
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/17863#issuecomment-1573279515

**Closed by Koenkk** 2023-06-12 15:50 UTC
Labels: problem

**Comment by cat2devnull** [comment] 2023-06-13 04:50
Thanks!
