### ISSUE TITLE
Eco.Dim-07 Zigbee Smart Dimmer Switch 200W LED

### ISSUE THREAD

**Issue by Krolik1988** [Koenkk/zigbee2mqtt#7512] opened 2021-05-18 07:17 UTC
Eco.Dim-07 Zigbee Smart Dimmer Switch 200W LED (Router)
Type dimmer: R,C  Phase cut
Operation: Push / turn button

Input Cluster:
     - 0x0000: Basic
     - 0x0003: Identify
     - 0x0004: Groups
     - 0x0005: Scenes
     - 0x0006: On/off
     - 0x0008: Level Control
     - 0x0b05: Diagnostics
Output Cluster:
     - 0x0019: OTA
     
   `` {"id":7,
"type":"Router",
"ieeeAddr":"0x086bd7fffe5f149d",
"nwkAddr":30462,
"manufId":4714,
"manufName":"EcoDim BV",
"powerSource":"Mains (single phase)",
"modelId":"Dimmer-Switch-ZB3.0",
"epList":[1,242],
"endpoints":{"1":{"profId":260,"epId":1,"devId":257,"inClusterList":[0,3,4,5,6,8,2821,4096],"outClusterList":[25],
"clusters":{"genBasic":{"attributes":{"modelId":"Dimmer-Switch-ZB3.0","manufacturerName":"EcoDim BV",
"powerSource":1,
"zclVersion":3,
"appVersion":3,
"stackVersion":6,
"hwVersion":1,
"dateCode":"20200701",
"swBuildId":"3.09"}}},
"binds":[],
"configuredReportings":[],"meta":{}},
"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},
"binds":[],
"configuredReportings":[],
"meta":{}}},"appVersion":3,
"stackVersion":6,
"hwVersion":1,
"dateCode":"20200701",
"swBuildId":"3.09",
"zclVersion":3,
"interviewCompleted":true,"meta":{},
"lastSeen":1621281125643}``

 [Manual](https://www.ecobright.nl/wms/fm/userfiles/catalogus/attachments/ECO-DIM-07-Zigbee-Basic-handleiding.pdf)

Hello, I would like to ask you for help. I moved from Domoticz to Home Assistant (HASS) and now can't understand how to add new devices. In logs I can see:
 
Device '0x086bd7fffe5f149d' with Zigbee model 'Dimmer-Switch-ZB3.0' and manufacturer name 'EcoDim BV' is NOT supported.
10x Received message from unsupported device.

It was [#2342](https://github.com/Koenkk/zigbee2mqtt/issues/2342) @17.11.2019, Strange it not work now.

Thanks you, and have a good day.

**Comment by huizebruin** [comment] 2021-05-18 07:52
same here.

Friendly name
    0xccccccfffe3a1530
Last seen
    N/A
Device type
    Router
Zigbee model
    Dimmer-Switch-ZB3.0
Support status

    Unsupported
IEEE address
    0xccccccfffe3a1530
Network address
    0xE628
Firmware build date
    20190803
Firmware version
    3.02

**Comment by Koenkk** [comment] 2021-05-18 15:06
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/7325

**Closed by Koenkk** 2021-05-18 15:06 UTC
