### ISSUE TITLE
[Feature request]: support new EZSP protocol v13 (gecko 4.4.0) ?

### ISSUE THREAD

**Issue by jonyrh** [Koenkk/zigbee2mqtt#20652] opened 2024-01-07 17:46 UTC
### Is your feature request related to a problem? Please describe

Hello! Are you planning to add support for the new EZSP protocol version 13 (gecko 4.4.0)

### Describe the solution you'd like

New FW (ncp-uart-hw-v7.4.0.0-zb-gw04-1v2-115200.gbl) for USB doungle ZB-GW04 v1.2 not work with last z2m. 

### Describe alternatives you've considered

on FW v7.3.2.0 work fine

### Additional context

FW source https://github.com/darkxst/silabs-firmware-builder/issues/40

**Comment by Koenkk** [comment] 2024-01-08 18:43
Duplicate of https://github.com/Koenkk/zigbee-herdsman/issues/854

**Closed by Koenkk** 2024-01-08 18:43 UTC
Labels: feature request
