### ISSUE TITLE
MQTT device naming issues with home assisstant

### ISSUE THREAD

**Issue by thomasdelaet** [Koenkk/zigbee2mqtt#18510] opened 2023-08-03 09:07 UTC
### What happened?

With the latest release of home assistant (2023.8), I'm getting a lot of warnings around MQTT entity naming:
- "Discovered MQTT entities with a name that is equal to the device name" => for all my lights
- "Discovered entities with a name that starts with the device name" => for all _update_available, an _power_on_behavior entities.

Suggested fix: just add _device as suffix to the device name field in MQTT config entry.

wdyt?

### How to reproduce it (minimal and precise)

Upgrade to home assistant 2023.8 and check repairs list (and log)

### Zigbee2MQTT version

1.32.2

### Adapter firmware version

not relevant for this issue

### Adapter

not relevant for this issue

**Comment by stefanuytterhoeven** [comment] 2023-08-03 09:26
From what I read on the HA website, you can ignore these messages. In september there should be a solution. (correct me if i'm wrong :) )

**Comment by Gorouk** [comment] 2023-08-03 09:57
https://community.home-assistant.io/t/psa-mqtt-name-changes-in-2023-8/598099

**Comment by juahan** [comment] 2023-08-03 10:13
It is known and looks like it will be fixed in https://github.com/Koenkk/zigbee2mqtt/pull/18490.

**Comment by Koenkk** [comment] 2023-08-03 17:33
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/18445

**Closed by Koenkk** 2023-08-03 17:33 UTC
Labels: problem
