### ISSUE TITLE
WXKG01LM detects long click instead off 1 click after update to 1.36.0

### ISSUE THREAD

**Issue by kitopopo** [Koenkk/zigbee2mqtt#21723] opened 2024-03-08 17:02 UTC
### What happened?

After update from 1.35.3 commit: fe0742a to 1.36.0 the WXKG01LM aqara switch doesn't detect correctly the clicks. After push "1 click" zigbe2mqtt detects "long push"

### What did you expect to happen?

1 click must be detected by zigbee2mqtt = 1 click, no a long push

### How to reproduce it (minimal and precise)

pressing one time the aqara switch (1 click)

### Zigbee2MQTT version

1.36.0

### Adapter firmware version

20230507

### Adapter

zzh 

### Setup

Raspberry pi 5 8gb

### Debug log

Zigbee2MQTT:info  2024-03-08 17:01:31: MQTT publish: topic 'zigbee2mqtt/switch salon', payload '{"action":"single","battery":100,"click":null,"linkquality":127,"power_outage_count":780,"voltage":3132}'
Zigbee2MQTT:info  2024-03-08 17:01:31: MQTT publish: topic 'zigbee2mqtt/switch salon', payload '{"action":"","battery":100,"click":null,"linkquality":127,"power_outage_count":780,"voltage":3132}'
Zigbee2MQTT:info  2024-03-08 17:01:31: MQTT publish: topic 'zigbee2mqtt/switch salon/action', payload 'single'
Zigbee2MQTT:info  2024-03-08 17:01:32: MQTT publish: topic 'zigbee2mqtt/switch salon', payload '{"action":null,"battery":100,"click":"long","linkquality":127,"power_outage_count":780,"voltage":3132}'
Zigbee2MQTT:info  2024-03-08 17:01:32: MQTT publish: topic 'zigbee2mqtt/switch salon', payload '{"action":null,"battery":100,"click":"","linkquality":127,"power_outage_count":780,"voltage":3132}'
Zigbee2MQTT:info  2024-03-08 17:01:32: MQTT publish: topic 'zigbee2mqtt/switch salon/click', payload 'long'

**Comment by Koenkk** [comment] 2024-03-08 21:25
Dupe of https://github.com/Koenkk/zigbee2mqtt/issues/21661

**Closed by Koenkk** 2024-03-08 21:25 UTC
Labels: problem
