### ISSUE TITLE
Xiaomi Smoke: Data request failed with error: 'No network route' (205)

### ISSUE THREAD

**Issue by pedroke** [Koenkk/zigbee2mqtt#4502] opened 2020-09-30 11:06 UTC
## What happened
When I try to set attribute of Xiaomi Smoke Detector or perform the self test I get the following error:

Publish 'set' 'selftest' to '0x00158d0002cb0c6a' failed: 'Error: Write 0x00158d0002cb0c6a/1 ssIasZone({"65521":{"value":50397184,"type":35}}, {"timeout":35000,"disableResponse":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4447,"transactionSequenceNumber":null}) failed (Data request failed with error: 'No network route' (205))'

Few important remarks:

- I'm using ZZH! stick.
- Otherwise, the device works correctly. It is reporting periodically.
- Interesting is that on zigbee network map the device appears detached, although it is working and I suppose that it has the same root cause, since for some reason "No network route" is reported.
- It seems to be specific for this device, since e.g. Neo Siren can be triggered and set and appears correctly in zigbee network map. Only other device that appear detached is Sonoff temperature sensor I suppose for the same reason.
- It started when I switched from CC2531 to ZZH.

## What did you expect to happen

I would expect the device to be found and reachable.

## How to reproduce it (minimal and precise)

Electrolama ZZH! stick with CC26X2R1_20200805.zip firmware and send self test command to Xiaomi smoke detector.

## Debug info
Zigbee2MQTT version: 1.14.4
Adapter hardware: CC26X2R1 ZZH
Adapter firmware version: CC26X2R1_20200805

**Comment by Koenkk** [comment] 2020-09-30 11:26
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/4285 , solution is new firmware from https://github.com/Koenkk/zigbee2mqtt/issues/4285#issuecomment-698973429

**Closed by Koenkk** 2020-09-30 11:26 UTC
Labels: problem
