### ISSUE TITLE
IKEA E1524/E1810 Group bindings don't work

### ISSUE THREAD

**Issue by 00joshi** [Koenkk/zigbee2mqtt#10041] opened 2021-12-06 11:52 UTC
## What happened
 * I updated IKEA E1524/E1810 to Firmware 2.3.080 and updated zigbee2mqtt to the latest version
 * The remote no longer has a default group (group = 0).
 * Bindings to new groups are created but don't have any effect.
## What did you expect to happen
 * Use remote to control device by group.

## How to reproduce it (minimal and precise)
 * Created binding from IKEA E1524/E1810 (Firmware 2.3.080) to group with two bulbs.
 * Binding has no effect ( Can't control light bulb)
## Debug info
Zigbee2MQTT version:  1.22.1 commit: 48b790cb
Adapter hardware: CC2652RB
Adapter firmware version:
Coordinator Typ
    zStack3x0

Coordinator Version
    20201026

**Comment by Koenkk** [comment] 2021-12-06 18:55
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/7716 (TLDR; latest firmware doesn't support binding to groups anymore)

**Closed by Koenkk** 2021-12-06 18:55 UTC
Labels: problem
