### ISSUE TITLE
Aqara (Xiaomi) RTCGQ14LM Firmware OTA 

### ISSUE THREAD

**Issue by Sonic62** [Koenkk/zigbee2mqtt#20770] opened 2024-01-13 19:05 UTC
### Link

https://www.zigbee2mqtt.io/devices/MCCGQ14LM.html#xiaomi-mccgq14lm

### Database entry

{"id":54,"type":"EndDevice","ieeeAddr":"0x54ef441000295579","nwkAddr":45961,"manufId":4447,"manufName":"LUMI","powerSource":"Battery","modelId":"lumi.magnet.acn001","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[0,1,3,1280,64704],"outClusterList":[3,25],"clusters":{"genBasic":{"attributes":{"hwVersion":0,"appVersion":4,"modelId":"lumi.magnet.acn001"}},"ssIasZone":{"attributes":{"iasCieAddr":"0x0000000000000000","zoneState":0}},"aqaraOpple":{"attributes":{"247":{"type":"Buffer","data":[1,33,167,11,3,40,25,4,33,0,0,5,33,1,0,8,33,4,0,10,33,0,0,12,32,30,100,16,1]}}},"genPowerCfg":{"attributes":{"batteryVoltage":29}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":4,"stackVersion":2,"hwVersion":0,"zclVersion":3,"interviewCompleted":true,"meta":{"configured":1906590817},"lastSeen":1705168197066,"defaultSendRequestWhen":"immediate"}

### Comments

Hello

An OTA update is seen by HAOS and Zigbee2Mqtt, but impossible to do, and those despite the numerous posts that I have read on the git.

Surprisingly, I only have 3 devices of this reference but only one sees an update.
![Capture d'écran 2024-01-13 200049](https://github.com/Koenkk/zigbee2mqtt/assets/103725660/35ce5aa9-d0d5-4900-834b-442e44fbc5c6)
![Capture d'écran 2024-01-13 200123](https://github.com/Koenkk/zigbee2mqtt/assets/103725660/7d6242aa-6600-48a1-bd6e-c4333c3cea49)
![Capture d'écran 2024-01-13 200123](https://github.com/Koenkk/zigbee2mqtt/assets/103725660/3cd82a37-b0f9-4243-a3b7-0481155fbaa6)
![Capture d'écran 2024-01-13 200323](https://github.com/Koenkk/zigbee2mqtt/assets/103725660/48b625e7-10c6-4441-9853-74d08865728b)
![Capture d'écran 2024-01-13 200355](https://github.com/Koenkk/zigbee2mqtt/assets/103725660/4412391d-92d8-4724-a9fa-26a4e4e0c164)

![Capture d'écran 2024-01-13 200401](https://github.com/Koenkk/zigbee2mqtt/assets/103725660/73399e9c-c034-4c82-a62d-516aa2e4057d)
![Capture d'écran 2024-01-13 200443](https://github.com/Koenkk/zigbee2mqtt/assets/103725660/a7f9bf5b-bff9-440a-90dc-52a4db99509b)

Thx

### External defintion

```shell
Non
```

**Comment by Koenkk** [comment] 2024-01-13 20:51
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/20658

**Closed by Koenkk** 2024-01-13 20:51 UTC
Labels: new device support
