### ISSUE TITLE
Permit join NOT working

### ISSUE THREAD

**Issue by fdapport** [Koenkk/zigbee2mqtt#7814] opened 2021-06-17 16:59 UTC
## Debug info
Zigbee2MQTT version: 1.19.1-1

With this version I am not able to Join new device. If I look in the logs I have the following errors:

error 2021-06-14 20:44:17: Failed to set permit join to false
error 2021-06-14 20:44:45: Request 'zigbee2mqtt/bridge/request/permit_join' failed with error: 'SRSP - UTIL - ledControl after 6000ms'
error 2021-06-14 20:45:55: Request 'zigbee2mqtt/bridge/request/permit_join' failed with error: 'SRSP - UTIL - ledControl after 6000ms'

with a version 1.18.3-1 works without any problems.
Please let me know if you need additional information

**Comment by Koenkk** [comment] 2021-06-18 10:46
Duplicate of #7693 and already fixed in the dev branch. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Closed by Koenkk** 2021-06-18 10:46 UTC
Labels: problem
