### ISSUE TITLE
IKEA E1524/E1810 does not control light temperature

### ISSUE THREAD

**Issue by vdkeybus** [Koenkk/zigbee2mqtt#4161] opened 2020-08-22 16:55 UTC
# Bug Report
## What happened
Bound an IKEA E1524 to a "TRADFRI bulb E27 WS clear 950lm". After this, the light can be turned on and off, and its brightness can be set. However, the color temperature setting does not work. The temperature can be set using HA.

## What did you expect to happen
Light temperature can be set using the arrows on the remote control.

## How to reproduce it (minimal and precise)
- Create group '10002'
- Unbind E1524/1810 (tried with both) from 'default_bind_group'
- Bind E1524/1810 to '10002'
- Bind light to '10002'
- Observe on/off and brightness control, but no color temperature control

## Additional info
- The light (obviously) supports light temperature.
- I also encountered this with an IKEA GU10 light.
- It happens with both CC2531 and Conbee II coordinators
- It has worked before. I cannot recall if it stopped working after updating zigbee2mqtt

## Debug Info
Zigbee2MQTT version: 1.14.3-dev
Adapter hardware: DeCONZ Conbee II
Adapter firmware version: 0x26580700 (coordinator version)

**Comment by Koenkk** [comment] 2020-08-23 20:16
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/1232

**Closed by Koenkk** 2020-08-23 20:16 UTC
