### ISSUE TITLE
Please add new device.... LIDL Livarno GU10 TS0505B TZ3000 device5

### ISSUE THREAD

**Issue by tottelitott** [Koenkk/zigbee2mqtt#9697] opened 2021-11-16 18:55 UTC
Hi. i bought four new LIDL Livarno E10 Bulbs.

Sadly they don't work. I'm not able to add them. My Zigbee2mqtt runs on a synology in docker. I only have access to the config files...
Can somebody help here? Add a known device is something i can do but this is all new to me...

## Information about the device + link
E10 Multicolor Zigbee device [Link to LIDL](https://www.lidl.de/p/livarno-home-leuchtmittel-rgb-fur-zigbee-smart-home-best/p100335197001)

## data/database.db entry of the device
{"id":75,"type":"Router","ieeeAddr":"0x0c4314fffe84d06f","nwkAddr":16547,"manufId":4098,"manufName":"_TZ3000_quqaeew6","powerSource":"Mains (single phase)","modelId":"TS0505B","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":269,"inClusterList":[0,3,4,5,6,4096,8,768],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS0505B","manufacturerName":"_TZ3000_quqaeew6","powerSource":1,"zclVersion":3,"appVersion":66,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":66,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1637087569051}

**Comment by Koenkk** [comment] 2021-11-16 19:09
Duplicate of https://github.com/Koenkk/zigbee-herdsman-converters/issues/3320#issuecomment-970531762

**Closed by Koenkk** 2021-11-16 19:09 UTC
Labels: new device support
