### ISSUE TITLE
SRSP - AF - interPanCtl after 6000ms

### ISSUE THREAD

**Issue by dbotman** [Koenkk/zigbee2mqtt#7368] opened 2021-05-06 19:48 UTC
## What happened
I bought a new CC2652R. I have tried to migrate from my existing CC2531 to the CC2652R using Touchlink. 
I followed [this steps](https://github.com/koenkk/zigbee2mqtt/issues/4151#issuecomment-684003951), everything looks fine. But when i scan for devices with Touchlink, or send the reset command, i received this error message "SRSP - AF - interPanCtl after 6000ms".
When i restart Zigbee2MQTT it fails to start. I have to reconnect the CC2652R before Zigbee2MQTT starts up again. 

I've done these steps on a Raspberry Pi. After this, I installed a clean version of Zigbee2MQTT on a Windows device, with the same result.

## What did you expect to happen
Send a reset command or scan for devices with touchlink

## How to reproduce it (minimal and precise)

`zigbee2mqtt/bridge/request/touchlink/scan`

`zigbee2mqtt/bridge/request/touchlink/factory_reset`

## Debug info
Zigbee2MQTT version: 1.18.3
Adapter hardware: CC2652R
Adapter firmware version: CC2652R_coordinator_20210120

Logs can be found [here](https://pastebin.com/TTjXgUrr)

`Can you try removing coordinator_backup.json and reflashing the CC2652R using`
I found this in another issue and have already tried it.

**Comment by Koenkk** [comment] 2021-05-07 16:25
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/5356

**Closed by Koenkk** 2021-05-07 16:25 UTC
Labels: problem
