### ISSUE TITLE
Networkmap failure

### ISSUE THREAD

**Issue by JanJaapKo** [Koenkk/zigbee2mqtt#3691] opened 2020-06-08 06:49 UTC
# Bug Report
## What happened
requesting a networkmap via MQTT publish on 'zigbee2mqtt/bridge/networkmap/routes' with data 'graphviz'
Most devices queried OK (some reports on failed LQI and networkmap, but it used to work before)
Then error occurs:
Jun 08 08:22:57 raspberrypi npm[9731]: zigbee2mqtt:info  2020-06-08 08:22:57: Network scan finished
Jun 08 08:22:57 raspberrypi npm[9731]: zigbee2mqtt:error 2020-06-08 08:22:57: Failed to call 'NetworkMap' 'onMQTTMessage' (TypeError: Cannot read property 'map' of undefined
Jun 08 08:22:57 raspberrypi npm[9731]:     at fingerprintMatch (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/index.js:75:42)
Jun 08 08:22:57 raspberrypi npm[9731]:     at Object.findByDevice (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/index.js:50:21)
Jun 08 08:22:57 raspberrypi npm[9731]:     at /opt/zigbee2mqtt/lib/extension/networkMap.js:74:61
Jun 08 08:22:57 raspberrypi npm[9731]:     at Array.forEach (<anonymous>)
Jun 08 08:22:57 raspberrypi npm[9731]:     at NetworkMap.graphviz (/opt/zigbee2mqtt/lib/extension/networkMap.js:60:24)
Jun 08 08:22:57 raspberrypi npm[9731]:     at NetworkMap.onMQTTMessage (/opt/zigbee2mqtt/lib/extension/networkMap.js:44:65)
Jun 08 08:22:57 raspberrypi npm[9731]:     at async Controller.callExtensionMethod (/opt/zigbee2mqtt/lib/controller.js:350:21))

Full logging: [https://pastebin.com/KUDbHGLa](url)

## What did you expect to happen
the networkmap published to the topic

## How to reproduce it (minimal and precise)
Request networkmap

## Debug Info
Zigbee2mqtt version: v.1.13.1
Adapter hardware: CC2531
Adapter firmware version: zStack12 20190608

**Comment by Koenkk** [comment] 2020-06-08 08:08
Duplicate of #3623

**Closed by Koenkk** 2020-06-08 08:08 UTC
