### ISSUE TITLE
Add-on config 'auto_uart' is deprecated, use 'uart'

### ISSUE THREAD

**Issue by rhl2401** [Koenkk/zigbee2mqtt#6226] opened 2021-02-11 09:45 UTC
The supervisor log in Home Assistant requests using "uart" instead of "auto_uart". 
The log reads: 

`21-02-11 08:29:57 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Zigbee2mqtt
21-02-11 08:29:57 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Zigbee2mqtt Edge`

**Comment by Koenkk** [comment] 2021-02-11 09:51
Duplicate of https://github.com/danielwelch/hassio-zigbee2mqtt/issues/533

**Closed by Koenkk** 2021-02-11 09:51 UTC
Labels: problem
