### ISSUE TITLE
[Feature request] implement increment/decrement brightness and color_temp for bulbs

### ISSUE THREAD

**Issue by elfhack** [Koenkk/zigbee2mqtt#3975] opened 2020-07-25 19:22 UTC
Hue has a nice API endpoint for incrementing/decrementing brightness without knowing the prior state of the bulb. This saves on latency since the the user doesn't have to get the previous state of the bulb and calculate the target brightness on its own. Would it be possible to add this functionality? The same principle could be added to color temperature as well

**Comment by Koenkk** [comment] 2020-07-26 12:14
Duplicate of #1348

**Closed by Koenkk** 2020-07-26 12:14 UTC
