### ISSUE TITLE
Xiaomi JTYJ-GD-01LM/BW Smoke Alarm has no Network Route

### ISSUE THREAD

**Issue by Anjerlaan** [Koenkk/zigbee2mqtt#4832] opened 2020-11-01 09:29 UTC
## What happened
I Have 3 Xiaomi JTYJ-GD-01LM/BW Smoke Alarm devices.
But after I send a selftest, one of them "Rookmelder_beneden (0x00158d0003584868)" reports to have no Network Route.

`debug 2020-11-01 10:00:54: Received MQTT message on 'zigbee2mqtt/Rookmelder_beneden/set' with data '{"selftest": ""}'
debug 2020-11-01 10:00:54: Publishing 'set' 'selftest' to 'Rookmelder_beneden'
debug 2020-11-01 10:01:01: Received Zigbee message from 'Keuken_Router', type 'attributeReport', cluster 'genOnOff', data '{"onOff":0}' from endpoint 8 with groupID 0
info  2020-11-01 10:01:01: MQTT publish: topic 'zigbee2mqtt/Keuken_Router', payload '{"led":false,"led_state":false,"linkquality":69,"state":true}'
error 2020-11-01 10:01:14: Publish 'set' 'selftest' to 'Rookmelder_beneden' failed: 'Error: Write 0x00158d0003584868/1 ssIasZone({"65521":{"value":50397184,"type":35}}, {"timeout":35000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4447,"transactionSequenceNumber":null}) failed (Data request failed with error: 'No network route' (205))'
debug 2020-11-01 10:01:14: Error: Write 0x00158d0003584868/1 ssIasZone({"65521":{"value":50397184,"type":35}}, {"timeout":35000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4447,"transactionSequenceNumber":null}) failed (Data request failed with error: 'No network route' (205))
    at ZStackAdapter.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:319:27)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:24:58)
info  2020-11-01 10:01:14: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'selftest' to 'Rookmelder_beneden' failed: 'Error: Write 0x00158d0003584868/1 ssIasZone({\"65521\":{\"value\":50397184,\"type\":35}}, {\"timeout\":35000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":true,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":4447,\"transactionSequenceNumber\":null}) failed (Data request failed with error: 'No network route' (205))'","meta":{"friendly_name":"Rookmelder_beneden"},"type":"zigbee_publish_error"}'`

Here is the full LOG: https://pastebin.com/amBXXNzA

## What did you expect to happen
This was working before....Why does this happen to only one of the devices?
I have created a graphviz, which is also in the LOG file.
There you see the device present but not in the network route

## How to reproduce it (minimal and precise)
I send a self test to: **zigbee2mqtt/Rookmelder_beneden/set** with payload: {"selftest": ""}
I have restarted Z2M, but with no result
How do I solve this problem?

## Debug info
Zigbee2MQTT version: v.1.15.0 
Adapter hardware: CC26X2R1
Adapter firmware version: (zStack3x0 20200925)

**Comment by Koenkk** [comment] 2020-11-01 09:39
Duplicate of #4285 (possible fix is in next Z2M version released today in combination with new fw).

**Closed by Koenkk** 2020-11-01 09:39 UTC
Labels: problem
