### ISSUE TITLE
INNR RB 251 C firmware update "does not stick" 

### ISSUE THREAD

**Issue by DoerakkerHA** [Koenkk/zigbee2mqtt#17374] opened 2023-04-17 09:38 UTC
### What happened?

see notification update is available
starting update
update completes
configuration occurs
configuration completes
somewhere a new notification appears: update available
rinse and repeat

### What did you expect to happen?

update completes, configuration completes end of story

Info 2023-04-17 08:51:34MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":{"id":"0xc498860000077ed0"},"meta":{"device":"03 voorraam 1","from":{"dateCode":"20211013","softwareBuildID":"2.03.00"},"status":"update_succeeded","to":{"dateCode":"20211013","softwareBuildID":"2.03.00"}},"type":"ota_update"}'
Info 2023-04-17 08:51:34MQTT publish: topic 'zigbee2mqtt/03 voorraam 1', payload '{"brightness":48,"color":{"h":22,"hue":22,"s":97,"saturation":97,"x":0.5492,"y":0.4082},"color_mode":"color_temp","color_temp":555,"color_temp_startup":555,"last_seen":1681714294639,"level_config":{"on_level":"previous"},"linkquality":72,"power_on_behavior":null,"state":"OFF","update":{"installed_version":604050705,"latest_version":604050705,"state":"idle"},"update_available":false}'
Info 2023-04-17 08:51:34MQTT publish: topic 'zigbee2mqtt/03 voorraam 1', payload '{"brightness":48,"color":{"h":22,"hue":22,"s":97,"saturation":97,"x":0.5492,"y":0.4082},"color_mode":"color_temp","color_temp":555,"color_temp_startup":555,"last_seen":1681714294715,"level_config":{"on_level":"previous"},"linkquality":76,"power_on_behavior":null,"state":"OFF","update":{"installed_version":604050705,"latest_version":604050705,"state":"idle"},"update_available":false}'
Info 2023-04-17 08:51:34Successfully configured '03 voorraam 1'

### How to reproduce it (minimal and precise)

see notification update is available
starting update
update completes
configuration occurs
configuration completes
somewhere a new notification appears: update available
rinse and repeat

### Zigbee2MQTT version

1.30.3

### Adapter firmware version

20211217

### Adapter

ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus

### Debug log

Info 2023-04-17 08:51:34MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":{"id":"0xc498860000077ed0"},"meta":{"device":"03 voorraam 1","from":{"dateCode":"20211013","softwareBuildID":"2.03.00"},"status":"update_succeeded","to":{"dateCode":"20211013","softwareBuildID":"2.03.00"}},"type":"ota_update"}'
Info 2023-04-17 08:51:34MQTT publish: topic 'zigbee2mqtt/03 voorraam 1', payload '{"brightness":48,"color":{"h":22,"hue":22,"s":97,"saturation":97,"x":0.5492,"y":0.4082},"color_mode":"color_temp","color_temp":555,"color_temp_startup":555,"last_seen":1681714294639,"level_config":{"on_level":"previous"},"linkquality":72,"power_on_behavior":null,"state":"OFF","update":{"installed_version":604050705,"latest_version":604050705,"state":"idle"},"update_available":false}'
Info 2023-04-17 08:51:34MQTT publish: topic 'zigbee2mqtt/03 voorraam 1', payload '{"brightness":48,"color":{"h":22,"hue":22,"s":97,"saturation":97,"x":0.5492,"y":0.4082},"color_mode":"color_temp","color_temp":555,"color_temp_startup":555,"last_seen":1681714294715,"level_config":{"on_level":"previous"},"linkquality":76,"power_on_behavior":null,"state":"OFF","update":{"installed_version":604050705,"latest_version":604050705,"state":"idle"},"update_available":false}'
Info 2023-04-17 08:51:34Successfully configured '03 voorraam 1'

**Comment by m0wlheld** [comment] 2023-04-18 17:57
Same here. Same device, same Z2M version, same coordinator device.

**Comment by m0wlheld** [comment] 2023-04-19 07:36
Just did another OTA run for a Innr RB 251 C. The status after the update is as expected:

```json
{
    "brightness": 179,
    "color": {
        "h": 40,
        "hue": 40,
        "s": 51,
        "saturation": 51,
        "x": 0.3827,
        "y": 0.3781
    },
    "color_mode": "color_temp",
    "color_temp": 253,
    "level_config": {
        "on_level": "previous"
    },
    "linkquality": 36,
    "state": "OFF",
    "update": {
        "installed_version": 604050705,
        "latest_version": 604050705,
        "state": "idle"
    }
}
```

when checking for available OTA for that device, the status "resets" to the previous version:

```json
{
    "brightness": 179,
    "color": {
        "h": 40,
        "hue": 40,
        "s": 51,
        "saturation": 51,
        "x": 0.3827,
        "y": 0.3781
    },
    "color_mode": "color_temp",
    "color_temp": 253,
    "level_config": {
        "on_level": "previous"
    },
    "linkquality": 51,
    "state": "OFF",
    "update": {
        "installed_version": 587207953,
        "latest_version": 604050705,
        "state": "available"
    },
    "power_on_behavior": null,
    "update_available": null
}
```

**Comment by wolterink** [comment] 2023-04-29 19:05
Same here, but for a [RB 286 C]
installed_version: 587207953
latest_version: 604050705

**Comment by d-berk** [comment] 2023-05-07 09:36
same here.
RB 251 C
Coordinator: SONOFF Zigbee 3.0 USB Dongle Plus
z2m Version 1.30.4

**Comment by DoerakkerHA** [comment] 2023-06-07 01:27
The issue persists on install running all latest updates....

Please pick up

**Comment by DoerakkerHA** [comment] 2023-06-21 05:25
hello all, this issue persists ... just tried to update 2 of these lights, updates ok (appears) then when querying the ota it returns as update available.  I can live with it but would like to know what we can do about it to address this issue

**Comment by DoerakkerHA** [comment] 2023-07-22 04:11
The issue persists while all components/HaOs are up to date

**Comment by m0wlheld** [comment] 2023-08-23 04:16
Still present issue.

**Comment by DoerakkerHA** [comment] 2023-08-23 05:16
This issue has not been resolved; it still reports via update. When update executed and zigbee2mqtt restarted error reappears

**Comment by m0wlheld** [comment] 2023-09-03 09:43
Issue is still present with 1.33.0.

Affected devices (here) are Innr RB 251 C with firmware date 20211013 and firmware version 2.03.00 . OTA is reported available and gets applied without issues. But when checking for firmware updates afterwards, OTA availability is reported again.

**Comment by jstaro** [comment] 2023-09-04 09:40
I am also seeing this with:
- RB 266, firmware build date 20211022, version 2.03.01
- RB 245, firmware build date 20211022, version 2.03.01

Interestingly, it has once worked to upgrade a RB 245 to 2.04.01 (several months ago) but at some point, this stopped working.

**Comment by anthraxn8b** [comment] 2023-09-13 07:11
The interesting thing is, that this happens with INNR bulbs but not with PHILIPS HUE bulbs...

My log where the problem occurs that the new version does not seem be be installed:

`info 2023-09-13 08:47:30Update of 'diningroom/table_light_0' at 99.57%, ≈ 0 minutes remaining
info 2023-09-13 08:47:30MQTT publish: topic 'zigbee2mqtt/diningroom/table_light_0', payload '{"brightness":254,"color":{"x":0.4599,"y":0.4106},"color_mode":"color_temp","color_temp":370,"color_temp_startup":370,"linkquality":188,"power_on_behavior":null,"state":"ON","update":{"installed_version":587207953,"latest_version":604050705,"progress":99.57,"remaining":3,"state":"updating"},"update_available":true}'
info 2023-09-13 08:47:38Update of 'diningroom/table_light_0' at 100.00%
info 2023-09-13 08:47:38MQTT publish: topic 'zigbee2mqtt/diningroom/table_light_0', payload '{"brightness":254,"color":{"x":0.4599,"y":0.4106},"color_mode":"color_temp","color_temp":370,"color_temp_startup":370,"linkquality":188,"power_on_behavior":null,"state":"ON","update":{"installed_version":587207953,"latest_version":604050705,"progress":100,"remaining":3,"state":"updating"},"update_available":true}'
...
info 2023-09-13 08:49:38Finished update of 'diningroom/table_light_0'
info 2023-09-13 08:49:38Configuring 'diningroom/table_light_0'
info 2023-09-13 08:49:38MQTT publish: topic 'zigbee2mqtt/diningroom/table_light_0', payload '{"brightness":254,"color":{"x":0.4599,"y":0.4106},"color_mode":"color_temp","color_temp":370,"color_temp_startup":370,"linkquality":188,"power_on_behavior":null,"state":"ON","update":{"installed_version":604050705,"latest_version":604050705,"state":"idle"},"update_available":true}'
info 2023-09-13 08:49:38MQTT publish: topic 'zigbee2mqtt/diningroom/table_light', payload '{"brightness":254,"color":{"x":0.4599,"y":0.4106},"color_mode":"color_temp","color_temp":370,"state":"ON"}'
info 2023-09-13 08:49:38MQTT publish: topic 'zigbee2mqtt/diningroom/table_light_0', payload '{"brightness":254,"color":{"x":0.4599,"y":0.4106},"color_mode":"color_temp","color_temp":370,"color_temp_startup":370,"linkquality":188,"power_on_behavior":null,"state":"ON","update":{"installed_version":604050705,"latest_version":604050705,"state":"idle"},"update_available":true}'
info 2023-09-13 08:49:38MQTT publish: topic 'zigbee2mqtt/fam_room/light', payload '{"brightness":254,"color":{"x":0.4599,"y":0.4106},"color_mode":"color_temp","color_temp":370,"state":"ON"}'
info 2023-09-13 08:49:38Device 'diningroom/table_light_0' was updated from '{"dateCode":"20211013","softwareBuildID":"2.03.00"}' to '{"dateCode":"20211013","softwareBuildID":"2.03.00"}'
info 2023-09-13 08:49:38MQTT publish: topic 'zigbee2mqtt/bridge/response/device/ota_update/update', payload '{"data":{"from":{"date_code":"20211013","software_build_id":"2.03.00"},"id":"diningroom/table_light_0","to":{"date_code":"20211013","software_build_id":"2.03.00"}},"status":"ok","transaction":"ljsp7-3"}'
info 2023-09-13 08:49:39MQTT publish: topic 'zigbee2mqtt/diningroom/table_light_0', payload '{"brightness":254,"color":{"x":0.4599,"y":0.4106},"color_mode":"color_temp","color_temp":370,"color_temp_startup":370,"linkquality":188,"power_on_behavior":null,"state":"ON","update":{"installed_version":604050705,"latest_version":604050705,"state":"idle"},"update_available":true}'
info 2023-09-13 08:49:39Successfully configured 'diningroom/table_light_0'
...
info 2023-09-13 09:01:26Checking if update available for 'diningroom/table_light_0'
info 2023-09-13 09:01:27Update available for 'diningroom/table_light_0'
info 2023-09-13 09:01:27MQTT publish: topic 'zigbee2mqtt/diningroom/table_light_0', payload '{"brightness":254,"color":{"x":0.4599,"y":0.4106},"color_mode":"color_temp","color_temp":370,"color_temp_startup":370,"linkquality":188,"power_on_behavior":null,"state":"ON","update":{"installed_version":587207953,"latest_version":604050705,"state":"available"},"update_available":true}'
info 2023-09-13 09:01:27MQTT publish: topic 'zigbee2mqtt/bridge/response/device/ota_update/check', payload '{"data":{"id":"diningroom/table_light_0","updateAvailable":true},"status":"ok","transaction":"ljsp7-4"}'
`

**Comment by m0wlheld** [comment] 2023-10-14 07:12
Still present.

**Comment by DoerakkerHA** [comment] 2023-10-14 07:29
Updated to version 11.0
Issue persists

**Comment by Koenkk** [comment] 2023-10-14 07:54
Does it still occur with the latest dev branch? It contains some OTA fixes.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by m0wlheld** [comment] 2023-10-14 08:14
Checking with -dev now …

**Comment by m0wlheld** [comment] 2023-10-14 08:55
No change. Device reports firmware 2.03.00 with update available. Update initiated okay, takes about 25min, but device afterwards still reports 2.03.00

**Comment by DoerakkerHA** [comment] 2023-10-14 09:37
Same hereKind RegardsROnald GroeneveldSent from my iPhone +31 650 989 689On 14 Oct 2023, at 10:55, Christoph Dahlen ***@***.***> wrote:﻿
No change. Device reports firmware 2.03.00 with update available. Update initiated okay, takes about 25min, but device afterwards still reports 2.03.00

**Comment by Koenkk** [comment] 2023-10-14 11:34
Can you provide the herdsman debug log of the complete firmware upgrade?


See https://www.zigbee2mqtt.io/guide/usage/debug.html on how to enable the herdsman debug logging. Note that this is only logged to STDOUT and not to log files.

**Comment by DoerakkerHA** [comment] 2023-10-16 04:55
Hallo Koen, the log is overwritten during the update (takes about 30+ minutes) so a full log is barely possible to provide. I will run another update and try and capture relevant sections for the light in questionKind RegardsROnald GroeneveldSent from my iPhone +31 650 989 689On 14 Oct 2023, at 13:35, Koen Kanters ***@***.***> wrote:﻿
Can you provide the herdsman debug log of the complete firmware upgrade?
See https://www.zigbee2mqtt.io/guide/usage/debug.html on how to enable the herdsman debug logging. Note that this is only logged to STDOUT and not to log files.

**Comment by DoerakkerHA** [comment] 2023-10-16 05:01
Zigbee2MQTT:info  2023-10-16 06:57:22: MQTT publish: topic 'zigbee2mqtt/03 zijraam', payload '{"brightness":1,"color":{"h":31,"hue":31,"s":85,"saturation":85,"x":0.4717,"y":0.4129},"color_mode":"color_temp","color_temp":390,"last_seen":1697432242610,"level_config":{"on_level":"previous"},"linkquality":25,"power_on_behavior":null,"state":"ON","update":{"installed_version":604050705,"latest_version":604050705,"state":"idle"},"update_available":false}'
Zigbee2MQTT:debug 2023-10-16 06:57:22: Received Zigbee message from '03 zijraam', type 'readResponse', cluster 'genBasic', data '{"dateCode":"20211013","swBuildId":"2.03.00"}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2023-10-16 06:57:22: MQTT publish: topic 'zigbee2mqtt/03 zijraam', payload '{"brightness":1,"color":{"h":31,"hue":31,"s":85,"saturation":85,"x":0.4717,"y":0.4129},"color_mode":"color_temp","color_temp":390,"last_seen":1697432242729,"level_config":{"on_level":"previous"},"linkquality":25,"power_on_behavior":null,"state":"ON","update":{"installed_version":604050705,"latest_version":604050705,"state":"idle"},"update_available":false}'
Zigbee2MQTT:info  2023-10-16 06:57:22: Device '03 zijraam' was updated from '{"dateCode":"20211013","softwareBuildID":"2.03.00"}' to '{"dateCode":"20211013","softwareBuildID":"2.03.00"}'
Zigbee2MQTT:info  2023-10-16 06:57:23: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":{"id":"0xc49886000007a473"},"meta":{"device":"03 zijraam","from":{"dateCode":"20211013","softwareBuildID":"2.03.00"},"status":"update_succeeded","to":{"dateCode":"20211013","softwareBuildID":"2.03.00"}},"type":"ota_update"}'
Zigbee2MQTT:info  2023-10-16 06:57:23: MQTT publish: topic 'zigbee2mqtt/bridge/response/device/ota_update/update', payload '{"data":{"from":{"date_code":"20211013","software_build_id":"2.03.00"},"id":"0xc49886000007a473","to":{"date_code":"20211013","software_build_id":"2.03.00"}},"status":"ok"}'
Zigbee2MQTT:debug 2023-10-16 06:57:23: Received Zigbee message from '03 zijraam', type 'readResponse', cluster 'lightingColorCtrl', data '{"colorTempPhysicalMax":555,"colorTempPhysicalMin":153}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2023-10-16 06:57:23: MQTT publish: topic 'zigbee2mqtt/03 zijraam', payload '{"brightness":1,"color":{"h":31,"hue":31,"s":85,"saturation":85,"x":0.4717,"y":0.4129},"color_mode":"color_temp","color_temp":390,"last_seen":1697432243032,"level_config":{"on_level":"previous"},"linkquality":25,"power_on_behavior":null,"state":"ON","update":{"installed_version":604050705,"latest_version":604050705,"state":"idle"},"update_available":false}'
Zigbee2MQTT:info  2023-10-16 06:57:23: Successfully configured '03 zijraam'
Zigbee2MQTT:debug 2023-10-16 06:57:23: Received Zigbee message from '10 logeer plafond', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":285605891,"imageType":256,"manufacturerCode":4454}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2023-10-16 06:57:23: MQTT publish: topic 'zigbee2mqtt/10 logeer plafond', payload '{"brightness":117,"last_seen":1697432243348,"linkquality":87,"power_on_behavior":null,"state":"OFF"}'
Zigbee2MQTT:debug 2023-10-16 06:57:23: Device '10 logeer plafond' requested OTA
Zigbee2MQTT:debug 2023-10-16 06:57:23: Responded to OTA request of '10 logeer plafond' with 'NO_IMAGE_AVAILABLE'
Zigbee2MQTT:debug 2023-10-16 06:57:23: Retrieving state of '03 zijraam' after reconnectKind RegardsROnald GroeneveldSent from my iPhone +31 650 989 689On 14 Oct 2023, at 13:35, Koen Kanters ***@***.***> wrote:﻿
Can you provide the herdsman debug log of the complete firmware upgrade?
See https://www.zigbee2mqtt.io/guide/usage/debug.html on how to enable the herdsman debug logging. Note that this is only logged to STDOUT and not to log files.

**Comment by Koenkk** [comment] 2023-10-21 07:46
@m0wlheld since you know how to edit the zigbee-herdsman-converters source code, in `node_modules/zigbee-herdsman-converters/lib/ota/common.js` can you try changing `upgradeTime: 1,` to `upgradeTime: 0,` around line 342?

**Comment by m0wlheld** [comment] 2023-10-21 11:06
Did, but no (visible) effect. The OTA update is reported as available and before update, the status of the device is:

Status before update:

```json
{
    "brightness": 203,
    "color": {
        "h": 39,
        "hue": 39,
        "s": 53,
        "saturation": 53,
        "x": 0.3863,
        "y": 0.3803
    },
    "color_mode": "color_temp",
    "color_temp": 258,
    "level_config": {
        "on_level": "previous"
    },
    "linkquality": 61,
    "state": "OFF",
    "update": {
        "installed_version": 587207953,
        "latest_version": 604050705,
        "state": "available"
    }
}
```

Then update is initiated and completed, lines printed to logfile are:

```
Zigbee2MQTT:info  2023-10-21 12:59:55: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x9c69370000cbc69d","ieee_address":"0x9c69370000cbc69d"},"type":"device_announce"}'
Zigbee2MQTT:info  2023-10-21 12:59:55: Finished update of '0x9c69370000cbc69d'
Zigbee2MQTT:info  2023-10-21 12:59:55: Configuring '0x9c69370000cbc69d'
Zigbee2MQTT:info  2023-10-21 12:59:55: MQTT publish: topic 'zigbee2mqtt/0x9c69370000cbc69d', payload '{"brightness":203,"color":{"h":39,"hue":39,"s":53,"saturation":53,"x":0.3863,"y":0.3803},"color_mode":"color_temp","color_temp":258,"level_config":{"on_level":"previous"},"linkquality":65,"power_on_behavior":"on","state":"OFF","update":{"installed_version":604050705,"latest_version":604050705,"state":"idle"},"update_available":null}'
Zigbee2MQTT:info  2023-10-21 12:59:55: MQTT publish: topic 'zigbee2mqtt/Lichter Felix', payload '{"brightness":203,"color":{"h":39,"hue":39,"s":53,"saturation":53,"x":0.3863,"y":0.3803},"color_mode":"color_temp","color_temp":258,"state":"OFF"}'
Zigbee2MQTT:info  2023-10-21 12:59:55: MQTT publish: topic 'zigbee2mqtt/0x9c69370000cbc69d', payload '{"brightness":203,"color":{"h":39,"hue":39,"s":53,"saturation":53,"x":0.3863,"y":0.3803},"color_mode":"color_temp","color_temp":258,"level_config":{"on_level":"previous"},"linkquality":65,"power_on_behavior":"on","state":"OFF","update":{"installed_version":604050705,"latest_version":604050705,"state":"idle"},"update_available":null}'
Zigbee2MQTT:info  2023-10-21 12:59:55: MQTT publish: topic 'zigbee2mqtt/Stehlampe Felix', payload '{"brightness":203,"color":{"h":39,"hue":39,"s":53,"saturation":53,"x":0.3863,"y":0.3803},"color_mode":"color_temp","color_temp":258,"state":"OFF"}'
Zigbee2MQTT:info  2023-10-21 12:59:55: Device '0x9c69370000cbc69d' was updated from '{"dateCode":"20211013","softwareBuildID":"2.03.00"}' to '{"dateCode":"20211013","softwareBuildID":"2.03.00"}'
Zigbee2MQTT:info  2023-10-21 12:59:56: MQTT publish: topic 'zigbee2mqtt/bridge/response/device/ota_update/update', payload '{"data":{"from":{"date_code":"20211013","software_build_id":"2.03.00"},"id":"0x9c69370000cbc69d","to":{"date_code":"20211013","software_build_id":"2.03.00"}},"status":"ok","transaction":"itqnc-1"}'
Zigbee2MQTT:info  2023-10-21 12:59:56: MQTT publish: topic 'zigbee2mqtt/0x9c69370000cbc69d', payload '{"brightness":203,"color":{"h":39,"hue":39,"s":53,"saturation":53,"x":0.3863,"y":0.3803},"color_mode":"color_temp","color_temp":258,"level_config":{"on_level":"previous"},"linkquality":65,"power_on_behavior":"on","state":"OFF","update":{"installed_version":604050705,"latest_version":604050705,"state":"idle"},"update_available":null}'
Zigbee2MQTT:info  2023-10-21 12:59:56: Successfully configured '0x9c69370000cbc69d'
Zigbee2MQTT:info  2023-10-21 12:59:56: MQTT publish: topic 'zigbee2mqtt/0x60a423fffe6852a5', payload '{"current":10.15,"energy":1465.31,"indicator_mode":"off/on","linkquality":120,"power":2300,"power_outage_memory":"restore","state":"ON","voltage":225}'
Zigbee2MQTT:info  2023-10-21 12:59:57: MQTT publish: topic 'zigbee2mqtt/Lichter Felix', payload '{"brightness":203,"color":{"h":39,"hue":39,"s":53,"saturation":53,"x":0.3863,"y":0.3803},"color_mode":"color_temp","color_temp":258,"state":"OFF"}'
Zigbee2MQTT:info  2023-10-21 12:59:57: MQTT publish: topic 'zigbee2mqtt/0x9c69370000cbc69d', payload '{"brightness":203,"color":{"h":39,"hue":39,"s":53,"saturation":53,"x":0.3863,"y":0.3803},"color_mode":"color_temp","color_temp":258,"level_config":{"on_level":"previous"},"linkquality":61,"power_on_behavior":"on","state":"OFF","update":{"installed_version":604050705,"latest_version":604050705,"state":"idle"},"update_available":null}'
Zigbee2MQTT:info  2023-10-21 12:59:57: MQTT publish: topic 'zigbee2mqtt/Stehlampe Felix', payload '{"brightness":203,"color":{"h":39,"hue":39,"s":53,"saturation":53,"x":0.3863,"y":0.3803},"color_mode":"color_temp","color_temp":258,"state":"OFF"}'
```

The status after the update is 

```json
{
    "brightness": 203,
    "color": {
        "h": 39,
        "hue": 39,
        "s": 53,
        "saturation": 53,
        "x": 0.3863,
        "y": 0.3803
    },
    "color_mode": "color_temp",
    "color_temp": 258,
    "level_config": {
        "on_level": "previous"
    },
    "linkquality": 65,
    "state": "OFF",
    "update": {
        "installed_version": 604050705,
        "latest_version": 604050705,
        "state": "available"
    }
}
```

so the "installed_version" attribute has changed and reflects the "latest_version" attribute's value. But when returning to OTA page (event without checking for an OTA) the status is reverted to the previous version, as it was before the update.

**Comment by m0wlheld** [comment] 2023-10-21 11:47
Full debug log from start OTA to end OTA and returning to previous version.

[z2m-17374.log.gz](https://github.com/Koenkk/zigbee2mqtt/files/13060579/z2m-17374.log.gz)

**Comment by Koenkk** [comment] 2023-10-22 06:48
@m0wlheld could you send me the herdsman debug log?

See https://www.zigbee2mqtt.io/guide/usage/debug.html on how to enable the herdsman debug logging. Note that this is only logged to STDOUT and not to log files.

**Comment by m0wlheld** [comment] 2023-10-22 08:33
It‘s in the archive, I run Z2M in a container, so everything is logged to stdout.

**Comment by Koenkk** [comment] 2023-10-22 18:05
@m0wlheld as far as I can see, this file contains 1 log file which is the normal z2m debug logging (not the herdsman one)

**Comment by m0wlheld** [comment] 2023-10-25 07:34
Created a new archive using the instructions from https://www.zigbee2mqtt.io/guide/usage/debug.html . Result (gzip compressed) is attached.

[log.txt.gz](https://github.com/Koenkk/zigbee2mqtt/files/13162659/log.txt.gz)

**Comment by Koenkk** [comment] 2023-10-25 18:36
@m0wlheld In the log I see the following:

```
2023-10-25T06:58:35.372Z zigbee-herdsman:controller:endpoint CommandResponse 0x9c69370000cbc69d/1 genOta.upgradeEndResponse({"manufacturerCode":4454,"imageType":300,"fileVersion":604050705,"imageSize":291130,"currentTime":0,"upgradeTime":1}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":1,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false})
```

`"upgradeTime":1` -> it seems the change from https://github.com/Koenkk/zigbee2mqtt/issues/17374#issuecomment-1773708885 got lost? I would expect `"upgradeTime":0` here.

**Comment by m0wlheld** [comment] 2023-10-30 13:33
[log-20231030-z2m.txt.gz](https://github.com/Koenkk/zigbee2mqtt/files/13205656/log-20231030-z2m.txt.gz)

Next try logging with `upgradeTime: 1` enabled. No success with OTA update however.

**Comment by Koenkk** [comment] 2023-10-30 19:39
@m0wlheld this log still has `"upgradeTime":1`, I would expect `"upgradeTime":0`. Did you apply the change as I suggested in https://github.com/Koenkk/zigbee2mqtt/issues/17374#issuecomment-1773708885 ?

**Comment by m0wlheld** [comment] 2023-10-30 19:54
I did and restarted the container afterwards. This should not reset the image‘s content. Is it required to restart after changing the file?Regards Christoph DahlenAm 30.10.2023 um 20:39 schrieb Koen Kanters ***@***.***>:﻿
@m0wlheld this log still has "upgradeTime":1, I would expect "upgradeTime":0. Did you apply the change as I suggested in #17374 (comment) ?

**Comment by Koenkk** [comment] 2023-10-30 20:05
@m0wlheld the container needs to be restarted but with `docker restart CONTAINER_ID`, not via e.g. HA OS (if you are using the HA addon)

**Comment by m0wlheld** [comment] 2023-10-30 20:39
```json
                const payload = {
                    manufacturerCode: image.header.manufacturerCode, imageType: image.header.imageType,
                    fileVersion: image.header.fileVersion, imageSize: image.header.totalImageSize,
                    currentTime: 0, upgradeTime: 0,
                };
```

Repeating test with this setting now, gathering logs ...

**Comment by m0wlheld** [comment] 2023-10-30 21:20
[log.txt.gz](https://github.com/Koenkk/zigbee2mqtt/files/13209933/log.txt.gz)

**Comment by m0wlheld** [comment] 2023-10-30 21:21
No success however with "sticky" OTA update ...

**Comment by t34wrj** [comment] 2023-11-02 15:06
> I am also seeing this with:
> 
> * RB 266, firmware build date 20211022, version 2.03.01
> * RB 245, firmware build date 20211022, version 2.03.01
> 
> Interestingly, it has once worked to upgrade an RB 245 to 2.04.01 (several months ago) but at some point, this stopped working.

The same happened to me with the RB266 - one of three bulbs did upgrade to 2.04.01 with the remaining two stuck on 2.04.01 despite numerous attempts to update the firmware on these each time a new version of Zigbee2mqtt is released.

**Comment by Koenkk** [comment] 2023-11-03 15:48
I've asked Innr for more support, will update here.

**Comment by peter1rhodes** [comment] 2023-11-20 11:21
This issue is still present, and affects the Innr RS227T (white spectrum GU10 bulb) devices (even after the recent 1.33 release which includes some sort of fix for those devices in the notes). Same firmware versions as noted above

**Comment by Koenkk** [comment] 2023-11-22 20:31
Does anyone have sniffer hardware and could make a sniff of the update process? I've received a sniff from Innr of a successful update, then I can compare those: https://www.zigbee2mqtt.io/advanced/zigbee/04_sniff_zigbee_traffic.html

**Comment by m0wlheld** [comment] 2023-12-04 16:30
Both changes do no affect the outcome. With upgradeTime: 5 update completes but with the next OTA step it is reversed. With upgradeTime: 1 and the proposed changes update fails at 99% with timeout. Logs attached.

[upgrade-time-1-and-code_log.txt.gz](https://github.com/Koenkk/zigbee2mqtt/files/13548937/upgrade-time-1-and-code_log.txt.gz)
[upgrade-time-5_log.txt.gz](https://github.com/Koenkk/zigbee2mqtt/files/13548940/upgrade-time-5_log.txt.gz)

**Comment by m0wlheld** [comment] 2023-12-05 11:41
> @m0wlheld is there any chance you could sniff the OTA update process? https://www.zigbee2mqtt.io/advanced/zigbee/04_sniff_zigbee_traffic.html

From a hardware perspective: Yes. I do have the CC debugger and a spare CC2531. I've setup the devices and the software as explained from the link (for Windows). I see alot of data running through the window, but it's all mystery to me.

I can follow your instructions but also happy to donate the required hardware (incl. an Innr bulb) to you.

**Comment by Koenkk** [comment] 2023-12-05 19:25
>  I see alot of data running through the window, but it's all mystery to me.


Can you send the sniff + your network key to me?

You can use [this form](https://form.jotform.com/233385867866072) to privately share a file with me.

**Comment by m0wlheld** [comment] 2023-12-06 08:36
Uploaded sniff + key. An unmodified Z2M 1.34.0 was used. The protocol starts immediatly before OTA was requested and ends after an error message at the end of OTA was displayed (see below). The device in OTA affected has network address 0x6291.

```
Update of '0x9c69370000cbc69d' failed (Upgrade end response failed (CommandResponse 0x9c69370000cbc69d/1 genOta.upgradeEndResponse({"manufacturerCode":4454,"imageType":300,"fileVersion":604050705,"imageSize":291130,"currentTime":0,"upgradeTime":1}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":1,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 25233 - 1 - 228 - 25 - 11 after 10000ms)))
```

**Comment by Koenkk** [comment] 2023-12-06 15:07
I see that commands from the bulb are missing, could you sniff close to the bulb?

**Comment by DoerakkerHA** [comment] 2023-12-28 06:13
I just updated one of the 2 failing INNR bulbs and it appears to stick 👍 "update": {
        "installed_version": 604050705,
        "latest_version": 604050705,
... currently running the second one as we speak:
{
  "message": "Update of '03 zijraam' at 48.04%, ≈ 17 minutes remaining",
  "meta": {
    "device": "03 zijraam",
    "progress": 48.04,
    "status": "update_progress"
  },
  "type": "ota_update"
}

resulting in:
        "installed_version": 604050705,
        "latest_version": 604050705,

finally a reboot of HA: succes !

**Comment by DoerakkerHA** [comment] 2023-12-28 06:14
resulting in:
"installed_version": 604050705,
"latest_version": 604050705,

finally a reboot of HA: succes !

**Comment by jstaro** [comment] 2024-01-01 19:46
This was not resolved for RB 245 and RB 266.

**Comment by DoerakkerHA** [comment] 2024-01-02 04:32
Correction: it was indeed not resolved. After another reboot of HA the items returned to be updated, ran updates it appears successful but it wasn't 

Sorry for causing any confusion

**Comment by jstaro** [comment] 2024-01-09 12:55
@Koenkk Can we re-open this thread since the issue persists? I can look into sniffing an OTA update close to a bulb as mentioned to @m0wlheld .

**Comment by Koenkk** [comment] 2024-01-11 19:07
@GerryInnr I just checked, the `imageSize` is ignored (I've removed it now), in the sniff from @m0wlheld the `Upgrade End Response` is valid. One interesting thing is that it's sent after the device restarts:

<img width="1398" alt="Screenshot 2024-01-11 at 20 07 07" src="https://github.com/Koenkk/zigbee2mqtt/assets/2892853/e207e209-fb81-4754-977f-7ffd51966c86">

I'm also missing the `Upgrade End Request`, @jstaro it would be great if you could make a new sniff.

**Comment by jstaro** [comment] 2024-01-12 00:06
I didn't manage to do it with a spare Sonoff Dongle Plus-E I had laying around (the stick wouldn't start in Windows with the SiLabs drivers). I will give it another try w/ Linux, and I've also ordered a CC2531 stick just in case.

**Comment by wolterink** [comment] 2024-01-20 10:05
version firmware 2.04.02 seems to have fixed the issue for me.

**Comment by t34wrj** [comment] 2024-01-20 10:38
Same for me.

**Comment by christopher-david-smith** [comment] 2024-01-20 12:03
Updating to 2.04.02 this morning appears to have resolved the issue for myself too

**Comment by m0wlheld** [comment] 2024-01-20 12:19
Confirmed. Still trying to understand, how a firmware update can fix a broken firmware update process, but maybe the previous firmware image was just broken …Am 20.01.2024 um 13:03 schrieb Chris Smith ***@***.***>:﻿
Updating to 2.04.02 this morning appears to have resolved the issue for myself too

**Comment by Koenkk** [comment] 2024-01-21 20:56
That's awesome! I assume we can close this now.

**Closed by Koenkk** 2024-01-21 20:56 UTC
Labels: problem
