### ISSUE TITLE
zigbee2mqtt not starting after upgrade to 1.30.0

### ISSUE THREAD

**Issue by bmf7777** [Koenkk/zigbee2mqtt#16483] opened 2023-02-02 14:55 UTC
### What happened?

i'm getting an error during startup (on two instances) of zigbee2mqtt after upgrading to 1.30.0 (see debug log below) ... process dies and restarts

### What did you expect to happen?

worked fine in 1.29.2 ...

### Zigbee2MQTT version

1.30.0

### Adapter firmware version

process not starting

### Adapter

conbee2

### Debug log

> node index.js

/opt/zigbee2mqtt/node_modules/rimraf/dist/cjs/src/ignore-enoent.js:15
        if (er?.code !== 'ENOENT') {
               ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/opt/zigbee2mqtt/node_modules/rimraf/dist/cjs/src/rimraf-posix.js:14:28)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
npm ERR! code 1
npm ERR! path /opt/zigbee2mqtt
npm ERR! command failed

**Comment by Koenkk** [comment] 2023-02-02 16:43
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/16458; TLDR: update your node.js version (the one you are using is unsupported)

**Closed by Koenkk** 2023-02-02 16:43 UTC
Labels: problem
