### ISSUE TITLE
Aqara roller shade motor state broken after z2m update to 1.29.0 

### ISSUE THREAD

**Issue by szymucha94** [Koenkk/zigbee2mqtt#15895] opened 2023-01-02 16:30 UTC
### What happened?

I've updated z2m to 1.29.0 yesterday (from 1.28.4-1). The issue is that in 1.29.0 when I close or open roller shade (Aqara ZNJLBL01LM) status given to HA after open/close action is "opening" or "closing". It stays in this state for hours and never changes to correct "closed" or "open".
Aqara motors are updated to newest firmware, but I guess it shouldn't make a difference.

### What did you expect to happen?

I expect correct states to be shown in HA, ie. "closed" and "open" instead of "closing" and "opening"

### Zigbee2MQTT version

1.29.0

### Adapter firmware version

20220219

### Adapter

Sonoff CC2652P Plus USB adaptor (zStack3x0)

![1](https://user-images.githubusercontent.com/95378717/210258274-447942f9-b148-4d3d-84f8-742d2d44ba62.JPG)
![2](https://user-images.githubusercontent.com/95378717/210258277-96e5d7ab-a8a1-4163-a510-fe325567d803.JPG)

**Comment by Koenkk** [comment] 2023-01-03 09:14
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/15873

**Closed by Koenkk** 2023-01-03 09:14 UTC
Labels: problem
