### ISSUE TITLE
network map not connected devices

### ISSUE THREAD

**Issue by sander816** [Koenkk/zigbee2mqtt#2609] opened 2019-12-26 11:16 UTC
I have a cc2531 as router and the same module as coordinator.
Besides that i have 2 lights and a powerswitch that work as router.
Why is it that when i reboot my pi, my networkmap shows almost all devices not connected to anything?
All devices are working correct though
When i look in Zigbee2MqttAssistant i see this: Link quality is unknown/255.
Repairing them makes them connected again, but what is going wrong here?
![Naamloos](https://user-images.githubusercontent.com/35403173/71473931-70148180-27d9-11ea-865a-7d83aa0fa48e.png)

**Comment by pcb1962** [comment] 2019-12-26 15:08
#2542

**Comment by Koenkk** [comment] 2019-12-26 20:59
Indeed duplicate of #2436

**Closed by Koenkk** 2019-12-26 20:59 UTC
