### ISSUE TITLE
Docker container fails to restart after coordinator is disconnected from power

### ISSUE THREAD

**Issue by Notrial** [Koenkk/zigbee2mqtt#7257] opened 2021-04-30 10:14 UTC
## What happened
After power loss, docker container doesn't restart automatically, I have to restart it manually. Screenshot from the log is below:

![image](https://user-images.githubusercontent.com/36201754/116681179-e700f200-a9ac-11eb-850e-98ccf0dc43ac.png)

## What did you expect to happen

When the power is restored, the container is started automatically.

## How to reproduce it (minimal and precise)

Unplug and plug back in the coordinator stick.

## Debug info
Zigbee2MQTT version: 1.18.2
Adapter hardware: CC2652P2
Adapter firmware version: CC1352P2_CC2652P_launchpad_coordinator_20210120.zip

**Comment by ssiergl** [comment] 2021-04-30 11:23
see 

here

https://github.com/Koenkk/zigbee2mqtt/issues/7198

and here

https://github.com/Koenkk/zigbee2mqtt/pull/7230

**Comment by Notrial** [comment] 2021-04-30 12:05
So if I'm reading this right, I should just update the docker to this latest version?

Thanks!

**Comment by ssiergl** [comment] 2021-04-30 12:36
No...IT is better with this patch but not finally solved.

Still being worked on

**Comment by Notrial** [comment] 2021-04-30 12:38
Thanks again, will keep an eye out ;)

**Comment by Koenkk** [comment] 2021-04-30 14:20
Duplicate of #7198

**Closed by Koenkk** 2021-04-30 14:20 UTC
Labels: problem
