### ISSUE TITLE
Battery level on Xiaomi PIR and door sensors

### ISSUE THREAD

**Issue by flouck** [Koenkk/zigbee2mqtt#3243] opened 2020-03-30 10:31 UTC
Hi there,
I am using both an "Aqara human body movement and illuminance sensor" and a "MiJia door & window contact sensor". After pairing them to my zigbee2mqtt using a CC2531, it works great! The only problem I have is their battery level, indicated as 100%. When I check with the official Mi Home app, it was around 60%.  Here is what I receive in the addon:

```
zigbee2mqtt:info  2020-03-30 11:03:53: MQTT publish: topic 'zigbee2mqtt/0x00158d0002b93ec8', payload '{"battery":100,"voltage":3005,"illuminance":265,"illuminance_lux":265,"linkquality":81,"occupancy":false}'
zigbee2mqtt:info  2020-03-30 11:21:11: MQTT publish: topic 'zigbee2mqtt/0x00158d00034f91bb', payload '{"battery":100,"voltage":3005,"linkquality":34,"contact":true}'
```

**Comment by Koenkk** [comment] 2020-03-30 17:42
Duplicate of https://github.com/Koenkk/zigbee-herdsman-converters/issues/1036

**Closed by Koenkk** 2020-03-30 17:42 UTC
