### ISSUE TITLE
zigbee2mqtt:error Failed to configure ... (Osram SMART+ motion sensor)

### ISSUE THREAD

**Issue by rosch100** [Koenkk/zigbee2mqtt#3504] opened 2020-05-07 06:34 UTC
# Bug Report
## What happened
For one of my Osram SMART+ Motion Sensors, there are errors in the Zigbee2MQTT log. This sensor seems to be unreliable. I needed several attempts before it was successfully connected. It also seems to be unreliable.
All other sensors (four of the same brand) work reliably without issues.

```
zigbee2mqtt:info  2020-05-07 08:07:14: MQTT publish: topic 'homeassistant/sensor/0x000d6f000e63acf2/linkquality/config', payload '{"icon":"mdi:signal","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}","state_topic":"zigbee2mqtt/0x000d6f000e63acf2","json_attributes_topic":"zigbee2mqtt/0x000d6f000e63acf2","name":"0x000d6f000e63acf2_linkquality","unique_id":"0x000d6f000e63acf2_linkquality_zigbee2mqtt","device":{"identifiers":["zigbee2mqtt_0x000d6f000e63acf2"],"name":"0x000d6f000e63acf2","sw_version":"Zigbee2mqtt 1.13.0","model":"SMART+ Motion Sensor (AC01353010G)","manufacturer":"OSRAM"},"availability_topic":"zigbee2mqtt/bridge/state"}'
zigbee2mqtt:info  2020-05-07 08:07:23: MQTT publish: topic 'zigbee2mqtt/0x000d6f000e63acf2', payload '{"temperature":19.2,"linkquality":42,"occupancy":false,"tamper":true,"battery_low":false}'
zigbee2mqtt:error 2020-05-07 08:07:30: Failed to configure '0x000d6f000e63acf2', attempt 1 (Error: ConfigureReporting 0x000d6f000e63acf2/1 genPowerCfg([{"attribute":"batteryPercentageRemaining","minimumReportInterval":3600,"maximumReportInterval":62000,"reportableChange":0}], {"timeout":10000,"manufacturerCode":null,"disableDefaultResponse":true}) failed (Error: Status 'UNSUPPORTED_ATTRIBUTE')
    at Endpoint.<anonymous> (/zigbee2mqtt-1.13.0/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:326:23)
    at Generator.next (<anonymous>)
    at fulfilled (/zigbee2mqtt-1.13.0/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:5:58))
zigbee2mqtt:error 2020-05-07 08:13:25: Failed to configure '0x000d6f000e63acf2', attempt 3 (Error: Bind 0x000d6f000e63acf2/1 genPowerCfg from '0x00124b00193673ac/1' failed (Error: AREQ - ZDO - bindRsp after 10000ms)
    at Endpoint.<anonymous> (/zigbee2mqtt-1.13.0/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:244:23)
    at Generator.throw (<anonymous>)
    at rejected (/zigbee2mqtt-1.13.0/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:6:65))

```
## Debug Info
Zigbee2mqtt version: 1.13.0
Adapter hardware: CC2531
Adapter firmware version: April 2019

**Comment by Koenkk** [comment] 2020-05-07 07:05
Duplicate of #3416 (already fixed in latest dev branch)

**Closed by Koenkk** 2020-05-07 07:05 UTC
