### ISSUE TITLE
Z2M 1.21.1-1 Failed to call 'OTAUpdate'

### ISSUE THREAD

**Issue by shirou93** [Koenkk/zigbee2mqtt#8875] opened 2021-09-24 21:06 UTC
Z2M 1.21.1-1

logs:

`Zigbee2MQTT:error 2021-09-24 19:37:51: Failed to call 'OTAUpdate' 'onZigbeeEvent' (Error: certificate has expired
    at TLSSocket.onConnectSecure (_tls_wrap.js:1514:34)
    at TLSSocket.emit (events.js:400:28)
    at TLSSocket._finishInit (_tls_wrap.js:936:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:708:12))`

**Comment by Koenkk** [comment] 2021-09-25 09:48
Duplicate of #8864

**Closed by Koenkk** 2021-09-25 09:48 UTC
Labels: problem
