### ISSUE TITLE
ZWT198/ZWT100-BH get EventBus error 'Publish/mqttMessage': Cannot read properties of undefined (reading 'some')

### ISSUE THREAD

**Issue by Danieldiazi** [Koenkk/zigbee2mqtt#23851] opened 2024-09-04 21:12 UTC
### What happened?

When I change any item in "Exposes" tab I always get " EventBus error 'Publish/mqttMessage': Cannot read properties of undefined (reading 'some')"

This is my device:

![imagen](https://github.com/user-attachments/assets/4d375e71-49cb-4e89-933a-b05ff4877faa)

And this is the error message:

![error](https://github.com/user-attachments/assets/b5bccb93-7529-4123-890a-4346184275b9)

### What did you expect to happen?

Don't see this messages.

### How to reproduce it (minimal and precise)

Go to "Exposes" section and try to change any item, like Child Lock switch.

### Zigbee2MQTT version

1.40.0

### Adapter firmware version

20240510

### Adapter

SLZB-06M

### Setup

Docker container

### Debug log

error 2024-09-04 20:49:04z2m: EventBus error 'Publish/mqttMessage': Cannot read properties of undefined (reading 'some')
info 2024-09-04 20:49:09 z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/termostato', payload '{"backlight_mode":null,"child_lock":"UNLOCK","current_heating_setpoint":6,"deadzone_temperature":0.5,"device":{"applicationVersion":65,"dateCode":"","friendlyName":"termostato","hardwareVersion":1,"ieeeAddr":"XXXXXXX","manufacturerID":4098,"manufacturerName":"_TZE200_viy9ihs7","model":"ZWT198/ZWT100-BH","networkAddress":XXXXX,"powerSource":"Battery","stackVersion":0,"type":"EndDevice","zclVersion":3},"factory_reset":null,"frost_protection":null,"linkquality":152,"local_temperature":24.6,"local_temperature_calibration":null,"max_temperature_limit":35.5,"preset":"auto","running_state":"idle","schedule_holiday":null,"schedule_weekday":null,"sensor":"both","system_mode":"off","working_day":null}'

**Comment by Koenkk** [comment] 2024-09-05 11:13
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/23821

**Closed by Koenkk** 2024-09-05 11:13 UTC
Labels: problem
