### ISSUE TITLE
TS130F Problem with update of Z2M

### ISSUE THREAD

**Issue by thierry-rhone** [Koenkk/zigbee2mqtt#14018] opened 2022-09-15 20:01 UTC
### What happened?

When I update Z2M from 1.26.0-1 to 1.27.2-1 :
- in lovelace, my curtain switch TS130F Show state closed when it's fully open and opened when it's fully closed.
The slider remains correct.
when the curtain isn't fully opened or closed the number is correct
If I downgrade the version the problem disappears

![volet de la cuisine](https://user-images.githubusercontent.com/65720627/190496104-7e0beedd-ba3e-458c-a0f1-435a5c97969c.png)

### What did you expect to happen?

unchanged operation with update

### Zigbee2MQTT version

1.27.2-1

### Adapter firmware version

2022.9.1

### Adapter

Electrolama or sonoff (the problem remains the same)

### Debug log

_
[debug volet.txt](https://github.com/Koenkk/zigbee2mqtt/files/9578600/debug.volet.txt)

**Comment by Koenkk** [comment] 2022-09-16 07:30
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/13813

**Closed by Koenkk** 2022-09-16 07:30 UTC
Labels: problem
