### ISSUE TITLE
zigbee shepperd error

### ISSUE THREAD

**Issue by pedrogense** [Koenkk/zigbee2mqtt#1078] opened 2019-02-12 15:13 UTC
my zigbee sheperd wont start.
Ive did a clean install on hassio and i reflashed my stick with latest firmware.
The dev/port is the correct one, also tried other usb ports.

i've tried the steady zigbee2mqtt and the edge one.

{
  "data_path": "/share/zigbee2mqtt",
  "homeassistant": true,
  "permit_join": false,
  "mqtt_base_topic": "zigbee2mqtt",
  "mqtt_server": "mqtt://core-mosquitto",
  "serial_port": "/dev/ttyACM1",
  "devices": [],
  "network_key": [],
  "mqtt_user": "*****",
  "mqtt_pass": "******",
  "log_level": "debug",
  "zigbee_shepherd_debug": true
}

2019-02-12T15:04:36.676Z zigbee-shepherd:init zigbee-shepherd booting...
2019-02-12T15:04:36.723Z zigbee-shepherd:request REQ --> SYS:osalNvRead
2019-02-12T15:04:39.745Z zigbee-shepherd:request RSP <-- SYS:osalNvRead
2019-02-12T15:04:39.772Z zigbee-shepherd:init Coordinator initialize had an error: Error: request timeout
    at CcZnp.<anonymous> (/zigbee2mqtt-1.1.1/node_modules/cc-znp/lib/ccznp.js:255:22)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at CcZnp.emit (events.js:211:7)
    at Timeout.<anonymous> (/zigbee2mqtt-1.1.1/node_modules/cc-znp/lib/ccznp.js:234:18)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)

**Comment by Koenkk** [comment] 2019-02-12 16:33
Duplicate of #937, can you try with zigbee2mqtt 1.0.0 and report in #937?

**Closed by Koenkk** 2019-02-12 16:33 UTC
