### ISSUE TITLE
Lixee kWh_precision

### ISSUE THREAD

**Issue by roumano** [Koenkk/zigbee2mqtt#11345] opened 2022-02-10 17:47 UTC
### What happened?

On the product [LiXee](https://www.zigbee2mqtt.io/supported-devices/#v=LiXee) , Modèle
    [ZLinky_TIC](https://www.zigbee2mqtt.io/devices/ZLinky_TIC.html#lixee-zlinky_tic)

i use it, actually, with the `historique` mode
I set the specific parameters with "kWh_precision" to 3, but even after a restart of Z2M, i'm stiff getting a integer for current_summ_delivered / current_tier1_summ_delivered

Please found the full expose information :  
```
{
    "active_register_tier_delivered": "TH..",
    "apparent_power": 510,
    "available_power": 30,
    "current_summ_delivered": 38199,
    "current_tier1_summ_delivered": 38199,
    "current_tier2_summ_delivered": 0,
    "current_tier3_summ_delivered": 0,
    "current_tier4_summ_delivered": 0,
    "current_tier5_summ_delivered": 0,
    "current_tier6_summ_delivered": 0,
    "last_seen": "2022-02-10T17:45:13.037Z",
    "linkquality": 255,
    "meter_serial_number": "031764648881",
    "rms_current": 2,
    "rms_current_max": 90,
    "current_tarif": null,
    "update": {
        "state": null
    },
    "update_available": null,
    "warn_d_p_s": null
}
```

PS : i use the last firmware version  : 4000-0004 ( date firmware 20220117 )

### What did you expect to happen?

Get a detailled current_summ_delivered attribue

### Zigbee2MQTT version

 1.23.0-dev

### Adapter firmware version

0x26720700

### Adapter

ConBee2

**Comment by vk496** [comment] 2022-02-11 10:23
@roumano  I've tried to reproduce your issue, but works as expected on my side. The unique condition is to receive another update from the zlinky, so the values get updated. If you don't receive any data from the deive, they will remain as old style (integers)

**Comment by roumano** [comment] 2022-02-11 12:26
Hi,
Sorry for the noise, the device is disconnect so much, it's difficult to debug and get real and useful information.
  as example, i have retry ~ 10 times the update of firmware via OTA before success... 

Do you known if someone is working to improve this ?(maybe need in the firmware ) 

PS : it's need a restart of z2m (after set it in z2m) to remove these continuous log information :  
```
févr. 11 13:18:35 rasp npm[15358]: Was not able to detect the Linky linky_mode. Default to historique
févr. 11 13:18:35 rasp npm[15358]: Was not able to detect the Linky energy_phase. Default to single_phase
```

**Comment by vk496** [comment] 2022-02-11 12:48
The flood of that messages is fixed in the last dev branch (you had to reinstall, since z2m edge doesn't receive updates as stable do). Also, I would make sure that you remove your old database/state.json from Z2M config file, since I'm still thinking the problem is somehow related to the cache of old data

**Comment by antoinelibert** [comment] 2022-02-11 17:19
@roumano, a limited number of modules had a hardware defect, the module could disconnect randomly (blue LED indicator off). Did you get in touch with the shop for an exchange?

**Comment by roumano** [comment] 2022-02-11 20:52
I was not alone as i saw on a gist "wiki", so i was waiting few weeks , ...

Look on this issue, other issue have the same behavior : https://github.com/fairecasoimeme/Zlinky_TIC/issues/42
But i contacted the creator of the chip about it.

**Closed** 2022-02-15 08:21 UTC
Labels: problem
