### ISSUE TITLE
Disable coordinator LED on cc2652r

### ISSUE THREAD

**Issue by Sloth-on-meth** [Koenkk/zigbee2mqtt#4861] opened 2020-11-03 12:21 UTC
Hi there, my cc2652r coordinator works, but the disable_led option does not seem supported for this  stick. can this please be added?

**Comment by Koenkk** [comment] 2020-11-03 12:35
Duplicate of https://github.com/Koenkk/Z-Stack-firmware/issues/203

**Closed by Koenkk** 2020-11-03 12:35 UTC
Labels: feature request

**Comment by Sloth-on-meth** [comment] 2020-11-03 12:48
ooops, sorry
