### ISSUE TITLE
1.5.0 crashes with CC2530 after 1-30 minutes

### ISSUE THREAD

**Issue by Sonsi79** [Koenkk/zigbee2mqtt#1739] opened 2019-07-15 22:18 UTC
Hi @Koenkk its me again after long time,

since update from 1.4.0 to your new 1.5.0 my zigbee2mqtt crashes after running 1-30 minutes.
it seems that the tool freezes, because no errors will be shown and logging (info) stops.

With loglevel=debug these errors will be shown in Docker log.
https://pastebin.com/2BgHGvBV

I tried with Docker and also with local installation. Same errors.
I also tried by re-flash to newest firmware (Newest Master Standard for CC2530) but still the same errors.

I can force this crash by moving in front of my motion sensor (Xiaomi RTCGQ11LM) but it also crash after removing the Sensor.

Hope you can help (again) :-)

**Comment by Koenkk** [comment] 2019-07-16 03:32
Duplicate of #1743

**Closed by Koenkk** 2019-07-16 03:32 UTC
