### ISSUE TITLE
Temperature calibration unstable on xiaomi SP-EUC01

### ISSUE THREAD

**Issue by KimCarlsen** [Koenkk/zigbee2mqtt#16015] opened 2023-01-07 19:27 UTC
### What happened?

After i adjusted temperature_calibration on my smart plug the readings are bumping up and down.
![image](https://user-images.githubusercontent.com/13509827/211167094-e4cc26b3-83b8-4765-a699-5a3d062cd478.png)
![image](https://user-images.githubusercontent.com/13509827/211167112-941fc6a1-2e08-4a84-aa18-b8a73d7fc81e.png)

The spikes fits with the original value, as i adjusted the calibration with -4

HA version 2022.12.8
SP-EUC01 firmware date: 12-06-2021

### What did you expect to happen?

consistant readings

### How to reproduce it (minimal and precise)

set device_temperature_calibration to -4 (same with -5)

### Zigbee2MQTT version

1.29.0

### Adapter firmware version

20220219

### Adapter

Sonoff CC2652P

**Comment by Koenkk** [comment] 2023-01-08 08:31
Can you provide the debug log when the temperature jumps up?

**Comment by KimCarlsen** [comment] 2023-01-08 14:21
[z2m.txt](https://github.com/Koenkk/zigbee2mqtt/files/10368624/z2m.txt)
Affected device "Murphy"
15:12:04 temperature 11
15:12:30 temperature 6

The peaks comes every 30 min, down to the second

**Comment by Koenkk** [comment] 2023-01-09 18:06
Can you provide the debug log of the z2m start? (start till 1 min after start)

**Comment by KimCarlsen** [comment] 2023-01-09 18:37
[Z2MStart.txt](https://github.com/Koenkk/zigbee2mqtt/files/10375939/Z2MStart.txt)

**Comment by Koenkk** [comment] 2023-01-09 18:50
Could you check if the issue is fixed with the following external converter: https://gist.github.com/Koenkk/553d5f0b200536c5d478a7f734499381

- save this as file next to `configuration.yaml` as `ext_converter.js`
- add it to `configuration.yaml`:
```yaml
external_converters:
  - ext_converter.js
```
- start z2m, check if issue is fixed

**Comment by KimCarlsen** [comment] 2023-01-10 04:31
Better. now the spikes are only one degree off

**Comment by Koenkk** [comment] 2023-01-11 17:11
I updated https://gist.github.com/Koenkk/553d5f0b200536c5d478a7f734499381, can you provide the debug logging when running with that external converter and getting the off by one degree?

**Comment by KimCarlsen** [comment] 2023-01-13 16:55
[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/10413644/log.txt)

one degree spike at 17:43:13
Back to normal at 17:49:58

**Comment by Koenkk** [comment] 2023-01-14 08:13
Can you provide the logging again? I updated https://gist.github.com/Koenkk/553d5f0b200536c5d478a7f734499381

**Comment by KimCarlsen** [comment] 2023-01-15 06:22
Seems it has been fixed no. no spikes for 12 hours. thanks

**Comment by KimCarlsen** [comment] 2023-02-15 17:06
@Koenkk will this be part of the release?

**Comment by Koenkk** [comment] 2023-02-15 19:22
I don't understand how https://gist.github.com/Koenkk/553d5f0b200536c5d478a7f734499381 can fix this, this is the same code as in 1.30.1. How are you running z2m?

**Comment by KimCarlsen** [comment] 2023-02-15 20:16
Just tested with 1.30.1 (was using 1.30.0), but still it fails if i remove the 
" external_converters:
  - ext_converter.js"
It is running on windows server 2019 as a windows service.
Is there any file i can compare?

**Comment by Koenkk** [comment] 2023-02-16 17:11
After updating, did you execute `npm ci` in the zigbee2mqtt directory? Also, what is the content of the `package.json` file?

**Comment by KimCarlsen** [comment] 2023-02-17 19:08
okay. reinstalled everything and now it seems to work, so something must have been missing updates. thanks

**Comment by Koenkk** [comment] 2023-02-18 08:37
Great!

**Closed by Koenkk** 2023-02-18 08:37 UTC
Labels: problem
