### ISSUE TITLE
Cannot Open Shutter Blaupunkt o Lupus Shutter after upgrade

### ISSUE THREAD

**Issue by mccoy88f** [Koenkk/zigbee2mqtt#2328] opened 2019-11-12 17:49 UTC
After upgrading 1.7 from 1.5.1.2 everything works good but when i send up or down command for the shutter i receive this in the log...
Someone can help?

zigbee2mqtt:error 2019-11-12T17:42:49: Publish 'set' 'state' to '0x00124b00144b48a5' failed: 'TypeError: Cannot read property 'convertSet' of undefined'
zigbee2mqtt:info  2019-11-12T17:42:49: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"zigbee_publish_error","message":"Publish 'set' 'state' to '0x00124b00144b48a5' failed: 'TypeError: Cannot read property 'convertSet' of undefined'","meta":{"friendly_name":"0x00124b00144b48a5"}}'

This is the code inside zigbee herdsman converter 
    // Lupus
    {
        zigbeeModel: ['SCM_00.00.03.11TC'],
        model: '12031',
        vendor: 'Lupus',
        description: 'Roller shutter',
        supports: 'open/close',
        fromZigbee: [fz.cover_position_via_brightness, fz.cover_state_via_onoff],
        toZigbee: [tz.cover_position_via_brightness, tz.cover_open_close_via_brightness],
    },

    // Blaupunkt
    {
        zigbeeModel: ['SCM-R_00.00.03.15TC', 'SCM_00.00.03.14TC'],
        model: 'SCM-S1',
        vendor: 'Blaupunkt',
        description: 'Roller shutter',
        supports: 'open/close',
        fromZigbee: [fz.cover_position_via_brightness, fz.cover_state_via_onoff],
        toZigbee: [tz.cover_position_via_brightness, tz.cover_open_close_via_brightness],
    },

**Comment by Koenkk** [comment] 2019-11-12 17:55
Duplicate of #2323 and possible solution: https://github.com/Koenkk/zigbee2mqtt/issues/2323#issuecomment-552963019

**Closed by Koenkk** 2019-11-12 17:55 UTC
