### ISSUE TITLE
TS0041 does not show correct button press after recent upgrade

### ISSUE THREAD

**Issue by NeoFax75** [Koenkk/zigbee2mqtt#21205] opened 2024-02-04 00:17 UTC
### What happened?

I press the button on the ts0041 and z2mqtt shows Empty string("").

### What did you expect to happen?

I expected it to show a single click, double click or hold depending on how I click it.

### How to reproduce it (minimal and precise)

Have the current z2mqtt installed and press the button.

### Zigbee2MQTT version

1.35.2

### Adapter firmware version

6.10.3.0 build 297

### Adapter

ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2

### Setup

Home Assistant OS

### Debug log

`2024-02-03 19:18:08Received Zigbee message from 'Living Room Button', type 'raw', cluster 'genOnOff', data '{"data":[1,75,253,0],"type":"Buffer"}' from endpoint 1 with groupID 0`

**Comment by Koenkk** [comment] 2024-02-04 07:56
Dupe of https://github.com/Koenkk/zigbee2mqtt/issues/21158

**Closed by Koenkk** 2024-02-04 07:56 UTC
Labels: problem
