### ISSUE TITLE
Snzb-02 dont give temperature and humidity valors

### ISSUE THREAD

**Issue by maiflaii** [Koenkk/zigbee2mqtt#8835] opened 2021-09-21 18:02 UTC
Cc2531 z-stack 1.2 
Zigbee2mqtt version 1.21.1-1 
Ha Versión
core-2021.9.7
supervisor-2021.09.0

When I try connect a new device of this,temperature and humidity dont show me the valor,show null both

**Comment by chimcanhcut1112** [comment] 2021-09-22 08:15
> Cc2531 z-stack 1.2
> Zigbee2mqtt version 1.21.1-1
> Ha Versión
> core-2021.9.7
> supervisor-2021.09.0
> 
> When I try connect a new device of this,temperature and humidity dont show me the valor,show null both

rollback core version 9.6, will fine.

**Comment by Koenkk** [comment] 2021-10-09 08:35
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/8971

**Closed by Koenkk** 2021-10-09 08:35 UTC
Labels: problem
