### ISSUE TITLE
Lost exposed color settings on Sengled E11-N1EA Bulbs

### ISSUE THREAD

**Issue by monogoat** [Koenkk/zigbee2mqtt#13476] opened 2022-08-09 21:04 UTC
### What happened?

Two of my color bulbs, Sengled model E11-N1EA, no longer have color mode or temperature options exposed by zigbee2mqtt. I just noticed it, so it had to be a recent update that caused it. These are the only two I have of this model, but I have some E12-N1E bulbs in another room that still have the color changing available.

### Zigbee2MQTT version

1.27.0 commit: unknown

### Adapter firmware version

20210120

### Adapter

LAUNCHXL-CC26X2R1

**Comment by Koenkk** [comment] 2022-08-10 14:56
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/13365

**Closed by Koenkk** 2022-08-10 14:56 UTC
Labels: problem
