### ISSUE TITLE
Data request failed with error: 'MAC no ack'

### ISSUE THREAD

**Issue by BremerButjer** [Koenkk/zigbee2mqtt#4101] opened 2020-08-14 10:14 UTC
There are also problems with the Osram Smart+ plug.
If this is switched, often no feedback appears:
https://pastebin.com/1SJMKtzM

I had the network map output with graphviz. According to the output "OsramPlug" has a "green" route to the next device and two "red" connections to other devices.
These devices each have a direct connection to the coordinator.

Actually the feedback from OsramPlug should be passed on. Right?

**Comment by Koenkk** [comment] 2020-08-14 10:42
Duplicate of #3910, possible solution is to switch to the source routing firmware (https://github.com/Koenkk/zigbee2mqtt/issues/3910#issuecomment-667647574)

**Closed by Koenkk** 2020-08-14 10:42 UTC
