### ISSUE TITLE
Cover states are lost for  ZNCLDJ12LM and ZNCLDJ11LM

### ISSUE THREAD

**Issue by new-kirte** [Koenkk/zigbee2mqtt#15954] opened 2023-01-04 22:19 UTC
### What happened?

All of a sudden cover.toggle stopped working for all curtains in HA. I have noticed, that curtains state in HA has also changed to unknown regardless of the position (0 or 100). In z2m all covers also do not report any state at the Exposes tab. And their state is reported as OFF:
`{
    "device_temperature": 34,
    "linkquality": 252,
    "motor_state": "stopped",
    "position": 0,
    "power_outage_count": 17,
    "running": false,
    "state": "OFF",
    "temperature": 35,
    "update": {
        "installed_version": 36,
        "latest_version": 36,
        "state": "idle"
    },
    "update_available": false,
    "device": {
        "applicationVersion": 1,
        "dateCode": "01-25-2022",
        "friendlyName": "Sonya Curtains Wired",
        "ieeeAddr": "0x00158d00040e6261",
        "manufacturerID": 4447,
        "manufacturerName": "LUMI",
        "model": "ZNCLDJ11LM",
        "networkAddress": 24578,
        "powerSource": "Mains (single phase)",
        "type": "Router",
        "zclVersion": 1
    }
}`

In HA the state is reported as unknown and none by the following template:
`  {{states('cover.sonya_curtains_wired')}}
  {{state_attr('cover.sonya_curtains_wired', 'state')}}`

### What did you expect to happen?

I expect the curtains state to be Opened or Closed

### How to reproduce it (minimal and precise)

Change the position to 0 or 100 and check if the state has changed

### Zigbee2MQTT version

1.29.0

### Adapter firmware version

0x26720700

### Adapter

ConBee2

### Debug log

[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/10347843/log.txt)

**Comment by Koenkk** [comment] 2023-01-05 09:06
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/15873

**Closed by Koenkk** 2023-01-05 09:06 UTC
Labels: problem
