### ISSUE TITLE
Operation mode cannot changed for Aqara smart wall switch H1 EU (no neutral, double rocker)

### ISSUE THREAD

**Issue by k-szabi** [Koenkk/zigbee2mqtt#20274] opened 2023-12-18 14:48 UTC
### What happened?

When I try to change the operation mode for the Aqara smart wall switch H1 EU (no neutral, double rocker) I got the following error message: 
Publish 'set' 'operation_mode' to 'kitchen/lights' failed: 'Error: undefined is not a object, got string ("control_relay")'

### What did you expect to happen?

The operational mode should be changed to either control_relay or decoupled. It works fine on Zigbee2MQTT v1.33.2

### How to reproduce it (minimal and precise)

I removed the switch from the zigbee network then pair it again. Then tried to change the operational mode.

### Zigbee2MQTT version

1.34.0

### Adapter firmware version

20221226

### Adapter

Sonoff  Dongle Plus "ZBDongle-P"

**Comment by julianfs** [comment] 2023-12-18 17:26
Duplicate of #20036

**Closed** 2023-12-18 18:43 UTC
Labels: problem
