### ISSUE TITLE
Hue bulb power loss does change status

### ISSUE THREAD

**Issue by danpowell88** [Koenkk/zigbee2mqtt#717] opened 2018-12-17 11:21 UTC
With the phillips hue hub when a bulb lost power usually within 10 seconds or so it would be updated to have its status show as off (or on if it got power back).

I cant seem to see anything here that marks the bulbs as on/off when power is lost, it doesnt even appear to log any MQTT messages when the power comes back on (not sure if theres something in the zigbee network that just isnt being logged on power on?)

What I do to have the status of the bulbs change when power is lost or restored ?

Somewhat related to #679 however that is around the settings being lost and not the actual state of the bulbs not changing

**Comment by Koenkk** [comment] 2018-12-17 13:14
Duplicate of #534

**Closed by Koenkk** 2018-12-17 13:14 UTC
