### ISSUE TITLE
QBKG26LM zigbee2mqtt action support

### ISSUE THREAD

**Issue by satedone** [Koenkk/zigbee2mqtt#7254] opened 2021-04-29 22:41 UTC
I have a QBKG26LM.
In zigbee2mqtt it will be well defined.
Switch (state) is supported.
I am changing the decoupled mode.
And after that I want to customize the action.
But the device does not track these events.
There is nothing in the history and in the logs too.
Although the device page states that action is supported.
https://www.zigbee2mqtt.io/devices/QBKG26LM.html#xiaomi-qbkg26lm
Please help me figure it out.

**Comment by Koenkk** [comment] 2021-04-30 14:23
Duplicate of https://github.com/Koenkk/zigbee-herdsman-converters/issues/1986

**Closed by Koenkk** 2021-04-30 14:23 UTC
Labels: problem

**Comment by redesigndavid** [comment] 2021-05-05 16:06
Hi @Koenkk, I appreciate you managing all of this.  Curious though, in #1986, it looks as though @slydiman was able to get it to work with his last few comments, where all that's needed to be done is update the firmware?  Wish there were steps you could provide that'll let us do that.  Or other steps we can follow to achieve the same.  Thanks again!

**Comment by Koenkk** [comment] 2021-05-05 18:08
Let's continue in https://github.com/Koenkk/zigbee2mqtt/issues/1986
