### ISSUE TITLE
Wrong Battery calculation with Xiaomi-Devices

### ISSUE THREAD

**Issue by Diet1976** [Koenkk/zigbee2mqtt#15308] opened 2022-12-02 08:44 UTC
### What happened?

Since the last update of IOBRoker.Zigbee, my battery percentages of all of my windows-contacts/motion sensors are really low, even the Volt-Value is near 100%.
I didn't find a change logged in the adapter history?

Greetings, Dietmar

### Zigbee2MQTT version

1.7.6

### Adapter firmware version

0x26690700

### Adapter

ZigBee-Adapter 1.7.6

**Comment by Koenkk** [comment] 2022-12-02 16:19
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/8499

**Closed by Koenkk** 2022-12-02 16:19 UTC
Labels: problem

**Comment by Diet1976** [comment] 2022-12-02 16:46
Hello!Are you sure, that it is a duplicate? Because the other issue describes the opposite? My Devices were at 90-100% and suddenly they are all low?Greets, DietmarAm 02.12.2022 um 17:19 schrieb Koen Kanters ***@***.***>:﻿
Duplicate of #8499
