### ISSUE TITLE
z2m is reporting update to HA for SNZB-01P even it is not reporting that in its OTA and it is providing wrong versions

### ISSUE THREAD

**Issue by Hadatko** [Koenkk/zigbee2mqtt#20863] opened 2024-01-18 06:22 UTC
### What happened?

In z2m OTA it looks everything ok:
![image](https://github.com/Koenkk/zigbee2mqtt/assets/13130700/796610b2-9806-41b0-9dd0-c51307b16f04)
But in HA:
![image](https://github.com/Koenkk/zigbee2mqtt/assets/13130700/ca66b90c-3644-4712-a647-d7273c13cef4)
![image](https://github.com/Koenkk/zigbee2mqtt/assets/13130700/ceee64eb-6bf9-4cd6-904c-5cb1c70abf7e)

### What did you expect to happen?

No update trigger in HA.

### How to reproduce it (minimal and precise)

Pair SNZB-01P device

### Zigbee2MQTT version

1.35.1

### Adapter firmware version

7.1.1.0 build 273

### Adapter

skyconnect

### Setup

addon in HA

**Comment by Great-Chart** [comment] 2024-01-18 17:18
I have a similar issue that shows similar -1 value presented for 2 devices (although I have multiples of one of them).
These aren't Sonoff items as per above which suggests its not device specific.
No OTA updates visible in Z2M however.
Using Sonoff Dongle-P also with 1.35.1 Z2M
![Capture2](https://github.com/Koenkk/zigbee2mqtt/assets/101117351/d87d2d0c-1cb1-400a-b2d7-01e579eb734b)
![Capture1](https://github.com/Koenkk/zigbee2mqtt/assets/101117351/69b78c3c-549c-40fc-b224-1d8825b3bdae)
![Capture3](https://github.com/Koenkk/zigbee2mqtt/assets/101117351/d44e485a-a403-4e3b-90c9-c20efd5d7c1c)

**Comment by DittmannCz** [comment] 2024-01-18 19:05
Any advice?

**Comment by Koenkk** [comment] 2024-01-18 20:49
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/20658

**Closed by Koenkk** 2024-01-18 20:49 UTC
Labels: problem
