### ISSUE TITLE
TS110E_TZ3210_k1msuvg6 physical switch doesn't work after switch-off via Z2M

### ISSUE THREAD

**Issue by micihol** [Koenkk/zigbee2mqtt#16190] opened 2023-01-15 22:33 UTC
### What happened?

TS110E_TZ3210_k1msuvg6 is not responding to physical switch presses when the light is powered off via ZigBee.

Issues I reviewed refer to State and State_1 handling while mine is different.
When the light is switched off via the front-end (either Z2M UI or HA integration) the brightness goes to 0 at the same time:

// switched off via ZigBee:
**2023-01-15 22:10:49MQTT publish: topic** 'zigbee2mqtt/0xa4c138e22af6f6de', payload '{"brightness":195,"brightness_1":0,"level":953,"linkquality":51,"max_brightness":175,"min_brightness":40,"power_on_behavior":"previous","power_on_behavior_1":"previous",**"state":"OFF","state_1":"OFF"**,"switch_type":"momentary","switch_type_1":"momentary"}'
**2023-01-15 22:10:50Received Zigbee message from '0xa4c138e22af6f6de'**, type 'attributeReport', cluster **'genLevelCtrl', data '{"61440":0,"currentLevel":0}'** from endpoint 1 with groupID 0
**2023-01-15 22:10:50MQTT publish: topic** 'zigbee2mqtt/0xa4c138e22af6f6de', payload **'{"brightness":0,"brightness_1":0**,"level":953,"linkquality":48,"max_brightness":175,"min_brightness":40,"power_on_behavior":"previous","power_on_behavior_1":"previous","state":"OFF","state_1":"OFF","switch_type":"momentary","switch_type_1":"momentary"}'

Now, when I press the physical switch:
 2023-01-15 22:15:10MQTT publish: topic 'zigbee2mqtt/0xa4c138e22af6f6de', payload '{**"brightness":0,"brightness_1":0**,"level":953,"linkquality":39,"max_brightness":175,"min_brightness":40,"power_on_behavior":"previous","power_on_behavior_1":"previous"**,"state":"ON","state_1":"OFF"**,"switch_type":"momentary","switch_type_1":"momentary"}'

Obviously the light doesn't come up, you can hold the physical switch now to light it up but it's not the way it should work.

When you turn the light off and on only from via ZigBee or by physical switch, everything works as expected. Turning on via ZigBee restores the previous brightness from 0

//ZigBee:

---- Turn OFF ---
Info 2023-01-15 22:19:22MQTT publish: topic 'zigbee2mqtt/0xa4c138e22af6f6de', payload '{"brightness":152,"brightness_1":0,"level":953,"linkquality":45,"max_brightness":175,"min_brightness":40,"power_on_behavior":"previous","power_on_behavior_1":"previous","state":"OFF","state_1":"OFF","switch_type":"momentary","switch_type_1":"momentary"}'
Debug 2023-01-15 22:19:23Received Zigbee message from '0xa4c138e22af6f6de', type 'attributeReport', cluster 'genLevelCtrl', data '{"61440":0,"currentLevel":0}' from endpoint 1 with groupID 0
Info 2023-01-15 22:19:23MQTT publish: topic 'zigbee2mqtt/0xa4c138e22af6f6de', payload '**{"brightness":0,"brightness_1":0,**"level":953,"linkquality":45,"max_brightness":175,"min_brightness":40,"power_on_behavior":"previous","power_on_behavior_1":"previous","state":"OFF","state_1":"OFF","switch_type":"momentary","switch_type_1":"momentary"}'

--- Turn ON ---
Debug 2023-01-15 22:19:26Received MQTT message on 'zigbee2mqtt/0xa4c138e22af6f6de/set' with data '{"state":"ON"}'
Debug 2023-01-15 22:19:26Publishing 'set' 'state' to '0xa4c138e22af6f6de'
Info 2023-01-15 22:19:26MQTT publish: topic 'zigbee2mqtt/0xa4c138e22af6f6de', payload '{"brightness":152,"brightness_1":0,"level":953,"linkquality":42,"max_brightness":175,"min_brightness":40,"power_on_behavior":"previous","power_on_behavior_1":"previous","state":"ON","state_1":"OFF","switch_type":"momentary","switch_type_1":"momentary"}'
Debug 2023-01-15 22:19:26Received Zigbee message from '0xa4c138e22af6f6de', type 'attributeReport', cluster 'genLevelCtrl', data '{"61440":597,"currentLevel":152}' from endpoint 1 with groupID 0
Info 2023-01-15 22:19:26MQTT publish: topic 'zigbee2mqtt/0xa4c138e22af6f6de', payload '{"brightness":152,"brightness_1":0,"level":953,"linkquality":45,"max_brightness":175,"min_brightness":40,"power_on_behavior":"previous","power_on_behavior_1":"previous","state":"ON","state_1":"OFF","switch_type":"momentary","switch_type_1":"momentary"}'
Debug 2023-01-15 22:20:07Received Zigbee message from '0xa4c138e22af6f6de', type 'attributeReport', cluster 'genOnOff', data '{"onOff":1}' from endpoint 1 with groupID 0
Info 2023-01-15 22:20:07MQTT publish: topic 'zigbee2mqtt/0xa4c138e22af6f6de', payload '{"brightness":152,"brightness_1":0,"level":953,"linkquality":45,"max_brightness":175,"min_brightness":40,"power_on_behavior":"previous","power_on_behavior_1":"previous","state":"ON","state_1":"OFF","switch_type":"momentary","switch_type_1":"momentary"}'
Debug 2023-01-15 22:20:08Received Zigbee message from '0xa4c138e22af6f6de', type 'attributeReport', cluster 'genLevelCtrl', data '{"currentLevel":195}' from endpoint 1 with groupID 0
Info 2023-01-15 22:20:08MQTT publish: topic 'zigbee2mqtt/0xa4c138e22af6f6de', payload '{"brightness":195,"brightness_1":0,"level":953,"linkquality":48,"max_brightness":175,"min_brightness":40,"power_on_behavior":"previous","power_on_behavior_1":"previous","state":"ON","state_1":"OFF","switch_type":"momentary","switch_type_1":"momentary"}'

// Physical
--- Turn OFF ---
Info 2023-01-15 22:22:39MQTT publish: topic 'zigbee2mqtt/0xa4c138e22af6f6de', payload **'{"brightness":195,"brightness_1":0,"**level":953,"linkquality":54,"max_brightness":175,"min_brightness":40,"power_on_behavior":"previous","power_on_behavior_1":"previous",**"state":"OFF","state_1":"OFF"**,"switch_type":"momentary","switch_type_1":"momentary"}'

---Turn ON---
Debug 2023-01-15 22:22:42Received Zigbee message from '0xa4c138e22af6f6de', type 'attributeReport', cluster 'genOnOff', data '{"onOff":1}' from endpoint 1 with groupID 0
Info 2023-01-15 22:22:42MQTT publish: topic 'zigbee2mqtt/0xa4c138e22af6f6de', payload '{**"brightness":195,"brightness_1":0,"**level":953,"linkquality":42,"max_brightness":175,"min_brightness":40,"power_on_behavior":"previous","power_on_behavior_1":"previous","state":"ON","state_1":"OFF","switch_type":"momentary","switch_type_1":"momentary"}'

### What did you expect to happen?

I expect that physical and Z2M control can control the light exchangeable.

### How to reproduce it (minimal and precise)

1. Turn off the light via UI (HA or Z2M)
2. Try turning it back on using physical switch.

### Zigbee2MQTT version

1.29.2-dev commit: c927b4b and 1.29.1

### Adapter firmware version

20210708

### Adapter

Sonoff ZigBee 3.0 USB Dongle Plus [zStack3x0]

**Comment by Koenkk** [comment] 2023-01-16 17:02
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/15902

**Closed by Koenkk** 2023-01-16 17:02 UTC
Labels: problem
