### ISSUE TITLE
NOT Issue - but strange - "info: succesfully reenabled joining

### ISSUE THREAD

**Issue by vexter0944** [Koenkk/zigbee2mqtt#1585] opened 2019-05-30 12:57 UTC
# Bug Report
## What happened
I see this all the time in the logs - "info: succesfully reenabled joining" - is this normal?
## Debug Info
zigbee2mqtt version:
CC253X firmware version:

**Comment by davekr8** [comment] 2019-05-31 12:13
I was wondering about this messages, too. They seems to appear in less den 3-4 minutes interval.

**Comment by SebiGo** [comment] 2019-06-01 09:59
I think, this comment from zigbee.js:184 explains why:
`        // In zigbee 3.0 a network automatically closes after 254 seconds.
        // As a workaround, we enable joining again.
`
To disable the message, see the [configuration documentation](https://www.zigbee2mqtt.io/configuration/configuration.html):

> # Required: allow new devices to join.
> # WARNING: Disable this after all devices have been paired!
> permit_join: true

You can also disable joining through MQTT, see the [message structure description](https://www.zigbee2mqtt.io/information/mqtt_topics_and_message_structure.html) in chapter "zigbee2mqtt/bridge/config/permit_join".

It's generally a good idea to disable joining, unless you want to join your devices. Otherwise you might end up with your neighbors devices or someone might mess with your zigbee network :)

**Comment by Koenkk** [comment] 2019-06-03 08:02
@SebiGo that is indeed the reason, closing this as this is expected behaviour.

**Closed by Koenkk** 2019-06-03 08:02 UTC
