### ISSUE TITLE
TS011F_plug_3 stop working after 3hours on 1.30.4-1

### ISSUE THREAD

**Issue by smh51** [Koenkk/zigbee2mqtt#17569] opened 2023-05-05 08:46 UTC
### What happened?

After upgrade to 1.30.4-1 from 1.30.3-1, my 4 TS011F_plug_3 smart plug stop working. They froze and cannot be controlled anymore.
This happens after 3-4 hours after upgrade. Right after the upgrade, everything was working great.

edit :
by looking at the logs, plug stop transmitting and being actualised. They use to transmit every seconds. While being frozen, they transmitted once every 10 min. 

### What did you expect to happen?

To be able to contol the plugs

### How to reproduce it (minimal and precise)

Upgrade from 1.30.3-1 to 1.30.4-1 and wait 3-4 hours

### Zigbee2MQTT version

1.30.4 commit: unknown

### Adapter firmware version

7.1.1.0 build 273

### Adapter

skyconnect

**Comment by martinusgithubius** [comment] 2023-05-05 14:32
I have similar problems, with TS011F (_TZ3000_gvn91tmx), z2m version 1.30.4-1. The values of 'power' and 'current' remain unchanged after a certain period, especially when the device has been turned off. The recorded values during the 'on' period are still being displayed.

**Comment by smh51** [comment] 2023-05-05 15:02
maybe it's due also to new update 2023.5.

**Comment by Chronocento** [comment] 2023-05-06 11:03
> I have similar problems, with TS011F (_TZ3000_gvn91tmx), z2m version 1.30.4-1. The values of 'power' and 'current' remain unchanged after a certain period, especially when the device has been turned off. The recorded values during the 'on' period are still being displayed.

I'm having the exact same problem since the 1.30.4-1 update, with the exact same plug (TS011F _TZ3000_gvn91tmx).

The problem occured also with HASS 2023.4, no changes since the upgrade to 2023.5.

**Comment by Koenkk** [comment] 2023-05-06 13:36
Can you check if this is fixed with the latest dev branch? (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by smh51** [comment] 2023-05-06 14:16
For the next week i'll not be able to test it. If @Chronocento or @martinusgithubius  could test it, it would be great :)

**Comment by drifter75** [comment] 2023-05-07 06:44
> Can you check if this is fixed with the latest dev branch? (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

had the same isse with 2 of my TS011F_plug_1 (_TZ3000_gvn91tmx), where power was reporting the last value instead of 0W as the appliance is switched of. noticed this after upgrading Z2M to 1.30.4.

After upgrading to latest-dev it's back to 0W, so seems like it's fixed.

**Comment by martinusgithubius** [comment] 2023-05-09 17:22
Having installed the edge version tonight, I am now commencing its testing, and at this stage, it seems to hold great promise. Thank you, Koenkk, for your valuable support.

**Comment by martinusgithubius** [comment] 2023-05-10 18:39
after 24h  I can show a 'thumbs up'

**Comment by Koenkk** [comment] 2023-05-11 14:53
Thanks than I will close this (it is a duplicate of #16709)

**Closed by Koenkk** 2023-05-11 14:53 UTC
Labels: problem
