### ISSUE TITLE
VOCKQJK11LM measurement 'ºC' which is not a valid unit for the device class ('temperature')

### ISSUE THREAD

**Issue by BlastyCZ** [Koenkk/zigbee2mqtt#20612] opened 2024-01-06 11:58 UTC
### What happened?

There is difference between units "ºC" and "°C"

### What did you expect to happen?

Correct the unit of measurement 

### Zigbee2MQTT version

1.35.0-1

### Adapter firmware version

20230507

### Adapter

SMLIGHT SLZB-06

**Comment by Koenkk** [comment] 2024-01-06 12:01
Duplicate of https://github.com/Koenkk/zigbee-herdsman-converters/issues/6808

**Closed by Koenkk** 2024-01-06 12:01 UTC
Labels: problem
