### ISSUE TITLE
Hue bulb OTA update failed (self-signed certificate in certificate chain)

### ISSUE THREAD

**Issue by eekamouze** [Koenkk/zigbee2mqtt#20609] opened 2024-01-06 10:08 UTC
### What happened?

An OTA update is available for a Hue bulb but when launching the firmware update I get this error:
`Update of 'my_light_name' failed (self-signed certificate in certificate chain)`

Don't know if it fails with all Hue devices as others are up to date.
My bulb:
Philips 8718696449691
Hue White A60 Single bulb E27/B22
firmware version 1.101.2

### What did you expect to happen?

Update should start as expected. I've updated the same type of bulb a week ago with no issue, but with previous z2m version (1.34.0)

### Zigbee2MQTT version

1.35.0

### Adapter firmware version

6.10.3.0 build 297

### Adapter

Sonoff ZBDongle-E (EFR32MG21)

**Comment by Koenkk** [comment] 2024-01-06 10:34
Duplicate of https://github.com/Koenkk/zigbee-OTA/issues/420

**Closed by Koenkk** 2024-01-06 10:34 UTC
Labels: problem
