### ISSUE TITLE
Binding bug? Change in binding behaviour (left arrow not working anymore)

### ISSUE THREAD

**Issue by jd1900** [Koenkk/zigbee2mqtt#3485] opened 2020-05-03 20:06 UTC
# Bug Report
## What happened
I don't get it, but the behaviour in a device bound to another one has changed. Something that shouldn't happen as zigbee2mqtt shouldn't interfere in here. 

The Ikea E1810 (https://www.zigbee2mqtt.io/devices/E1524_E1810.html) used to work fine when bound to a group with a Ikea bulb. Using the arrow left/right I could control the temperature of the Ikea bulb. However, it doesn't work anymore. It does nothing now, only the toggle and the intensity buttons work. It doesn't work anymore. In the logs, I can see the left/right arrow events, but nothing happens.

I have unbound from the group, created a new group and bind the remote to the new group with just the light, and similar things. However..., nothing. It doesn't change the temperature anymore.

Can this be a bug?

## What did you expect to happen
To change temperature.

## How to reproduce it (minimal and precise)
Press left/right arrow in the E1810 bound to a group with a Ikea bulb. 
It doesn't change the temperature.

## Debug Info
Zigbee2mqtt version: 1.13.0
Adapter hardware: CC26X2R1 / CC1352P-2
Adapter firmware version: CC26X2R1_20200417.zip

**Comment by Koenkk** [comment] 2020-05-04 12:37
Duplicate of #1232

**Closed by Koenkk** 2020-05-04 12:37 UTC
