### ISSUE TITLE
[New device support]: MFCZQ12LM Aqara Cube T1 Pro

### ISSUE THREAD

**Issue by ybizeul** [Koenkk/zigbee2mqtt#15884] opened 2023-01-02 10:51 UTC
### Link

https://www.aqara.com/eu/product/cube-t1-pro

### Database entry

{"id":76,"type":"EndDevice","ieeeAddr":"0x54ef44100062d5cc","nwkAddr":27372,"manufId":4447,"manufName":"LUMI","powerSource":"Battery","modelId":"lumi.remote.cagl02","epList":[1,2,3],"endpoints":{"1":{"profId":260,"epId":1,"devId":259,"inClusterList":[0,3,1,18,6],"outClusterList":[0,3,25],"clusters":{"genBasic":{"attributes":{"modelId":"lumi.remote.cagl02","appVersion":25}},"aqaraOpple":{"attributes":{"247":{"type":"Buffer","data":[1,33,225,11,3,40,25,4,33,168,19,5,33,18,0,6,36,39,1,0,0,0,8,33,25,1,10,33,235,162,12,32,1,102,32,3,103,32,1,104,33,168,0,151,33,0,0,152,33,0,0,153,33,0,0,154,33,4,0,155,32,1]}}},"genPowerCfg":{"attributes":{"batteryVoltage":30}}},"binds":[],"configuredReportings":[],"meta":{}},"2":{"profId":260,"epId":2,"devId":259,"inClusterList":[18],"outClusterList":[18],"clusters":{"genMultistateInput":{"attributes":{"presentValue":1028}},"aqaraOpple":{"attributes":{"329":4}}},"binds":[],"configuredReportings":[],"meta":{}},"3":{"profId":260,"epId":3,"devId":259,"inClusterList":[12],"outClusterList":[12],"clusters":{"genAnalogInput":{"attributes":{"267":500,"329":2,"presentValue":75.95999908447266}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":25,"stackVersion":2,"hwVersion":1,"dateCode":"20220602","swBuildId":"2019\u0000www.","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1672655076725,"defaultSendRequestWhen":"immediate"}

### Comments

It doesn't seem using the existing converters for other versions of the cube works. I'm getting some data but they don't really make sense.
For example, face change message is :
```
Zigbee2MQTT:debug 2023-01-02 11:33:36: Received Zigbee message from 'cube1', type 'attributeReport', cluster 'genMultistateInput', data '{"presentValue":1028}' from endpoint 2 with groupID 0
```
`presentedValue` is from 1024 (face 1) to 1029 (face 6)

I couldn't get data on "tap" but maybe the device mode needs to be set first.

Device rotation looks like this :

```
Zigbee2MQTT:debug 2023-01-02 11:49:46: Received Zigbee message from 'cube1', type 'attributeReport', cluster 'genAnalogInput', data '{"267":500,"329":4,"presentValue":61.619998931884766}' from endpoint 3 with groupID 0
Zigbee2MQTT:debug 2023-01-02 11:49:46: Received Zigbee message from 'cube1', type 'attributeReport', cluster 'aqaraOpple', data '{"329":4}' from endpoint 2 with groupID 0
```

### External converter

```shell
const fzlocal = {
    MFCZQ12LM_action_multistate : {
        cluster: 'genMultistateInput',
        type: ['attributeReport', 'readResponse'],
        convert: (model, msg, publish, options, meta) => {
            const value = msg.data['presentValue'];
            let result = null;

            if (value >= 1024) {
                result = {
                    action: 'flip90',
                    action_side: value - 1023
                }
            }

            return result ? result : null;
        },
   },
}
```

**Comment by Koenkk** [comment] 2023-01-03 09:13
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/15652

**Closed by Koenkk** 2023-01-03 09:13 UTC
Labels: new device support
