### ISSUE TITLE
Upgrading to 1.19 fails

### ISSUE THREAD

**Issue by atxbyea** [Koenkk/zigbee2mqtt#7829] opened 2021-06-19 07:59 UTC
# Bug Report
## What did you do 
Upgraded from 1.18.3 to 1.19.1

## What did you expect to happen
A working update as usual

## How to reproduce it (minimal and precise)
Upgrade to 1.19 branch
Revert to 1.18.3 and no problems

## Debug Info
Zigbee2MQTT version:
Adapter hardware: zzh 
Adapter firmware version:  Coordinator firmware version: '{"meta":{"maintrel":1,"majorrel":2,"minorrel":7,"product":1,"revision":20210120,"transportre
v":2},"type":"zStack3x0"}'

zigbee2mqtt    | Zigbee2MQTT:error 2021-06-19 09:51:23: Configuration is not consistent with adapter state/backup!
zigbee2mqtt    | Zigbee2MQTT:error 2021-06-19 09:51:23: - PAN ID: configured=6754, adapter=6755
zigbee2mqtt    | Zigbee2MQTT:error 2021-06-19 09:51:23: - Extended PAN ID: configured=00124b001ca60b3c, adapter=dddddddddddddddd

**Comment by Koenkk** [comment] 2021-06-20 18:36
Duplicate of #7664 , check https://github.com/Koenkk/zigbee2mqtt/issues/7664#issuecomment-853267958 for the solution.

**Closed by Koenkk** 2021-06-20 18:36 UTC
