### ISSUE TITLE
HASSIO shows updates available for zigbee2mqtt devices: latest version: -1

### ISSUE THREAD

**Issue by DoerakkerHA** [Koenkk/zigbee2mqtt#20852] opened 2024-01-17 11:14 UTC
### What happened?

suddenly a number of lights:
INNR installed version 268768615 Latest -1 version Type RB 245
INNR installed version 587207953 Latest 604050705 version Type RB 251 C
IKEA installed version 65572 Latest version -1 Type E2001/E2002

### What did you expect to happen?

either not show update available or fix OTA as described in previous issue

### How to reproduce it (minimal and precise)

open updates in hassio settings (showing 8) 

### Zigbee2MQTT version

 1.35.1

### Adapter firmware version

20211217

### Adapter

ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus

### Setup

add-on

**Comment by Koenkk** [comment] 2024-01-17 19:35
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/20658

**Closed by Koenkk** 2024-01-17 19:35 UTC
Labels: problem
