### ISSUE TITLE
Candeo C202 Dimmer not compatible

### ISSUE THREAD

**Issue by viciovb** [Koenkk/zigbee2mqtt#16613] opened 2023-02-10 14:32 UTC
### What happened?

The Candeo C202 dimmer should be compatible according to https://www.zigbee2mqtt.io/devices/HK-DIM-A.html but when I try to pair it, I get an error that the device is not compatible. 

### What did you expect to happen?

Pair the Candeo C202 dimmer

### Zigbee2MQTT version

1.30.1-1 and Edge

### Adapter firmware version

20220531

### Adapter

Candeo Zigbee Dimmer

### Debug log

warn  2023-02-10 14:31:21: Received message from unsupported device with Zigbee model 'Candeo Zigbee Dimmer' and manufacturer name 'Candeo'
warn  2023-02-10 14:31:21: Please see: https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html

**Comment by Koenkk** [comment] 2023-02-10 16:05
Could you check if the issue is fixed with the following external converter: 

```js
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const ota = require('zigbee-herdsman-converters/lib/ota');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const utils = require('zigbee-herdsman-converters/lib/utils');
const globalStore = require('zigbee-herdsman-converters/lib/store');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['HK-DIM-A', 'Candeo Zigbee Dimmer'],
    model: 'HK-DIM-A',
    vendor: 'Candeo',
    description: 'Zigbee LED dimmer smart switch',
    extend: extend.light_onoff_brightness({noConfigure: true, disableEffect: true}),
    configure: async (device, coordinatorEndpoint, logger) => {
        await extend.light_onoff_brightness().configure(device, coordinatorEndpoint, logger);
        const endpoint = device.getEndpoint(1);
        await reporting.bind(endpoint, coordinatorEndpoint, ['genOnOff', 'genLevelCtrl']);
        await reporting.onOff(endpoint);

        // The default reporting from the Candeo dimmer can result in a lot of Zigbee traffic
        // to the extent that reported brighness values can arrive at the endpoint out of order
        // giving the appearance that the values are jumping around.
        // Limit the reporting to once a second to give a smoother reporting of brightness.
        await reporting.brightness(endpoint, {min: 1});
    },
};

module.exports = definition;

```

- save this as file next to `configuration.yaml` as `ext_converter.js`
- add it to `configuration.yaml`:
```yaml
external_converters:
  - ext_converter.js
```
- start z2m, check if issue is fixed

**Comment by viciovb** [comment] 2023-02-10 16:17
With this 

`const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const ota = require('zigbee-herdsman-converters/lib/ota');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const utils = require('zigbee-herdsman-converters/lib/utils');
const globalStore = require('zigbee-herdsman-converters/lib/store');
const e = exposes.presets;
const ea = exposes.access;

module.exports = [
    {
        zigbeeModel: ['HK-DIM-A'],
        model: 'HK-DIM-A',
        vendor: 'Candeo',
        description: 'Zigbee LED dimmer smart switch',
        extend: extend.light_onoff_brightness({noConfigure: true, disableEffect: true}),
        configure: async (device, coordinatorEndpoint, logger) => {
            await extend.light_onoff_brightness().configure(device, coordinatorEndpoint, logger);
            const endpoint = device.getEndpoint(1);
            await reporting.bind(endpoint, coordinatorEndpoint, ['genOnOff', 'genLevelCtrl']);
            await reporting.onOff(endpoint);

            // The default reporting from the Candeo dimmer can result in a lot of Zigbee traffic
            // to the extent that reported brighness values can arrive at the endpoint out of order
            // giving the appearance that the values are jumping around.
            // Limit the reporting to once a second to give a smoother reporting of brightness.
            await reporting.brightness(endpoint, {min: 1});
        },
    }
];`

Z2M starts but I can't still add the C202 candeo dimmer.

**Comment by Koenkk** [comment] 2023-02-10 16:23
`zigbeeModel: ['HK-DIM-A'],` should be ` zigbeeModel: ['HK-DIM-A', 'Candeo Zigbee Dimmer'],`

**Comment by viciovb** [comment] 2023-02-10 16:28
I had to use 

`        zigbeeModel: ['Candeo Zigbee Dimmer'],
        model: 'Candeo Zigbee Dimmer',`

and it's now working. Thank you so much for your help

**Comment by Koenkk** [comment] 2023-02-12 08:20
Great, added the device for out-of-the-box support!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Closed by Koenkk** 2023-02-12 08:20 UTC
Labels: problem
