### ISSUE TITLE
Warnings to repair mames for 2024.2.0

### ISSUE THREAD

**Issue by Mab306** [Koenkk/zigbee2mqtt#18526] opened 2023-08-04 21:20 UTC
### What happened?

After Update homeassistant core now i have Warnings with same name as entity....
I attched a pic. What i should do or could some one help?
![Screenshot_20230804_225328_Home Assistant](https://github.com/Koenkk/zigbee2mqtt/assets/114089256/fdbc8b77-73c5-4987-9293-59b9facd6670)

### Zigbee2MQTT version

1.32.2

### Adapter firmware version

7.1.4.0 build 389

### Adapter

Ezsp v9

**Comment by fumantsu** [comment] 2023-08-04 21:52
Little search doesn't hurt. https://community.home-assistant.io/t/psa-mqtt-name-changes-in-2023-8/598099

**Comment by Koenkk** [comment] 2023-08-05 06:19
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/18445

**Closed by Koenkk** 2023-08-05 06:19 UTC
Labels: problem
