### ISSUE TITLE
zh:ember: Delivery of BROADCAST failed for "65533" on fw 7.4.1, 7.4.2, and 7.43 

### ISSUE THREAD

**Issue by lennon101** [Koenkk/zigbee2mqtt#22816] opened 2024-05-29 00:53 UTC
### What happened?

- Journal of steps
	- upgraded zigbee2mqtt to 1.37
	- received the `zh:ezsp: Deprecated driver 'ezsp' currently in use, 'ember' will become the officially supported EmberZNet driver in next release. If using Zigbee2MQTT see https://github.com/Koenkk/zigbee2mqtt/discussions/21462`
	- changed adapter: ezsp to adapter: ember and restarted
	- got an error that my coordinator was not on EZSP
	- upgraded my coordinator firmware to FW ncp-uart-hw-v7.4.2.0-zbdonglee-230400
		- using the steps outlined here: https://github.com/Koenkk/zigbee2mqtt/issues/22398#issuecomment-2094674395
		- link to fw files here: https://github.com/darkxst/silabs-firmware-builder/tree/4.4.3/firmware_builds/zbdonglee
	- changed config in zigbee2mqtt to `adapter: ember` + `rtscts: false`
	- restarted zigbee2mqtt and I can open the webpage but
		- now at startup I get the message `zh:ember: Delivery of BROADCAST failed for "65533" `
		- the coordinator can only find the non-router devices
		- all powered devices are missing from the network map
		- switching back to `adapter: ezsp` doesn't work either as I then get the error `zh:controller:greenpower: Received undefined command from '0'`.
	- Found this closed issue saying reporting exactly the same issue saying that 7.4.2 was the problem:
		- https://github.com/Koenkk/zigbee2mqtt/issues/22469
	- Downgraded zigbee coordinator fw to 7.4.1
		- using: `universal-silabs-flasher --device /dev/ttyACM0 flash --firmware ncp-uart-hw-v7.4.1.0-zbdonglee-115200.gbl --force`
	- got the same error as before: `zh:ember: Delivery of BROADCAST failed for "65533" `
	- upgraded zigbee coordinator fw to 7.4.3 using: `universal-silabs-flasher --device /dev/ttyACM0 flash --firmware ncp-uart-hw-v7.4.3.0-zbdonglee-115200.gbl --force`
	- got the same error as before: `zh:ember: Delivery of BROADCAST failed for "65533" `

zigbee2mqtt docker compose: 

```
version: '3.8'
services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:1.37.1
    restart: unless-stopped
    volumes:
      - /home/<usernam>/docker/zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8089:8080
    environment:
      - TZ=Australia/Brisbane
    devices:
      - /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20230220095219-if00:/dev/ttyACM0
    group_add:
      - dialout
    user: hidden:hidden
    privileged: 'true'

```

zigbee2mqtt configuration.yaml

```
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://hidden ip and port
  user: hidden
  password: hidden
serial:
  port: /dev/ttyACM0
  adapter: ember
  baudrate: 115200
  rtscts: false
frontend: true
availability: true
devices:
  <removed but you get the idea>
advanced:
  log_syslog:
    app_name: Zigbee2MQTT
    eol: /n
    host: localhost
    localhost: localhost
    path: /dev/log
    pid: process.pid
    port: 514
    protocol: udp4
    type: '5424'
  last_seen: ISO_8601_local
  log_level: error

```

### Zigbee2MQTT version

1.37.1

### Adapter firmware version

ncp-uart-hw-v7.4.3.0-zbdonglee-115200

### Adapter

zbdongle-e

### Setup

docker container

### Debug log

[log.log](https://github.com/Koenkk/zigbee2mqtt/files/15477318/log.log)

**Comment by lennon101** [comment] 2024-05-29 02:28
Update: 

- rolled back to zigbee2mqtt **server** version`1.36.1` and changed the settings in the configuation.yaml
	-
	  ```
	  serial:
	    port: /dev/ttyACM0
	    adapter: ezsp
	    baudrate: 115200
	    rtscts: false
	  ```
- Network returned to a completely working state (all devices have returned to network and all routers have also returned)
	- no errors in the log either
- ## Final state of working system is:
	- Zigbee2mqtt Server Version: `1.36.1` running docker container
	- Zigbee2mqtt coordinator version: `7.4.3`
	- configuration.yaml settings specific to fixing this issue:
		-
		  ```
		  serial:
		    adapter: ezsp
		  ```

**Comment by Nerivec** [comment] 2024-06-01 20:53
This is already being discussed in https://github.com/Koenkk/zigbee2mqtt/issues/22453
Unfortunately, there appears to be a half dozen or so different "fixes" from different people, all pointing to nowhere specific at the moment... And we have yet to be able to reproduce it in this manner, making it that much harder to dissect...

**Comment by lennon101** [comment] 2024-06-03 04:17
Apologies for the duplication! I did a search but didn't find that thread. I appreciate any/all efforts you are all doing to get this fixed. I'll endevour to keep looking it on my end and report back with any findings. Thanks!

**Comment by kwetnico** [comment] 2024-06-15 21:00
Hello
I have the same problem..
Sonoff with firmware 7.4.2

**Comment by Nerivec** [comment] 2024-06-15 21:48
Closing this thread in favor of the other one mentioned above to avoid feedback in multiple places.

**Closed by Nerivec** 2024-06-15 21:48 UTC
Labels: problem

**Comment by clertonraf** [comment] 2024-08-08 07:26
Just to comment that I had the same configuration and the same problem. I went through https://github.com/Koenkk/zigbee2mqtt/issues/22453 and tried a bunch of things, but this proposed solution solved my issues.

**Comment by lennon101** [comment] 2024-08-27 23:19
> but this proposed solution solved my issues.

What proposed solution are you referring to?

**Comment by Nerivec** [comment] 2024-08-28 08:23
As mentioned in the other thread, issue should be solved in September release (current dev branch).

**Comment by lennon101** [comment] 2024-08-28 10:10
> As mentioned in the other thread, issue should be solved in September release (current dev branch).

Had a good dig around "the other thread" but couldn't find where anyone mentions the fix. Could you provide a link to a specific post? I'm glad to hear that the issue is getting fixed!

**Comment by Nerivec** [comment] 2024-08-30 09:38
https://github.com/Koenkk/zigbee2mqtt/issues/22453#issuecomment-2294108058
https://github.com/Koenkk/zigbee2mqtt/issues/22453#issuecomment-2295280123

**Comment by jespervdw** [comment] 2024-12-21 12:41
Had the same problem. Broadcast error every 10min. Reintalling Z2M and updating firmware didn't work.
For now, the error seems not to return since I don't allow new devices to join. 

`Zigbee2MQTT versie
[1.42.0](https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.42.0) commit: [bc6eccf](https://github.com/Koenkk/zigbee2mqtt/commit/bc6eccf)
Coördinator type
EmberZNet
Coordinator revisie
7.4.5 [GA]
Coordinator IEEE adres
0xe0798dfffecfaeef
Versie frontend
0.7.6
zigbee_herdsman_converters_version
20.58.0
zigbee_herdsman_version
2.1.9`
