### ISSUE TITLE
TuYa TS0042  _TZ3000_kt7obmnn stopped working after Zigbee2mqtt update

### ISSUE THREAD

**Issue by SmolikOne** [Koenkk/zigbee2mqtt#21196] opened 2024-02-03 16:12 UTC
### What happened?

All TuYa TS0042_TZ3000_kt7obmnn stopped working after Zigbee2mqtt 1.35.2-1 update. All my four TuYa TS0042 switches are visible, can be added to Z2M and are recognized, but automation is not working anymore. Pressing switches button is not tuning on the light (light can be still switched on or off via HA) . Deleting the automation and creating new one is not resolving the issue, either deleting this device from Z2M and re-adding it. Before latest Z2M update, it was working. 

### What did you expect to happen?

Restor functionality of TuYa TS0042_TZ3000_kt7obmnn switches. 

### Zigbee2MQTT version

1.35.2-1

### Adapter firmware version

20221226

### Adapter

Sonoff Dongle P

### Setup

Add-on on Home Assistant running on Raspberry Pi 4B

**Comment by NReiher** [comment] 2024-02-03 18:26
Having the exact same issue. I was trialing the same model with my Z2M setup. A few days ago the switch stopped working with the automations I have set up with it. Removed and re-paired it MANY times and every time it fails to add correctly/register the actions properly. It has worked perfectly fine for 3 months. No other devices (switches, bulbs, plugs. sensors) seem to be effected.

I still had ZHA installed/configured so I added it to that config and verified that the switch still actually works signal wise. Something with Z2M just seemed to stop working with this device.

Verified add on version "Current version: 1.35.2-1". Adapter is Sonoff_Zigbee_3.0_USB_Dongle_Plus. Firmware version - 20230507. Setup is a VM inside of a Proxmox install.

If more information/logs or whatever would be helpful to address this problem please let me know and I can try to assist.

**Comment by vinodmishra** [comment] 2024-02-03 18:29
Exact same thing happened to me. Could be related to this PR 
https://github.com/Koenkk/zigbee-herdsman-converters/pull/6944

**Comment by Koenkk** [comment] 2024-02-04 07:39
Can you provide the debug log when pressing the button?

See [this](https://www.zigbee2mqtt.io/guide/usage/debug.html) on how to enable debug logging.

CC @kiler129

**Comment by kiler129** [comment] 2024-02-04 07:44
@NReiher @vinodmishra debug log will be useful as @Koenkk mentioned; also can you post a screenshot how your switch appears in Z2M?

It's possible that the fingerprint matched too widely and this switch has multiple incompatible firmwares. Wouldn't be the first time for TuYa for me :D Mine seems to be working.

**Comment by algar42** [comment] 2024-02-04 10:16
Not sure, but probably it is connected with some changes to actions in 1.35.2, 
Previously my TS0041 switch gave me the "sinlgle" action, but starting from 1.35.2 I see the "1_single" instead of just "single" as it was before. 
Probably the same thing happened with some other tuya switches?

**Comment by vinodmishra** [comment] 2024-02-04 10:54
@Koenkk  This is what I get
debug 2024-02-04 10:50:58Received Zigbee message from '0xa4c138d8861f1089', type 'raw', cluster 'genOnOff', data '{"data":[1,1,253,0],"type":"Buffer"}' from endpoint 1 with groupID 0
debug 2024-02-04 10:50:58No converter available for 'LKWSZ211' with cluster 'genOnOff' and type 'raw' and data '{"data":[1,1,253,0],"type":"Buffer"}'

For the second button the endpoint is 2

**Comment by Koenkk** [comment] 2024-02-04 10:56
@kiler129 [your commit](https://github.com/Koenkk/zigbee-herdsman-converters/commit/bb2ffdc861ef9146159a56f625c76d0016519488) includes both `TS0021` and `TS0042`, I can imagine that both devices send different data structures, did you test for both?

**Comment by BitWuehler** [comment] 2024-02-04 13:42
@Koenkk `TuYa IH-K663` also swithced from "single" and "double" to "1_single" and "1_double". It did never show the button in home assistant (only Battery stats) besides that, so i did use the mqtt payloads for detecting button press and recognised it yesterday.

**Comment by vinodmishra** [comment] 2024-02-04 15:34
@Koenkk @kiler129 
Reverting back to 1.35.1 container  image for Zigbee2MQTT fixes this for me. This is the model it is recognized as. Looks nothing like the picture but at least it works!
![image](https://github.com/Koenkk/zigbee2

**Comment by NReiher** [comment] 2024-02-04 19:09
@kiler129 @Koenkk 

Thanks guys for taking a look at this! Turned on Debug and this is what I got while pressing the buttons.

Debug 2024-02-04 13:59:49Received Zigbee message from '0xa4c13855b3744e54', type 'raw', cluster 'genOnOff', data '{"data":[1,2,253,0],"type":"Buffer"}' from endpoint 1 with groupID 0
Debug 2024-02-04 13:59:51Received Zigbee message from '0xa4c13855b3744e54', type 'raw', cluster 'genOnOff', data '{"data":[1,3,253,0],"type":"Buffer"}' from endpoint 2 with groupID 0
Debug 2024-02-04 13:59:52Received Zigbee message from '0xa4c13855b3744e54', type 'raw', cluster 'genOnOff', data '{"data":[1,4,253,0],"type":"Buffer"}' from endpoint 1 with groupID 0
Debug 2024-02-04 13:59:54Received Zigbee message from '0xa4c13855b3744e54', type 'raw', cluster 'genOnOff', data '{"data":[1,5,253,0],"type":"Buffer"}' from endpoint 2 with groupID 0

![image](https://github.com/Koenkk/zigbee2mqtt/assets/53537686/0d427e61-34ba-4551-a534-9c44fb838739)

I don't have a very recent backup (Feb one was after the update, next recent one is in early January so I'd rather not go back that far as other changes were made since then). If necessary I can roll back for testing purposes but I'd like to avoid that if possible. If there's anything else you guys need please let me know. (Appreciate the help dummy proofing as this is my first time bug reporting).

**Comment by Dinth** [comment] 2024-02-04 19:29
Im also affected. 
Will the new action names stay (then it would be good to update the documentation), or is this going to be changed back, as im not sure if i should edit all the automations

**Comment by Koenkk** [comment] 2024-02-04 19:56
Pushed a fix!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

**Comment by SmolikOne** [comment] 2024-02-04 21:26
Thank you very much for your quick support. I will still need to wait until next stable Z2M release, as I was finally able to stabilize my zigbee network (described my issues in 2023 test firmware release topic) and I don't want to mess around :)

**Comment by thatso** [comment] 2024-02-05 17:04
I can confirm what @algar42 already said: this also affects Tuya TS0041 (manufacturer name _TZ3000_axpdxqgu). Currently, it reports `1_single` whereas before it was just `single`.

**Comment by robertalexa** [comment] 2024-02-06 18:41
Also confirming `TS0041` `_TZ3000_tk3s5tyg`

```
Info 2024-02-06 18:33:17MQTT publish: topic 'homeassistant/device_automation/0x84fd27fffe849a8e/action_1_hold/config', payload '{"automation_type":"trigger","device":{"identifiers":["zigbee2mqtt_0x84fd27fffe849a8e"],"manufacturer":"TuYa","model":"Wireless switch with 1 button (TS0041)","name":"Hallway Secondary Light Switch","via_device":"zigbee2mqtt_bridge_0x00124b0021b953c1"},"origin":{"name":"Zigbee2MQTT","sw":"1.35.2","url":"https://www.zigbee2mqtt.io"},"payload":"1_hold","subtype":"1_hold","topic":"zigbee2mqtt/Hallway Secondary Light Switch/action","type":"action"}'
Info 2024-02-06 18:33:17MQTT publish: topic 'zigbee2mqtt/Hallway Secondary Light Switch/action', payload '1_hold'
```

Same applies for the other possible actions `1_double` and `1_hold`

@Koenkk not sure if your commit will also fix it for this device?

**Comment by Koenkk** [comment] 2024-02-06 19:30
@robertalexa yes

**Comment by maryjam01** [comment] 2024-02-09 07:37
> ### What happened?
> All TuYa TS0042_TZ3000_kt7obmnn stopped working after Zigbee2mqtt 1.35.2-1 update. All my four TuYa TS0042 switches are visible, can be added to Z2M and are recognized, but automation is not working anymore. Pressing switches button is not tuning on the light (light can be still switched on or off via HA) . Deleting the automation and creating new one is not resolving the issue, either deleting this device from Z2M and re-adding it. Before latest Z2M update, it was working.
> 
> ### What did you expect to happen?
> Restor functionality of TuYa TS0042_TZ3000_kt7obmnn switches.
> 
> ### How to reproduce it (minimal and precise)
> _No response_
> 
> ### Zigbee2MQTT version
> 1.35.2-1
> 
> ### Adapter firmware version
> 20221226
> 
> ### Adapter
> Sonoff Dongle P
> 
> ### Setup
> Add-on on Home Assistant running on Raspberry Pi 4B
> 
> ### Debug log
> _No response_

Hi,
I have the same issue on my TS004F (ESW-OZAA-EU). Exactly the behavior in the desription above.
The [1.35.3](https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.35.3) doesn´t fix it for my case.

Or are there any other suggestions?

Regards Mary

**Comment by NReiher** [comment] 2024-02-09 15:05
Updated to 1.35.3-1, re-paired the switch and it is working properly now. Thanks so much for the help!

**Comment by ihor-admin** [comment] 2024-02-09 21:30
The buttons work again, Thanks

**Closed** 2024-02-10 21:01 UTC
Labels: problem
