### ISSUE TITLE
Buttons on 2 gang wall switch are switching on and off at same time

### ISSUE THREAD

**Issue by hsimm** [Koenkk/zigbee2mqtt#13749] opened 2022-08-29 10:54 UTC
### What happened?

In my 2-gang wall switch, from zigbee2mqtt ui, triggering 'on' of 1 button triggers the 'on' state of 2nd button and vice versa.
When pressing a button physically, the state of the other button does not change.

https://user-images.githubusercontent.com/1507531/187185275-668a4352-1624-4b2f-8998-a5f943dabd06.mp4

**Details of wall switch below:**
Friendly name: 0xa4c138de59e7cb48
Description: 
Last seen: N/A
Availability: [Disabled](https://www.zigbee2mqtt.io/guide/configuration/device-availability.html#availability-advanced-configuration)
Device type: EndDevice
Zigbee Model: TS0012
Zigbee Manufacturer: _TZ3000_18ejxno0
Description: Smart light switch - 2 gang
Support status: Supported

IEEE Address: 0xa4c138de59e7cb48
Network address: 0xA677
Manufacturer: [TuYa](https://www.zigbee2mqtt.io/supported-devices/#v=TuYa)
Model: [TS0012](https://www.zigbee2mqtt.io/devices/TS0012.html#tuya-ts0012)
Power: 
Interview completed: True

### What did you expect to happen?

Triggering the state of 1 button does not affect the state of 2nd button

### How to reproduce it (minimal and precise)

1. Go to zigbee2mqtt ui > **Devices**
2. **Permit all** to pair 2 gang wall switch
3. After pairing and interviewing is completed, go to **Dashboard**
5. From Dashboard, on any button of recent paired 2 gang wall switch, select 'on'

### Zigbee2MQTT version

 1.27.0

### Adapter firmware version

 6.10.3.0 build 297

### Adapter

 EZSP v8

### Debug log

Debug 2022-08-29 18:46:16Received MQTT message on 'zigbee2mqtt/0xa4c138de59e7cb48/set' with data '{"state_left":"ON"}'
Debug 2022-08-29 18:46:16Publishing 'set' 'state' to '0xa4c138de59e7cb48'
Info 2022-08-29 18:46:16MQTT publish: topic 'zigbee2mqtt/0xa4c138de59e7cb48', payload '{"linkquality":200,"state_left":"ON","state_right":"OFF"}'
Debug 2022-08-29 18:46:16Received Zigbee message from '0xa4c138de59e7cb48', type 'attributeReport', cluster 'genOnOff', data '{"onOff":1}' from endpoint 1 with groupID 0
Info 2022-08-29 18:46:16MQTT publish: topic 'zigbee2mqtt/0xa4c138de59e7cb48', payload '{"linkquality":200,"state_left":"ON","state_right":"OFF"}'
Debug 2022-08-29 18:46:17Received Zigbee message from '0xa4c138de59e7cb48', type 'attributeReport', cluster 'genOnOff', data '{"onOff":1}' from endpoint 2 with groupID 0
Info 2022-08-29 18:46:17MQTT publish: topic 'zigbee2mqtt/0xa4c138de59e7cb48', payload '{"linkquality":200,"state_left":"ON","state_right":"ON"}'
Debug 2022-08-29 18:46:18Received MQTT message on 'zigbee2mqtt/0xa4c138de59e7cb48/set' with data '{"state_left":"OFF"}'
Debug 2022-08-29 18:46:18Publishing 'set' 'state' to '0xa4c138de59e7cb48'
Info 2022-08-29 18:46:18MQTT publish: topic 'zigbee2mqtt/0xa4c138de59e7cb48', payload '{"linkquality":200,"state_left":"OFF","state_right":"ON"}'
Debug 2022-08-29 18:46:18Received Zigbee message from '0xa4c138de59e7cb48', type 'attributeReport', cluster 'genOnOff', data '{"onOff":0}' from endpoint 1 with groupID 0
Info 2022-08-29 18:46:18MQTT publish: topic 'zigbee2mqtt/0xa4c138de59e7cb48', payload '{"linkquality":200,"state_left":"OFF","state_right":"ON"}'
Debug 2022-08-29 18:46:18Received Zigbee message from '0xa4c138de59e7cb48', type 'attributeReport', cluster 'genOnOff', data '{"onOff":0}' from endpoint 2 with groupID 0
Info 2022-08-29 18:46:18MQTT publish: topic 'zigbee2mqtt/0xa4c138de59e7cb48', payload '{"linkquality":200,"state_left":"OFF","state_right":"OFF"}'
Debug 2022-08-29 18:46:19Received MQTT message on 'zigbee2mqtt/0xa4c138de59e7cb48/set' with data '{"state_right":"ON"}'
Debug 2022-08-29 18:46:19Publishing 'set' 'state' to '0xa4c138de59e7cb48'
Info 2022-08-29 18:46:19MQTT publish: topic 'zigbee2mqtt/0xa4c138de59e7cb48', payload '{"linkquality":200,"state_left":"OFF","state_right":"ON"}'
Debug 2022-08-29 18:46:19Received Zigbee message from '0xa4c138de59e7cb48', type 'attributeReport', cluster 'genOnOff', data '{"onOff":1}' from endpoint 1 with groupID 0
Info 2022-08-29 18:46:19MQTT publish: topic 'zigbee2mqtt/0xa4c138de59e7cb48', payload '{"linkquality":200,"state_left":"ON","state_right":"ON"}'
Debug 2022-08-29 18:46:20Received Zigbee message from '0xa4c138de59e7cb48', type 'attributeReport', cluster 'genOnOff', data '{"onOff":1}' from endpoint 2 with groupID 0
Info 2022-08-29 18:46:20MQTT publish: topic 'zigbee2mqtt/0xa4c138de59e7cb48', payload '{"linkquality":200,"state_left":"ON","state_right":"ON"}'
Debug 2022-08-29 18:46:21Received MQTT message on 'zigbee2mqtt/0xa4c138de59e7cb48/set' with data '{"state_right":"OFF"}'
Debug 2022-08-29 18:46:21Publishing 'set' 'state' to '0xa4c138de59e7cb48'
Info 2022-08-29 18:46:21MQTT publish: topic 'zigbee2mqtt/0xa4c138de59e7cb48', payload '{"linkquality":200,"state_left":"ON","state_right":"OFF"}'
Debug 2022-08-29 18:46:21Received Zigbee message from '0xa4c138de59e7cb48', type 'attributeReport', cluster 'genOnOff', data '{"onOff":0}' from endpoint 1 with groupID 0
Info 2022-08-29 18:46:21MQTT publish: topic 'zigbee2mqtt/0xa4c138de59e7cb48', payload '{"linkquality":200,"state_left":"OFF","state_right":"OFF"}'
Debug 2022-08-29 18:46:21Received Zigbee message from '0xa4c138de59e7cb48', type 'attributeReport', cluster 'genOnOff', data '{"onOff":0}' from endpoint 2 with groupID 0
Info 2022-08-29 18:46:21MQTT publish: topic 'zigbee2mqtt/0xa4c138de59e7cb48', payload '{"linkquality":200,"state_left":"OFF","state_right":"OFF"}'

**Comment by Koenkk** [comment] 2022-08-29 16:27
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/13656 (will be fixed in the next release on 1 September)

**Closed by Koenkk** 2022-08-29 16:27 UTC
Labels: problem
