### ISSUE TITLE
Double messages

### ISSUE THREAD

**Issue by SargonofAssyria** [Koenkk/zigbee2mqtt#1266] opened 2019-03-16 18:00 UTC
I get double or tripple messages from a ZNLDP12LM - Xiaomi Aqara smart LED bulb (Router)
Could that be prevented. It seems that those messages are exactly the same, except for linkquality.
I am using on a CC2531 the latest firmware (20190223) and zigbee2mqtt version 1.2.1

`3/16/2019, 6:51:14 PM - info: Zigbee publish to device '0x00158d0002b7d689', genOnOff - off - {} - {"manufSpec":0,"disDefaultRsp":0} - null
3/16/2019, 6:51:14 PM - info: MQTT publish: topic 'zigbee2mqtt/Lamp', payload '{"state":"OFF","device":{"ieeeAddr":"0x00158d0002b7d689","friendlyName":"Lamp","type":"Router","nwkAddr":48565,"manufId":4447,"manufName":"LUMI","powerSource":"DC Source","modelId":"lumi.light.aqcn02","status":"online"},"linkquality":78,"brightness":127,"color_temp":250,"color_mode":1,"color":{"x":0.383,"y":0.382}}'
3/16/2019, 6:51:14 PM - info: MQTT publish: topic 'zigbee2mqtt/Lamp', payload '{"state":"OFF","device":{"ieeeAddr":"0x00158d0002b7d689","friendlyName":"Lamp","type":"Router","nwkAddr":48565,"manufId":4447,"manufName":"LUMI","powerSource":"DC Source","modelId":"lumi.light.aqcn02","status":"online"},"linkquality":84,"brightness":127,"color_temp":250,"color_mode":1,"color":{"x":0.383,"y":0.382}}'
3/16/2019, 6:51:15 PM - info: MQTT publish: topic 'zigbee2mqtt/Lamp', payload '{"state":"OFF","device":{"ieeeAddr":"0x00158d0002b7d689","friendlyName":"Lamp","type":"Router","nwkAddr":48565,"manufId":4447,"manufName":"LUMI","powerSource":"DC Source","modelId":"lumi.light.aqcn02","status":"online"},"linkquality":81,"brightness":127,"color_temp":250,"color_mode":1,"color":{"x":0.383,"y":0.382}}'
`

**Comment by Koenkk** [comment] 2019-03-16 19:38
This is expected, see https://github.com/Koenkk/zigbee2mqtt/issues/1155#issuecomment-467094619

Duplicate of #1155 and #1212

**Closed by Koenkk** 2019-03-16 19:38 UTC
