### ISSUE TITLE
Problem controlling Gledopto GL-MC-001

### ISSUE THREAD

**Issue by stoinov** [Koenkk/zigbee2mqtt#2551] opened 2019-12-17 22:27 UTC
# Bug Report
## What happened
I am not able to control the white LED strip as expected and also not getting proper feedback.

For instance in the famous (for Gledopto devices) issue #1711 there is much discussion about the existence of `zigbee2mqtt/<FRIENDLY_NAME>/white/set` topic, which I am having issues using (my naming convention is `place/location/room/gle01/light/set`). There are errors in the logs like this:
```
zigbee2mqtt:error 2019-12-17 21:17:11: Failed to call 'EntityPublish' 'onMQTTMessage' (AssertionError [ERR_ASSERTION]: Postfix 'white' is given but device defines no endpoints
    at Zigbee.resolveEntity (/app/lib/zigbee.js:180:25)
    at EntityPublish.onMQTTMessage (/app/lib/extension/entityPublish.js:57:36)
    at Controller.callExtensionMethod (/app/lib/controller.js:322:44)
    at Controller.onMQTTMessage (/app/lib/controller.js:237:14)
    at MQTT.emit (events.js:198:13)
    at MQTT.onMessage (/app/lib/mqtt.js:86:14)
    at MqttClient.emit (events.js:198:13)
    at MqttClient._handlePublish (/app/node_modules/mqtt/lib/client.js:1162:12)
    at MqttClient._handlePacket (/app/node_modules/mqtt/lib/client.js:351:12)
    at work (/app/node_modules/mqtt/lib/client.js:283:12))
```
The standard `set` topic is also giving some errors like this:
```
zigbee2mqtt:info  2019-12-17 21:28:33: MQTT publish: topic 'place/location/room/gle01/light/state', payload 'ON'
zigbee2mqtt:info  2019-12-17 21:28:33: MQTT publish: topic 'place/location/room/gle01/light/brightness', payload '100'
zigbee2mqtt:info  2019-12-17 21:28:33: MQTT publish: topic 'place/location/room/gle01/light/last_seen', payload '1576618113134'
(node:23) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'hasOwnProperty' of undefined
    at Object.objectHasProperties (/app/lib/util/utils.js:93:21)
    at Controller.iteratePayloadAttributeOutput (/app/lib/controller.js:301:42)
(node:23) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:23) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
this happens only when the white light is ON and I try to change brightness or color_temp. With the RGB light I do not see the errors.

Another quirk, is that if I send JSON with multiple values (brightness and color_temp OR brightness and color) I get two consecutive responds. It's not handled by the debounce property, and it seems that each property is updated one at a time. Is this a hardware limitation? Is there a way to make this a single update instead of two in a short time window (usually tens of milliseconds)?

## What did you expect to happen
I was expecting to be able to control white LEDs using the dedicated subtopic or to at least not get error messages using the normal one.

I am also expecting just one update upon sending multiple values in JSON format. Or if you're handling them one by one then is it better to use direct manipulation like `topic/set/brightness`? How do I set the color using similar notation?

## Debug Info
device: [GL-MC-001](https://www.zigbee2mqtt.io/devices/GL-MC-001.html)
zigbee2mqtt version: 1.8.0
CC253X firmware version: 20190608

**Comment by Koenkk** [comment] 2019-12-19 19:52
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/2540#issuecomment-566190511

**Closed by Koenkk** 2019-12-19 19:52 UTC
