### ISSUE TITLE
Ikea E2103 TREDANSEN Incorrect Battery Reporting

### ISSUE THREAD

**Issue by FriedCheese2006** [Koenkk/zigbee2mqtt#17888] opened 2023-06-02 22:50 UTC
### What happened?

After upgrading to firmware 24.4.11, all five E2103s I have are reporting what appears to be doubled battery values.

### What did you expect to happen?

No battery report over 100%

### How to reproduce it (minimal and precise)

Check battery report after upgrade.

### Zigbee2MQTT version

1.31.0

### Adapter firmware version

20210708

### Adapter

Sonoff Dongle P

### Debug log

![Screenshot_20230602-184518](https://github.com/Koenkk/zigbee2mqtt/assets/49689423/5b04f85a-85d2-4b1f-9bf6-3efa3f553867)
![Screenshot_20230602-183418](https://github.com/Koenkk/zigbee2mqtt/assets/49689423/3c81de5e-fe37-4813-a802-2f84483b6ed0)

**Comment by Koenkk** [comment] 2023-06-03 15:37
Pushed a possible fix, can you check if this is fixed now? 

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

After updating wait 1 day to make the device report a new battery value, if the issue is not fixed provide me the data/database.db entry of this device.

**Comment by MattWestb** [comment] 2023-06-03 17:03
All released 24.X firmware is doing the batter reporting as Zigbee standard so all IKEA blinds have the same function then they is using the same firmware.
Also new and the old motion sensor and all remotes with 24.X firmware (Styrbar is having one 255 bug) shall not using doubling (i think some is fixed).

**Comment by FriedCheese2006** [comment] 2023-06-03 19:01
Looks like it may be good. I cycled them up/down to force a battery report.

![Screenshot_20230603-150038.png](https://github.com/Koenkk/zigbee2mqtt/assets/49689423/0515be4d-d923-4d1d-8452-94389679b19f)

**Comment by Koenkk** [comment] 2023-06-04 11:52
Great! I assume this can be closed now.

**Closed by Koenkk** 2023-06-04 11:52 UTC
Labels: problem
