### ISSUE TITLE
Received undefined command from '0'

### ISSUE THREAD

**Issue by E99yBend** [Koenkk/zigbee2mqtt#22480] opened 2024-05-06 10:47 UTC
### What happened?

When setting MQTT into pairing mode I get the following message: "Received undefined command from '0'" I have added lots of devices without a problem but with this error it does not do any interviews with new devices.

### What did you expect to happen?

I expected pairing mode to become active

### How to reproduce it (minimal and precise)

Put MQTT in pairing mode. I get the message every time i do that

### Zigbee2MQTT version

1.37.0

### Adapter firmware version

6.10.3.0 build 297

### Adapter

Sonoff zigbee 3.0

### Setup

HA on PI running from SSD

**Comment by jschroeder624** [comment] 2024-05-06 12:24
I am also getting this exact same error, although for me, it happens whether I am in pairing mode or not. When I click Disable join, or Permit Join, I immediately get the error. While updating Ikea firmware last night, I received the error every 3 minutes and 20 seconds in the logs. This morning, the error continues to be logged. It seems connected to the Ikea firmware updates that have showed up. So far, I have only been successful in updating 1 device out of 6 (3 Rodret, 2 Styrbar, 1 motion detector).

**Comment by kikejherrera** [comment] 2024-05-06 16:16
same here

**Comment by Aughmen** [comment] 2024-05-06 18:05
Also me

**Comment by Koenkk** [comment] 2024-05-06 18:56
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/22140

**Closed by Koenkk** 2024-05-06 18:56 UTC
Labels: problem

**Comment by DixyRASTA** [comment] 2024-05-07 08:26
Same here

**Comment by BrixSat** [comment] 2024-05-07 11:16
Same here

**Comment by BenDavidson90** [comment] 2024-05-10 16:01
Same here, Z2M 1.37.0, Sonoff Zigbee Dongle E.
No problem with another Z2M container in 1.37.0 too but with a Conbee II.
