### ISSUE TITLE
Tradfri remote control hold function

### ISSUE THREAD

**Issue by 0000vt** [Koenkk/zigbee2mqtt#2242] opened 2019-10-31 21:07 UTC
Thank you for this great application.

It works fine for many different devices. However, when I hold the main button on the IKEA E1524/E1810, zigbee2mqtt shows an error:

### 
```
PROBLEM DETECTED
Please create an issue here with the contents of below: https://github.com/koenkk/zigbee2mqtt/issues
===== Stack =====
AssertionError [ERR_ASSERTION]: { frameCntl:
   { frameType: 1, manufSpec: 1, direction: 0, disDefaultRsp: 0 },
  manufCode: 4476,
  seqNum: 17,
  cmdId: 'tr... deepEqual { frameCntl:
   { frameType: 1, manufSpec: 1, direction: 0, disDefaultRsp: 0 },
  manufCode: 4476,
  seqNum: 17,
  cmdId: 'tr...
    at cb (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/lib/components/zcl.js:59:24)
    at /opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/deprecated/zcl-packet/lib/zcl.js:31:17
    at Dissolve.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/deprecated/zcl-packet/lib/functional.js:76:17)
    at Object.onceWrapper (events.js:286:20)
    at Dissolve.emit (events.js:198:13)
    at Dissolve.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/deprecated/dissolve-chunks/index.js:65:29)
    at Dissolve.emit (events.js:198:13)
    at emitReadable_ (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/node_modules/readable-stream/lib/_stream_readable.js:456:10)
    at emitReadable (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/node_modules/readable-stream/lib/_stream_readable.js:450:7)
    at readableAddChunk (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/node_modules/readable-stream/lib/_stream_readable.js:206:11)
===== Buffer =====
{ type: 'Buffer', data: [ 5, 124, 17, 17, 7, 2, 0, 0, 0 ] }
===== Arguments =====
<Buffer 05 7c 11 11 07 02 00 00 00> 5
===== zcl-packet parse =====
{"frameCntl":{"frameType":1,"manufSpec":1,"direction":0,"disDefaultRsp":0},"manufCode":4476,"seqNum":17,"cmdId":"tradfriArrowSingle","payload":{"value":2}}
===== zcl =====
{"frameCntl":{"frameType":1,"manufSpec":1,"direction":0,"disDefaultRsp":0},"manufCode":4476,"seqNum":17,"cmdId":"tradfriArrowSingle","payload":{"value":2,"value2":0}}
===============



PROBLEM DETECTED
Please create an issue here with the contents of below: https://github.com/koenkk/zigbee2mqtt/issues
===== Stack =====
AssertionError [ERR_ASSERTION]: { frameCntl:
   { frameType: 1, manufSpec: 1, direction: 0, disDefaultRsp: 0 },
  manufCode: 4476,
  seqNum: 17,
  cmdId: 'tr... deepEqual { frameCntl:
   { frameType: 1, manufSpec: 1, direction: 0, disDefaultRsp: 0 },
  manufCode: 4476,
  seqNum: 17,
  cmdId: 'tr...
    at cb (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/lib/components/zcl.js:59:24)
    at /opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/deprecated/zcl-packet/lib/zcl.js:31:17
    at Dissolve.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/deprecated/zcl-packet/lib/functional.js:76:17)
    at Object.onceWrapper (events.js:286:20)
    at Dissolve.emit (events.js:198:13)
    at Dissolve.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/deprecated/dissolve-chunks/index.js:65:29)
    at Dissolve.emit (events.js:198:13)
    at emitReadable_ (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/node_modules/readable-stream/lib/_stream_readable.js:456:10)
    at emitReadable (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/node_modules/readable-stream/lib/_stream_readable.js:450:7)
    at readableAddChunk (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/node_modules/readable-stream/lib/_stream_readable.js:206:11)
===== Buffer =====
{ type: 'Buffer', data: [ 5, 124, 17, 17, 7, 2, 0, 0, 0 ] }
===== Arguments =====
<Buffer 05 7c 11 11 07 02 00 00 00> 5
===== zcl-packet parse =====
{"frameCntl":{"frameType":1,"manufSpec":1,"direction":0,"disDefaultRsp":0},"manufCode":4476,"seqNum":17,"cmdId":"tradfriArrowSingle","payload":{"value":2}}
===== zcl =====
{"frameCntl":{"frameType":1,"manufSpec":1,"direction":0,"disDefaultRsp":0},"manufCode":4476,"seqNum":17,"cmdId":"tradfriArrowSingle","payload":{"value":2,"value2":0}}
===============
```

Thank you for your reply in forward

**Comment by Koenkk** [comment] 2019-11-01 14:48
Thanks for reporting, closing this as it is a duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/2006#issuecomment-533691577

**Closed by Koenkk** 2019-11-01 14:48 UTC
