### ISSUE TITLE
[Feature request]: Ability to set transmit power of CxxxxP-dongles with Z-Stack router firmware

### ISSUE THREAD

**Issue by jorisvervuurt** [Koenkk/zigbee2mqtt#13588] opened 2022-08-18 06:56 UTC
### Is your feature request related to a problem? Please describe

I have two Sonoff Zigbee 3.0 USB Dongle Plus (CC2652P-based) dongles in my home, both running Z-Stack 3.x firmware. One is the coordinator, the other one is flashed with the router firmware. I have set the transmit power of the coordinator to the maximum value (20dBm), but I can't find where to set the transmit power of the other (router) dongle.

### Describe the solution you'd like

Similar to the 'Transmit power' option under the 'Settings' -> 'Advanced' tab, I'd like to set the transmit power of the dongle that is running the Z-Stack 3.x router firmware. This is the device definition that is being used for the router dongle:
https://www.zigbee2mqtt.io/devices/ti.router.html

### Describe alternatives you've considered

I did take a look in the converter script, but it seems only the link quality is being passed to Zigbee2MQTT:
https://github.com/Koenkk/zigbee-herdsman-converters/blob/5809aa0ea42b2c2e5edf9e0c655fb2e10b4dff8f/devices/custom_devices_diy.js#L266

### Additional context

Not applicable.

**Comment by Koenkk** [comment] 2022-08-18 16:36
Duplicate of https://github.com/Koenkk/Z-Stack-firmware/issues/341

**Closed by Koenkk** 2022-08-18 16:36 UTC
Labels: feature request
