### ISSUE TITLE
EcoDim dimmer gives error when trying to OTA update

### ISSUE THREAD

**Issue by 85mnl** [Koenkk/zigbee2mqtt#20759] opened 2024-01-13 08:08 UTC
### What happened?

I have multiple EcoDim dimmers installed in my home. All of them work fine except. I keep having issues with the OTA update within Z2M for my EcoDim dimmers.

Recently HA start showing below notification.
![image](https://github.com/Koenkk/zigbee2mqtt/assets/5189740/9aa02a1f-358c-44a8-ac89-fe53f8ea9352)

When i go to Z2M and i try to do the OTA update i get below error

![image](https://github.com/Koenkk/zigbee2mqtt/assets/5189740/7c9e1d0b-9292-4ae3-9fd6-a317cbaec8b6)

More info about the dimmer i use and where the error pops up when try to do OTA.

Firmware build date: 20210802
Firmwareversie: 1.01
Model: Eco-Dim.07/Eco-Dim.10

### What did you expect to happen?

No error when trying to perform OTA update

### How to reproduce it (minimal and precise)

Go to Z2M then go to OTA section. Go the EcoDim dimmer and press on Check for updates.

### Zigbee2MQTT version

1.35.1

### Adapter firmware version

20220219

### Adapter

SONOFF ZigBee 3.0 USB

### Setup

Add-on on Home Assistant Intel NUC

**Comment by Koenkk** [comment] 2024-01-13 20:15
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/20658

**Closed by Koenkk** 2024-01-13 20:15 UTC
Labels: problem
