### ISSUE TITLE
When renaming a device (IKEA bulb) using the new Z2M IDE, the device looses connection to MQTT Broker/HA

### ISSUE THREAD

**Issue by esbenr** [Koenkk/zigbee2mqtt#5458] opened 2020-12-29 18:36 UTC
## What happened
Adding a new device (passive or active) to Z2M it appears in the Z2M IDE and as a new device in HA (MQTT Broker integration).
Then renaming the device from the Z2M IDE (enable rename in HA) actually renames the device, but it looses it's connection to MQTT Broker/HA. (Disappears in HA)
After renaming it's also not possible to click "Configure" in the Z2M IDE in order to re-create the device in MQTT Broker/HA. It will fail with:
```
INFO: MQTT publish: topic 'zigbee2mqtt/bridge/response/device/configure', payload '{"data":{"id":"Living room Black floor lamp"},"error":"Device 'Living room Black floor lamp' cannot be configured","status":"error"}'
```

This happens with both active devices and passive devices - even if you press/activate them while clicking configure.

The only way to fix this is to force remove the device, restart Z2M and then re-pair the device.
Then it will again show up named with the address. You can still not rename the device, then the same will happen again.

## What did you expect to happen
The old Zigbee2MQTT Assistant did rename properly in both Z2M and MQTT Broker/HA. The device would remain connected, but with the new name.

## How to reproduce it (minimal and precise)

1. Add new device
2. Rename in Z2M IDE (Enable rename in HA)
3. See if the device is still in MQTT Broker integration/HA either is disappeared if not;
4. Toggle the device in Z2M IDE
5. See that the device in HA does not change value.

## Debug info
Zigbee2MQTT version:  1.16.2.2
Adapter hardware: ZZH
Adapter firmware version: CC26X2R1_20201026

**Comment by Koenkk** [comment] 2020-12-29 18:45
Looks like a duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/5150 (feel free to re-open if not). It is a HA issue: https://github.com/Koenkk/zigbee2mqtt/issues/5150#issuecomment-752022929

**Closed by Koenkk** 2020-12-29 18:45 UTC
Labels: problem
