### ISSUE TITLE
Front UI broken since 1.35.3-1

### ISSUE THREAD

**Issue by jmcollin78** [Koenkk/zigbee2mqtt#21320] opened 2024-02-09 10:10 UTC
### What happened?

Since the installation of 1.35.3-1, the front UI is broken. Css is not found:
![Capture d’écran 2024-02-09 à 11 08 47](https://github.com/Koenkk/zigbee2mqtt/assets/1712374/704d6695-3c0a-45e8-99f6-5a612769f3d0)

Of course I try to empty the browser cache, restart the add-on and alos restart HA without success.

Am I alone with this problem ?

### Zigbee2MQTT version

1.35.3-1

### Adapter firmware version

-

### Adapter

ezsp

### Setup

add-on

### Debug log
May be this could help (in inspector):
![Capture d’écran 2024-02-09 à 11 12 48](https://github.com/Koenkk/zigbee2mqtt/assets/1712374/d39e1392-5a5f-4b61-829e-424a5c0d4f41)

**Comment by Usandu** [comment] 2024-02-09 10:18
You are not alone m8, same problem here.

**Comment by jmcollin78** [comment] 2024-02-09 10:24
As a workaround, clicking on the sun icon solve the problem:

![Capture d’écran 2024-02-09 à 11 24 01](https://github.com/Koenkk/zigbee2mqtt/assets/1712374/8ef08990-2d81-4f44-89d1-f29b4f282ea1)

**Comment by Wesleyl89** [comment] 2024-02-09 10:47
Same here but clicking on the sun icon indeed fixes it like @jmcollin78 said

**Comment by neovarsis** [comment] 2024-02-09 10:55
Same here, as above, sun icon does fix it.

**Comment by araik1998** [comment] 2024-02-09 13:08
То же самое, что и выше

**Comment by NReiher** [comment] 2024-02-09 14:38
Same issue. Sun resolved it. Happened on two different computers. Resolving it in one (clicking the sun) does not fix it on the other.

**Comment by giscal** [comment] 2024-02-09 22:02
same issue for me to - no front end

**Comment by energywave** [comment] 2024-02-10 00:18
Same here. Clicking the sun fix it.
To add something: I'm using Edge and just updated zigbee2mqtt to 1.35.3, then, after update, it was like in the screenshot of this issue (italian language, if that matters).
So I've installed a clean Chrome and there was no problem.
I checked the browser dev tools and found this error (in Edge, not in chrome):
```
Could not find specified theme
(anonimo) @ index-a782d339.js:1058
```

**Comment by lgander** [comment] 2024-02-10 14:31
Same here. Sun fixes it.

**Comment by Koenkk** [comment] 2024-02-10 16:01
Dupe of https://github.com/Koenkk/zigbee2mqtt/issues/21268

**Closed by Koenkk** 2024-02-10 16:01 UTC
Labels: problem
