### ISSUE TITLE
My Xiaomi sends me two lines like this

### ISSUE THREAD

**Issue by peacermaker** [Koenkk/zigbee2mqtt#3085] opened 2020-03-07 21:44 UTC
# Bug Report
## What happened
My Xiaomi  wireless switch WXKG01LM sends me two lines like this when I press buttons
`zigbee2mqtt:info  2020-03-07 21:25:47: MQTT publish: topic 'zigbee2mqtt/0x00158d0001a21114', payload '{"battery":100,"voltage":3002,"linkquality":47,"click":"single"}'
zigbee2mqtt:info  2020-03-07 21:25:47: MQTT publish: topic 'zigbee2mqtt/0x00158d0001a21114', payload '{"battery":100,"voltage":3002,"linkquality":47,"click":""}'`
## What did you expect to happen
I get in Fhem no readings in click in the device reading click is empty .why is he sending this reading twice,Is it wanted like that?
## How to reproduce it (minimal and precise)
with 2 buttons several times the same problem
## Debug Info
zigbee2mqtt version:@1.11.0.
CC253X firmware version:

**Comment by Koenkk** [comment] 2020-03-07 22:28
This is expected, duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/1457#issuecomment-485401419

**Closed by Koenkk** 2020-03-07 22:28 UTC
