### ISSUE TITLE
[Problem]: Tuya TRV's - TS0601 - losing time/being sent random times

### ISSUE THREAD

**Issue by Thrasher2020** [Koenkk/zigbee2mqtt#10635] opened 2022-01-07 12:07 UTC
### What happened?

Prior to the latest update my TRV's got the time from HA (or the Pi). Since the latest update they have gone haywire and no longer operate when they are scheduled (as in because the time is suddenly completely wrong). I have reverted to 1.22.0-3 and everything is working again - so I think there's something going on in the new tuya.js ....

### What did you expect to happen?

The TRV's to receive the time as previously.

### How to reproduce it (minimal and precise)

Check time on TRV. Set to real time. Time changes after a few minutes/hours. 

### Zigbee2MQTT version

1.22.1

### Adapter firmware version

20211217

### Adapter

ZZh!

### Debug log

N/A

**Comment by Koenkk** [comment] 2022-01-07 16:07
Duplicate of #10489

**Closed by Koenkk** 2022-01-07 16:07 UTC
Labels: problem
