### ISSUE TITLE
_TZE200_gd4rvykv not working

### ISSUE THREAD

**Issue by SnakeZi** [Koenkk/zigbee2mqtt#16966] opened 2023-03-08 19:57 UTC
### What happened?

As mentioned here https://github.com/Koenkk/zigbee2mqtt/discussions/16642#discussioncomment-5184246 recently added support for _TZE200_gd4rvykv does not work. MQTT entity doesn't communicate correctly with real device.

Zigbee2Mqtt installed as Home Assistant addon v1.30.2-1 (stable branch).

Messages sent from device to Z2M are not supported
debug 2023-03-08 20:03:45: Received Zigbee message from 'heater_familyroom', type 'commandDataReport', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,220],"type":"Buffer"},"datatype":2,"dp":103}],"seq":768}' from endpoint 1 with groupID 0
debug 2023-03-08 20:03:45: Datapoint 103 not defined for '_TZE200_gd4rvykv' with data {"dp":103,"datatype":2,"data":{"type":"Buffer","data":[0,0,0,220]}}
[dp 103 is for wanted Temperature and is sent after manual turn of the valve. 220 = 22.0C]

debug 2023-03-08 20:09:18: Received Zigbee message from 'heater_familyroom', type 'commandDataReport', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,213],"type":"Buffer"},"datatype":2,"dp":102}],"seq":512}' from endpoint 1 with groupID 0
debug 2023-03-08 20:09:18: Datapoint 102 not defined for '_TZE200_gd4rvykv' with data {"dp":102,"datatype":2,"data":{"type":"Buffer","data":[0,0,0,213]}}
[dp 102 is for Current temperature in Celsius. 213 = 21.3C]

Messages sent from Z2M to device, are ignored

### What did you expect to happen?

I'd like it to work :)

### Zigbee2MQTT version

1.30.2

### Adapter firmware version

 20220219

### Adapter

Sonoff ZBDongle-P ( zStack3x0 firmware)

### Debug log

[_TZE200_gd4rvykv.txt](https://github.com/Koenkk/zigbee2mqtt/files/10924699/_TZE200_gd4rvykv.txt)

**Comment by Kraviecc** [comment] 2023-04-09 15:19
Any luck with this or help needed?

**Comment by pioniziolek** [comment] 2023-04-09 21:57
I got some progress with this device after I assigned it to model [Saswell] SEA801-Zigbee/SEA802-Zigbee.
It reports local_temperature and accepts current_heating_setpoint.
I'm able to set system_mode as well.
I'm not sure about local temperature - reported values seem to be to high.
I have no clue how to setup schedules etc.

**Comment by pioniziolek** [comment] 2023-04-13 18:26
I just used external converter saswell.js with added _TZE200_gd4rvykv to the modelid list. 
Just one remark - it did not report local_temperature initially. 
I found it reports local_temperature only when it changes.

**Comment by elad-bar** [comment] 2023-04-13 18:54
I think I found the issue after struggling with another device I added,
tuya.fz.datapoints handler is trying to compare DPs from meta to match the DPs from the event, while the event DP is numeric, for some reason the meta.tuyaDatapoints is being converted to string before and doesn't find them.

```log
meta: [["3","accurate_calibration",{}],["7","backlight_switch",{}],["8","motor_steering",{}],["101","switch_2",{}],["102","switch_1",{}],["103","child_lock",{}]]
04/13/2023 9:46:49 PM
data: [{"dp":101,"datatype":1,"data":{"type":"Buffer","data":[0]}}]
```

convert code is:
```javascript
            let result = {};
            if (!model.meta || !model.meta.tuyaDatapoints) throw new Error('No datapoints map defined');
            const datapoints = model.meta.tuyaDatapoints;
            for (const dpValue of msg.data.dpValues) {
                const dpId = dpValue.dp;
                const dpEntry = datapoints.find((d) => d[0] === dpId);
                if (dpEntry) {
                    const value = getDataValue(dpValue);
                    if (dpEntry[1]) {
                        result[dpEntry[1]] = dpEntry[2].from(value, meta, options);
                    } else if (dpEntry[2]) {
                        result = {...result, ...dpEntry[2].from(value, meta, options)};
                    }
                } else {
                    meta.logger.debug(`Datapoint ${dpId} not defined for '${meta.device.manufacturerName}' ` +
                        `with data ${JSON.stringify(dpValue)}`);
                }
            }
```

fix for it should be compare the same type :
```javascript
const dpEntry = datapoints.find((d) => d[0].toString() === dpId.toString());
```

**Comment by elad-bar** [comment] 2023-04-14 03:52
It's not about the value, the key is not found which makes the issue,
According to the OP, there is an issue (same as I encountered):
Datapoint 103 not defined for '_TZE200_gd4rvykv' with data {"dp":103,"datatype":2,"data":{"type":"Buffer","data":[0,0,0,220]}}

DP 103 defined as numeric, but converter is getting as string,
Event data is being sent as numeric,
As result of that, comparing the values fails, it is not that sophisticated to cast values to string before comparing,
It would be best to fix the root cause, but it will implcate much wider consumers (breaking change) as they might done something with it and changing the meta tuyaDatapoint to numetic value will break the other code.

If fix will not approve, I will need to clone that converter and adjust my devices to use the new one

**Comment by pioniziolek** [comment] 2023-10-29 20:09
Please advice - after all discussion my devices '_TZE200_gd4rvykv' are still recognized by zigbee2mqtt (stable branch) as 'TS0601_thermostat_3' but not as 'SEA802-ZT5'. What shall I do to implement this change as official?

**Comment by Koenkk** [comment] 2023-11-06 19:53
Could you check if the issue is fixed with the following external converter: https://gist.github.com/Koenkk/10240e8b6b0a1aa2cb596c8ac4d6369e

- save this as file next to `configuration.yaml` as `ext_converter.js`
- add it to `configuration.yaml`:
```yaml
external_converters:
  - ext_converter.js
```
- start z2m, check if issue is fixed

**Comment by Koenkk** [comment] 2023-11-07 20:50
Integrated the fix, you can remove the ext converter after updating to the next release.

**Closed by Koenkk** 2023-11-07 20:50 UTC
Labels: problem
