### ISSUE TITLE
1.18.2 has high cpu usage

### ISSUE THREAD

**Issue by hfcheng66** [Koenkk/zigbee2mqtt#7194] opened 2021-04-24 18:06 UTC
## What happened

Running koenkk/zigbee2mqtt image under ubuntu 18.4

After upgrade to 1.18.2, noticed the cpu usage is high, constantly around 10%.
Revert back to 1.17.1, the cpu usage is around 1%

Using Conbee II stick.
Have 7 zigbee bulbs and 4 xiaomi buttons.

## Debug info
Zigbee2MQTT version: 1.18.2
Adapter hardware: Conbee II

**Comment by Koenkk** [comment] 2021-04-25 13:01
Duplicate of #7004

**Closed by Koenkk** 2021-04-25 13:01 UTC
Labels: problem
