### ISSUE TITLE
Device TS0601 not supported even though it should be as - IOTPerfect PF-PM02D-TYZ

### ISSUE THREAD

**Issue by neriburo** [Koenkk/zigbee2mqtt#12093] opened 2022-04-06 15:30 UTC
### What happened?

I have purchased a gas/water walve opener just like this one: https://www.zigbee2mqtt.io/devices/PF-PM02D-TYZ.html#iotperfect-pf-pm02d-tyz . It is supposed to be supported. But when I pair it to Zigbee2MQTT it gives me endless errors:
```
Warning Received message from unsupported device with Zigbee model 'TS0601' and manufacturer name '_TZE200_d0ypnbvn'
Warning Please see: https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html
Info MQTT publish: topic 'zigbee2mqtt/boilerio_sklende', payload '{"last_seen":"2022-04-06T18:06:33+03:00","linkquality":138}'
```
I've tried to remove and re-pair - nothing changes.
When searching on the internet for "TS0601" it gives me results for a zigbee radiator smart valve. Might it be that for some reason Zigbee2MQTT recognises it wrongly and therefore treats it as unsupported? And if yes, is there a way around this?
Thank you.

![PF-PM02D-TYZ 1](https://user-images.githubusercontent.com/91637398/162007632-6a023640-ff2a-42f5-805a-417fd370cd6d.jpg)

### What did you expect to happen?

The device is supposed to be supported:
https://www.zigbee2mqtt.io/images/devices/PF-PM02D-TYZ.jpg

### Zigbee2MQTT version

1.25.0

### Adapter firmware version

20211217

### Adapter

Sonoff ZIGBEE 3.0 USB dongle Plus

### Debug log

[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/8428363/log.txt)

**Comment by kylinfedora** [comment] 2022-04-08 14:43
It's same to me  
Duplicate of #12117

**Comment by Koenkk** [comment] 2022-04-08 14:46
`_TZE200_d0ypnbvn` was not supported yet, added it now.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Closed by Koenkk** 2022-04-08 14:46 UTC
Labels: problem

**Comment by kkossev** [comment] 2023-03-26 17:12
@neriburo I suppose you are using your TS0601 _TZE200_d0ypnbvn valve now.
Do you see in the logs data packets from this device (the open or closed state) to Z2M every 3 seconds non-stop?

**Comment by neriburo** [comment] 2023-03-26 18:48
> @neriburo I suppose you are using your TS0601 _TZE200_d0ypnbvn valve now. Do you see in the logs data packets from this device (the open or closed state) to Z2M every 3 seconds non-stop?

Hi. Newer noticed this, but yes, it does. Every 2-3 seconds.

![image](https://user-images.githubusercontent.com/91637398/227797336-7eeec24b-c2ba-45f3-b233-3f2d76e8745f.png)
