### ISSUE TITLE
Bosch BSP-FZ2 is unkown

### ISSUE THREAD

**Issue by joachim-beck** [Koenkk/zigbee2mqtt#16626] opened 2023-02-11 18:33 UTC
### What happened?

It pairs as unknown device.

2023-02-11 19:02:31Received message from unsupported device with Zigbee model 'RBSH-SP-ZB-EU' and manufacturer name 'BOSCH'
2023-02-11 19:02:31Please see: https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html

### What did you expect to happen?

The device should be supported

### How to reproduce it (minimal and precise)

Happens everytime when pairing such a device.

### Zigbee2MQTT version

1.30.1-dev commit: e9a38353

### Adapter firmware version

20220219

### Adapter

Tube's Zigbee Gateways (CC2652P2 variant)

### Debug log

[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/10714456/log.txt)

**Comment by Koenkk** [comment] 2023-02-12 08:43
Duplicate of https://github.com/Koenkk/zigbee2mqtt/discussions/16625

**Closed by Koenkk** 2023-02-12 08:43 UTC
Labels: problem
