### ISSUE TITLE
Timezone Error in 1.7.1

### ISSUE THREAD

**Issue by jasimancas** [Koenkk/zigbee2mqtt#2341] opened 2019-11-15 08:12 UTC
Hi, i have a problem with datetime in docker, Im living in Europe/Madrid, But the time zone of the container shows one hour less.

Bug? Bad config?

I have: "-TZ=Europe/Madrid

I have tried with /etc/locatime:etc/localtime:ro and nothing...

## Debug Info
zigbee2mqtt version: 1.7.1
CC253X firmware version: latest sourcerouting

**Comment by Koenkk** [comment] 2019-11-15 22:05
Should be fixed in latest dev! thanks

**Comment by iStitch07** [comment] 2019-11-23 18:54
Hello. 
I can't to set log timestamp to local time too
Have in docker-compose.yml
   environment:
      - TZ=Europe/Moscow
    volumes:
      - ./zigbee2mqtt:/app/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

and if I attach console, command data show me correct my local time. But in log I anyway have timestamp GMT as I think

**Comment by Koenkk** [comment] 2019-11-25 16:46
@iStitch07 I cannot reproduce this with the latest dev, can you?

**Comment by iStitch07** [comment] 2019-11-25 18:58
@Koenkk latest-dev work perfect in this plane
zigbee2mqtt:info  2019-11-25 21:54:38: Logging to directory: '/app/data/log/2019-11-25.21-54-38'
zigbee2mqtt:info  2019-11-25 21:54:39: Starting zigbee2mqtt version 1.7.1+dev (commit #7d1635a)
zigbee2mqtt:info  2019-11-25 21:54:39: Starting zigbee-herdsman...

I have this error on just latest, sorry )

**Comment by Koenkk** [comment] 2019-11-26 09:05
Cool, thanks

**Closed by Koenkk** 2019-11-26 09:05 UTC
