### ISSUE TITLE
MCCGQ12LM does not display battery level.

### ISSUE THREAD

**Issue by Murianwind** [Koenkk/zigbee2mqtt#19996] opened 2023-12-03 06:42 UTC
### What happened?

![image](https://github.com/Koenkk/zigbee2mqtt/assets/6447460/580bc86c-04fe-441a-a4c8-d495df35ee9e)
![image](https://github.com/Koenkk/zigbee2mqtt/assets/6447460/c73ead80-9072-4db2-96e6-948bb770a195)
![image](https://github.com/Koenkk/zigbee2mqtt/assets/6447460/b8f900ea-b186-4027-9779-37acce50f6e8)
![image](https://github.com/Koenkk/zigbee2mqtt/assets/6447460/782065fa-0988-4c0b-bfcd-f8ab9b78b155)
Battery information appears on Z2M's web UI page. However, the battery information cannot be retrieved from the HA device information sensor as N/A. Battery information is not uploaded after the latest Z2M update.

### What did you expect to happen?

The battery level should be displayed on the sensor.

### Zigbee2MQTT version

1.34.0-1

### Adapter firmware version

20230507

### Adapter

SMARTLIGHT CC2652P (SLZB-02)

**Comment by Klapperman** [comment] 2023-12-05 08:16
This is a duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/19559

**Closed** 2023-12-05 18:21 UTC
Labels: problem
