### ISSUE TITLE
MIR-HE200-TY Presence Sensor unknown

### ISSUE THREAD

**Issue by robertbigk** [Koenkk/zigbee2mqtt#16541] opened 2023-02-05 14:42 UTC
### What happened?

Presence Sensor go to unknown state delete , reconnect , restore backup nothing work all entities load proper but that stay unknown. I got two   MIR-HE200-TY and two stop work that same way

### What did you expect to happen?

Way to reset restore, bring to life unknown entities

### How to reproduce it (minimal and precise)

I don't know is happened after restart home assistant

### Zigbee2MQTT version

1.30.0-1

### Adapter firmware version

DE2489585

### Adapter

Conbee II

### Debug log

[mqtt-51013cf66a2430982d6ff15e021a75cd-Presence-01bec6d97110b8b8e37bbb82510af89b.json.txt](https://github.com/Koenkk/zigbee2mqtt/files/10611247/mqtt-51013cf66a2430982d6ff15e021a75cd-Presence-01bec6d97110b8b8e37bbb82510af89b.json.txt)

**Comment by Koenkk** [comment] 2023-02-05 14:44
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/16467

**Closed by Koenkk** 2023-02-05 14:44 UTC
Labels: problem
