### ISSUE TITLE
Exception in async_discover when dispatching 'mqtt_discovery_new_cover_mqtt'

### ISSUE THREAD

**Issue by rogu22** [Koenkk/zigbee2mqtt#7701] opened 2021-06-04 13:22 UTC
Since the update from 2021.5 to 2021.6 , the devices are not able to be discovered by Home Assistant. It seems that zigbee2mqtt is not publishing the payloads as Home Assitant expects.
The error that home assistant shows is this:

•	Exception in async_discover when dispatching 'mqtt_discovery_new_cover_mqtt': ({'availability': [{'topic': 'zigbee2mqtt/bridge/state'}], 'command_topic': 'zigbee2mqtt/0x804b50fffe4e8382/set', 'device': {'identifiers': ['zigbee2mqtt_0x804b50fffe4e8382'], 'manufacturer': 'Lonsonho', 'model': 'Curtain/blind motor controller (QS-Zigbee-C01)', 'name': '0x804b50fffe4e8382', 'sw_version': 'Zigbee2MQTT 1.18.1'}, 'json_attributes_topic': 'zigbee2mqtt/0x804b50fffe4e8382', 'name': '0x804b50fffe4e8382', 'position_topic': 'zigbee2mqtt/0x804b50fffe4e8382', 'set_position_template': '{ "position": {{ position }} }', 'set_position_topic': 'zigbee2mqtt/0x804b50fffe4e8382/set', 'unique_id': '0x804b50fffe4e8382_cover_zigbee2mqtt', 'value_template': '{{ value_json.position }}', 'platform': 'mqtt'},) Traceback (most recent call last): File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__ return self._compiled([], data) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable return schema(data) File "/usr/src/homeassistant/homeassistant/components/mqtt/cover.py", line 118, in validate_options raise vol.Invalid( voluptuous.error.Invalid: 'value_template' must be set together with 'state_topic'. During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 160, in async_discover config = schema(discovery_payload) File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 218, in __call__ return self._exec((Schema(val) for val in self.validators), v) File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 341, in _exec raise e if self.msg is None else AllInvalid(self.msg, path=path) File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 337, in _exec v = func(v) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 276, in __call__ raise er.MultipleInvalid([e]) voluptuous.error.MultipleInvalid: 'value_template' must be set together with 'state_topic'.
•	Exception in async_discover when dispatching 'mqtt_discovery_new_cover_mqtt': ({'availability': [{'topic': 'zigbee2mqtt/bridge/state'}], 'command_topic': 'zigbee2mqtt/0x804b50fffe4e64a2/set', 'device': {'identifiers': ['zigbee2mqtt_0x804b50fffe4e64a2'], 'manufacturer': 'Lonsonho', 'model': 'Curtain/blind motor controller (QS-Zigbee-C01)', 'name': '0x804b50fffe4e64a2', 'sw_version': 'Zigbee2MQTT 1.18.1'}, 'json_attributes_topic': 'zigbee2mqtt/0x804b50fffe4e64a2', 'name': '0x804b50fffe4e64a2', 'position_topic': 'zigbee2mqtt/0x804b50fffe4e64a2', 'set_position_template': '{ "position": {{ position }} }', 'set_position_topic': 'zigbee2mqtt/0x804b50fffe4e64a2/set', 'unique_id': '0x804b50fffe4e64a2_cover_zigbee2mqtt', 'value_template': '{{ value_json.position }}', 'platform': 'mqtt'},) Traceback (most recent call last): File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__ return self._compiled([], data) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable return schema(data) File "/usr/src/homeassistant/homeassistant/components/mqtt/cover.py", line 118, in validate_options raise vol.Invalid( voluptuous.error.Invalid: 'value_template' must be set together with 'state_topic'. During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 160, in async_discover config = schema(discovery_payload) File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 218, in __call__ return self._exec((Schema(val) for val in self.validators), v) File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 341, in _exec raise e if self.msg is None else AllInvalid(self.msg, path=path) File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 337, in _exec v = func(v) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 276, in __call__ raise er.MultipleInvalid([e]) voluptuous.error.MultipleInvalid: 'value_template' must be set together with 'state_topic'.
•	Exception in async_discover when dispatching 'mqtt_discovery_new_cover_mqtt': ({'availability': [{'topic': 'zigbee2mqtt/bridge/state'}], 'command_topic': 'zigbee2mqtt/0x804b50fffeefc011/set', 'device': {'identifiers': ['zigbee2mqtt_0x804b50fffeefc011'], 'manufacturer': 'Lonsonho', 'model': 'Curtain/blind motor controller (QS-Zigbee-C01)', 'name': '0x804b50fffeefc011', 'sw_version': 'Zigbee2MQTT 1.18.1'}, 'json_attributes_topic': 'zigbee2mqtt/0x804b50fffeefc011', 'name': '0x804b50fffeefc011', 'position_topic': 'zigbee2mqtt/0x804b50fffeefc011', 'set_position_template': '{ "position": {{ position }} }', 'set_position_topic': 'zigbee2mqtt/0x804b50fffeefc011/set', 'unique_id': '0x804b50fffeefc011_cover_zigbee2mqtt', 'value_template': '{{ value_json.position }}', 'platform': 'mqtt'},) Traceback (most recent call last): File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__ return self._compiled([], data) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable return schema(data) File "/usr/src/homeassistant/homeassistant/components/mqtt/cover.py", line 118, in validate_options raise vol.Invalid( voluptuous.error.Invalid: 'value_template' must be set together with 'state_topic'. During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 160, in async_discover config = schema(discovery_payload) File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 218, in __call__ return self._exec((Schema(val) for val in self.validators), v) File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 341, in _exec raise e if self.msg is None else AllInvalid(self.msg, path=path) File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 337, in _exec v = func(v) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 276, in __call__ raise er.MultipleInvalid([e]) voluptuous.error.MultipleInvalid: 'value_template' must be set together with 'state_topic'.
•	Exception in async_discover when dispatching 'mqtt_discovery_new_cover_mqtt': ({'availability': [{'topic': 'zigbee2mqtt/bridge/state'}], 'command_topic': 'zigbee2mqtt/0x804b50fffe4e6432/set', 'device': {'identifiers': ['zigbee2mqtt_0x804b50fffe4e6432'], 'manufacturer': 'Lonsonho', 'model': 'Curtain/blind motor controller (QS-Zigbee-C01)', 'name': '0x804b50fffe4e6432', 'sw_version': 'Zigbee2MQTT 1.18.1'}, 'json_attributes_topic': 'zigbee2mqtt/0x804b50fffe4e6432', 'name': '0x804b50fffe4e6432', 'position_topic': 'zigbee2mqtt/0x804b50fffe4e6432', 'set_position_template': '{ "position": {{ position }} }', 'set_position_topic': 'zigbee2mqtt/0x804b50fffe4e6432/set', 'unique_id': '0x804b50fffe4e6432_cover_zigbee2mqtt', 'value_template': '{{ value_json.position }}', 'platform': 'mqtt'},) Traceback (most recent call last): File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__ return self._compiled([], data) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable return schema(data) File "/usr/src/homeassistant/homeassistant/components/mqtt/cover.py", line 118, in validate_options raise vol.Invalid( voluptuous.error.Invalid: 'value_template' must be set together with 'state_topic'. During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 160, in async_discover config = schema(discovery_payload) File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 218, in __call__ return self._exec((Schema(val) for val in self.validators), v) File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 341, in _exec raise e if self.msg is None else AllInvalid(self.msg, path=path) File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 337, in _exec v = func(v) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 276, in __call__ raise er.MultipleInvalid([e]) voluptuous.error.MultipleInvalid: 'value_template' must be set together with 'state_topic'.
•	Exception in async_discover when dispatching 'mqtt_discovery_new_cover_mqtt': ({'availability': [{'topic': 'zigbee2mqtt/bridge/state'}], 'command_topic': 'zigbee2mqtt/0x804b50fffe4e7fc9/set', 'device': {'identifiers': ['zigbee2mqtt_0x804b50fffe4e7fc9'], 'manufacturer': 'Lonsonho', 'model': 'Curtain/blind motor controller (QS-Zigbee-C01)', 'name': '0x804b50fffe4e7fc9', 'sw_version': 'Zigbee2MQTT 1.18.1'}, 'json_attributes_topic': 'zigbee2mqtt/0x804b50fffe4e7fc9', 'name': '0x804b50fffe4e7fc9', 'position_topic': 'zigbee2mqtt/0x804b50fffe4e7fc9', 'set_position_template': '{ "position": {{ position }} }', 'set_position_topic': 'zigbee2mqtt/0x804b50fffe4e7fc9/set', 'unique_id': '0x804b50fffe4e7fc9_cover_zigbee2mqtt', 'value_template': '{{ value_json.position }}', 'platform': 'mqtt'},) Traceback (most recent call last): File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__ return self._compiled([], data) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable return schema(data) File "/usr/src/homeassistant/homeassistant/components/mqtt/cover.py", line 118, in validate_options raise vol.Invalid( voluptuous.error.Invalid: 'value_template' must be set together with 'state_topic'. During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 160, in async_discover config = schema(discovery_payload) File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 218, in __call__ return self._exec((Schema(val) for val in self.validators), v) File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 341, in _exec raise e if self.msg is None else AllInvalid(self.msg, path=path) File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 337, in _exec v = func(v) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 276, in __call__ raise er.MultipleInvalid([e]) voluptuous.error.MultipleInvalid: 'value_template' must be set together with 'state_topic'.

Debug info
Version core-2021.6.1
Home Assistant OS 5.13
Supervisior Info-2021.05.04
Zigbee2MQTT version:1.18.1-1
Adapter hardware: CC2530_CC2591_20190523
Adapter firmware version: Z-Stack_3.0.x

**Comment by Koenkk** [comment] 2021-06-04 19:09
Dupe of https://github.com/Koenkk/zigbee2mqtt/issues/7680 (fixed in 1.19.0+)

**Closed by Koenkk** 2021-06-04 19:09 UTC
