### ISSUE TITLE
Template variable warning: 'dict object' has no attribute 'latest_version'

### ISSUE THREAD

**Issue by haforme** [Koenkk/zigbee2mqtt#15870] opened 2023-01-01 21:15 UTC
### What happened?

Upgrade to zigbee2mqtt version 1.29.0-1 from version 1.28.4-1 and started receiving error messages in the log. 

Template variable warning: 'dict object' has no attribute 'latest_version' when rendering '{{ value_json['update']['latest_version'] }}'

### What did you expect to happen?

No error messages.

### How to reproduce it (minimal and precise)

Started up zigbe2mqtt addon.

### Zigbee2MQTT version

1.29.0-1

### Adapter firmware version

Could not locate info requested for adapter using above link.

### Adapter

Conbee II

**Comment by DarwinData** [comment] 2023-01-01 22:57
Same here.  I have about 60 devices and a ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus and I can't tell which device is causing this same error.

**Comment by peterbogar** [comment] 2023-01-02 07:20
The same for me, with Sonoff

Source: helpers/template.py:589

**Comment by SVH-Powel** [comment] 2023-01-02 08:02
I have around 15000 messages each hour, so it is kind of filling up the log........

**Comment by Koenkk** [comment] 2023-01-02 08:53
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/15747

**Closed by Koenkk** 2023-01-02 08:53 UTC
Labels: problem
