### ISSUE TITLE
[Problem]: value_json template parsing errors and access to update of dict unsafe error

### ISSUE THREAD

**Issue by adekloet** [Koenkk/zigbee2mqtt#10351] opened 2021-12-25 09:48 UTC
### What happened?

core 12.5
Z2MQTT Current version: 1.22.1-1

Still has the problem with errors in the log for some devices

2021-12-25 10:31:43 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'value_json' is undefined when rendering '{{ value_json.battery }}'
2021-12-25 10:31:43 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'value_json' is undefined when rendering '{{ value_json.occupancy }}'
2021-12-25 10:31:43 ERROR (MainThread) [homeassistant.helpers.template] Error parsing value: 'value_json' is undefined (value: , template: {{ value_json.occupancy }})
2021-12-25 10:31:43 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'value_json' is undefined when rendering '{{ value_json.illuminance_above_threshold }}'
2021-12-25 10:31:43 ERROR (MainThread) [homeassistant.helpers.template] Error parsing value: 'value_json' is undefined (value: , template: {{ value_json.illuminance_above_threshold }})
2021-12-25 10:31:43 ERROR (MainThread) [homeassistant.helpers.template] Error parsing value: 'value_json' is undefined (value: , template: {{ value_json['update']['state'] == "available" }})
2021-12-25 10:32:11 ERROR (MainThread) [homeassistant.helpers.template] Error parsing value: access to attribute 'update' of 'dict' object is unsafe. (value: {"battery":100,"illuminance_above_threshold":false

also for the above attributes I get the dict error:

Error parsing value: access to attribute 'update' of 'dict' object is unsafe.

### What did you expect to happen?

no errors from the attributes of the sensor

### How to reproduce it (minimal and precise)

pair a motion sensor in this case to Z2MQTT 1.22.1 / core 12.5

### Zigbee2MQTT version

1.22.1

### Adapter firmware version

20210120

### Adapter

CC2652 RB

### Debug log

2021-12-25 10:31:43 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'value_json' is undefined when rendering '{{ value_json.battery }}'
2021-12-25 10:31:43 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'value_json' is undefined when rendering '{{ value_json.occupancy }}'
2021-12-25 10:31:43 ERROR (MainThread) [homeassistant.helpers.template] Error parsing value: 'value_json' is undefined (value: , template: {{ value_json.occupancy }})
2021-12-25 10:31:43 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'value_json' is undefined when rendering '{{ value_json.illuminance_above_threshold }}'
2021-12-25 10:31:43 ERROR (MainThread) [homeassistant.helpers.template] Error parsing value: 'value_json' is undefined (value: , template: {{ value_json.illuminance_above_threshold }})
2021-12-25 10:31:43 ERROR (MainThread) [homeassistant.helpers.template] Error parsing value: 'value_json' is undefined (value: , template: {{ value_json['update']['state'] == "available" }})
2021-12-25 10:32:11 ERROR (MainThread) [homeassistant.helpers.template] Error parsing value: access to attribute 'update' of 'dict' object is unsafe. (value: {"battery":100,"illuminance_above_threshold":false,"linkquality":144,"occupancy":true,"requested_brightness_level":254,"requested_brightness_percent":100,"update_available":null}, template: {{ value_json['update']['state'] == "available" }})

**Comment by Koenkk** [comment] 2021-12-25 14:57
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/9939, check if it is fixed in the latest dev branch, if not report it in https://github.com/Koenkk/zigbee2mqtt/issues/9939 with the HA logs + z2m debug logs at the moment this error is logged by HA. 

See https://www.zigbee2mqtt.io/guide/usage/debug.html on how to enable debug logging.

See https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html on how to switch to the dev branch

**Closed by Koenkk** 2021-12-25 14:57 UTC
Labels: problem
