### ISSUE TITLE
HomeAssistant: Invalid JSON 'OPEN' on Aqara Curtain ZNCLDJ11LM

### ISSUE THREAD

**Issue by wolverinevn** [Koenkk/zigbee2mqtt#4137] opened 2020-08-20 03:03 UTC
# Bug Report
## What happened
Can't control Aqara ZNCLDJ11LM Curtain Motor. Open (Up), Close (Down) and Stop do not work.

Add-on log:
```
Zigbee2MQTT:error 2020-08-20 09:45:28: Invalid JSON 'STOP', skipping...
Zigbee2MQTT:error 2020-08-20 09:45:28: Invalid JSON 'CLOSE', skipping...
Zigbee2MQTT:error 2020-08-20 09:53:29: Invalid JSON 'OPEN', skipping...
```

Set position works.

It used to work well before last edge-version uninstall/re-install (3 days ago).

## Debug Info
Zigbee2MQTT version: zigbee2mqtt-edge addon on Home Assistant
Adapter hardware: CC2530
Adapter firmware version:

**Comment by Koenkk** [comment] 2020-08-20 06:33
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/4123, should already be fixed in latest dev branch.

**Closed by Koenkk** 2020-08-20 06:33 UTC
