### ISSUE TITLE
Device with Zigbee model 'TS0203' and manufacturer name '_TZ3000_f1hmoyj4' is NOT supported

### ISSUE THREAD

**Issue by bambo86** [Koenkk/zigbee2mqtt#8295] opened 2021-08-07 18:25 UTC
## What happened

After the z2m update (Current version: 1.21.0-1 ), some of my door open sensors show as unsupported.
It is the TS0203 model
and it is in the 'zigbee-herdsman-converters' database in the tuya.js file that zigbee2mqtt uses.
So it should work

I don't know what's going on 🤔

When I have paired these sensors for the first time (about a month ago), they were also unsupported, and then I've paired they one more time and they worked normally as supported.

## What did you expect to happen
Pairing devices as supported

## Debug info
Zigbee2MQTT version: 1.21.0-1 
Adapter hardware: Conbee II
Adapter firmware version: deCONZ_ConBeeII_0x26680700.bin.GCF (30-Nov-2020 18:03)

**Comment by robert2s** [comment] 2021-08-08 08:51
Is a duplicate of #8266 and fixed in the dev branch. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by Koenkk** [comment] 2021-08-09 14:48
Already fixed in the dev branch indeed.

**Closed by Koenkk** 2021-08-09 14:48 UTC
Labels: problem
