### ISSUE TITLE
Add device_class to Temperature and Humidity sensors in homeassistant.js

### ISSUE THREAD

**Issue by RodBr** [Koenkk/zigbee2mqtt#521] opened 2018-10-22 01:08 UTC
Can "device_class: temperature" and "device_class: humidity" be added to the temperature and humidity sensors in homeassistant.js and remove the custom icon setting?  This will bring them into line with default appearance for temperature and humidity sensors from non-MQTT sensors.

**Comment by felixtriller** [comment] 2018-10-22 21:04
This is a duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/522

**Comment by RodBr** [comment] 2018-10-23 04:34
Duplicate

**Closed** 2018-10-23 04:34 UTC
