### ISSUE TITLE
new version 1.31 zigbee2mqtt doesn't start

### ISSUE THREAD

**Issue by Alessandro1983** [Koenkk/zigbee2mqtt#17894] opened 2023-06-03 07:38 UTC
### What happened?

after uploaded to the new version 1.31 the add-on in home assistant doesn't start, the log report this:

[09:03:11] INFO: [32mPreparing to start...[0m
[09:03:14] INFO: [32mSocat not enabled[0m
[09:03:21] INFO: [32mStarting Zigbee2MQTT...[0m
/app/data/extension/externally-loaded.js:71
      .enum("self_test", ea.STATE, Object.values(tuya.tuyaHPSCheckingResult))
                                          ^
TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at /app/data/extension/externally-loaded.js:71:43
    at Script.runInContext (node:vm:141:12)
    at Script.runInNewContext (node:vm:146:17)
    at Object.runInNewContext (node:vm:306:38)
    at loadModuleFromText (/app/lib/util/utils.ts:150:8)
    at loadModuleFromFile (/app/lib/util/utils.ts:157:12)
    at Object.getExternalConvertersDefinitions (/app/lib/util/utils.ts:167:25)
    at getExternalConvertersDefinitions.next (<anonymous>)
    at new ExternalConverters (/app/lib/extension/externalConverters.ts:12:20)

I don't know what this means, I restored the old version (1.30.4) and the add-on works.

### Zigbee2MQTT version

1.31

### Adapter firmware version

20201010

### Adapter

zStack30x

**Comment by Koenkk** [comment] 2023-06-03 15:43
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/17863#issuecomment-1573279515

**Closed by Koenkk** 2023-06-03 15:43 UTC
Labels: problem
