### ISSUE TITLE
Samotech SM323 v2 needs power metering

### ISSUE THREAD

**Issue by triblondon** [Koenkk/zigbee2mqtt#19599] opened 2023-11-06 17:15 UTC
### What happened?

I bought a Samotech SM323 v2 dimmer switch, hooked it up to my zigbee network and it was [correctly recognised by Z2M](https://www.zigbee2mqtt.io/devices/SM323.html).  The exposes tab lists `state`, `brightness`, `power_on_behavior`, `effect`, and `linkquality`.   In HA, these map to the following entities:

<img width="860" alt="image" src="https://github.com/Koenkk/zigbee2mqtt/assets/1735391/278eb438-782d-4797-9118-3db3dfe98d5e">

### What did you expect to happen?

The [Samotech product page](https://www.samotech.co.uk/products/zigbee-dimmer-switch-hue-compatible/) for the new v2 ("new for 2024") version states that it has power metering, and when I asked them for support they referred me to a screenshot of a test Home assistant instance where the device was added with ZHA, where it does indeed appear to expose power metering entities:

![image](https://github.com/Koenkk/zigbee2mqtt/assets/1735391/c2b65709-f5b2-4bdb-87a3-548f2355eac7)

So I expected to see power metering on the 'exposes' tab of Z2M, and I expected to see power metering entities on the HA device screen.

### How to reproduce it (minimal and precise)

Buy an SM323 v2, connect to Z2M.  Observe the 'Exposes' tab.

### Zigbee2MQTT version

1.32.2

### Adapter firmware version

20210120

### Adapter

https://slae.sh/projects/cc2652/

**Comment by djkemp** [comment] 2023-11-23 11:43
Very interested to see this implemented also as about to pull the trigger and purchase a few of these.

**Comment by Koenkk** [comment] 2023-11-23 17:50
could you provide the data/database.db entry of this device?

**Comment by triblondon** [comment] 2023-11-27 15:04
@Koenkk can you refer me to instructions for how to do that?

**Comment by Koenkk** [comment] 2023-11-27 16:57
you can find it next to your z2m configuration.yaml

**Comment by Koenkk** [comment] 2023-12-13 19:16
Could you check if the issue is fixed with the following [external converter](https://gist.github.com/Koenkk/0d46ad10a98424c8c839094fadcd0e7e): 

- make sure you are using z2m 1.34.0
- save this as file next to `configuration.yaml` as `ext_converter.js`
- add it to `configuration.yaml`:
```yaml
external_converters:
  - ext_converter.js
```
- start z2m, check if issue is fixed

**Comment by mpartington** [comment] 2023-12-13 19:29
Failed to restart, maybe I've done something wrong?

SyntaxError: Identifier 'tuya' has already been declared
    at new Script (node:vm:100:7)
    at createScript (node:vm:265:10)
    at Object.runInNewContext (node:vm:306:10)
    at loadModuleFromText (/app/lib/util/utils.ts:154:8)
    at loadModuleFromFile (/app/lib/util/utils.ts:161:12)
    at Object.getExternalConvertersDefinitions (/app/lib/util/utils.ts:171:25)
    at getExternalConvertersDefinitions.next (<anonymous>)
    at new ExternalConverters (/app/lib/extension/externalConverters.ts:12:20)
    at new Controller (/app/lib/controller.ts:84:58)
    at start (/app/index.js:106:18)

**Comment by Koenkk** [comment] 2023-12-13 19:31
whoops, fixed the ext converter.

**Comment by mpartington** [comment] 2023-12-13 19:35
some different errors

[19:33:50] INFO: Starting Zigbee2MQTT...
/app/data/extension/externally-loaded.js:21
    extend: [light({configureReporting: true}), electricityMeter()],
            ^

ReferenceError: light is not defined
    at /app/data/extension/externally-loaded.js:21:13
    at Script.runInContext (node:vm:141:12)
    at Script.runInNewContext (node:vm:146:17)
    at Object.runInNewContext (node:vm:306:38)
    at loadModuleFromText (/app/lib/util/utils.ts:154:8)
    at loadModuleFromFile (/app/lib/util/utils.ts:161:12)
    at Object.getExternalConvertersDefinitions (/app/lib/util/utils.ts:171:25)
    at getExternalConvertersDefinitions.next (<anonymous>)
    at new ExternalConverters (/app/lib/extension/externalConverters.ts:12:20)
    at new Controller (/app/lib/controller.ts:84:58)

**Comment by Koenkk** [comment] 2023-12-13 19:37
are you using z2m 1.34.0?

**Comment by mpartington** [comment] 2023-12-13 19:39
<img width="448" alt="image" src="https://github.com/Koenkk/zigbee2mqtt/assets/106986397/85588c60-2013-45ff-b114-26867f9fcc2a">
I think so, this is from the add on section

**Comment by Koenkk** [comment] 2023-12-13 19:48
Updated https://gist.github.com/Koenkk/0d46ad10a98424c8c839094fadcd0e7e, can you try again?

**Comment by mpartington** [comment] 2023-12-13 19:53
Looks good this time thanks, although it probably doesn't need the colour setting

<img width="551" alt="image" src="https://github.com/Koenkk/zigbee2mqtt/assets/106986397/8bad1fcc-c21c-4528-8880-29fcfd33e83a">
<img width="541" alt="image" src="https://github.com/Koenkk/zigbee2mqtt/assets/106986397/423bc28f-6496-4857-9318-fa1af609f850">

**Comment by mpartington** [comment] 2023-12-14 07:57
Working well, but am getting these errors. Imagine it's something simple, but outside my knowledge how to fix
![Screenshot_2023-12-14-07-50-15-274_io homeassistant companion android](https://github.com/Koenkk/zigbee2mqtt/assets/106986397/9607966e-eca4-43b7-8b86-0c3eda891e6c)

**Comment by Koenkk** [comment] 2023-12-15 19:09
> Another observation is the energy field doesn't seem correct (I haven't used 11kWh today on a 20W light)

This is the total consumption of that plug, not of today.

**Comment by mpartington** [comment] 2023-12-16 19:28
Thanks. It was a brand new switch, just installed, so not sure where it's got the consumption from. Not a major issue and can work around it

**Comment by Koenkk** [comment] 2023-12-17 08:17
Great, I've integrated the changes.

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

**Closed by Koenkk** 2023-12-17 08:17 UTC
Labels: problem

**Comment by viharm** [comment] 2024-01-08 14:38
Hi @Koenkk, thanks. I am using this device in HA (via the Z2M add-on) through the external converter you have linked above. Since this has been merged, can we remove the relevant external converter configuration if this is part of the release?

Also, would these power/energy related entities be exposed and available within HA?

**Comment by Koenkk** [comment] 2024-01-09 19:31
You can remove the external converter, electrical measurements entities will be available in HA

**Comment by james-fry** [comment] 2024-01-13 23:46
I have ~10 of the old version of the SM323 without power measurement capability.
I'm seeing errors in log about haElectricalMeasurement now:
`Zigbee2MQTT:error 2024-01-13 23:41:48: Failed to configure 'Kitchen Island Plinth Strips', attempt 1 (Error: Device 0xf4b3b1fffef5f8d6 has no input cluster haElectricalMeasurement
    at getEndpointsWithInputCluster (/app/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:18:15)
    at configure (/app/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:196:36)
    at Object.configure (/app/node_modules/zigbee-herdsman-converters/src/index.ts:140:31)
    at Configure.configure (/app/lib/extension/configure.ts:120:13)
    at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:167:17))`
Is this related?

**Comment by viharm** [comment] 2024-01-14 00:15
> You can remove the external converter, electrical measurements entities will be available in HA

I can't seem to find these entities/attributes in HA. I've checked the developer tools and these are not exposed. Am I doing something wrong? I'm happy to open a new issues, but trying to prevent additional admin if it's not needed.

**Comment by mpartington** [comment] 2024-01-14 07:36
@viharm, you will need to enable them in the MQTT device. They seem to be turned off by default.

![Screenshot_2024-01-14-07-33-50-904_io homeassistant companion android](https://github.com/Koenkk/zigbee2mqtt/assets/106986397/9cf9d38d-d3d1-4cf1-9ae6-2ddfdbcb67c5)

**Comment by viharm** [comment] 2024-01-14 09:11
> @viharm, you will need to enable them in the MQTT device. They seem to be turned off by default.
> 
> 

Thanks @mpartington. However the diagnostic panel is merely read-only, and there are no configurable settings to "enable" reading the power metrics.

Fig.1 MQTT Device screen
![image](https://github.com/Koenkk/zigbee2mqtt/assets/2663937/e78306fb-7f51-4ecf-b179-d9993ca92ac7)

Fig. 2 Z2M device exposed metrics
![image](https://github.com/Koenkk/zigbee2mqtt/assets/2663937/0a5d5eb2-83cb-45cc-ac13-1b31c0561787)

I may have to unpair and repair the device, which I was trying to avoid, as this will require opening the wall face plate.

Are there any other alternatives?

**Comment by mpartington** [comment] 2024-01-14 10:57
Maybe ive got the wrong end of the stick, but I just opened up the diagnostic entity and 'enabled' it. This created an entity that can be monitored for me. I just enabled voltage and current this morning seeing this.
![Uploading Screenshot_2024-01-14-10-56-59-013_io.homeassistant.companion.android.jpg…]()

**Comment by mpartington** [comment] 2024-01-14 10:59
![Screenshot_2024-01-14-10-56-17-684_io homeassistant companion android](https://github.com/Koenkk/zigbee2mqtt/assets/106986397/033f248f-9852-4efe-b587-671cf7cd002a)

![Uploading Screenshot_2024-01-14-10-56-59-013_io.homeassistant.companion.android.jpg…]()

**Comment by mpartington** [comment] 2024-01-14 11:00
![Screenshot_2024-01-14-10-56-59-013_io homeassistant companion android](https://github.com/Koenkk/zigbee2mqtt/assets/106986397/b7d11f2c-e3a2-4be5-809c-12205174b5a6)

**Comment by mpartington** [comment] 2024-01-14 11:08
![Screenshot_2024-01-14-11-06-43-916_io homeassistant companion android~2](https://github.com/Koenkk/zigbee2mqtt/assets/106986397/40aa3d18-e8d1-4f86-ac68-d02410c98045)

**Comment by mpartington** [comment] 2024-01-14 11:11
![Screenshot_2024-01-14-11-06-43-916_io homeassistant companion android~2](https://github.com/Koenkk/zigbee2mqtt/assets/106986397/3eddc09e-ccc9-479a-8a79-8136d8ea24a8)

Then
![Screenshot_2024-01-14-11-06-51-477_io homeassistant companion android~2](https://github.com/Koenkk/zigbee2mqtt/assets/106986397/cce8903d-1857-4083-b914-0af02156d4af)

**Comment by viharm** [comment] 2024-01-14 17:20
Yes! That's it! I'm sorry I'm still quite new to HA, so didn't realise that clicking on the disable entities from the dashboard view and drilling through to the "cog" icon allowed enabling. Now I realise what you meant in your [earlier comment](https://github.com/Koenkk/zigbee2mqtt/issues/19599#issuecomment-1890872754) when you said they are "turned off" by default. Thanks for your patience with me.

**Comment by viharm** [comment] 2024-01-14 17:20
I've enabled it, and am waiting for the values to come through over the next few minutes.

**Comment by viharm** [comment] 2024-01-14 17:32
Success! Thanks so much.

![image](https://github.com/Koenkk/zigbee2mqtt/assets/2663937/4fe24fcb-ba41-4d21-83c0-a58755856a08)
