### ISSUE TITLE
[Problem]: TUYA Valve - time is not synced

### ISSUE THREAD

**Issue by kremik** [Koenkk/zigbee2mqtt#10712] opened 2022-01-11 10:58 UTC
### What happened?

Tuya thermostat valves (https://www.zigbee2mqtt.io/devices/TS0601_thermostat.html#tuya-ts0601_thermostat) time and day of the week are no longer synced with the server. I wonder why the heating is not set according to the time plan and according to info in the valve the time was totally wrong for each valve. 
I think it should be synced with the server time via Z2M.

### What did you expect to happen?

I think date and time it should be synced with the server time via Z2M.

### How to reproduce it (minimal and precise)

Check the valve through its own menu.

### Zigbee2MQTT version

1.22.2 commit: 301ba14b

### Adapter firmware version

20210211

### Adapter

N/A

### Debug log

N/A

**Comment by Koenkk** [comment] 2022-01-11 17:46
Duplicate of #10489

**Closed by Koenkk** 2022-01-11 17:46 UTC
Labels: problem
