### ISSUE TITLE
Ability to set friendly name through mqtt

### ISSUE THREAD

**Issue by thinkl33t** [Koenkk/zigbee2mqtt#202] opened 2018-07-19 21:52 UTC
We have the ability to enable joining through mqtt already, but joined devices get long random names.

It would be useful to be able to set the friendly name of newly-joined devices in a similar way, for example `mosquitto_pub -t 'zigbee2mqtt/0x00158d0001e7b10d/friendly_name/set' -m 'office-button'`

I ask for this as it prevents having to restart zigbee2mqtt after changing the config file.

**Comment by tb-killa** [comment] 2018-07-20 04:52
Seems to be related to this https://github.com/Koenkk/zigbee2mqtt/issues/177.??

**Comment by Koenkk** [comment] 2018-07-20 20:53
Closing, duplicate of #177

**Closed by Koenkk** 2018-07-20 20:53 UTC
