### ISSUE TITLE
Aqara door / window sensor not recognized

### ISSUE THREAD

**Issue by MysterePMS** [Koenkk/zigbee2mqtt#9484] opened 2021-11-03 17:33 UTC
Hello,
I just received 16 Aqara door / window sensor
Today I only installed 7, but they are not recognized ...
![image](https://user-images.githubusercontent.com/74379147/140155347-e6c52f1e-35a9-48a9-a598-14e992adccb4.png)
![image](https://user-images.githubusercontent.com/74379147/140161941-4ec54da0-8267-4822-9ef1-5c418c6433f6.png)

```
{"id":44,"type":"EndDevice","ieeeAddr":"0x54ef44100025c29a","nwkAddr":31003,"manufId":4447,"manufName":"LUMI","powerSource":"Battery","modelId":"lumi.magnet.acn001","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[0,1,3,1280,64704],"outClusterList":[3,25],"clusters":{"genBasic":{"attributes":{"appVersion":4,"modelId":"lumi.magnet.acn001","manufacturerName":"LUMI","powerSource":3,"zclVersion":3,"stackVersion":2}},"ssIasZone":{"attributes":{"iasCieAddr":"0x0000000000000000","zoneState":0}},"aqaraOpple":{"attributes":{"247":{"type":"Buffer","data":[1,33,112,11,3,40,25,4,33,0,0,5,33,1,0,8,33,4,0,10,33,134,217,12,32,30,100,16,0]}}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":4,"stackVersion":2,"zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1635954601427}
{"id":45,"type":"EndDevice","ieeeAddr":"0x54ef44100025c5e3","nwkAddr":38417,"manufId":4447,"manufName":"LUMI","powerSource":"Battery","modelId":"lumi.magnet.acn001","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[0,1,3,1280,64704],"outClusterList":[3,25],"clusters":{"genBasic":{"attributes":{"appVersion":4,"modelId":"lumi.magnet.acn001","manufacturerName":"LUMI","powerSource":3,"zclVersion":3,"stackVersion":2,"hwVersion":0}},"aqaraOpple":{"attributes":{"247":{"type":"Buffer","data":[1,33,132,11,3,40,25,4,33,0,0,5,33,1,0,8,33,4,0,10,33,147,105,12,32,30,100,16,0]}}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":4,"stackVersion":2,"hwVersion":0,"zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1635954818486}
{"id":46,"type":"EndDevice","ieeeAddr":"0x54ef44100025be90","nwkAddr":43658,"manufId":4151,"manufName":"LUMI","powerSource":"Battery","modelId":"lumi.magnet.acn001","epList":[1],"endpoints":{"1":{"epId":1,"inClusterList":[],"outClusterList":[],"clusters":{"genBasic":{"attributes":{"appVersion":4,"modelId":"lumi.magnet.acn001"}},"aqaraOpple":{"attributes":{"247":{"type":"Buffer","data":[1,33,112,11,3,40,25,4,33,0,0,5,33,1,0,8,33,4,0,10,33,212,33,12,32,30,100,16,0]}}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":4,"interviewCompleted":true,"meta":{},"lastSeen":1635955131352}
{"id":47,"type":"EndDevice","ieeeAddr":"0x54ef44100025be78","nwkAddr":59327,"manufId":4151,"manufName":"LUMI","powerSource":"Battery","modelId":"lumi.magnet.acn001","epList":[1],"endpoints":{"1":{"epId":1,"inClusterList":[],"outClusterList":[],"clusters":{"genBasic":{"attributes":{"appVersion":4,"modelId":"lumi.magnet.acn001"}},"aqaraOpple":{"attributes":{"247":{"type":"Buffer","data":[1,33,88,11,3,40,25,4,33,0,0,5,33,1,0,8,33,4,0,10,33,55,100,12,32,30,100,16,0]}}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":4,"interviewCompleted":true,"meta":{},"lastSeen":1635955589358}
{"id":48,"type":"EndDevice","ieeeAddr":"0x54ef44100025d857","nwkAddr":49312,"manufId":4447,"manufName":"LUMI","powerSource":"Battery","modelId":"lumi.magnet.acn001","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[0,1,3,1280,64704],"outClusterList":[3,25],"clusters":{"genBasic":{"attributes":{"appVersion":4,"modelId":"lumi.magnet.acn001","manufacturerName":"LUMI","powerSource":3,"zclVersion":3,"stackVersion":2,"hwVersion":0}},"ssIasZone":{"attributes":{"iasCieAddr":"0x0000000000000000","zoneState":0}},"aqaraOpple":{"attributes":{"247":{"type":"Buffer","data":[1,33,96,11,3,40,25,4,33,0,0,5,33,1,0,8,33,4,0,10,33,17,16,12,32,30,100,16,0]}}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":4,"stackVersion":2,"hwVersion":0,"zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1635956044545}
{"id":49,"type":"EndDevice","ieeeAddr":"0x54ef44100025d623","nwkAddr":64294,"manufId":4447,"manufName":"LUMI","powerSource":"Battery","modelId":"lumi.magnet.acn001","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[0,1,3,1280,64704],"outClusterList":[3,25],"clusters":{"genBasic":{"attributes":{"modelId":"lumi.magnet.acn001","manufacturerName":"LUMI","powerSource":3,"zclVersion":3,"appVersion":4,"stackVersion":2}},"aqaraOpple":{"attributes":{"247":{"type":"Buffer","data":[1,33,185,11,3,40,25,4,33,0,0,5,33,1,0,8,33,4,0,10,33,55,100,12,32,30,100,16,0]}}},"ssIasZone":{"attributes":{"iasCieAddr":"0x0000000000000000","zoneState":0}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":4,"stackVersion":2,"zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1635958529480}
{"id":50,"type":"EndDevice","ieeeAddr":"0x54ef44100025d3a3","nwkAddr":44207,"manufId":4447,"manufName":"LUMI","powerSource":"Battery","modelId":"lumi.magnet.acn001","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[0,1,3,1280,64704],"outClusterList":[3,25],"clusters":{"genBasic":{"attributes":{"appVersion":4,"modelId":"lumi.magnet.acn001","manufacturerName":"LUMI","powerSource":3,"stackVersion":2,"hwVersion":0}},"ssIasZone":{"attributes":{"iasCieAddr":"0x0000000000000000","zoneState":0}},"aqaraOpple":{"attributes":{"247":{"type":"Buffer","data":[1,33,73,11,3,40,25,4,33,0,0,5,33,1,0,8,33,4,0,10,33,212,33,12,32,30,100,16,0]}}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":4,"stackVersion":2,"hwVersion":0,"interviewCompleted":true,"meta":{},"lastSeen":1635959489646}
```

Jeedom 4.1.27
Version Zigbee2MQTT     1.22.0 commit: b3e9afaf
Type de Coordinateur     ConBee2/RaspBee2
Révision du Coordinateur     0x26720700
Version Interface     0.6.30

**Comment by Koenkk** [comment] 2021-11-03 18:41
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/9274

**Closed by Koenkk** 2021-11-03 18:41 UTC
Labels: problem
