### ISSUE TITLE
Aqara Vibration Sensor no longer report x/y access after upgrading to 1.40.2-1

### ISSUE THREAD

**Issue by kirashogun** [Koenkk/zigbee2mqtt#24298] opened 2024-10-12 05:52 UTC
### What happened?

Upgraded to 1.40.2-1 and the aqara vibration sensor (lumi.vibration.aq1) no longer reports any stat other than binary "vibration" field.

    "angle": 35,
    "angle_x": null,
    "angle_x_absolute": null,
    "angle_y": null,
    "angle_y_absolute": null,
    "angle_z": null,
    "linkquality": 172,
    "vibration": false,
    "x_axis": 0,
    "y_axis": 0,
    "z_axis": 0

### What did you expect to happen?

I expect Angle x y z to have values and not null.

### How to reproduce it (minimal and precise)

Upgrade to 1.40.2-1 (HA 2024.10.2).

### Zigbee2MQTT version

1.40.2-1

### Adapter firmware version

 7.3.1.0 build 176

### Adapter

 EZSP v12

### Setup

HA Add-on

**Comment by Koenkk** [comment] 2024-10-12 11:28
Duplicate of https://github.com/Koenkk/zigbee2mqtt/discussions/24185

**Closed by Koenkk** 2024-10-12 11:28 UTC
Labels: problem
