### ISSUE TITLE
[TS130F] Regression since last update

### ISSUE THREAD

**Issue by DarkrysVakarian** [Koenkk/zigbee2mqtt#23277] opened 2024-07-07 00:51 UTC
### What happened?

Hello,

I use Z2M on Home Assistant, and it seems that there is a regression since the last update concerning the TS130F shutter controls.

Z2M no longer indicates the correct state for the controls.
For example, today, out of my 7 shutters, 2 returned the correct state and all the others indicated the opposite state (closed when they were open).

Using the specific Invert Covert parameter also gives false results.

Thnaks for your help.

### Zigbee2MQTT version

1.39.0

### Adapter firmware version

7.3.1.0 build 176

### Adapter

Home Assistant Yellow built-in adapter

### Setup

Add-on on Homa Assistant

**Comment by adrienvsj** [comment] 2024-07-13 06:37
@Koenkk same error here. But I notice this problem since HomeAssistant 2024.6.0.

**Comment by Koenkk** [comment] 2024-07-15 19:56
Could you provide the debug log when closing them and the incorrect state is reported?

See [this](https://www.zigbee2mqtt.io/guide/configuration/logging.html) on how to enable debug logging.

**Comment by DarkrysVakarian** [comment] 2024-07-15 23:52
Hello,

There is a debug file when I close my shutter maned "Volet roulant - Véranda porte".
[log.txt](https://github.com/user-attachments/files/16241376/log.txt)

But after all I don't know if it's Z2M fault or HA, because on Z2M the state seams to be right : 
<img width="811" alt="Capture d’écran 2024-07-16 à 01 49 59" src="https://github.com/user-attachments/assets/1815707f-3e11-4fcf-9103-50631c3b85f7">

But HA say it's open : 
<img width="602" alt="Capture d’écran 2024-07-16 à 01 50 15" src="https://github.com/user-attachments/assets/25d36539-33d5-4e04-a2d6-5271260d9b94">

@adrienvsj hum you maybe right, I've the problem since a HA update

Thanks :)

**Comment by Koenkk** [comment] 2024-07-16 19:44
Is this without `invert_cover` being set? When:
- cover is closed, position should be 0
- cover is open, position should be 100

HA docs; https://www.home-assistant.io/integrations/cover.mqtt/#position_closed

**Comment by DarkrysVakarian** [comment] 2024-07-16 23:11
Indeed, my screen was taken witout invert_covert set.

**Comment by Koenkk** [comment] 2024-07-17 19:26
Then it looks to be an HA issue

**Comment by adrienvsj** [comment] 2024-07-17 20:02
Hello @Koenkk @DarkrysVakarian 
I just found the commit (https://github.com/home-assistant/core/pull/118044) on homeassistant core that produces the bug. It has been present since HomeAssistant version 2024.6.0b0, as I suspected.
I'm going to open an issue about this bug and I'm currently working on a fix.
In the meantime, I advise you to go back to version 2024.5.X (I think the latest version is 2024.5.5).

**Comment by DarkrysVakarian** [comment] 2024-07-17 23:17
Hello @Koenkk @adrienvsj 
Thanks for your reply.

@adrienvsj  I just donwdrading to version 2024.5.5 thank you.

**Comment by Koenkk** [comment] 2024-07-18 18:37
Great that you've found the root cause, then I will close this as it's not something that can be fixed by z2m.

**Closed by Koenkk** 2024-07-18 18:37 UTC
Labels: problem

**Comment by adrienvsj** [comment] 2024-07-19 16:50
@DarkrysVakarian for your information I have opened a PR to fix the problem: https://github.com/home-assistant/core/pull/122192

**Comment by ElCaplar** [comment] 2024-08-16 06:33
Update for this problem. Since the last version i have updated : 
Core 2024.8.1
Supervisor 2024.08.0
Operating System 13.0
Interface utilisateur 20240809.0
Version de Zigbee2MQTT [1.39.1]

Everything seems to be ok.
