### ISSUE TITLE
Eco-dim 07 not supported anymore

### ISSUE THREAD

**Issue by frager82** [Koenkk/zigbee2mqtt#7476] opened 2021-05-15 09:06 UTC
It did work correct, now they are defined as dimmer switch ZB-3.0 and they don't work.

Not in supported devices also... But this page still exists:
https://www.zigbee2mqtt.io/devices/Eco-Dim.07.html

**Comment by Koenkk** [comment] 2021-05-15 12:26
Duplicate of #7325

**Closed by Koenkk** 2021-05-15 12:26 UTC
Labels: new device support
