### ISSUE TITLE
Eco-DIM.07 Led dimmer no longer works

### ISSUE THREAD

**Issue by johanvh83** [Koenkk/zigbee2mqtt#7367] opened 2021-05-06 19:20 UTC
Problem about Eco-DIM.07 (https://www.ecodim.nl/eco-dim07-zigbee-basic.html).
It way automatically joined and supported and worked fine for some weeks...

Some days ago the entity in Home Assistant became unavailable. I checked Zigbee2MQTT and the device was changed into 'unsupported' device.

I removed the device, activated 'join', reset the Eco-DIM.07 and put it in again in link/sync mode.
Zigbee2Mqtt did an interview. The debug log: https://pastebin.com/ga80ce0r

Zigbee2MQTT version: 1.18.3-1
Adapter hardware: slae.sh_cc2652rb_stick
Adapter firmware version: unknown

This is another log from Home Assistant: https://pastebin.com/XTzzKjbm

Please advise what to do.

Many thanks,
Johan

**Comment by Koenkk** [comment] 2021-05-06 19:40
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/7325

**Closed by Koenkk** 2021-05-06 19:40 UTC
Labels: problem
