### ISSUE TITLE
Problem with devices which contain "/"

### ISSUE THREAD

**Issue by berrywhite96** [Koenkk/zigbee2mqtt#562] opened 2018-11-03 23:52 UTC
Named a device with an "/", but zigbee2mqtt cant set new settings with a mqtt msg. So maybe you give the user a warning that you cant rename a device with "/" in the friendly name or you fix this problem :D.

My log (I know I should have post it on pastebin, but are just two lines):
`zigbee2mqtt:info 2018-11-4 00:40:59 MQTT publish, topic: 'zigbee2mqtt/room_1/hue_go_1', payload: '{"state":"OFF","brightness":254,"color_temp":153,"color":{"x":0.156,"y":0.142}}'
  zigbee2mqtt:error 2018-11-4 00:42:16 Cannot handle 'zigbee2mqtt/room_1/hue_go_1/set' because deviceID of 'room_1' cannot be found`

I hope I can find all bugs and help this project, really like this project very good work!

**Comment by Koenkk** [comment] 2018-11-04 07:47
Which version are you running?

**Comment by berrywhite96** [comment] 2018-11-04 11:11
Installed it yesterday step by step with the wiki, so I have the clone from the master.
Btw. I changed the friendly name with the configuration.yaml.

**Comment by dirstel** [comment] 2018-11-05 11:56
Currently nested Topics are not supported:
Duplicate of #470

**Comment by Koenkk** [comment] 2018-11-07 12:52
As @dirstel mentioned, duplicate of #470

**Closed by Koenkk** 2018-11-07 12:52 UTC
