### ISSUE TITLE
Homeassistant - Dict Object has no attribute

### ISSUE THREAD

**Issue by kaykoch** [Koenkk/zigbee2mqtt#7073] opened 2021-04-14 07:53 UTC
I use Home assistant with Zigbee2mqtt-AddOn
Current version: 1.18.2-1

I got following Warnings in Homeasistant Log:
```
...
...
2021-04-14 09:24:35 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'linkquality' when rendering '{{ value_json.linkquality }}'
2021-04-14 09:24:36 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'linkquality' when rendering '{{ value_json.linkquality }}'
2021-04-14 09:24:43 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'requested_brightness_level' when rendering '{{ value_json.requested_brightness_level }}'
2021-04-14 09:24:43 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'requested_brightness_percent' when rendering '{{ value_json.requested_brightness_percent }}'
...
...
```

They are throwing with different variables (equested_brightness_percent,requested_brightness_level ,linkquality etc.)
They were starting after update to:
core-2021.4.4

I guess, Hassio changed  exception handling.
I had an if/else Block, which worked up to core-2021.4.4. Then it throws same Warning
```
        {% if  trigger.event.data.room  %}
            {{ trigger.event.data.room }}
        {% else %}
            {{ trigger.event.data._intent.siteId }}
        {% endif %} 
```
I changed it to:
```
        {% if  trigger.event.data.room is defined  %}
            {{ trigger.event.data.room }}
        {% else %}
            {{ trigger.event.data._intent.siteId }}
        {% endif %}
```
That works and no warning any more
I guess, after core-2021.4.4, all variables needs to be checked. 
I hoped that helps

**Comment by Koenkk** [comment] 2021-04-14 14:47
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/6987

**Closed by Koenkk** 2021-04-14 14:47 UTC
Labels: problem
