### ISSUE TITLE
1.16.0 Not connected to MQTT server!

### ISSUE THREAD

**Issue by rickkdotnet** [Koenkk/zigbee2mqtt#4876] opened 2020-11-04 20:29 UTC
## What happened

Stopped z2m 1.15.0 container, upgraded z2m docker image to 1.16.0, started the new z2m and suddenly z2m does not want to connect to my mosquitto mqtt broker. The logfile says: 
Not connected to MQTT server!

After downgrading it's connecting to mosquitto again 
without issues. 

Se log: [zigbee2mqtt-log.txt](https://github.com/Koenkk/zigbee2mqtt/files/5490344/zigbee2mqtt-log.txt)

## What did you expect to happen
I expected zigbee2mqtt to connect to the mosquitto broker

## How to reproduce it (minimal and precise)

- stop z2m
- use the attached config [zigbee2mqtt-cfg.txt](https://github.com/Koenkk/zigbee2mqtt/files/5490324/zigbee2mqtt-cfg.txt)
- upgrade to 1.16.0 
- start z2m

## Debug info
Zigbee2MQTT version: 1.16.0
Adapter hardware: CC2531
Adapter firmware version: 20190619

**Comment by Koenkk** [comment] 2020-11-05 11:36
Duplicate of https://github.com/danielwelch/hassio-zigbee2mqtt/issues/460

**Closed by Koenkk** 2020-11-05 11:36 UTC
Labels: problem
