### ISSUE TITLE
GWA1531 Shutter not reporting position

### ISSUE THREAD

**Issue by frabnet** [Koenkk/zigbee2mqtt#12157] opened 2022-04-12 15:23 UTC
### What happened?

Hi, I have 2 GWA1531_Shutter.

If I use them from:
- Physical buttons connected to the unit
- OPEN CLOSE STOP buttons on Zigbee2mqtt Web ui

The new position is not reported in Zigbee2mqtt.

If I click the "Sync" button in Zigbee2mqtt Web UI, the position is updated immediately (also clicking many times i can see the progress in real time).

This causes me some troubles: I can't see if my shutters are closed or opened.

### What did you expect to happen?

I expect the position of the shutter updated in real time or so.

### How to reproduce it (minimal and precise)

Join a GWA1531 to the network, click CLOSE on the web ui. The shutter closes, but the position is still 100 opened.

### Zigbee2MQTT version

1.25.1

### Adapter firmware version

20220219

### Adapter

Electrolama zig-a-zig-ah! CC2652R

### Debug log

Error Failed to configure 'tapparella_studio', attempt 4 (Error: ConfigureReporting 0x000d6f0015275aa9/1 genLevelCtrl([{"attribute":"currentLevel","minimumReportInterval":0,"maximumReportInterval":3600,"reportableChange":1}], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE') at Endpoint.checkStatus (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:317:28) at Endpoint.configureReporting (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:649:22) at Object.brightness (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/lib/reporting.js:76:9) at Object.configure (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/devices/gewiss.js:43:13) at Configure.configure (/opt/zigbee2mqtt/lib/extension/configure.ts:115:13) at Configure.onMQTTMessage (/opt/zigbee2mqtt/lib/extension/configure.ts:55:21))

**Comment by CiccioDroid** [comment] 2022-05-20 14:15
I have the same problem with same device, zigbee2mqtt version 1.24.0 receiver conbee 2

**Comment by Vitani** [comment] 2022-06-13 11:09
I have the same issue, but for [TuYa TS0601_cover](https://www.zigbee2mqtt.io/devices/TS0601_cover.html)

Was working fine a couple of weeks ago, and recently stopped reporting position.

**Comment by Vitani** [comment] 2022-07-04 07:54
As of 1.26.0, this appears to be fixed for me

**Comment by CiccioDroid** [comment] 2022-07-04 20:57
@Vitani your device is different from ours and appears in the 1.26.0 changelog fixes. The device mentioned in this issue is the Gewiss GWA1531 that reporting position only if it's setted from z2m with setPosition feature, but not if button on the wall is pressed.

**Comment by CiccioDroid** [comment] 2022-08-08 23:08
Hi koenkk i opened the file gewiss.js and i see this line of code:
await reporting.brightness(endpoint);
The devide does not report brightness and this line is mentioned on the error, can you remove it and send to me the new code for testing?
I have noticed another thing, when i refresh manually the shutter position i get the correct value. Why?

Thank you

**Comment by Koenkk** [comment] 2022-08-09 14:12
Could you check if the issue is fixed with the following external converter:

```js
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const ota = require('zigbee-herdsman-converters/lib/ota');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['GWA1531_Shutter'],
    model: 'GWA1531',
    description: 'Shutter actuator',
    vendor: 'Gewiss',
    fromZigbee: [fz.cover_position_tilt, fz.ignore_basic_report],
    toZigbee: [tz.cover_state, tz.cover_position_tilt],
    configure: async (device, coordinatorEndpoint, logger) => {
        const endpoint = device.getEndpoint(1);
        await reporting.bind(endpoint, coordinatorEndpoint, ['closuresWindowCovering']);
        await reporting.currentPositionLiftPercentage(endpoint);
    },
    exposes: [e.cover_position()],
};

module.exports = definition;

```

- save this as file next to `configuration.yaml` as `ext_converter.js`
- add it to `configuration.yaml`:
```yaml
external_converters:
  - ext_converter.js
```
- start z2m, check if issue is fixed

**Comment by CiccioDroid** [comment] 2022-08-10 10:41
Hi koenkk, i have tested the converter and it works very well, the error on the log has disappeared and now the position is updated in every situation (tested by pressing the wall button and position is updated on the zigbee2mqtt dasboard automatically).
Thank you very much.

**Comment by Koenkk** [comment] 2022-08-10 15:06
Thanks, pushed the fix!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Closed by Koenkk** 2022-08-10 15:06 UTC
Labels: problem
