### ISSUE TITLE
last_seen is not updated in the attributes

### ISSUE THREAD

**Issue by poisondima** [Koenkk/zigbee2mqtt#9036] opened 2021-10-06 12:54 UTC
## What happened
The "last_seen" field value is not updated in the attributes:
![изображение](https://user-images.githubusercontent.com/39500249/136203212-e43a324a-30e1-49a0-93f1-20379079d710.png)
In Zigbee2MQTT it shows correctly:
![изображение](https://user-images.githubusercontent.com/39500249/136203373-6a5b5122-5f1a-4497-a86b-de2c87118749.png)
![изображение](https://user-images.githubusercontent.com/39500249/136203381-6a6f0200-a2d0-4ca5-af43-fcfa9ddb51e9.png)
I keep track of the "last_seen" field and if the device hasn't been updated in a while I assume it has fallen off.
In the settings "last_seen" is selected as "ISO_8601_local"
But if I physically press the switch button, the field updates with no problem:
![изображение](https://user-images.githubusercontent.com/39500249/136205693-dd210147-2c39-4dea-abc9-f78d81cd56ad.png)
![изображение](https://user-images.githubusercontent.com/39500249/136205792-ebaf3d15-fd14-4dc0-aaed-20f9fe8341e3.png)
## What did you expect to happen
I would like to get the real value of the "last_seen" field, so it can be used in scripts and monitor devices that have fallen off the network.
## Debug info
Zigbee2MQTT version: 1.21.2-1
Adapter hardware: RFStar CC2652P2
Adapter firmware version: 20210708

**Comment by Koenkk** [comment] 2021-10-06 18:38
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/7423 (already fixed in the latest-dev)

**Closed by Koenkk** 2021-10-06 18:38 UTC
Labels: problem
