### ISSUE TITLE
OTA update on IKEA TRADFRI E1743

### ISSUE THREAD

**Issue by fedebruni84** [Koenkk/zigbee2mqtt#4672] opened 2020-10-15 09:45 UTC
## What happened

IKEA E1743 does not update from 2.2.008 firmware.

## What did you expect to happen

Firmware to be updated to 2.2.010

## How to reproduce it (minimal and precise)

If I check id there is an update for a E1743 on/off button, z2m says there is an update available. I can start the update but after it is successfully completed, firmware version does not change. 
Current firmware version is 2.2.008, IKEA release notes indicate there is a 2.2.010 version. 
After the update, E1743 annouces himself with 2.2.008 version

```txt
{"message":"announce","meta":{"friendly_name":"ikea_tradfri_switch02"},"type":"device_announced"}
{"message":"Update of 'ikea_tradfri_switch02' at 100.00%","meta":{"device":"ikea_tradfri_switch02","progress":100,"status":"update_progress"},"type":"ota_update"}
{"message":"ikea_tradfri_switch02","meta":{"device":"ikea_tradfri_switch02","from":{"date_code":"20190410","software_build_id":"2.2.008"},"status":"update_succeeded","to":{"date_code":"20190410","software_build_id"   :"2.2.008"}},"type":"ota_update"}
{"message":"announce","meta":{"friendly_name":"ikea_tradfri_switch02"},"type":"device_announced"}

```

## Debug info
Zigbee2MQTT version: 1.15.0
Adapter hardware: CC2531
Adapter firmware version: 20190608

**Comment by Koenkk** [comment] 2020-10-15 14:08
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/4559

**Closed by Koenkk** 2020-10-15 14:08 UTC
Labels: problem
