### ISSUE TITLE
Moes 1gang wall switch posting status twice when set through WebUI or MQTT

### ISSUE THREAD

**Issue by stoinov** [Koenkk/zigbee2mqtt#9280] opened 2021-10-22 17:55 UTC
## What happened

I added a new modification of [Moes ZTS-EU_1gang](https://www.zigbee2mqtt.io/devices/ZTS-EU_1gang.html) (that [looks like this](https://www.moeshouse.com/collections/eu-smart-switch/products/zigbee-smart-wall-light-switch-with-neutral-wire-or-no-neutral-wire-wiring-no-capacitor-needed-smart-life-tuya-2-3-way-muilti-control-association-works-with-alexa-google-home-hub-required)) and when switching through the WebUI or MQTT, I get two consecutive messages with the same state, but one having `last_seen` as the previous packet time and the second having `last_seen` as now.
Pressing the hardware button does not yield the same result, although very rarely returns doubled messages, but they can be fixed with `debounce`.

## What did you expect to happen

To receive just one MQTT message when using the WebUI.

## How to reproduce it (minimal and precise)

I am not sure if this is limited to only this new modification of the switch as it's recognized as [`_TZE200_amp6tsvy`](https://github.com/Koenkk/zigbee-herdsman-converters/blob/1546e07016198522576987690e15aaf944448e2a/devices/moes.js#L95), but this issue is very similar to another one I have - #8990 

## Debug info
Zigbee2MQTT version: 1.21.2 commit: 4492212
Adapter hardware: ZZH
Adapter firmware version: 20210708

**Comment by stoinov** [comment] 2021-11-27 10:54
it's still relevant, so unstalling.

**Comment by Koenkk** [comment] 2021-12-16 18:10
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/8944

**Closed by Koenkk** 2021-12-16 18:10 UTC
Labels: problem
