### ISSUE TITLE
[ZNCZ04LM]Mi power plug ZigBee EU - consumption energy issue

### ISSUE THREAD

**Issue by Ulekuli** [Koenkk/zigbee2mqtt#5689] opened 2021-01-11 08:25 UTC
# Bug Report
## What happened
After upgrade to 1.17.0.1 'consumption' variable stopped count.
All my 3 power plugs stopped reporting consumption. Last refresh was a moment before upgrade. 
Rest of variables like:

{
    "consumption": 5.74,
    "current": 0,
    "energy": 4.45,
    "linkquality": 100,
    "power": 0,
    "state": "OFF",
    "temperature": -1,
    "voltage": 234
}

are reported ok.

## What did you expect to happen
Consumption should increment.

## How to reproduce it (minimal and precise)
Connect plug nad see how consumption is reported.

## Debug Info
Zigbee2MQTT version: 1.17.0.1
Adapter hardware: Conbee II
Adapter firmware version:

**Comment by Koenkk** [comment] 2021-01-11 11:42
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/5614

**Closed by Koenkk** 2021-01-11 11:42 UTC
