### ISSUE TITLE
TuYa TS0044_1 (_TZ3000_dziaict4) 4-button remote control no longer working after last update to 1.31.0-1

### ISSUE THREAD

**Issue by gk-it** [Koenkk/zigbee2mqtt#17936] opened 2023-06-06 12:59 UTC
### What happened?

The button events for the 4 buttons are no longer recognized / processed.

### Zigbee2MQTT version

1.31.0-1

### Adapter firmware version

20221226

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus CC2652P + CP2102(N)

**Comment by Koenkk** [comment] 2023-06-07 07:13
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/17862

**Closed by Koenkk** 2023-06-07 07:13 UTC
Labels: problem
