### ISSUE TITLE
Aqara roller blinds ZNJLBL01LM cannot be controlled anymore (ember)

### ISSUE THREAD

**Issue by fir3drag0n** [Koenkk/zigbee2mqtt#22420] opened 2024-05-03 08:49 UTC
### What happened?

I switched to ember and the device is not usable anymore

`2024-05-03 10:45:46Publish 'set' 'position' to 'Rollo-Balkon' failed: 'Error: ZCL command 0x54ef4410004d298f/1 genAnalogOutput.write({"presentValue":61}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Delivery failed for {"profileId":260,"clusterId":13,"sourceEndpoint":1,"destinationEndpoint":1,"options":4160,"groupId":0,"sequence":43})'`

### What did you expect to happen?

To control it regularly 

### Zigbee2MQTT version

11.37.0-dev commit: 3a61f0a

### Adapter firmware version

7.4.2 [GA]

### Adapter

SLZB-06M

### Setup

Z2M Docker

### Debug log

[log.log](https://github.com/Koenkk/zigbee2mqtt/files/15197839/log.log)

**Comment by barrymossel** [comment] 2024-05-03 18:09
Not sure if related, but my Aqara roller blinds can be controlled through the Z2M web interface, but are not working properly through HA. State is unknown, cannot test more (as I am not home ATM).

**Comment by Koenkk** [comment] 2024-05-04 07:56
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/22387

**Closed by Koenkk** 2024-05-04 07:56 UTC
Labels: problem

**Comment by fir3drag0n** [comment] 2024-05-06 05:41
This problem appeared again
