### ISSUE TITLE
[New device support]: lumi.remote.cagl02 - Cube T1 Pro

### ISSUE THREAD

**Issue by hyperfive** [Koenkk/zigbee2mqtt#16006] opened 2023-01-07 14:33 UTC
### Link

https://www.aqara.com/en/product/cube-t1-pro

### Database entry

Unknown

### Comments

Hello,

I am fairly certain the integration of this device will be very similar if not identical to the original version - https://www.aqara.com/us/cube.html

**Comment by kariudo** [comment] 2023-01-07 20:07
This is a duplicate of #15652

**Closed** 2023-01-08 08:32 UTC
Labels: new device support
