### ISSUE TITLE
Error at npm start

### ISSUE THREAD

**Issue by majestro84** [Koenkk/zigbee2mqtt#984] opened 2019-01-31 14:26 UTC
after an update i get the following error at startup.
`pi@PiZeroFlur:/opt/zigbee2mqtt $ npm start

> zigbee2mqtt@1.1.0 start /opt/zigbee2mqtt
> node index.js

  zigbee2mqtt:info 1/31/2019, 2:57:28 PM Logging to directory: '/opt/zigbee2mqtt/data/log/2019-01-31.14-57-28'
  zigbee2mqtt:info 1/31/2019, 2:57:32 PM Starting zigbee2mqtt version 1.1.0 (commit #9d61184)
  zigbee2mqtt:info 1/31/2019, 2:57:32 PM Starting zigbee-shepherd
  zigbee2mqtt:info 1/31/2019, 2:57:44 PM Error while starting zigbee-shepherd, attemping to fix... (takes 60 seconds)
/opt/zigbee2mqtt/node_modules/q/q.js:155
                throw e;
                ^

TypeError: Cannot read property 'close' of undefined
    at shepherd.start (/opt/zigbee2mqtt/lib/zigbee.js:45:47)
    at /opt/zigbee2mqtt/node_modules/q/q.js:2059:17
    at runSingle (/opt/zigbee2mqtt/node_modules/q/q.js:137:13)
    at flush (/opt/zigbee2mqtt/node_modules/q/q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.1.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zigbee2mqtt@1.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-01-31T13_57_44_450Z-debug.log
pi@PiZeroFlur:/opt/zigbee2mqtt $ more /home/pi/.npm/_logs/2019-01-31T13_57_44_450Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@6.2.0
3 info using node@v10.9.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle zigbee2mqtt@1.1.0~prestart: zigbee2mqtt@1.1.0
6 info lifecycle zigbee2mqtt@1.1.0~start: zigbee2mqtt@1.1.0
7 verbose lifecycle zigbee2mqtt@1.1.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle zigbee2mqtt@1.1.0~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/opt/zigbee2mq
tt/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
9 verbose lifecycle zigbee2mqtt@1.1.0~start: CWD: /opt/zigbee2mqtt
10 silly lifecycle zigbee2mqtt@1.1.0~start: Args: [ '-c', 'node index.js' ]
11 silly lifecycle zigbee2mqtt@1.1.0~start: Returned: code: 1  signal: null
12 info lifecycle zigbee2mqtt@1.1.0~start: Failed to exec start script
13 verbose stack Error: zigbee2mqtt@1.1.0 start: `node index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:961:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:250:5)
14 verbose pkgid zigbee2mqtt@1.1.0
15 verbose cwd /opt/zigbee2mqtt
16 verbose Linux 4.14.79+
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v10.9.0
19 verbose npm  v6.2.0
20 error code ELIFECYCLE
21 error errno 1
22 error zigbee2mqtt@1.1.0 start: `node index.js`
22 error Exit status 1
23 error Failed at the zigbee2mqtt@1.1.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

Do you have any idea what I can do

**Comment by JLFN** [comment] 2019-01-31 14:54
Did you edit your configuration.yaml file?

**Comment by majestro84** [comment] 2019-01-31 14:57
the ymal ran without problems before the update.
get the error also with a new copy of Git, with the standard yaml

`homeassistant: false
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://192.168.0.10'
  client_id: Zigbee_Pi
serial:
  port: /dev/ttyACM0
  disable_led: true
advanced:
  channel: 25
`

**Comment by Koenkk** [comment] 2019-01-31 15:11
Duplicate of #971 and #937

**Closed by Koenkk** 2019-01-31 15:11 UTC
