### ISSUE TITLE
Pairing not possible anymore

### ISSUE THREAD

**Issue by Sportslite** [Koenkk/zigbee2mqtt#10935] opened 2022-01-21 14:49 UTC
### What happened?

After switching from C2531 to Sonoff C2652P I'm not able to pair any Smart Plug (Innr, Blitzwolf) after resetting them.
But could pair a button from Xiaomi. I'm using the latest version with HA.

### Zigbee2MQTT version

1.22.2-1

### Adapter firmware version

20210708

### Adapter

Sonoff C2652P

**Comment by Koenkk** [comment] 2022-01-21 15:22
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/10339

**Closed by Koenkk** 2022-01-21 15:22 UTC
Labels: problem
