### ISSUE TITLE
Touchlink reset fails on CC2531

### ISSUE THREAD

**Issue by wilcomir** [Koenkk/zigbee2mqtt#4691] opened 2020-10-17 12:42 UTC
## What happened
I updated zigbee2mqtt to the latest revision, and now touchlink reset does not work anymore.
## What did you expect to happen
touchlink working
## How to reproduce it (minimal and precise)
I publish an empty message to `zigbee2mqtt/bridge/config/touchlink/factory_reset`, and get an error in the logs
## Debug info
Zigbee2MQTT version: 1.15.0 (commit #ed8b4e5)
Adapter hardware: CC2531
Adapter firmware version: "maintrel":3,"majorrel":2,"minorrel":6,"product":0,"revision":20190608,"transportrev":2

The relevant portion of the log is available here:

https://pastebin.com/gVr8b3Qz

Things that I already tried to do, to no avail:
 - reinstall zigbee2mqtt from scratch, same error
 - removing the `node_modules` folder and running `npm install` 

The platform is a raspberry pi 3, I have less than 10 devices on the zigbee network, and as far as I can tell everything else is working fine.

**Comment by Koenkk** [comment] 2020-10-17 14:52
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/4543 (upgrade to dev branch to solve, https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Closed by Koenkk** 2020-10-17 14:52 UTC
Labels: problem
