### ISSUE TITLE
RGB+CCT (Only control the RGB and not the W)

### ISSUE THREAD

**Issue by davdav42** [Koenkk/zigbee2mqtt#1738] opened 2019-07-15 22:04 UTC
Hello,

I have a raspberry pi with Domoticz, And the ZigbeeM2qtt. I want to control a led ribbon with a GLEDOPTO RGB+CCT.
The led ribbon has 2 kind of led RBG and White and 6 wire (V+, RGB, W, WW).
 I can successfully control the RGB, I can switch off/on change the color. but it's impossible to control the white leds. These one stay switched on and I cannot change the intensity.

You will find below the database.db for this device :: 
{"id":3,"type":"Router","ieeeAddr":"0x00124b001ba6f3c7","nwkAddr":22174,"manufId":0,"manufName":"GLEDOPTO","powerSource":"Mains (single phase)","modelId":"GL-C-007","epList":[11,13,15],"zclVersion":1,"appVersion":1,"stackVersion":2,"hwV2,"hwVersion":1,"swBuildId":"2.0.2","status":"offline","joinTime":null,"endpoints":{"11":{"profId":49246,"epId":11,"devId":528,"inClusterList":[0,3,4,5,6,8,768],"outClusterList":[],"clusters":{}},"13":{"profId":49246,"epId":13,"devId":evId":57694,"inClusterList":[4096],"outClusterList":[4096],"clusters":{}},"15":{"profId":49246,"epId":15,"devId":544,"inClusterList":[0,3,4,5,6,8,768],"outClusterList":[],"clusters":{}}},"dateCode":"20180920","_id":"1X7PKOIHid2AmNLY"}
{"id":3,"type":"Router","ieeeAddr":"0x00124b001ba6f3c7","nwkAddr":22174,"manufId":0,"manufName":"GLEDOPTO","powerSource":"Mains (single phase)","modelId":"GL-C-007","epList":[11,13,15],"zclVersion":1,"appVersion":1,"stackVersion":2,"hwV2,"hwVersion":1,"swBuildId":"2.0.2","status":"offline","joinTime":null,"endpoints":{"11":{"profId":49246,"epId":11,"devId":528,"inClusterList":[0,3,4,5,6,8,768],"outClusterList":[],"clusters":{}},"13":{"profId":49246,"epId":13,"devId":evId":57694,"inClusterList":[4096],"outClusterList":[4096],"clusters":{}},"15":{"profId":49246,"epId":15,"devId":544,"inClusterList":[0,3,4,5,6,8,768],"outClusterList":[],"clusters":{}}},"dateCode":"20180920","_id":"1X7PKOIHid2AmNLY"}

and below the device.js : 

    // Gledopto
    {
        zigbeeModel: ['GLEDOPTO', 'GL-C-008', 'GL-C-007'],
        model: 'GL-C-008',
        vendor: 'Gledopto',
        description: 'Zigbee LED controller RGB + CCT / RGBW / WWCW / Dimmer',
        extend: gledopto.light_onoff_brightness_colortemp_colorxy,
        ep: (device) => {
            if (device.epList.toString() === '11,12,13') {
                return {'': 12};
            } else if (device.epList.toString() === '10,11,13' || device.epList.toString() === '11,13') {
                return {'': 11};
            } else if (device.epList.toString() === '11,12,13,15') {
                return {
                    'rgb': 12,
                    'white': 15,
                };
            } else if (device.epList.toString() === '11,13,15') {
                return {
                    'rgb': 11,
                    'white': 15,
                };
            } else {
                return {};
            }
        },
    },

On Domoticz the controller is a RGBWW. 

Can somebody could help me. Than you very much in advance

**Comment by Koenkk** [comment] 2019-07-16 03:37
Duplicate of #1711

**Closed by Koenkk** 2019-07-16 03:37 UTC
