### ISSUE TITLE
Update connected objects via OTA

### ISSUE THREAD

**Issue by Ricardo544** [Koenkk/zigbee2mqtt#2141] opened 2019-10-15 11:46 UTC
Hello,

Do you think it would be possible to integrate an update of Ikea connected objects via Ota as explained on this link.

https://github.com/pipiche38/Domoticz-Zigate-Wiki/blob/master/en-eng/OTA-Upgrade.md

thank you in advance

**Comment by Koenkk** [comment] 2019-10-15 13:08
Duplicate of #1696

**Closed by Koenkk** 2019-10-15 13:08 UTC
