### ISSUE TITLE
MQTT name for HA

### ISSUE THREAD

**Issue by RubenKelevra** [Koenkk/zigbee2mqtt#18545] opened 2023-08-07 11:06 UTC
### What happened?

I've got two error messages by HA today:

![Screenshot_2023-08-07-13-01-01-651_io homeassistant companion android](https://github.com/Koenkk/zigbee2mqtt/assets/614929/4842be2d-2ab8-4b80-8252-2528f44553dd)

![Screenshot_2023-08-07-13-03-37-381-edit_io homeassistant companion android](https://github.com/Koenkk/zigbee2mqtt/assets/614929/a10993c9-d408-430d-9571-2bf73df23595)

Learn more link goes in both cases to [this page](https://developers.home-assistant.io/blog/2023-057-21-change-naming-mqtt-entities/) which is no help at all.

How can I continue to use Z2M after 2024.2?

### Zigbee2MQTT version

1.32.2

### Adapter firmware version

20221226

### Adapter

Slaesh's CC2652RB stick

**Comment by olafz** [comment] 2023-08-07 13:39
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/18445

**Comment by RubenKelevra** [comment] 2023-08-07 15:15
Not a duplicate, as that one is closed as fixed. 🤷‍♂️

I couldn't find an open bug report for that.

**Comment by olafz** [comment] 2023-08-07 15:24
> Not a duplicate, as that one is closed as fixed. 🤷‍♂️

It is fixed in the image tagged "latest-dev". If you don't want to run that version, you will have to wait a bit: the fix will be included in the release of next month.

**Comment by RubenKelevra** [comment] 2023-08-07 15:29
Okay? In this ticket 1.32.2-dev was mentioned, which is the Version I'm running. So the fix is not in 1.32.2?

**Comment by olafz** [comment] 2023-08-07 15:33
> So the fix is not in 1.32.2?

No. See also this comment (and the ones after that) in the issue mentioned: https://github.com/Koenkk/zigbee2mqtt/issues/18445#issuecomment-1666801532

**Comment by Koenkk** [comment] 2023-08-07 16:56
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/18445 and already fixed in -dev.

**Closed by Koenkk** 2023-08-07 16:56 UTC
Labels: problem
