### ISSUE TITLE
Group of light with brightness set to 0

### ISSUE THREAD

**Issue by mr2c12** [Koenkk/zigbee2mqtt#3785] opened 2020-06-20 08:11 UTC
Since I have updated my z2m to 1.14 something strange has appened twice.

In my setup I have 3 groups of light:
- group1: 3 light bulbs
- group2: 2 light bulbs
- group3: 1 light bulb

Each group is controlled by its own automation.

It never happened before (was on 1.13).
When the automation set the group to "on", actually the lights turn on but their brightness is zero (i.e., completely dark).
I had to re-set the brightness to max value to the group (or to the lights).
In one case, I had to restart z2m (group1, had problems every time it turned on).

Am I the only one suffering from this?

**Comment by Koenkk** [comment] 2020-06-20 12:39
Duplicate of #3782

**Closed by Koenkk** 2020-06-20 12:39 UTC
