### ISSUE TITLE
Failed to interview LivingWise LVS-SN10ZW_SN11 to Zigbee2Mqtt 1.16.1-dev

### ISSUE THREAD

**Issue by khaidakin** [Koenkk/zigbee2mqtt#5113] opened 2020-11-28 15:41 UTC
## What happened
Trying to pair LivingWise LVS-SN10ZW_SN11 (https://www.zigbee2mqtt.io/devices/LVS-SN10ZW_SN11.html)

## What did you expect to happen
I expected the device to connect and work as it did on the old Z2M version, but the device connects with an error and does not show anything in State.

## How to reproduce it (minimal and precise)
try to LivingWise LVS-SN10ZW_SN11 to zigbee2mqtt

## Debug info
Zigbee2MQTT version: 1.16.1-dev
Adapter hardware: CC2652-E72
Adapter firmware version: 20200921 (Egony)
https://pastebin.com/Lcte29yp

**Comment by spurgelaurels** [comment] 2020-11-30 14:45
#5091 

Looks like we're having similar issue. I'm wondering if Livingwise has something weird in their stack that isn't working with 3.x.0. 
I assume you're running 3.x.0 on your end?

**Comment by Koenkk** [comment] 2020-11-30 18:18
Duplicate of #5091

**Closed by Koenkk** 2020-11-30 18:18 UTC
Labels: problem

**Comment by khaidakin** [comment] 2020-11-30 21:00
> #5091
> 
> Looks like we're having similar issue. I'm wondering if Livingwise has something weird in their stack that isn't working with 3.x.0.
> I assume you're running 3.x.0 on your end?
I think yes.
