### ISSUE TITLE
TONGOU TO-Q-SY2-163JZT (TS011F) still reporting energy consumption while switched off

### ISSUE THREAD

**Issue by eekamouze** [Koenkk/zigbee2mqtt#17798] opened 2023-05-26 09:55 UTC
### What happened?

I'm having this device for a couple of days now and it seems that energy sensor still increases while the device is switched off. This is about 0.05kWh / day approx.

### What did you expect to happen?

energy consumption sensor should not increase while device is off

### How to reproduce it (minimal and precise)

Switch off device and check energy sensor

### Zigbee2MQTT version

1.30.4 commit: b2dd21e

### Adapter firmware version

6.10.3.0 build 297

### Adapter

Sonoff ZBDongle-E (EFR32MG21)

### Debug log

MQTT publish: topic 'zigbee2mqtt/Ligne piscine', payload '{"current":0,"energy":0.13,"indicator_mode":"off/on","linkquality":152,"over_current_breaker":"ON","over_current_threshold":20,"over_voltage_breaker":"ON","over_voltage_threshold":250,"power":0,"power_breaker":"ON","power_outage_memory":"restore","power_threshold":9,"state":"OFF","temperature":26.91,"temperature_breaker":"ON","temperature_threshold":100,"under_voltage_breaker":"ON","under_voltage_threshold":90,"update":{"installed_version":-1,"latest_version":-1,"state":"idle"},"update_available":null,"voltage":236}'

**Comment by Koenkk** [comment] 2023-05-26 15:16
Duplicate of #16709

**Closed by Koenkk** 2023-05-26 15:16 UTC
Labels: problem
